### ISSUE TITLE
Manual test run on Windows ia-32 for 0.18.x (Beta Channel)

### ISSUE THREAD

**Issue by alexwykoff** [brave/browser-laptop#10111]
- [ ] Vertical alignment is off on Payments "Add Funds" button. ([#10098](https://github.com/brave/browser-laptop/issues/10098))
 - [ ] Error while build-package. ([#10060](https://github.com/brave/browser-laptop/issues/10060))
 - [ ] Keyboard shortcut for undo last closed frame with no last closed frame causes an error. ([#9948](https://github.com/brave/browser-laptop/issues/9948))
 - [ ] Upgrade to Chromium 60. ([#9947](https://github.com/brave/browser-laptop/issues/9947))
 - [ ] Extension: 1Password 4.6.7.90. ([#9946](https://github.com/brave/browser-laptop/issues/9946))
 - [ ] Use Chromium spell checker. ([#9880](https://github.com/brave/browser-laptop/issues/9880))
 - [ ] Upgrade 0.18.x to muon 4.3.5. ([#9856](https://github.com/brave/browser-laptop/issues/9856))
 - [ ] Unable to go back to previous website with long press on back button. ([#9852](https://github.com/brave/browser-laptop/issues/9852))
 - [ ] Session restore can lead to lost windows if there is a hung or slow Window on shutdown. ([#9806](https://github.com/brave/browser-laptop/issues/9806))
 - [ ] Adding a bookmarks folder makes the browser unresponsive. ([#9745](https://github.com/brave/browser-laptop/issues/9745))
 - [ ] Bookmark deletion may lead to duplicated bookmarks. ([#9724](https://github.com/brave/browser-laptop/issues/9724))
 - [ ] Don't send messages to all windows in onBeforeRequest. ([#9701](https://github.com/brave/browser-laptop/issues/9701))
 - [ ] Individual bookmarks not synced from laptop after Payments are switched off. ([#9684](https://github.com/brave/browser-laptop/issues/9684))
 - [ ] Urlbar icon disappears when video starts playing. ([#9652](https://github.com/brave/browser-laptop/issues/9652))
 - [ ] Move most extension registration from muon into browser-laptop . ([#9584](https://github.com/brave/browser-laptop/issues/9584))
 - [ ] Add browserButton_panelItem to BrowserButton component. ([#9543](https://github.com/brave/browser-laptop/issues/9543))
 - [ ] Urlbar titlemode appends colon to the end of the hostname. ([#9503](https://github.com/brave/browser-laptop/issues/9503))
 - [ ] Turn off shields on about:safebrowsing shows about:error page instead of loading the actual site and shields become inactive. ([#9441](https://github.com/brave/browser-laptop/issues/9441))
 - [ ] Bitwarden widget not shown on webpages, shows only on about pages. ([#9437](https://github.com/brave/browser-laptop/issues/9437))
 - [ ] Make welcome screen show up on first time run. ([#9423](https://github.com/brave/browser-laptop/issues/9423))
 - [ ] Sync objectsById should be cleared when browser quits. ([#9405](https://github.com/brave/browser-laptop/issues/9405))
 - [ ] Sync records are sent twice. ([#9404](https://github.com/brave/browser-laptop/issues/9404))
 - [ ] Add "iconOnly" property for browserButton. ([#9353](https://github.com/brave/browser-laptop/issues/9353))
 - [ ] Handle sync DELETE history/bookmark records with empty objects. ([#9308](https://github.com/brave/browser-laptop/issues/9308))
 - [ ] Scrollable code sample boxes on about:styles. ([#9280](https://github.com/brave/browser-laptop/issues/9280))
 - [ ] Redux component - Download area. ([#9260](https://github.com/brave/browser-laptop/issues/9260))
 - [ ] Notification button is not rendered as a button on about:styles. ([#9238](https://github.com/brave/browser-laptop/issues/9238))
 - [ ] Notification buttons should be larger. ([#9237](https://github.com/brave/browser-laptop/issues/9237))
 - [ ] Merge span.findButton with .closeButton on findbar.less. ([#9234](https://github.com/brave/browser-laptop/issues/9234))
 - [ ] Remove smallButton. ([#9232](https://github.com/brave/browser-laptop/issues/9232))
 - [ ] Remove inlineButton. ([#9229](https://github.com/brave/browser-laptop/issues/9229))
 - [ ] Sync input fields should have focus when clicked. ([#9175](https://github.com/brave/browser-laptop/issues/9175))
 - [ ] Move actionButton to Aphrodite. ([#9163](https://github.com/brave/browser-laptop/issues/9163))
 - [ ] "Allow this time" on NoScript dialog keeps allowing scripts even after reopening the tab. ([#9150](https://github.com/brave/browser-laptop/issues/9150))
 - [ ] Add "Hide 0% sites" button on Brave Payments. ([#9137](https://github.com/brave/browser-laptop/issues/9137))
 - [ ] Extension tabs not auto closing when finished. ([#9132](https://github.com/brave/browser-laptop/issues/9132))
 - [ ] TLD of long domain is not displayed in title tooltip on bravery panel. ([#9089](https://github.com/brave/browser-laptop/issues/9089))
 - [ ] Brave Fails to "Remember this decision". ([#9076](https://github.com/brave/browser-laptop/issues/9076))
 - [ ] About:brave shows win32 for all Windows platforms (even x64). ([#8933](https://github.com/brave/browser-laptop/issues/8933))
 - [ ] Bookmarks in Other Bookmarks folder is synced to the bookmark toolbar. ([#8024](https://github.com/brave/browser-laptop/issues/8024))
 - [ ] Unhide bitwarden password manager. ([#7921](https://github.com/brave/browser-laptop/issues/7921))
 - [ ] Blank tabs bar appears after increasing the number of tabs per tab set. ([#7806](https://github.com/brave/browser-laptop/issues/7806))
 - [ ] Provide an option to disable "Top Sites" in autocomplete. ([#4977](https://github.com/brave/browser-laptop/issues/4977))
 - [ ] Added Bitwarden Password Manager. ([#4776](https://github.com/brave/browser-laptop/issues/4776))
 - [ ] Remove darkening for all non-modal dialogs. ([#3653](https://github.com/brave/browser-laptop/issues/3653))
