### ISSUE TITLE
Manual test run on OS X for 0.18.x (Beta Channel)

### ISSUE THREAD

**Issue by alexwykoff** [brave/browser-laptop#10110]
- [ ] Vertical alignment is off on Payments "Add Funds" button. ([#10098](https://github.com/brave/browser-laptop/issues/10098))
 - [ ] Keyboard shortcut for undo last closed frame with no last closed frame causes an error. ([#9948](https://github.com/brave/browser-laptop/issues/9948))
 - [ ] Upgrade to Chromium 60. ([#9947](https://github.com/brave/browser-laptop/issues/9947))
 - [ ] Extension: 1Password 4.6.7.90. ([#9946](https://github.com/brave/browser-laptop/issues/9946))
 - [ ] Use Chromium spell checker. ([#9880](https://github.com/brave/browser-laptop/issues/9880))
 - [ ] Upgrade 0.18.x to muon 4.3.5. ([#9856](https://github.com/brave/browser-laptop/issues/9856))
 - [ ] Unable to go back to previous website with long press on back button. ([#9852](https://github.com/brave/browser-laptop/issues/9852))
 - [ ] Session restore can lead to lost windows if there is a hung or slow Window on shutdown. ([#9806](https://github.com/brave/browser-laptop/issues/9806))
 - [ ] Adding a bookmarks folder makes the browser unresponsive. ([#9745](https://github.com/brave/browser-laptop/issues/9745))
 - [ ] Bookmark deletion may lead to duplicated bookmarks. ([#9724](https://github.com/brave/browser-laptop/issues/9724))
 - [ ] Don't send messages to all windows in onBeforeRequest. ([#9701](https://github.com/brave/browser-laptop/issues/9701))
 - [ ] Individual bookmarks not synced from laptop after Payments are switched off. ([#9684](https://github.com/brave/browser-laptop/issues/9684))
 - [ ] Urlbar icon disappears when video starts playing. ([#9652](https://github.com/brave/browser-laptop/issues/9652))
 - [ ] Move most extension registration from muon into browser-laptop . ([#9584](https://github.com/brave/browser-laptop/issues/9584))
 - [ ] Add browserButton_panelItem to BrowserButton component. ([#9543](https://github.com/brave/browser-laptop/issues/9543))
 - [ ] Urlbar titlemode appends colon to the end of the hostname. ([#9503](https://github.com/brave/browser-laptop/issues/9503))
 - [ ] Turn off shields on about:safebrowsing shows about:error page instead of loading the actual site and shields become inactive. ([#9441](https://github.com/brave/browser-laptop/issues/9441))
 - [ ] Bitwarden widget not shown on webpages, shows only on about pages. ([#9437](https://github.com/brave/browser-laptop/issues/9437))
 - [ ] Make welcome screen show up on first time run. ([#9423](https://github.com/brave/browser-laptop/issues/9423))
 - [ ] Sync objectsById should be cleared when browser quits. ([#9405](https://github.com/brave/browser-laptop/issues/9405))
 - [ ] Sync records are sent twice. ([#9404](https://github.com/brave/browser-laptop/issues/9404))
 - [ ] Add "iconOnly" property for browserButton. ([#9353](https://github.com/brave/browser-laptop/issues/9353))
 - [ ] Handle sync DELETE history/bookmark records with empty objects. ([#9308](https://github.com/brave/browser-laptop/issues/9308))
 - [ ] Scrollable code sample boxes on about:styles. ([#9280](https://github.com/brave/browser-laptop/issues/9280))
 - [ ] Redux component - Download area. ([#9260](https://github.com/brave/browser-laptop/issues/9260))
 - [ ] Notification button is not rendered as a button on about:styles. ([#9238](https://github.com/brave/browser-laptop/issues/9238))
 - [ ] Notification buttons should be larger. ([#9237](https://github.com/brave/browser-laptop/issues/9237))
 - [ ] Merge span.findButton with .closeButton on findbar.less. ([#9234](https://github.com/brave/browser-laptop/issues/9234))
 - [ ] Remove smallButton. ([#9232](https://github.com/brave/browser-laptop/issues/9232))
 - [ ] Remove inlineButton. ([#9229](https://github.com/brave/browser-laptop/issues/9229))
 - [ ] Sync input fields should have focus when clicked. ([#9175](https://github.com/brave/browser-laptop/issues/9175))
 - [ ] Move actionButton to Aphrodite. ([#9163](https://github.com/brave/browser-laptop/issues/9163))
 - [ ] "Allow this time" on NoScript dialog keeps allowing scripts even after reopening the tab. ([#9150](https://github.com/brave/browser-laptop/issues/9150))
 - [ ] Add "Hide 0% sites" button on Brave Payments. ([#9137](https://github.com/brave/browser-laptop/issues/9137))
 - [ ] Extension tabs not auto closing when finished. ([#9132](https://github.com/brave/browser-laptop/issues/9132))
 - [ ] TLD of long domain is not displayed in title tooltip on bravery panel. ([#9089](https://github.com/brave/browser-laptop/issues/9089))
 - [ ] Brave Fails to "Remember this decision". ([#9076](https://github.com/brave/browser-laptop/issues/9076))
 - [ ] Bookmarks in Other Bookmarks folder is synced to the bookmark toolbar. ([#8024](https://github.com/brave/browser-laptop/issues/8024))
 - [ ] Unhide bitwarden password manager. ([#7921](https://github.com/brave/browser-laptop/issues/7921))
 - [ ] Blank tabs bar appears after increasing the number of tabs per tab set. ([#7806](https://github.com/brave/browser-laptop/issues/7806))
 - [ ] Opening a context menu freezes video (ex: Youtube). ([#5470](https://github.com/brave/browser-laptop/issues/5470))
 - [ ] Provide an option to disable "Top Sites" in autocomplete. ([#4977](https://github.com/brave/browser-laptop/issues/4977))
 - [ ] Added Bitwarden Password Manager. ([#4776](https://github.com/brave/browser-laptop/issues/4776))
 - [ ] Remove darkening for all non-modal dialogs. ([#3653](https://github.com/brave/browser-laptop/issues/3653))

# Manual Tests Template

Copy this to a new issue when Chromium is updated.
The tests should run for macOS, Windows ia32, and a Linux distro for each release. 

## Installer

1. [ ] Check that installer is close to the size of last release.
2. [ ] Check signature: If OS Run `spctl --assess --verbose /Applications/Brave.app/` and make sure it returns `accepted`.  If Windows right click on the installer exe and go to Properties, go to the Digital Signatures tab and double click on the signature.  Make sure it says "The digital signature is OK" in the popup window.
3. [ ] Check the libchromiumcontent version in about:brave and make sure it is EXACTLY as expected.

## Printing

1. [ ] Test that you can print a PDF

## Widevine/Netflix test

1. [ ] Test that you can log into Netflix and start a show.

## Performance test

_Each start should take less than 7 seconds_
1. [ ] Enable only sync (new sync group).
2. [ ] Enable only sync with a large sync group (many entries).
3. [ ] Enable only payments.
4. [ ] Only import a large set of bookmarks.
5. [ ] Combine sync, payments, and a large set of bookmarks.

## Ledger
1. [x] Create a wallet with a value other than $5 selected in the monthly budget dropdown. Click on the 'Add Funds' button and check that Coinbase transactions are blocked.
2. [x] Remove all `ledger-*.json` files from `~/Library/Application\ Support/Brave/`. Go to the Payments tab in about:preferences, enable payments, click on `create wallet`. Check that the `add funds` button appears after a wallet is created.
3. [ ] Click on `add funds` and verify that adding funds through Coinbase increases the account balance.
4. [ ] Repeat the step above but add funds by scanning the QR code in a mobile bitcoin app instead of through Coinbase.
5. [x] Visit nytimes.com for a few seconds and make sure it shows up in the Payments table.
6. [x] Check that disabling payments and enabling them again does not lose state.

## Sync
1. [x] Verify you are able to sync two devices using the secret code
2. [x] Visit a site on device 1 and change shield setting, ensure that the saved site preference is synced to device 2
3. [x] Enable Browsing history sync on device 1, ensure the history is shown on device 2 
4. [x] Import/Add bookmarks on device 1, ensure it is synced on device 2 
5. [x] Ensure imported bookmark folder structure is maintained on device 2
6. [x] Ensure bookmark favicons are shown after sync

## Data

1. [x] Make sure that data from the last version appears in the new version OK.
2. [x] Test that the previous version's cookies are preserved in the next version.

## Bookmarks

1. [x] Test that creating a bookmark on the bookmarks toolbar works
2. [x] Test that creating a bookmark folder on the bookmarks toolbar works
3. [x] Test that moving a bookmark into a folder by drag and drop on the bookmarks folder works
4. [x] Test that clicking a bookmark in the toolbar loads the bookmark.
5. [x] Test that clicking a bookmark in a bookmark toolbar folder loads the bookmark.

## Context menus
1. [x] Make sure context menu items in the URL bar work
2. [x] Make sure context menu items on content work with no selected text.
3. [x] Make sure context menu items on content work with selected text.
4. [x] Make sure context menu items on content work inside an editable control on `about:styles` (input, textarea, or contenteditable).

## Find on page

1. [x] Ensure search box is shown with shortcut
2. [x] Test successful find
3. [x] Test forward and backward find navigation
4. [x] Test failed find shows 0 results
5. [x] Test match case find

## Geolocation

1. [x] Check that https://developer.mozilla.org/en-US/docs/Web/API/Geolocation/Using_geolocation works

## Site hacks

1. [x] Test https://www.twitch.tv/adobe sub-page loads a video and you can play it

## Downloads

1. [x] Test downloading a file works and that all actions on the download item works.

## Fullscreen

1. [x] Test that entering full screen window works View -> Toggle Full Screen. And exit back (Not Esc).
2. [x] Test that entering HTML5 full screen works. And Esc to go back. (youtube.com)

## Tabs, Pinning and Tear off tabs

1. [ ] Test that tabs are pinnable
2. [ ] Test that tabs are unpinnable
3. [ ] Test that tabs are draggable to same tabset
4. [ ] Test that tabs are draggable to alternate tabset
5. [ ] Test that tabs can be detached to create a new window
6. [ ] Test that you are able to reattach a tab to an existing window
7. [ ] Test that you can quickly switch tabs

## Zoom

1. [x] Test zoom in / out shortcut works
2. [x] Test hamburger menu zooms.
3. [x] Test zoom saved when you close the browser and restore on a single site.
4. [x] Test zoom saved when you navigate within a single origin site.
5. [x] Test that navigating to a different origin resets the zoom

## Content tests

1. [ ] Go to https://brianbondy.com/ and click on the twitter icon on the top right. Test that context menus work in the new twitter tab.
2. [ ] Load twitter and click on a tweet so the popup div shows.   Click to dismiss and repeat with another div. Make sure it shows.
3. [x] Go to http://www.bennish.net/web-notifications.html and test that clicking on 'Show' pops up a notification asking for permission. Make sure that clicking 'Deny' leads to no notifications being shown.
4. [x] Go to https://trac.torproject.org/projects/tor/login and make sure that the password can be saved. Make sure the saved password shows up in `about:passwords`. Then reload https://trac.torproject.org/projects/tor/login and make sure the password is autofilled.
5. [x] Open a github issue and type some misspellings, make sure they are underlined.
6. [x] Make sure that right clicking on a word with suggestions gives a suggestion and that clicking on the suggestion replaces the text.
7. [x] Make sure that Command + Click (Control + Click on Windows, Control + Click on Ubuntu) on a link opens a new tab but does NOT switch to it.  Click on it and make sure it is already loaded.
8. [ ] Open an email on http://mail.google.com/ or inbox.google.com and click on a link. Make sure it works.
9. [x] Test that PDF is loaded at http://www.orimi.com/pdf-test.pdf
10. [x] Test that https://mixed-script.badssl.com/ shows up as grey not red (no mixed content scripts are run).

## Flash tests
1. [x] Turn on Flash in about:preferences#security. Test that clicking on 'Install Flash' banner on myspace.com shows a notification to allow Flash and that the banner disappears when 'Allow' is clicked.
2. [x] Test that flash placeholder appears on http://www.homestarrunner.com

## Autofill tests
1. [x] Test that autofill works on http://www.roboform.com/filling-test-all-fields

## Session storage

Do not forget to make a backup of your entire `~/Library/Application\ Support/Brave` folder.

1. [ ] Temporarily move away your `~/Library/Application\ Support/Brave/session-store-1` and test that clean session storage works. (`%appdata%\Brave in Windows`, `./config/brave` in Ubuntu)
2. [ ] Test that windows and tabs restore when closed, including active tab.
3. [ ] Move away your entire `~/Library/Application\ Support/Brave` folder (`%appdata%\Brave in Windows`, `./config/brave` in Ubuntu)

## Cookie and Cache

1. [ ] Make a backup of your profile, turn on all clearing in preferences and shut down.  Make sure when you bring the browser back up everything is gone that is specified.
2. [ ] Go to http://samy.pl/evercookie/ and set an evercookie. Check that going to prefs, clearing site data and cache, and going back to the Evercookie site does not remember the old evercookie value.

## Update tests

1. [ ] Test that updating using `BRAVE_UPDATE_VERSION=0.8.3` env variable works correctly.
