### ISSUE TITLE
Follow up of site splits

### ISSUE THREAD

**Issue by NejcZdovc** [brave/browser-laptop#10296]
Original PR #10136

### Known issues
- [x] bookmark toolbar is not refreshing when reordering https://github.com/brave/browser-laptop/pull/10136#issuecomment-320026616 (fix https://github.com/brave/browser-laptop/pull/10136#issuecomment-320083825) - fixed in #10325

### Tests
- [x] app/common/lib/historyUtil.js
- [x] app/common/state/aboutHistoryState.js
- [x] app/common/state/aboutNewTabState.js
- [x] app/common/state/bookmarkFoldersState.js
- [x] app/common/state/bookmarksState.js
