### ISSUE TITLE
Exclusion list for 0.18.x hotfix

### ISSUE THREAD

**Issue by alexwykoff** [brave/browser-laptop#10319]
Exclusion List:
 - [x] Upgrade to muon 4.3.9. ([#10262](https://github.com/brave/browser-laptop/issues/10262))
https://github.com/brave/browser-laptop/issues/10262
 - [x] Upgrade to Chromium 60.0.3112.90. ([#10261](https://github.com/brave/browser-laptop/issues/10261))
https://github.com/brave/browser-laptop/issues/10261
 - [x] Remove jsdox . ([#10254](https://github.com/brave/browser-laptop/issues/10254))
https://github.com/brave/browser-laptop/issues/10254
 - [x] Optimization Opportunities in extensionState. ([#10235](https://github.com/brave/browser-laptop/issues/10235))
https://github.com/brave/browser-laptop/issues/10235
 - [x] Extension popup menu items dismissed on click. ([#10130](https://github.com/brave/browser-laptop/issues/10130))
https://github.com/brave/browser-laptop/issues/10130
 - [x] Optimized window initialization data to use shared memory. ([#10018](https://github.com/brave/browser-laptop/issues/10018))
https://github.com/brave/browser-laptop/issues/10018
 - [x] Minimizing the browser window leaves the tooltip open. ([#8697](https://github.com/brave/browser-laptop/issues/8697))
https://github.com/brave/browser-laptop/issues/8697
 - [ ] Use shared memory for transfering window state to the browser process. ([#10292](https://github.com/brave/browser-laptop/issues/10292))
https://github.com/brave/browser-laptop/issues/10292
 - [ ] Short term video freezes. ([#9808](https://github.com/brave/browser-laptop/issues/9808))
https://github.com/brave/browser-laptop/issues/9808
- [ ]  Bitwarden widget not shown on webpages, shows only on about pages. (#9437)
- [ ]   Unhide bitwarden password manager. (#7921)
- [ ]   Added Bitwarden Password Manager. (#4776)
 - [ ] Clipboard copies URL instead of text selected on webpage. ([#10214](https://github.com/brave/browser-laptop/issues/10214))
https://github.com/brave/browser-laptop/issues/10214 
- [ ] Pinned tabs lost when browser closes abruptly . ([#10053](https://github.com/brave/browser-laptop/issues/10053)) https://github.com/brave/browser-laptop/issues/10053

**Comment by bsclifton** [comment]
@alexwykoff I checked each of the above- they should all be labelled properly and (if required) have steps 😄

**Comment by LaurenWags** [comment]
Updated Exclusion list from running changelog-generator

**Comment by srirambv** [comment]
Updated the list with Bitwarden tests

**Comment by LaurenWags** [comment]
Updated Exclusion list from running changelog-generator
