### ISSUE TITLE
Exclusion list for 0.18.x Hotfix 1

### ISSUE THREAD

**Issue by kjozwiak** [brave/browser-laptop#10747]
Exclusion List:
 - [ ] Brave fails to launch properly in the latest dev release. ([#10812](https://github.com/brave/browser-laptop/issues/10812))
https://github.com/brave/browser-laptop/issues/10812
 - [ ] MacOS signing issue when running buildInstaller.py. ([#10798](https://github.com/brave/browser-laptop/issues/10798))
https://github.com/brave/browser-laptop/issues/10798
 - [ ] Manual test run on Linux for 0.18.x Hotfix 1 (Release Channel) . ([#10785](https://github.com/brave/browser-laptop/issues/10785))
https://github.com/brave/browser-laptop/issues/10785
 - [ ] Manual test run on Windows x64 for 0.18.x Hotfix 1 (Release Channel). ([#10784](https://github.com/brave/browser-laptop/issues/10784))
https://github.com/brave/browser-laptop/issues/10784
 - [ ] Manual test run on Windows ia-32 for 0.18.x Hotfix 1 (Release Channel). ([#10783](https://github.com/brave/browser-laptop/issues/10783))
https://github.com/brave/browser-laptop/issues/10783
 - [ ] Manual test run on OS X for 0.18.x Hotfix 1 (Release Channel). ([#10782](https://github.com/brave/browser-laptop/issues/10782))
https://github.com/brave/browser-laptop/issues/10782
 - [ ] Support for Ubuntu Artful. ([#10755](https://github.com/brave/browser-laptop/issues/10755))
https://github.com/brave/browser-laptop/issues/10755
 - [ ] Manual test run on Linux for 0.18.x Hotfix 1 (Release Channel). ([#10746](https://github.com/brave/browser-laptop/issues/10746))
https://github.com/brave/browser-laptop/issues/10746
 - [ ] Manual test run on Windows x64 for 0.18.x Hotfix 1 (Release Channel). ([#10745](https://github.com/brave/browser-laptop/issues/10745))
https://github.com/brave/browser-laptop/issues/10745
 - [ ] Manual test run on Windows ia-32 for 0.18.x Hotfix 1 (Release Channel). ([#10744](https://github.com/brave/browser-laptop/issues/10744))
https://github.com/brave/browser-laptop/issues/10744
 - [ ] Manual test run on OS X for 0.18.x Hotfix 1 (Release Channel). ([#10743](https://github.com/brave/browser-laptop/issues/10743))
https://github.com/brave/browser-laptop/issues/10743
 - [ ] Manual test run on Linux x64 for 0.18.x Hotfix 1. ([#10734](https://github.com/brave/browser-laptop/issues/10734))
https://github.com/brave/browser-laptop/issues/10734
 - [ ] Manual test run on Windows x86 for 0.18.x Hotfix 1. ([#10733](https://github.com/brave/browser-laptop/issues/10733))
https://github.com/brave/browser-laptop/issues/10733
 - [ ] Manual test run on Windows x64 for 0.18.x Hotfix 1. ([#10732](https://github.com/brave/browser-laptop/issues/10732))
https://github.com/brave/browser-laptop/issues/10732
 - [ ] Manual test run on macOS x64 for 0.18.x Hotfix 1. ([#10731](https://github.com/brave/browser-laptop/issues/10731))
https://github.com/brave/browser-laptop/issues/10731
 - [ ] Fix unit tests on Windows. ([#10617](https://github.com/brave/browser-laptop/issues/10617))
https://github.com/brave/browser-laptop/issues/10617

**Comment by kjozwiak** [comment]
Updated after re-running the auto generator via `python braveautogen.py -t TEST` so the new manual passes aren't created in the milestone.
