### ISSUE TITLE
Extension: Tampermonkey

### ISSUE THREAD

**Issue by jonathansampson** [brave/browser-laptop#10981]
Extension: [Tampermonkey](https://chrome.google.com/webstore/detail/tampermonkey/dhdgffkkebhmkfjojejmpbldmpobfkfo?hl=en)

![image](https://user-images.githubusercontent.com/815158/30513463-511cb508-9ac9-11e7-874c-be305df6d167.png)

### Needed APIs:

**chrome.browserAction**

- [x] #5367 chrome.browserAction.setBadgeBackgroundColor
- [x] #5366 chrome.browserAction.setBadgeText
- [ ] #10985 chrome.browserAction.setIcon
- [ ] #10984 chrome.browserAction.setPopup
- [x] #8788 chrome.browserAction.setTitle

**chrome.commands**

- [ ] #9829 chrome.commands.onCommand

**chrome.contentSettings**

- [ ] #10996 chrome.contentSettings.javascript.clear
- [ ] #10996 chrome.contentSettings.javascript.get
- [ ] #10996 chrome.contentSettings.javascript.set

**chrome.contextMenus**

- [ ] #8331 chrome.contextMenus.create
- [ ] #8789 chrome.contextMenus.remove
- [x] #8815 chrome.contextMenus.removeAll
- [ ] #8332 chrome.contextMenus.update

**chrome.cookies**

- [ ] #6262 chrome.cookies.getAll

**chrome.downloads** _(Untested)_

- [ ] chrome.downloads.download
- [ ] chrome.downloads.onChanged.addListener

**chrome.extension** _(Untested)_

- [ ] chrome.extension.getViews
- [ ] chrome.extension.inIncognitoContext
- [ ] #10980 chrome.extension.isAllowedFileSchemeAccess

**chrome.i18n** _(Untested)_

- [ ] chrome.i18n.getAcceptLanguages
- [ ] chrome.i18n.getMessage
- [ ] chrome.i18n.getUILanguage

**chrome.idle** _(Untested)_

- [ ] chrome.idle.queryState

**chrome.management** _(Untested)_

- [ ] chrome.management.getAll
- [ ] chrome.management.setEnabled
- [ ] chrome.management.uninstall

**chrome.notifications** _(Untested)_

- [ ] chrome.notifications.clear
- [ ] chrome.notifications.create
- [ ] chrome.notifications.getPermissionLevel
- [ ] chrome.notifications.onClicked
- [ ] chrome.notifications.onClosed
- [ ] chrome.notifications.onPermissionLevelChanged

**chrome.permissions** _(Untested)_

- [ ] chrome.permissions.getAll
- [ ] chrome.permissions.remove
- [ ] chrome.permissions.request

**chrome.runtime** _(Untested)_

- [x] chrome.runtime.connect
- [x] chrome.runtime.getManifest
- [x] chrome.runtime.getURL
- [x] chrome.runtime.id
- [x] chrome.runtime.lastError
- [x] chrome.runtime.onConnect
- [ ] chrome.runtime.onConnectExternal
- [ ] chrome.runtime.onInstalled
- [x] chrome.runtime.onMessage
- [ ] chrome.runtime.onMessageExternal
- [ ] chrome.runtime.onUpdateAvailable
- [x] chrome.runtime.sendMessage

**chrome.storage** _(Untested)_

- [ ] chrome.storage.local.clear
- [ ] chrome.storage.local.get
- [ ] chrome.storage.local.remove
- [ ] chrome.storage.local.set
- [ ] chrome.storage.onChanged
- [ ] chrome.storage.sync.clear
- [ ] chrome.storage.sync.get
- [ ] chrome.storage.sync.remove
- [ ] chrome.storage.sync.set

**chrome.tabs** _(Untested)_

- [ ] chrome.tabs.create
- [ ] chrome.tabs.executeScript
- [ ] chrome.tabs.get
- [ ] chrome.tabs.getSelected
- [ ] chrome.tabs.highlight
- [ ] chrome.tabs.onActivated
- [ ] chrome.tabs.onRemoved
- [ ] chrome.tabs.onReplaced
- [ ] chrome.tabs.onUpdated
- [ ] chrome.tabs.query
- [ ] chrome.tabs.remove
- [x] chrome.tabs.sendMessage
- [ ] chrome.tabs.update

**chrome.webNavigation** _(Untested)_

- [ ] chrome.webNavigation.onCommitted
- [ ] chrome.webNavigation.onErrorOccurred

**chrome.webRequest** _(Untested)_

- [ ] chrome.webRequest.handlerBehaviorChanged
- [ ] chrome.webRequest.onBeforeRedirect
- [ ] chrome.webRequest.onBeforeRequest
- [ ] chrome.webRequest.onBeforeSendHeaders
- [ ] chrome.webRequest.onErrorOccurred
- [ ] chrome.webRequest.onHeadersReceived
- [ ] chrome.webRequset.onResponseStarted

**Comment by derjanb** [comment]
@jonathansampson 

Hi, Tampermonkey dev here. 
`commands` and `contextMenus` are not necessary to make Tampermonkey work. They are only used if present.

Just tell me if you need more information.

**Comment by bsclifton** [comment]
Closing as we will get extension support with [Brave Core](https://github.com/brave/brave-browser) and folks will be able to use the Chrome Web Store (or our own extension store)

**Comment by jamesscaur** [comment]
Looking forward to seeing Tampermonkey available with the new version of Brave...
