### ISSUE TITLE
Extension API: chrome.browserAction.setIcon

### ISSUE THREAD

**Issue by jonathansampson** [brave/browser-laptop#10985]
https://developer.chrome.com/extensions/browserAction#method-setIcon

### Related Issues:
- [ ] #4702 Pocket: chrome.browserAction.setIcon fails
- [ ] #6197 Extension API: chrome.browserAction.setIcon w/ imageData
- [ ] #8344 Extension API: chrome.browserAction.setIcon assumes a relative path
- [ ] #8500 Extension APIs: chrome.browserAction.setIcon fails with numerical tabId
