### ISSUE TITLE
Implement BAT matching funds promotion (UGP - user growth pool)

### ISSUE THREAD

**Issue by davidtemkin** [brave/browser-laptop#11100]
~With the launch of BAT Mercury, we will be creating an incentive program for users to add funds to their Brave wallet.~

The process will work as follows: Any user of the Brave desktop browser who updates to the BAT Mercury release will have at least their first $5 matched by Brave (from Brave's BAT User Growth Pool) when transferred to the Brave wallet. 

There are unfortunately still some unknowns, such as for what duration the promotion will run; will it be offered to a given user more than once, and if so at what frequency.

Regardless of the resolution of those outstanding questions, it is a requirement that the promotion be able to be switched off by setting a server-side flag. That is, if we find that the promotion is getting away from us for any reason, we will be able to discontinue it immediately, without requiring that users update their browsers.

This requires that the browser check with the server to see if the promotion has been disabled (likely when the Payments screen in Preferences is opened) and if it has been disabled, the elements of the UI that correspond to the promotion need to be disabled. This includes (in current UI designs) at least one dialog and one string. 

_**Sub-tasks**_
- [ ] Make BAT matching promotion configurable #11869
- [ ] Text on Payments screen should be retrieved from server side #11870
- [ ] Payments screen should have a "Claim free tokens" button #11871
- [ ] Show notification for BAT Matching - users with payments disabled #11867
- [ ] Show notification for BAT Matching - users with empty wallets #11868 
- [ ] Show notification for BAT Matching - users with non-empty wallets (TBD)

**Comment by NejcZdovc** [comment]
@davidtemkin is this release blocking issue?

**Comment by davidtemkin** [comment]
@NejcZdovc yes, at least some form of the matching funds promotion is a requirement for the release. perhaps we can simplify it, but we are planning to launch BAT Mercury with the promotion.

**Comment by bbondy** [comment]
Moved into 0.19.x release 2, need more info including designs before including. Chromium 62 is also slated for that release so we might want to push past even that milestone depending on if we have all details worked out.

**Comment by bbondy** [comment]
Removing milestone for now until we have specs on this.

**Comment by luixxiul** [comment]
quite basic question- on 0.19.x with #11874 will BATs be distributed to users or just a promotion message be displayed?

**Comment by bsclifton** [comment]
@luixxiul promotional messages are displayed and the integration with the server is done so that text shown is dynamic. The actual claim process happens server side (not in this code)

**Comment by luixxiul** [comment]
> The actual claim process happens server side (not in this code)

I got it, thanks! 😄 👍

**Comment by bsclifton** [comment]
Marked as `no-qa-needed` since the subtasks capture the specific things to test

**Comment by bradleyrichter** [comment]
@NejcZdovc Here is the language for the 3 message panels for UGP:

![image](https://user-images.githubusercontent.com/13509546/33354693-f2201354-d468-11e7-9ce0-cfeec5ae5ef9.png)



Congrats! 25 Tokens have been added to your account!

Please note that these tokens will expire in 90 days if not used, in whole or in part, towards your monthly Brave Payments contribution.

________
Sorry! The promotion has ended.

There may be additional Basic Attention Token promotions in the future so stay tuned!

_________

Uh oh. The Brave Payments server is not responding. Please try again later to claim your token grant.

Note: This error could also be caused by a network connection problem.
