### ISSUE TITLE
Ledger optimisations and cleanup

### ISSUE THREAD

**Issue by NejcZdovc** [brave/browser-laptop#11210]
### Description

- [ ] Move remaining functions from regular data to immutable
- [x] Add back flag for payments page in `browser/tabs.js`
- [x] Check why ledger page is enabled for a split second, before it's disabled while creating wallet #11387
- [x] Remove location item from `pageData->locations` when tab is closed (pages that have this tabID)
- [x] Clear pageData when browser is closed
- [x] Check if we can clear windows in synopsis publishers as well?
- [ ] Add unit tests
  - [ ] app/browser/api/ledger.js
  - [ ] app/browser/reducers/ledgerReducer.js
  - [ ] app/browser/reducers/pageDataReducer.js
  - [x] app/browser/reducers/siteSettingsReducer.js
  - [ ] app/common/lib/ledgerUtil.js
  - [ ] app/common/lib/pageDataUtil.js
  - [ ] app/common/state/ledgerState.js
  - [ ] app/common/state/pageDataState.js
  - [ ] app/common/state/siteSettingsState.js

**Comment by sergiorojasa** [comment]
I would like to work on this issue.

**Comment by bsclifton** [comment]
Closing - we've made lots of great progress in this area. For more specific tracking, check out the GitHub project that @NejcZdovc put together for Brave Payments:
https://github.com/brave/browser-laptop/projects/16#card-6746244
