### ISSUE TITLE
Per-release specialty test run on OS X for 0.20.x (Beta Channel)

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#12337]
## Per release specialty tests
 - [x] Shields menu cover entire browser view when clicked on view count. ([#11878](https://github.com/brave/browser-laptop/issues/11878))
 - [x] Pinning tabs when a window has been closed results in error. ([#11833](https://github.com/brave/browser-laptop/issues/11833))
 - [x] Action buttons on torrentViewer are not aligned with the title. ([#11800](https://github.com/brave/browser-laptop/issues/11800))
 - [ ] Reduce size of session-store-1 by removing 'data:' URLs. ([#11582](https://github.com/brave/browser-laptop/issues/11582))
 - [x] Bookmarks overflow indicator disappears. ([#11507](https://github.com/brave/browser-laptop/issues/11507))
 - [x] The first browserButton with 'groupedItem' should have margin-left: 0. ([#11288](https://github.com/brave/browser-laptop/issues/11288))
 - [x] Tab page (full of tabs) cannot be previewed. ([#11269](https://github.com/brave/browser-laptop/issues/11269))
 - [x] Pinning a tab leads to previous tab to be wrapped as pinned too. ([#11220](https://github.com/brave/browser-laptop/issues/11220))
 - [x] Display:flex ignores actual width of the buttons. ([#11201](https://github.com/brave/browser-laptop/issues/11201))
 - [x] BrowserButton should have -webkit-app-region: no-drag by default. ([#11111](https://github.com/brave/browser-laptop/issues/11111))
 - [x] Polish dropdown.js. ([#11063](https://github.com/brave/browser-laptop/issues/11063))
 - [x] PDF Presentation Mode banner lists Chrome Extension. ([#11020](https://github.com/brave/browser-laptop/issues/11020))
 - [x] Build from source causes white screen. ([#10995](https://github.com/brave/browser-laptop/issues/10995))
 - [x] Shift+click in a sortable table is broken after sorting it. ([#10971](https://github.com/brave/browser-laptop/issues/10971))
 - [x] Update siteInfo.js to our BEM style. ([#10932](https://github.com/brave/browser-laptop/issues/10932))
 - [x] BookmarkLocation is not working recursively when deleting folder. ([#10908](https://github.com/brave/browser-laptop/issues/10908))
 - [ ] Opening lots of tabs via "ctrl+t" and quickly closing them using "ctrl+w" created dead tabs. ([#10905](https://github.com/brave/browser-laptop/issues/10905))
 - [x] Apply display:block to sectionTitle. ([#10900](https://github.com/brave/browser-laptop/issues/10900))
 - [x] Create smooth transitions for tab components. ([#10883](https://github.com/brave/browser-laptop/issues/10883))
 - [x] Remove main.less. ([#10860](https://github.com/brave/browser-laptop/issues/10860))
 - [x] Active tab flicker on hover. ([#10838](https://github.com/brave/browser-laptop/issues/10838))
 - [x] Switch order should be same on the bravery shield panel and the preference page. ([#10813](https://github.com/brave/browser-laptop/issues/10813))
 - [x] Brave UA whitelist only applies to top level page loads. ([#10800](https://github.com/brave/browser-laptop/issues/10800))
 - [x] Bypass data: phishing warning by opening a URL in a new tab. ([#10754](https://github.com/brave/browser-laptop/issues/10754))
 - [ ] Unable to delete / using backspace in homepage field. ([#10703](https://github.com/brave/browser-laptop/issues/10703))
 - [x] Add English (U.K.) to browser language list. ([#10623](https://github.com/brave/browser-laptop/issues/10623))
 - [x] Intermittent - audio indicator is not shown. ([#10611](https://github.com/brave/browser-laptop/issues/10611))
 - [x] Convert helpfulText with Aphrodite. ([#10608](https://github.com/brave/browser-laptop/issues/10608))
 - [x] Tabs do not automatically resize until mousing over them.. ([#10582](https://github.com/brave/browser-laptop/issues/10582))
 - [x] Tabs cannot be muted via speaker icon. ([#10544](https://github.com/brave/browser-laptop/issues/10544))
 - [x] .dialog should have 'outline: none' on focus. ([#10536](https://github.com/brave/browser-laptop/issues/10536))
 - [x] Suggestion: Update MDN name on Search Setting. ([#10511](https://github.com/brave/browser-laptop/issues/10511))
 - [x] Pinned tabs disappear until close/relaunch. ([#10510](https://github.com/brave/browser-laptop/issues/10510))
 - [x] Favicons of imported bookmarks on the toolbar are missing. ([#10503](https://github.com/brave/browser-laptop/issues/10503))
 - [x] Can't create folder when selecting the download folder. ([#10479](https://github.com/brave/browser-laptop/issues/10479))
 - [x] Preserve z-index of windows when restoring from the session. ([#10473](https://github.com/brave/browser-laptop/issues/10473))
 - [x] Description for Session Tab on Hover. ([#10464](https://github.com/brave/browser-laptop/issues/10464))
 - [x] Tables on about:history and about:bookmarks does not have 100% width. ([#10450](https://github.com/brave/browser-laptop/issues/10450))
 - [ ] Replace node classList instances with dataset. ([#10443](https://github.com/brave/browser-laptop/issues/10443))
 - [x] Can't set minimum visits for publisher relevancy. ([#10439](https://github.com/brave/browser-laptop/issues/10439))
 - [x] LedgerTable with pinned sites does not have the orange border. ([#10434](https://github.com/brave/browser-laptop/issues/10434))
 - [x] Add findx as a Search Provider. ([#10432](https://github.com/brave/browser-laptop/issues/10432))
 - [x] Bookmark name updates when you View Page Source. ([#10372](https://github.com/brave/browser-laptop/issues/10372))
 - [x] Increase Padding on Pinned Tabs. ([#10368](https://github.com/brave/browser-laptop/issues/10368))
 - [x] Add accelerator keys for new session tab menu entries. ([#10363](https://github.com/brave/browser-laptop/issues/10363))
 - [ ] Split navigator in smaller components. ([#10354](https://github.com/brave/browser-laptop/issues/10354))
 - [x] Bookmarked icon keeps displayed after the bookmark is deleted. ([#10348](https://github.com/brave/browser-laptop/issues/10348))
 - [x] Update advancedSettings.js to the modified BEM style. ([#10339](https://github.com/brave/browser-laptop/issues/10339))
 - [x] Update disabledContent.js to the modified BEM style. ([#10336](https://github.com/brave/browser-laptop/issues/10336))
 - [x] Brave.com should be able to detect if you visit using Brave. ([#10329](https://github.com/brave/browser-laptop/issues/10329))
 - [x] Deleting history entries should remove them from 'History' menu. ([#10328](https://github.com/brave/browser-laptop/issues/10328))
 - [x] Do not show loading icon for about pages. ([#10303](https://github.com/brave/browser-laptop/issues/10303))
 - [ ] Browser freeze when syncing to profile with 6000+ bookmarks. ([#10273](https://github.com/brave/browser-laptop/issues/10273))
 - [ ] Paused download shows Infinity%. ([#10264](https://github.com/brave/browser-laptop/issues/10264))
 - [x] Add Panel Dropdown to styles.js. ([#10245](https://github.com/brave/browser-laptop/issues/10245))
 - [x] Restructure paymentsTab with grid property. ([#10236](https://github.com/brave/browser-laptop/issues/10236))
 - [ ] Remove keytar dependency. ([#10226](https://github.com/brave/browser-laptop/issues/10226))
 - [x] Update extensionsTab.js to our modified BEM style. ([#10207](https://github.com/brave/browser-laptop/issues/10207))
 - [x] Bookmarks cannot be moved to Other Bookmarks folder. ([#10157](https://github.com/brave/browser-laptop/issues/10157))
 - [x] Margin changes when payments is enabled and disabled. ([#10153](https://github.com/brave/browser-laptop/issues/10153))
 - [x] Apply panelItem to addFunds button. ([#10141](https://github.com/brave/browser-laptop/issues/10141))
 - [ ] Update react to ~15.6.1. ([#10126](https://github.com/brave/browser-laptop/issues/10126))
 - [ ] Tab preview does not work properly with DnD. ([#10103](https://github.com/brave/browser-laptop/issues/10103))
 - [ ] Split bookmark manager component and move it into app folder. ([#10075](https://github.com/brave/browser-laptop/issues/10075))
 - [x] Context menu bookmarks. ([#10054](https://github.com/brave/browser-laptop/issues/10054))
 - [x] Do not allow emojis for page title in titlemode. ([#10051](https://github.com/brave/browser-laptop/issues/10051))
 - [ ] Import Encrypted Cookies from Chrome. ([#10045](https://github.com/brave/browser-laptop/issues/10045))
 - [ ] Encrypt Cookies. ([#10044](https://github.com/brave/browser-laptop/issues/10044))
 - [ ] Data: URL warning popup should disappear when the window is navigated. ([#10039](https://github.com/brave/browser-laptop/issues/10039))
 - [x] Pinned tab disappears by reordering and unpinning. ([#10037](https://github.com/brave/browser-laptop/issues/10037))
 - [ ] Bookmarks toolbar : imported sorted bookmarks are represented in wacky order. ([#10026](https://github.com/brave/browser-laptop/issues/10026))
 - [x] Add groupedItem to BrowserButton on noScriptInfo.js. ([#9981](https://github.com/brave/browser-laptop/issues/9981))
 - [ ] Split sites into separate entities.. ([#9978](https://github.com/brave/browser-laptop/issues/9978))
 - [x] Buttons on messageBox should be grouped. ([#9973](https://github.com/brave/browser-laptop/issues/9973))
 - [ ] Pinning a PDF tab causes it to duplicate . ([#9954](https://github.com/brave/browser-laptop/issues/9954))
 - [ ] Bookmarks not fitting in the bookmark bar. ([#9939](https://github.com/brave/browser-laptop/issues/9939))
 - [x] Avoid bravery panel width from increasing. ([#9839](https://github.com/brave/browser-laptop/issues/9839))
 - [ ] Redundant Suggestions. ([#9827](https://github.com/brave/browser-laptop/issues/9827))
 - [ ] Changing tabset count messes up tab favicon and close button. ([#9779](https://github.com/brave/browser-laptop/issues/9779))
 - [x] MacOS Specific - Pinning a normal tab causes browser crash but retains the pinned tabs upon restart. ([#9763](https://github.com/brave/browser-laptop/issues/9763))
 - [ ] Rename Yes/No buttons to Allow/Deny for easier understanding. ([#9750](https://github.com/brave/browser-laptop/issues/9750))
 - [x] Add rel="noopener" to all external links with target="_blank". ([#9743](https://github.com/brave/browser-laptop/issues/9743))
 - [x] History inside autocomplete suggestions cannot be cleared until the browser is closed. ([#9736](https://github.com/brave/browser-laptop/issues/9736))
 - [x] Restoring session after re-opening windows does not restore position. ([#9709](https://github.com/brave/browser-laptop/issues/9709))
 - [ ] Browser crashes by pinning sites, reordering them, and visiting a site via dashboard. ([#9635](https://github.com/brave/browser-laptop/issues/9635))
 - [ ] Swipe Navigation Sensitivity Setting. ([#9615](https://github.com/brave/browser-laptop/issues/9615))
 - [ ] Move bookmark text calculation into the state. ([#9517](https://github.com/brave/browser-laptop/issues/9517))
 - [ ] Multiple screens , brave browser out of scope of the screen . ([#9371](https://github.com/brave/browser-laptop/issues/9371))
 - [ ] Custom bookmark title is not being displayed in suggestions. ([#9326](https://github.com/brave/browser-laptop/issues/9326))
 - [ ] Changing bookmark location causes duplicate bookmarks. ([#9301](https://github.com/brave/browser-laptop/issues/9301))
 - [x] Refactor findbar with Aphrodite. ([#9233](https://github.com/brave/browser-laptop/issues/9233))
 - [x] Notification bar - buttons not responding. ([#9171](https://github.com/brave/browser-laptop/issues/9171))
 - [x] Autoplay notification should be dismissed if user ignores notification and continues stream. ([#9143](https://github.com/brave/browser-laptop/issues/9143))
 - [x] Make Autofill country field into a dropdown list . ([#9053](https://github.com/brave/browser-laptop/issues/9053))
 - [ ] Fingerprinting protection should distinguish between first and third party. ([#9029](https://github.com/brave/browser-laptop/issues/9029))
 - [x] Playing media on a site adds it to the autoplay site permission list (even when defaulted to "always allow"). ([#9008](https://github.com/brave/browser-laptop/issues/9008))
 - [x] "open in new window" should cascade instead of layering at same x/y. ([#8925](https://github.com/brave/browser-laptop/issues/8925))
 - [ ] Make tab preview based on mouse idle time. ([#8860](https://github.com/brave/browser-laptop/issues/8860))
 - [ ] "Folder Upload" feature in Google Drive Broken. ([#8601](https://github.com/brave/browser-laptop/issues/8601))
 - [x] Revert span element to button on urlBar.js. ([#8457](https://github.com/brave/browser-laptop/issues/8457))
 - [x] Tabs No Longer Show Full-Color Emoji. ([#8414](https://github.com/brave/browser-laptop/issues/8414))
 - [x] Clicking labels should trigger click of associated element. ([#8243](https://github.com/brave/browser-laptop/issues/8243))
 - [ ] New windows are just white for a bit.. ([#8128](https://github.com/brave/browser-laptop/issues/8128))
 - [ ] Bookmark moved to a folder on the toolbar cannot be removed via the star button. ([#8022](https://github.com/brave/browser-laptop/issues/8022))
 - [x] Add extension inspectors. ([#8012](https://github.com/brave/browser-laptop/issues/8012))
 - [x] Throttling between window resize cause tabContent to pop. ([#7925](https://github.com/brave/browser-laptop/issues/7925))
 - [x] Tab title often isn't updated until the cursor is moved over it or tab focus is changed. ([#7765](https://github.com/brave/browser-laptop/issues/7765))
 - [x] Downloading the same name file disabling the save file dialog should change the filename. ([#7764](https://github.com/brave/browser-laptop/issues/7764))
 - [x] Title on new tab flickers after setting the language to Russian. ([#7730](https://github.com/brave/browser-laptop/issues/7730))
 - [x] Tabs display wrong after exiting HTML5 fullscreen. ([#7301](https://github.com/brave/browser-laptop/issues/7301))
 - [x] Selecting subfolders on the bookmark bar which have many entries can be quite laggy. ([#7053](https://github.com/brave/browser-laptop/issues/7053))
 - [x] Bookmark hanger shows a wrong folder name. ([#7032](https://github.com/brave/browser-laptop/issues/7032))
 - [x] Fading effect b/w tabs feels like flickering. ([#6716](https://github.com/brave/browser-laptop/issues/6716))
 - [ ] Remove customTitle from siteDetail object. ([#6585](https://github.com/brave/browser-laptop/issues/6585))
 - [ ] Bookmark title on bookmark toolbar is renamed. ([#6108](https://github.com/brave/browser-laptop/issues/6108))
 - [ ] Address bar should autocomplete from custom bookmark titles. ([#6104](https://github.com/brave/browser-laptop/issues/6104))
 - [x] Follow-up to #5724: the bravery panel should be much wider. ([#5726](https://github.com/brave/browser-laptop/issues/5726))
 - [x] Last Visited on Bookmark Manager is not recorded for newly created bookmarks. ([#5699](https://github.com/brave/browser-laptop/issues/5699))
 - [x] Not keeping browser height after close-reopen. ([#5537](https://github.com/brave/browser-laptop/issues/5537))
 - [ ] Clicking entries on about:history is laggy. ([#5382](https://github.com/brave/browser-laptop/issues/5382))
 - [ ] About:history omits recent history. ([#5072](https://github.com/brave/browser-laptop/issues/5072))
 - [ ] Bookmark title automatically changes on the bookmark form. ([#4929](https://github.com/brave/browser-laptop/issues/4929))
 - [ ] Rebookmarking from context menu does not reset bookmark title. ([#4868](https://github.com/brave/browser-laptop/issues/4868))
 - [ ] Bookmark title dynamically changed. ([#4833](https://github.com/brave/browser-laptop/issues/4833))
 - [x] Brave cannot load PDFs with JS PDF reader in session tabs. ([#4651](https://github.com/brave/browser-laptop/issues/4651))
 - [ ] Edited information of bookmark does not appear on bookmark dialog via star icon. ([#4260](https://github.com/brave/browser-laptop/issues/4260))
 - [ ] Hidden history entries appear by deleting the latest entry. ([#4224](https://github.com/brave/browser-laptop/issues/4224))
 - [x] Organize strings in .properties files. ([#3958](https://github.com/brave/browser-laptop/issues/3958))
 - [x] Brave crashes when tabs are pinned(Intermittent issues). ([#3760](https://github.com/brave/browser-laptop/issues/3760))
 - [x] Brave doesn't remember last position and size if you set it to start with homepage. ([#3754](https://github.com/brave/browser-laptop/issues/3754))
 - [ ] Bookmarks title changes when navigating around the page. ([#3646](https://github.com/brave/browser-laptop/issues/3646))
 - [x] Usernames are persisting in autofill despite clearing data. . ([#3541](https://github.com/brave/browser-laptop/issues/3541))
 - [ ] Don't show tab preview unless mouse velocity is low enough (and decelerating?). ([#3271](https://github.com/brave/browser-laptop/issues/3271))
 - [ ] Bookmark folder is created left of bookmark item, not right. ([#2771](https://github.com/brave/browser-laptop/issues/2771))
 - [ ] Bookmark name of a file does not appear in the autocomplete list. ([#2655](https://github.com/brave/browser-laptop/issues/2655))
 - [x] Two-finger swipe gesture on macOS should have visual indicator. ([#2477](https://github.com/brave/browser-laptop/issues/2477))
 - [ ] Removing sites from history - `siteUtil` functionality. ([#1856](https://github.com/brave/browser-laptop/issues/1856))
 - [ ] Wrong favicon is shown for bookmark. ([#1646](https://github.com/brave/browser-laptop/issues/1646))

**Comment by srirambv** [comment]
Closing in favour of #12405
