### ISSUE TITLE
Per-release specialty test run on Linux for 0.20.x (Beta Channel)

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#12339]
## Per release specialty tests
 - [ ] Hyperlinks in about:brave always looks grey. ([#12015](https://github.com/brave/browser-laptop/issues/12015))
 - [ ] Automatically append user-data-dir-name on Linux for different channels. ([#11900](https://github.com/brave/browser-laptop/issues/11900))
 - [x] Shields menu cover entire browser view when clicked on view count. ([#11878](https://github.com/brave/browser-laptop/issues/11878))
 - [x] Pinning tabs when a window has been closed results in error. ([#11833](https://github.com/brave/browser-laptop/issues/11833))
 - [x] Move language setting under advanced tab. ([#11814](https://github.com/brave/browser-laptop/issues/11814))
 - [x] Spellcheck setting is too tied to languages option. ([#11811](https://github.com/brave/browser-laptop/issues/11811))
 - [x] Action buttons on torrentViewer are not aligned with the title. ([#11800](https://github.com/brave/browser-laptop/issues/11800))
 - [ ] Reduce size of session-store-1 by removing 'data:' URLs. ([#11582](https://github.com/brave/browser-laptop/issues/11582))
 - [ ] Bookmarks overflow indicator disappears. ([#11507](https://github.com/brave/browser-laptop/issues/11507))
 - [x] Pinning a tab leads to previous tab to be wrapped as pinned too. ([#11220](https://github.com/brave/browser-laptop/issues/11220))
 - [ ] Build from source causes white screen. ([#10995](https://github.com/brave/browser-laptop/issues/10995))
 - [ ] Opening lots of tabs via "ctrl+t" and quickly closing them using "ctrl+w" created dead tabs. ([#10905](https://github.com/brave/browser-laptop/issues/10905))
 - [x] Can't set minimum visits for publisher relevancy. ([#10439](https://github.com/brave/browser-laptop/issues/10439))
 - [ ] LedgerTable with pinned sites does not have the orange border. ([#10434](https://github.com/brave/browser-laptop/issues/10434))
 - [ ] Update advancedSettings.js to the modified BEM style. ([#10339](https://github.com/brave/browser-laptop/issues/10339))
 - [ ] Browser freeze when syncing to profile with 6000+ bookmarks. ([#10273](https://github.com/brave/browser-laptop/issues/10273))
 - [ ] Remove keytar dependency. ([#10226](https://github.com/brave/browser-laptop/issues/10226))
 - [ ] Import Encrypted Cookies from Chrome. ([#10045](https://github.com/brave/browser-laptop/issues/10045))
 - [ ] Bookmarks not fitting in the bookmark bar. ([#9939](https://github.com/brave/browser-laptop/issues/9939))
 - [ ] Move bookmark text calculation into the state. ([#9517](https://github.com/brave/browser-laptop/issues/9517))
 - [ ] Multiple screens , brave browser out of scope of the screen . ([#9371](https://github.com/brave/browser-laptop/issues/9371))
 - [ ] "Folder Upload" feature in Google Drive Broken. ([#8601](https://github.com/brave/browser-laptop/issues/8601))
 - [x] Clicking labels should trigger click of associated element. ([#8243](https://github.com/brave/browser-laptop/issues/8243))
 - [ ] New windows are just white for a bit.. ([#8128](https://github.com/brave/browser-laptop/issues/8128))
 - [ ] Brave will not install on OpenSuse. ([#6946](https://github.com/brave/browser-laptop/issues/6946))
 - [x] Brave cannot load PDFs with JS PDF reader in session tabs. ([#4651](https://github.com/brave/browser-laptop/issues/4651))
 - [x] The position of bookmarks on the toolbar shouldn't be preserved after re-bookmarking. ([#2447](https://github.com/brave/browser-laptop/issues/2447))

**Comment by srirambv** [comment]
Closing in favour of #12407
