### ISSUE TITLE
Release checklist for 0.19.x Hotfix 8 (Release channel)

### ISSUE THREAD

**Issue by kjozwiak** [brave/browser-laptop#12331]
# Release Process Checklist

Feel free to copy this into an issue if you want to keep track of items per-milestone.
Be super sure that <version> is replaced with the version you wish to use.

### First-time Setup
- [x] `git clone git@github.com:brave/vault-updater && cd vault-updater`
- [x] `git clone git@github.com:brave/release-tools`
- [x] `npm install`
- [x] install the heroku toolbelt https://toolbelt.heroku.com/ , ask @mrose17 to add you
- [x] `git remote add heroku-staged https://git.heroku.com/brave-laptop-updates-pre.git`
- [x] `git remote add heroku https://git.heroku.com/brave-laptop-updates.git`
- [x] *(optional) you can check logs : `heroku logs --tail --app brave-laptop-updates-pre`

### Every time thereafter
- [x] `cd vault-updater`
- [x] `git pull`
- [x] `git checkout -b dev-<version>`
- [x] `cd ../release-tools`
- [x] `node bin/promotePreview.js --location ../vault-updater/data --overwrite --channel=dev --notes='Notes go here'`
- [x] `cd ../vault-updater`
- [x] `git add -u`
- [x] `git commit -m "<version>" -m "Auditors: @aekeus"`
- [x] `git push (alternatively: git push --set-upstream origin dev-<version>)`
- [x] `git push heroku-staged dev-<version>:master`

## Fastly
- [x] Log into Fastly and purge the cache

## Test Staging
- [x] Install a prior version of the app
- [x] `BRAVE_UPDATE_HOST=https://laptop-updates-pre.brave.com open -a ./Brave.app`
- [x] Confirm SHA in about:brave matches expectations

## Merge Into Master
- [x] `git checkout master`
- [x] `git merge dev-<version>`
- [x] `git push`

## Release Notes
- [x] Edit the release notes title and uncheck the box to publish : https://github.com/brave/browser-laptop/releases
- [x] Update dependency release notes as needed
- [x] Add release notes into https://community.brave.com/

## Push To Production
- [x] `git push heroku`

## Updates And Broadcast
- [x] Wait for confirmation that Windows live update works
- [ ] Wait for confirmation that Linux live update works
- [x] Wait for confirmation that macOS live update works
- [x] Notify w0ts0n and update the Brave Snap Package under Ubuntu
- [x] Notify #browser, #community, #general, #pr, #testers of the latest release with a link to the release notes
- [x] Add a screenshot to the #pr channel for social broadcast

## Update crash server
- [x] Modify BRAVE_VERSIONS env. var. on brave-stats to include brave/electron version (at most three versions) (`BRAVE_VERSIONS='1.3.1 1.3.2 1.3.3'`) We need to keep to a maximum of three versions currently.
- [x] Modify `NODE_MODULES_CACHE` env. var. to force node_modules reload (`NODE_MODULES_CACHE=false`)
- [x] Commit empty change for Heroku (`git commit -am 'install electron symbols for 1.3.3, remove old version' --allow-empty`)
- [x] `git push heroku master`

## Update Release channel wiki
- [x] Update entries here as needed: https://github.com/brave/browser-laptop/wiki/Release-channels

## Branch Channel Maintenance
- [x] Create branch channel if needed
