### ISSUE TITLE
Per-release specialty test run on Windows x64 for 0.20.x (Beta Channel)

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#12406]
## Per release specialty tests
 - [x] Move folder into Other bookmarks. ([#12378](https://github.com/brave/browser-laptop/issues/12378))
 - [x] Duplicate pinned tabs on tear off window which doesn't close when all tabs are closed. ([#12377](https://github.com/brave/browser-laptop/issues/12377))
 - [x] Option to disable promotions. ([#12313](https://github.com/brave/browser-laptop/issues/12313))
 - [x] Update Brave CSPs. ([#12263](https://github.com/brave/browser-laptop/issues/12263))
 - [x] Restart notification should be global notification bar. ([#12216](https://github.com/brave/browser-laptop/issues/12216))
 - [x] Pinning tabs with multiple windows open results in duplicates. ([#11861](https://github.com/brave/browser-laptop/issues/11861))
 - [x] About:blank on URL bar of a tab opened with control key. ([#11796](https://github.com/brave/browser-laptop/issues/11796))
 - [ ] Reduce size of session-store-1 by removing 'data:' URLs. ([#11582](https://github.com/brave/browser-laptop/issues/11582))
 - [ ] Fix bug where users behind multiple releases could get preview releases (Windows only). ([#11152](https://github.com/brave/browser-laptop/issues/11152))
 - [x] Extension icons do not appear at top right of app. ([#11142](https://github.com/brave/browser-laptop/issues/11142))
 - [x] Create smooth transitions for tab components. ([#10883](https://github.com/brave/browser-laptop/issues/10883))
 - [x] OnTabMouseMove is called too many times. ([#10689](https://github.com/brave/browser-laptop/issues/10689))
 - [x] Intermittent - audio indicator is not shown. ([#10611](https://github.com/brave/browser-laptop/issues/10611))
 - [x] Tabs do not automatically resize until mousing over them.. ([#10582](https://github.com/brave/browser-laptop/issues/10582))
 - [x] Tabs cannot be muted via speaker icon. ([#10544](https://github.com/brave/browser-laptop/issues/10544))
 - [x] Description for Session Tab on Hover. ([#10464](https://github.com/brave/browser-laptop/issues/10464))
 - [ ] Replace node classList instances with dataset. ([#10443](https://github.com/brave/browser-laptop/issues/10443))
 - [x] Split navigator in smaller components. ([#10354](https://github.com/brave/browser-laptop/issues/10354))
 - [ ] Browser freeze when syncing to profile with 6000+ bookmarks. ([#10273](https://github.com/brave/browser-laptop/issues/10273))
 - [ ] Restructure paymentsTab with grid property. ([#10236](https://github.com/brave/browser-laptop/issues/10236))
 - [ ] Remove keytar dependency. ([#10226](https://github.com/brave/browser-laptop/issues/10226))
 - [ ] Update react to ~15.6.1. ([#10126](https://github.com/brave/browser-laptop/issues/10126))
 - [ ] No tab close icon is shown for the active tab on Windows. ([#10123](https://github.com/brave/browser-laptop/issues/10123))
 - [x] Tab preview does not work properly with DnD. ([#10103](https://github.com/brave/browser-laptop/issues/10103))
 - [x] Import Encrypted Cookies from Chrome. ([#10045](https://github.com/brave/browser-laptop/issues/10045))
 - [x] Pinned tab disappears by reordering and unpinning. ([#10037](https://github.com/brave/browser-laptop/issues/10037))
 - [x] Bookmarks toolbar : imported sorted bookmarks are represented in wacky order. ([#10026](https://github.com/brave/browser-laptop/issues/10026))
 - [x] Split sites into separate entities.. ([#9978](https://github.com/brave/browser-laptop/issues/9978))
 - [x] Rename Yes/No buttons to Allow/Deny for easier understanding. ([#9750](https://github.com/brave/browser-laptop/issues/9750))
 - [x] Browser crashes by pinning sites, reordering them, and visiting a site via dashboard. ([#9635](https://github.com/brave/browser-laptop/issues/9635))
 - [x] Move bookmark text calculation into the state. ([#9517](https://github.com/brave/browser-laptop/issues/9517))
 - [ ] Multiple screens , brave browser out of scope of the screen . ([#9371](https://github.com/brave/browser-laptop/issues/9371))
 - [ ] Rebookmarking from context menu does not reset bookmark title. ([#4868](https://github.com/brave/browser-laptop/issues/4868))
 - [ ] Bookmark folder is created left of bookmark item, not right. ([#2771](https://github.com/brave/browser-laptop/issues/2771))
 - [x] PDFJS returns CORS error when PDF is loaded directly. ([#2715](https://github.com/brave/browser-laptop/issues/2715))

**Comment by srirambv** [comment]
Closing in favour of #12461
