### ISSUE TITLE
Per-release specialty test run on OS X for 0.20.x (Beta Channel)

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#12405]
## Per release specialty tests
 - [ ] Move folder into Other bookmarks. ([#12378](https://github.com/brave/browser-laptop/issues/12378))
 - [ ] Duplicate pinned tabs on tear off window which doesn't close when all tabs are closed. ([#12377](https://github.com/brave/browser-laptop/issues/12377))
 - [ ] Reload is not working. ([#12375](https://github.com/brave/browser-laptop/issues/12375))
 - [ ] Submenu's not being dismissed under the kabob menu. ([#12363](https://github.com/brave/browser-laptop/issues/12363))
 - [ ] Option to disable promotions. ([#12313](https://github.com/brave/browser-laptop/issues/12313))
 - [ ] Update Brave CSPs. ([#12263](https://github.com/brave/browser-laptop/issues/12263))
 - [ ] Restart notification should be global notification bar. ([#12216](https://github.com/brave/browser-laptop/issues/12216))
 - [ ] Pinning tabs with multiple windows open results in duplicates. ([#11861](https://github.com/brave/browser-laptop/issues/11861))
 - [ ] About:blank on URL bar of a tab opened with control key. ([#11796](https://github.com/brave/browser-laptop/issues/11796))
 - [ ] Brave Beta/Developer fails to launch. ([#11791](https://github.com/brave/browser-laptop/issues/11791))
 - [ ] Reduce size of session-store-1 by removing 'data:' URLs. ([#11582](https://github.com/brave/browser-laptop/issues/11582))
 - [ ] Extension icons do not appear at top right of app. ([#11142](https://github.com/brave/browser-laptop/issues/11142))
 - [ ] Unable to delete / using backspace in homepage field. ([#10703](https://github.com/brave/browser-laptop/issues/10703))
 - [ ] OnTabMouseMove is called too many times. ([#10689](https://github.com/brave/browser-laptop/issues/10689))
 - [ ] Replace node classList instances with dataset. ([#10443](https://github.com/brave/browser-laptop/issues/10443))
 - [ ] Split navigator in smaller components. ([#10354](https://github.com/brave/browser-laptop/issues/10354))
 - [ ] Browser freeze when syncing to profile with 6000+ bookmarks. ([#10273](https://github.com/brave/browser-laptop/issues/10273))
 - [ ] Paused download shows Infinity%. ([#10264](https://github.com/brave/browser-laptop/issues/10264))
 - [ ] Remove keytar dependency. ([#10226](https://github.com/brave/browser-laptop/issues/10226))
 - [ ] Update react to ~15.6.1. ([#10126](https://github.com/brave/browser-laptop/issues/10126))
 - [ ] Tab preview does not work properly with DnD. ([#10103](https://github.com/brave/browser-laptop/issues/10103))
 - [ ] Split bookmark manager component and move it into app folder. ([#10075](https://github.com/brave/browser-laptop/issues/10075))
 - [ ] Import Encrypted Cookies from Chrome. ([#10045](https://github.com/brave/browser-laptop/issues/10045))
 - [ ] Encrypt Cookies. ([#10044](https://github.com/brave/browser-laptop/issues/10044))
 - [ ] Data: URL warning popup should disappear when the window is navigated. ([#10039](https://github.com/brave/browser-laptop/issues/10039))
 - [ ] Bookmarks toolbar : imported sorted bookmarks are represented in wacky order. ([#10026](https://github.com/brave/browser-laptop/issues/10026))
 - [ ] Split sites into separate entities.. ([#9978](https://github.com/brave/browser-laptop/issues/9978))
 - [ ] Pinning a PDF tab causes it to duplicate . ([#9954](https://github.com/brave/browser-laptop/issues/9954))
 - [ ] Redundant Suggestions. ([#9827](https://github.com/brave/browser-laptop/issues/9827))
 - [ ] Changing tabset count messes up tab favicon and close button. ([#9779](https://github.com/brave/browser-laptop/issues/9779))
 - [ ] Rename Yes/No buttons to Allow/Deny for easier understanding. ([#9750](https://github.com/brave/browser-laptop/issues/9750))
 - [ ] Browser crashes by pinning sites, reordering them, and visiting a site via dashboard. ([#9635](https://github.com/brave/browser-laptop/issues/9635))
 - [ ] Move bookmark text calculation into the state. ([#9517](https://github.com/brave/browser-laptop/issues/9517))
 - [ ] Multiple screens , brave browser out of scope of the screen . ([#9371](https://github.com/brave/browser-laptop/issues/9371))
 - [ ] Custom bookmark title is not being displayed in suggestions. ([#9326](https://github.com/brave/browser-laptop/issues/9326))
 - [ ] Changing bookmark location causes duplicate bookmarks. ([#9301](https://github.com/brave/browser-laptop/issues/9301))
 - [ ] Fingerprinting protection should distinguish between first and third party. ([#9029](https://github.com/brave/browser-laptop/issues/9029))
 - [ ] Make tab preview based on mouse idle time. ([#8860](https://github.com/brave/browser-laptop/issues/8860))
 - [ ] New windows are just white for a bit.. ([#8128](https://github.com/brave/browser-laptop/issues/8128))
 - [ ] Bookmark moved to a folder on the toolbar cannot be removed via the star button. ([#8022](https://github.com/brave/browser-laptop/issues/8022))
 - [ ] Remove customTitle from siteDetail object. ([#6585](https://github.com/brave/browser-laptop/issues/6585))
 - [ ] Bookmark title on bookmark toolbar is renamed. ([#6108](https://github.com/brave/browser-laptop/issues/6108))
 - [ ] Address bar should autocomplete from custom bookmark titles. ([#6104](https://github.com/brave/browser-laptop/issues/6104))
 - [ ] Clicking entries on about:history is laggy. ([#5382](https://github.com/brave/browser-laptop/issues/5382))
 - [ ] About:history omits recent history. ([#5072](https://github.com/brave/browser-laptop/issues/5072))
 - [ ] Bookmark title automatically changes on the bookmark form. ([#4929](https://github.com/brave/browser-laptop/issues/4929))
 - [ ] Rebookmarking from context menu does not reset bookmark title. ([#4868](https://github.com/brave/browser-laptop/issues/4868))
 - [ ] Bookmark title dynamically changed. ([#4833](https://github.com/brave/browser-laptop/issues/4833))
 - [ ] Edited information of bookmark does not appear on bookmark dialog via star icon. ([#4260](https://github.com/brave/browser-laptop/issues/4260))
 - [ ] Hidden history entries appear by deleting the latest entry. ([#4224](https://github.com/brave/browser-laptop/issues/4224))
 - [ ] Bookmarks title changes when navigating around the page. ([#3646](https://github.com/brave/browser-laptop/issues/3646))
 - [ ] Don't show tab preview unless mouse velocity is low enough (and decelerating?). ([#3271](https://github.com/brave/browser-laptop/issues/3271))
 - [ ] Bookmark folder is created left of bookmark item, not right. ([#2771](https://github.com/brave/browser-laptop/issues/2771))
 - [ ] PDFJS returns CORS error when PDF is loaded directly. ([#2715](https://github.com/brave/browser-laptop/issues/2715))
 - [ ] Bookmark name of a file does not appear in the autocomplete list. ([#2655](https://github.com/brave/browser-laptop/issues/2655))
 - [ ] Removing sites from history - `siteUtil` functionality. ([#1856](https://github.com/brave/browser-laptop/issues/1856))
 - [ ] Wrong favicon is shown for bookmark. ([#1646](https://github.com/brave/browser-laptop/issues/1646))

**Comment by srirambv** [comment]
Closing in favour of #12460
