### ISSUE TITLE
Per-release specialty test run on Linux for 0.20.x (Beta Channel)

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#12407]
## Per release specialty tests
 - [ ] Move folder into Other bookmarks. ([#12378](https://github.com/brave/browser-laptop/issues/12378))
 - [ ] Duplicate pinned tabs on tear off window which doesn't close when all tabs are closed. ([#12377](https://github.com/brave/browser-laptop/issues/12377))
 - [ ] Reload is not working. ([#12375](https://github.com/brave/browser-laptop/issues/12375))
 - [ ] Submenu's not being dismissed under the kabob menu. ([#12363](https://github.com/brave/browser-laptop/issues/12363))
 - [ ] Option to disable promotions. ([#12313](https://github.com/brave/browser-laptop/issues/12313))
 - [ ] Update Brave CSPs. ([#12263](https://github.com/brave/browser-laptop/issues/12263))
 - [ ] Restart notification should be global notification bar. ([#12216](https://github.com/brave/browser-laptop/issues/12216))
 - [ ] Automatically append user-data-dir-name on Linux for different channels. ([#11900](https://github.com/brave/browser-laptop/issues/11900))
 - [ ] Pinning tabs with multiple windows open results in duplicates. ([#11861](https://github.com/brave/browser-laptop/issues/11861))
 - [ ] About:blank on URL bar of a tab opened with control key. ([#11796](https://github.com/brave/browser-laptop/issues/11796))
 - [ ] Reduce size of session-store-1 by removing 'data:' URLs. ([#11582](https://github.com/brave/browser-laptop/issues/11582))
 - [ ] Bookmarks overflow indicator disappears. ([#11507](https://github.com/brave/browser-laptop/issues/11507))
 - [ ] Extension icons do not appear at top right of app. ([#11142](https://github.com/brave/browser-laptop/issues/11142))
 - [ ] OnTabMouseMove is called too many times. ([#10689](https://github.com/brave/browser-laptop/issues/10689))
 - [ ] Replace node classList instances with dataset. ([#10443](https://github.com/brave/browser-laptop/issues/10443))
 - [ ] LedgerTable with pinned sites does not have the orange border. ([#10434](https://github.com/brave/browser-laptop/issues/10434))
 - [ ] Split navigator in smaller components. ([#10354](https://github.com/brave/browser-laptop/issues/10354))
 - [ ] Browser freeze when syncing to profile with 6000+ bookmarks. ([#10273](https://github.com/brave/browser-laptop/issues/10273))
 - [ ] Remove keytar dependency. ([#10226](https://github.com/brave/browser-laptop/issues/10226))
 - [ ] Import Encrypted Cookies from Chrome. ([#10045](https://github.com/brave/browser-laptop/issues/10045))
 - [ ] Rename Yes/No buttons to Allow/Deny for easier understanding. ([#9750](https://github.com/brave/browser-laptop/issues/9750))
 - [ ] Move bookmark text calculation into the state. ([#9517](https://github.com/brave/browser-laptop/issues/9517))
 - [ ] Multiple screens , brave browser out of scope of the screen . ([#9371](https://github.com/brave/browser-laptop/issues/9371))
 - [ ] New windows are just white for a bit.. ([#8128](https://github.com/brave/browser-laptop/issues/8128))
 - [ ] Brave will not install on OpenSuse. ([#6946](https://github.com/brave/browser-laptop/issues/6946))
 - [ ] Rebookmarking from context menu does not reset bookmark title. ([#4868](https://github.com/brave/browser-laptop/issues/4868))
 - [ ] Bookmark folder is created left of bookmark item, not right. ([#2771](https://github.com/brave/browser-laptop/issues/2771))
 - [ ] PDFJS returns CORS error when PDF is loaded directly. ([#2715](https://github.com/brave/browser-laptop/issues/2715))

**Comment by srirambv** [comment]
Closing in favour of #12462
