### ISSUE TITLE
Tracking issue of broken top sites features

### ISSUE THREAD

**Issue by cezaraugusto** [brave/browser-laptop#12435]
- [x] can't pin/unpin sites #12470
- [ ] can't ignore sites
- [ ] can't undo ignore
- [ ] dnd doesn't reorder in the right index
- [x] topSites go missing after restart #12470
- [x] can't unpin default pinned site (twitter) without removing other sites #12470
- [ ] can't unpin a reordered top site (using drag n drop)
