### ISSUE TITLE
Per-release specialty test run on Windows x64 for 0.20.x (Beta Channel)

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#12461]
## Per release specialty tests
 - [ ] Reload tab doesn't load PDF after quit-restart. ([#12408](https://github.com/brave/browser-laptop/issues/12408))
 - [ ] Continually prompted to play YT videos. ([#12382](https://github.com/brave/browser-laptop/issues/12382))
 - [ ] Reduce size of session-store-1 by removing 'data:' URLs. ([#11582](https://github.com/brave/browser-laptop/issues/11582))
 - [ ] DOMException: play() can only be initiated by a user gesture. ([#11527](https://github.com/brave/browser-laptop/issues/11527))
 - [ ] Fix bug where users behind multiple releases could get preview releases (Windows only). ([#11152](https://github.com/brave/browser-laptop/issues/11152))
 - [ ] Browser freeze when syncing to profile with 6000+ bookmarks. ([#10273](https://github.com/brave/browser-laptop/issues/10273))
 - [ ] Restructure paymentsTab with grid property. ([#10236](https://github.com/brave/browser-laptop/issues/10236))
 - [ ] Remove keytar dependency. ([#10226](https://github.com/brave/browser-laptop/issues/10226))
 - [ ] Update react to ~15.6.1. ([#10126](https://github.com/brave/browser-laptop/issues/10126))
 - [ ] Tab preview does not work properly with DnD. ([#10103](https://github.com/brave/browser-laptop/issues/10103))
 - [ ] Multiple screens , brave browser out of scope of the screen . ([#9371](https://github.com/brave/browser-laptop/issues/9371))
 - [ ] Autoplay notification shown for local files . ([#8929](https://github.com/brave/browser-laptop/issues/8929))
 - [ ] Rebookmarking from context menu does not reset bookmark title. ([#4868](https://github.com/brave/browser-laptop/issues/4868))
 - [ ] Bookmark folder is created left of bookmark item, not right. ([#2771](https://github.com/brave/browser-laptop/issues/2771))
