### ISSUE TITLE
Per-release specialty test run on OS X for 0.20.x (Beta Channel)

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#12560]
## Per release specialty tests
 - [ ] Moving bookmark folder from Bookmarks Toolbar to Other Bookmarks still displays on toolbar. ([#12484](https://github.com/brave/browser-laptop/issues/12484))
 - [ ] Right click on bookmark folder tree to add folder doesn't always add folder. ([#12478](https://github.com/brave/browser-laptop/issues/12478))
 - [ ] Right click on bookmark folder tree to add bookmark doesn't always add bookmark. ([#12477](https://github.com/brave/browser-laptop/issues/12477))
 - [ ] Changing pinned values is not working correctly. ([#12450](https://github.com/brave/browser-laptop/issues/12450))
 - [ ] Continually prompted to play YT videos. ([#12382](https://github.com/brave/browser-laptop/issues/12382))
 - [ ] Clicking through PDF link doesn't open the file. ([#12381](https://github.com/brave/browser-laptop/issues/12381))
 - [ ] Duplicate pinned tabs on tear off window which doesn't close when all tabs are closed. ([#12377](https://github.com/brave/browser-laptop/issues/12377))
 - [ ] Improve verified-caching. ([#12272](https://github.com/brave/browser-laptop/issues/12272))
 - [ ] Displayed Brave wallet address and QR code do not have the same value after restoring wallet. ([#12170](https://github.com/brave/browser-laptop/issues/12170))
 - [ ] Top site tiles go missing. ([#12027](https://github.com/brave/browser-laptop/issues/12027))
 - [ ] Top site tiles momentarily display defaults before showing actual ones. ([#12026](https://github.com/brave/browser-laptop/issues/12026))
 - [ ] Reduce size of session-store-1 by removing 'data:' URLs. ([#11582](https://github.com/brave/browser-laptop/issues/11582))
 - [ ] Navigated sites do not show up on new tab site top tiles. ([#11102](https://github.com/brave/browser-laptop/issues/11102))
 - [ ] Mute on tab's context menu should change to Unmute before switching tabs. ([#10545](https://github.com/brave/browser-laptop/issues/10545))
 - [ ] Browser freeze when syncing to profile with 6000+ bookmarks. ([#10273](https://github.com/brave/browser-laptop/issues/10273))
 - [ ] Paused download shows Infinity%. ([#10264](https://github.com/brave/browser-laptop/issues/10264))
 - [ ] Remove keytar dependency. ([#10226](https://github.com/brave/browser-laptop/issues/10226))
 - [ ] Update react to ~15.6.1. ([#10126](https://github.com/brave/browser-laptop/issues/10126))
 - [ ] Import Encrypted Cookies from Chrome. ([#10045](https://github.com/brave/browser-laptop/issues/10045))
 - [ ] Encrypt Cookies. ([#10044](https://github.com/brave/browser-laptop/issues/10044))
 - [ ] Data: URL warning popup should disappear when the window is navigated. ([#10039](https://github.com/brave/browser-laptop/issues/10039))
 - [ ] Redundant Suggestions. ([#9827](https://github.com/brave/browser-laptop/issues/9827))
 - [ ] Changing tabset count messes up tab favicon and close button. ([#9779](https://github.com/brave/browser-laptop/issues/9779))
 - [ ] Add 'always block' option to autoplay. ([#9755](https://github.com/brave/browser-laptop/issues/9755))
 - [ ] Rename Yes/No buttons to Allow/Deny for easier understanding. ([#9750](https://github.com/brave/browser-laptop/issues/9750))
 - [ ] Swipe Navigation Sensitivity Setting. ([#9615](https://github.com/brave/browser-laptop/issues/9615))
 - [ ] Multiple screens , brave browser out of scope of the screen . ([#9371](https://github.com/brave/browser-laptop/issues/9371))
 - [ ] New windows are just white for a bit.. ([#8128](https://github.com/brave/browser-laptop/issues/8128))
 - [ ] Visiting a new site puts the tile in between the two pinned tiles and not in first position. ([#5768](https://github.com/brave/browser-laptop/issues/5768))
 - [ ] Bookmarking a site on new tab gridSites change its position. ([#5413](https://github.com/brave/browser-laptop/issues/5413))
 - [ ] Rebookmarking from context menu does not reset bookmark title. ([#4868](https://github.com/brave/browser-laptop/issues/4868))
