### ISSUE TITLE
Per-release specialty test run on Linux for 0.20.x (Beta Channel)

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#12562]
## Per release specialty tests
 - [x] Moving bookmark folder from Bookmarks Toolbar to Other Bookmarks still displays on toolbar. ([#12484](https://github.com/brave/browser-laptop/issues/12484))
 - [x] Right click on bookmark folder tree to add folder doesn't always add folder. ([#12478](https://github.com/brave/browser-laptop/issues/12478))
 - [x] Right click on bookmark folder tree to add bookmark doesn't always add bookmark. ([#12477](https://github.com/brave/browser-laptop/issues/12477))
 - [x] Changing pinned values is not working correctly. ([#12450](https://github.com/brave/browser-laptop/issues/12450))
 - [x] Reload tab doesn't load PDF after quit-restart. ([#12408](https://github.com/brave/browser-laptop/issues/12408))
 - [ ] Continually prompted to play YT videos. ([#12382](https://github.com/brave/browser-laptop/issues/12382))
 - [ ] Clicking through PDF link doesn't open the file. ([#12381](https://github.com/brave/browser-laptop/issues/12381))
 - [x] Improve verified-caching. ([#12272](https://github.com/brave/browser-laptop/issues/12272))
 - [ ] Update Brave CSPs. ([#12263](https://github.com/brave/browser-laptop/issues/12263))
 - [ ] Displayed Brave wallet address and QR code do not have the same value after restoring wallet. ([#12170](https://github.com/brave/browser-laptop/issues/12170))
 - [x] Top site tiles go missing. ([#12027](https://github.com/brave/browser-laptop/issues/12027))
 - [x] Top site tiles momentarily display defaults before showing actual ones. ([#12026](https://github.com/brave/browser-laptop/issues/12026))
 - [ ] Reduce size of session-store-1 by removing 'data:' URLs. ([#11582](https://github.com/brave/browser-laptop/issues/11582))
 - [x] Bookmarks overflow indicator disappears. ([#11507](https://github.com/brave/browser-laptop/issues/11507))
 - [x] Navigated sites do not show up on new tab site top tiles. ([#11102](https://github.com/brave/browser-laptop/issues/11102))
 - [ ] OnTabMouseMove is called too many times. ([#10689](https://github.com/brave/browser-laptop/issues/10689))
 - [x] Mute on tab's context menu should change to Unmute before switching tabs. ([#10545](https://github.com/brave/browser-laptop/issues/10545))
 - [x] Replace node classList instances with dataset. ([#10443](https://github.com/brave/browser-laptop/issues/10443))
 - [ ] Browser freeze when syncing to profile with 6000+ bookmarks. ([#10273](https://github.com/brave/browser-laptop/issues/10273))
 - [x] Remove keytar dependency. ([#10226](https://github.com/brave/browser-laptop/issues/10226))
 - [x] Add 'always block' option to autoplay. ([#9755](https://github.com/brave/browser-laptop/issues/9755))
 - [ ] Multiple screens , brave browser out of scope of the screen . ([#9371](https://github.com/brave/browser-laptop/issues/9371))
 - [x] New windows are just white for a bit.. ([#8128](https://github.com/brave/browser-laptop/issues/8128))
 - [ ] Brave will not install on OpenSuse. ([#6946](https://github.com/brave/browser-laptop/issues/6946))
 - [ ] Visiting a new site puts the tile in between the two pinned tiles and not in first position. ([#5768](https://github.com/brave/browser-laptop/issues/5768))
 - [x] Bookmarking a site on new tab gridSites change its position. ([#5413](https://github.com/brave/browser-laptop/issues/5413))
 - [x] Rebookmarking from context menu does not reset bookmark title. ([#4868](https://github.com/brave/browser-laptop/issues/4868))
 - [x] Bookmark folder is created left of bookmark item, not right. ([#2771](https://github.com/brave/browser-laptop/issues/2771))
 - [ ] PDFJS returns CORS error when PDF is loaded directly. ([#2715](https://github.com/brave/browser-laptop/issues/2715))
