### ISSUE TITLE
Per-release specialty test run on Windows x64 for 0.20.x (Beta Channel)

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#12561]
## Per release specialty tests
 - [ ] Moving bookmark folder from Bookmarks Toolbar to Other Bookmarks still displays on toolbar. ([#12484](https://github.com/brave/browser-laptop/issues/12484))
 - [ ] Right click on bookmark folder tree to add folder doesn't always add folder. ([#12478](https://github.com/brave/browser-laptop/issues/12478))
 - [ ] Right click on bookmark folder tree to add bookmark doesn't always add bookmark. ([#12477](https://github.com/brave/browser-laptop/issues/12477))
 - [ ] Changing pinned values is not working correctly. ([#12450](https://github.com/brave/browser-laptop/issues/12450))
 - [ ] Reload tab doesn't load PDF after quit-restart. ([#12408](https://github.com/brave/browser-laptop/issues/12408))
 - [ ] Continually prompted to play YT videos. ([#12382](https://github.com/brave/browser-laptop/issues/12382))
 - [ ] Clicking through PDF link doesn't open the file. ([#12381](https://github.com/brave/browser-laptop/issues/12381))
 - [ ] Improve verified-caching. ([#12272](https://github.com/brave/browser-laptop/issues/12272))
 - [ ] Displayed Brave wallet address and QR code do not have the same value after restoring wallet. ([#12170](https://github.com/brave/browser-laptop/issues/12170))
 - [ ] Top site tiles go missing. ([#12027](https://github.com/brave/browser-laptop/issues/12027))
 - [ ] Top site tiles momentarily display defaults before showing actual ones. ([#12026](https://github.com/brave/browser-laptop/issues/12026))
 - [ ] Reduce size of session-store-1 by removing 'data:' URLs. ([#11582](https://github.com/brave/browser-laptop/issues/11582))
 - [ ] Fix bug where users behind multiple releases could get preview releases (Windows only). ([#11152](https://github.com/brave/browser-laptop/issues/11152))
 - [ ] Navigated sites do not show up on new tab site top tiles. ([#11102](https://github.com/brave/browser-laptop/issues/11102))
 - [ ] Mute on tab's context menu should change to Unmute before switching tabs. ([#10545](https://github.com/brave/browser-laptop/issues/10545))
 - [ ] Browser freeze when syncing to profile with 6000+ bookmarks. ([#10273](https://github.com/brave/browser-laptop/issues/10273))
 - [ ] Restructure paymentsTab with grid property. ([#10236](https://github.com/brave/browser-laptop/issues/10236))
 - [ ] Remove keytar dependency. ([#10226](https://github.com/brave/browser-laptop/issues/10226))
 - [ ] Update react to ~15.6.1. ([#10126](https://github.com/brave/browser-laptop/issues/10126))
 - [ ] Tab preview does not work properly with DnD. ([#10103](https://github.com/brave/browser-laptop/issues/10103))
 - [ ] Add 'always block' option to autoplay. ([#9755](https://github.com/brave/browser-laptop/issues/9755))
 - [ ] Multiple screens , brave browser out of scope of the screen . ([#9371](https://github.com/brave/browser-laptop/issues/9371))
 - [ ] Visiting a new site puts the tile in between the two pinned tiles and not in first position. ([#5768](https://github.com/brave/browser-laptop/issues/5768))
 - [ ] Bookmarking a site on new tab gridSites change its position. ([#5413](https://github.com/brave/browser-laptop/issues/5413))
 - [ ] Rebookmarking from context menu does not reset bookmark title. ([#4868](https://github.com/brave/browser-laptop/issues/4868))
 - [ ] Bookmark folder is created left of bookmark item, not right. ([#2771](https://github.com/brave/browser-laptop/issues/2771))
