### ISSUE TITLE
Moving frameState (window) to tabState (app)

### ISSUE THREAD

**Issue by bsclifton** [brave/browser-laptop#12578]
- [ ] Are there any frame / tab related lookups not in state helper? #12579
  - [ ] Look at how big this change would be
  - [ ] Find out diffs between tab / frame
  - [ ] Do the work: remove frame lookups
  - [ ] Remove old frame state
        
- [ ] URL bar multiple action calls https://github.com/brave/browser-laptop/issues/12599

## related
- [ ] Change windows in appState from List to Map #11151
- [ ] replace tab content methods from frameKey to tabId #10969
- [ ] Move closed tabs to appState #9986
