### ISSUE TITLE
Per-release specialty test run on Linux for 0.20.x (Beta Channel)

### ISSUE THREAD

**Issue by LaurenWags** [brave/browser-laptop#12775]
## Per release specialty tests
 - [x] Remove CoinMarketCap Empty Elements. ([#12755](https://github.com/brave/browser-laptop/issues/12755))
 - [ ] Dynamically build monthly amount dropdown . ([#12727](https://github.com/brave/browser-laptop/issues/12727))
 - [x] WebTorrent should warn users of potential privacy risks. ([#12631](https://github.com/brave/browser-laptop/issues/12631))
 - [x] Sometimes displayed Brave wallet address and QR code do not have the same value. ([#12592](https://github.com/brave/browser-laptop/issues/12592))
 - [ ] Pinned tabs duplicated after update to 0.20.16. ([#12580](https://github.com/brave/browser-laptop/issues/12580))
 - [x] No longer prompted to save wallet recovery file. ([#12508](https://github.com/brave/browser-laptop/issues/12508))
 - [ ] When dragging a newly made folder to a new position, the folder doesn't place properly in the bookmark toolbar.. ([#12506](https://github.com/brave/browser-laptop/issues/12506))
 - [ ] Site specific settings for Fingerprinting Protection on are lost when updating to 0.20. ([#12497](https://github.com/brave/browser-laptop/issues/12497))
 - [x] Sometimes there is a delay when closing Brave-Beta. ([#12488](https://github.com/brave/browser-laptop/issues/12488))
 - [x] Unable to drop lock/unlock icon onto folder on toolbar to create bookmark. ([#12476](https://github.com/brave/browser-laptop/issues/12476))
 - [x] Mute item is missing in the context menu. ([#12472](https://github.com/brave/browser-laptop/issues/12472))
 - [x] Update to Muon 4.7.3. ([#12425](https://github.com/brave/browser-laptop/issues/12425))
 - [x] Extensions icon broken on about:extensions. ([#12409](https://github.com/brave/browser-laptop/issues/12409))
 - [x] Not prompted to save Contribution Statement. ([#12385](https://github.com/brave/browser-laptop/issues/12385))
 - [ ] Continually prompted to play YT videos. ([#12382](https://github.com/brave/browser-laptop/issues/12382))
 - [ ] Middle click to close pinned tab causes other tabs to look pinned until mouse over. ([#12379](https://github.com/brave/browser-laptop/issues/12379))
 - [ ] Update Brave CSPs. ([#12263](https://github.com/brave/browser-laptop/issues/12263))
 - [x] Formatting for contribution report should match payments screen. ([#12217](https://github.com/brave/browser-laptop/issues/12217))
 - [ ] Displayed Brave wallet address and QR code do not have the same value after restoring wallet. ([#12170](https://github.com/brave/browser-laptop/issues/12170))
 - [ ] Moving nested bookmarks folder to root folder is not shown on toolbar. ([#12052](https://github.com/brave/browser-laptop/issues/12052))
 - [x] Hyperlinks in about:brave always looks grey. ([#12015](https://github.com/brave/browser-laptop/issues/12015))
 - [x] Bookmark can't move to a subfolder. ([#11893](https://github.com/brave/browser-laptop/issues/11893))
 - [x] Moving a bookmark on the toolbar folder makes a zombie bookmark. ([#11798](https://github.com/brave/browser-laptop/issues/11798))
 - [ ] Reduce size of session-store-1 by removing 'data:' URLs. ([#11582](https://github.com/brave/browser-laptop/issues/11582))
 - [ ] Pinning throws error. ([#11208](https://github.com/brave/browser-laptop/issues/11208))
 - [ ] Unique icons needed for the different product channels. ([#10938](https://github.com/brave/browser-laptop/issues/10938))
 - [ ] OnTabMouseMove is called too many times. ([#10689](https://github.com/brave/browser-laptop/issues/10689))
 - [ ] Browser freeze when syncing to profile with 6000+ bookmarks. ([#10273](https://github.com/brave/browser-laptop/issues/10273))
 - [ ] Restructure paymentsTab with grid property. ([#10236](https://github.com/brave/browser-laptop/issues/10236))
 - [ ] Multiple screens , brave browser out of scope of the screen . ([#9371](https://github.com/brave/browser-laptop/issues/9371))
 - [ ] Brave will not install on OpenSuse. ([#6946](https://github.com/brave/browser-laptop/issues/6946))
 - [ ] Visiting a new site puts the tile in between the two pinned tiles and not in first position. ([#5768](https://github.com/brave/browser-laptop/issues/5768))
 - [ ] Window off screen when monitors change. ([#3558](https://github.com/brave/browser-laptop/issues/3558))
 - [ ] PDFJS returns CORS error when PDF is loaded directly. ([#2715](https://github.com/brave/browser-laptop/issues/2715))

**Comment by srirambv** [comment]
Closing in favour of #12821
