### ISSUE TITLE
Per-release specialty test run on Windows x64 for 0.20.x (Beta Channel)

### ISSUE THREAD

**Issue by LaurenWags** [brave/browser-laptop#12774]
## Per release specialty tests
 - [ ] Remove CoinMarketCap Empty Elements. ([#12755](https://github.com/brave/browser-laptop/issues/12755))
 - [x] Dynamically build monthly amount dropdown . ([#12727](https://github.com/brave/browser-laptop/issues/12727))
 - [x] WebTorrent should warn users of potential privacy risks. ([#12631](https://github.com/brave/browser-laptop/issues/12631))
 - [x] Sometimes displayed Brave wallet address and QR code do not have the same value. ([#12592](https://github.com/brave/browser-laptop/issues/12592))
 - [x] Bookmark and tabs DND are not working on Windows. ([#12590](https://github.com/brave/browser-laptop/issues/12590))
 - [x] Pinned tabs duplicated after update to 0.20.16. ([#12580](https://github.com/brave/browser-laptop/issues/12580))
 - [x] When dragging a newly made folder to a new position, the folder doesn't place properly in the bookmark toolbar.. ([#12506](https://github.com/brave/browser-laptop/issues/12506))
 - [x] Site specific settings for Fingerprinting Protection on are lost when updating to 0.20. ([#12497](https://github.com/brave/browser-laptop/issues/12497))
 - [x] Sometimes there is a delay when closing Brave-Beta. ([#12488](https://github.com/brave/browser-laptop/issues/12488))
 - [x] Moving bookmark folder from Bookmarks Toolbar to Other Bookmarks still displays on toolbar. ([#12484](https://github.com/brave/browser-laptop/issues/12484))
 - [x] Update to Muon 4.7.3. ([#12425](https://github.com/brave/browser-laptop/issues/12425))
 - [x] Formatting for contribution report should match payments screen. ([#12217](https://github.com/brave/browser-laptop/issues/12217))
 - [x] Hyperlinks in about:brave always looks grey. ([#12015](https://github.com/brave/browser-laptop/issues/12015))
 - [ ] Bookmark toolbar context menu not working on 0.20.x. ([#11728](https://github.com/brave/browser-laptop/issues/11728))
 - [ ] Fix bug where users behind multiple releases could get preview releases (Windows only). ([#11152](https://github.com/brave/browser-laptop/issues/11152))
 - [ ] Restructure paymentsTab with grid property. ([#10236](https://github.com/brave/browser-laptop/issues/10236))
 - [ ] Remove keytar dependency. ([#10226](https://github.com/brave/browser-laptop/issues/10226))
 - [x] Rebookmarking from context menu does not reset bookmark title. ([#4868](https://github.com/brave/browser-laptop/issues/4868))
 - [x] Bookmark folder is created left of bookmark item, not right. ([#2771](https://github.com/brave/browser-laptop/issues/2771))

**Comment by srirambv** [comment]
Closing in favour of #12820
