### ISSUE TITLE
Extension: Reddit Enhancement Suite (RES)

### ISSUE THREAD

**Issue by jonathansampson** [brave/browser-laptop#12858]
Extension: [Reddit Enhancement Suite](https://chrome.google.com/webstore/detail/reddit-enhancement-suite/kbmfpngjjgdllneeigpgjifpgocmfgmb?hl=en-US)

![image](https://user-images.githubusercontent.com/815158/35425507-dcb9824e-0220-11e8-9abb-1f3773ced829.png)

### Needed APIs:

**chrome.downloads**

- [ ] #12859 chrome.downloads.download

**chrome.extension**

- [ ] #9551 chrome.extension.inIncognitoContext

**chrome.history**

- [ ] #7076 chrome.history.addUrl
- [ ] #12860 chrome.history.getVisits

**chrome.pageAction**

_This requires insight and direction from the design team._

- [ ] #12861 chrome.pageAction.hide
- [ ] #12863 chrome.pageAction.onClicked
- [ ] #12864 chrome.pageAction.setIcon
- [ ] #12865 chrome.pageAction.setTitle
- [ ] #12866 chrome.pageAction.show

**chrome.permissions**

- [ ] #12868 chrome.permissions.contains
- [ ] #12869 chrome.permissions.request

**chrome.runtime**

- [x] #8798 chrome.runtime.id
- [x] #8799 chrome.runtime.lastError
- [ ] #8791 chrome.runtime.onMessage
- [ ] #8802 chrome.runtime.sendMessage

**chrome.storage**

- [ ] #8806 chrome.storage.local.clear
- [ ] #8803 chrome.storage.local.get
- [ ] #8805 chrome.storage.local.remove
- [ ] #8804 chrome.storage.local.set

**chrome.tabs**

- [x] #8680 chrome.tabs.create
- [ ] #8809 chrome.tabs.onRemoved
- [ ] #8810 chrome.tabs.onUpdated
- [x] #8811 chrome.tabs.query
- [x] #4687 chrome.tabs.remove
- [ ] #8812 chrome.tabs.sendMessage

**chrome.webRequest**

- [ ] #12881 chrome.webRequest.onBeforeRedirect

**chrome.windows**

- [x] #6789 chrome.windows.create

**Comment by jonathansampson** [comment]
Some cursory testing of this extensions reveals a few obvious issues, though they may be minor in the grand scheme of things. The `pageAction.{show, setIcon, setTitle}` methods are not supported. Likewise, the `history.addUrl` method is unavailable to the extension. These are the biggest omissions in my 10-15 minutes of testing.

The absence of these methods don't appear to cripple the experience; we may be able to ship support before these are fully implemented. As noted above, _pageAction_ will require guidance from the design team, as this requires a new UI element.

**Comment by bsclifton** [comment]
When we move to [brave-core](https://github.com/brave/brave-browser) (which is just around the corner), we should have full support for extensions. Stay tuned 😄
