### ISSUE TITLE
Tracking: Issues caused by strict site isolation

### ISSUE THREAD

**Issue by Liunkae** [brave/browser-laptop#12907]
- [ ] #12526, Unable to scroll sometimes
- [ ] #12612, Extensions broken
- [ ] #12879, Print As PDF generates blank pages
- [ ] #13007, Cannot type into iframe
- [ ] #13496, reCAPTCHA not working
- [ ] #13716, Embedded YouTube videos are broken

**Comment by NumDeP** [comment]
[Yes Movies](https://yesmovies.to/movies) after selection, the play button in the middle of the console doesn't work.

**Comment by bsclifton** [comment]
Issues with strict site isolation are fixed with brave-core 😄 

You can download the developer channel release here:
https://brave.com/download-dev
