### ISSUE TITLE
Release checklist for 0.22.x Release 2 (Release Channel)

### ISSUE THREAD

**Issue by kjozwiak** [brave/browser-laptop#13800]
# Release Process Checklist

Feel free to copy this into an issue if you want to keep track of items per-milestone.
Be super sure that <version> is replaced with the version you wish to use.

### First-time Setup
- [x] `git clone git@github.com:brave/vault-updater && cd vault-updater`
- [x] `git clone git@github.com:brave/release-tools`
- [x] `npm install`
- [x] install the heroku toolbelt https://toolbelt.heroku.com/ , ask @mrose17 to add you
- [x] `git remote add heroku-staged https://git.heroku.com/brave-laptop-updates-pre.git`
- [x] `git remote add heroku https://git.heroku.com/brave-laptop-updates.git`
- [x] *(optional) you can check logs : `heroku logs --tail --app brave-laptop-updates-pre`

### Every time thereafter
- [ ] `cd vault-updater`
- [ ] `git pull`
- [ ] `git checkout -b dev-<version>`
- [ ] `cd ../release-tools`
- [ ] `node bin/promotePreview.js --location ../vault-updater/data --overwrite --channel=dev --notes='Notes go here'`
- [ ] `cd ../vault-updater`
- [ ] `git add -u`
- [ ] `git commit -m "<version>" -m "Auditors: @aekeus"`
- [ ] `git push (alternatively: git push --set-upstream origin dev-<version>)`
- [ ] `git push heroku-staged dev-<version>:master`

## Fastly
- [ ] Log into Fastly and purge the cache

## Test Staging
- [ ] Install a prior version of the app
- [ ] `BRAVE_UPDATE_HOST=https://laptop-updates-pre.brave.com open -a ./Brave.app`
- [ ] Confirm SHA in about:brave matches expectations

## Merge Into Master
- [ ] `git checkout master`
- [ ] `git merge dev-<version>`
- [ ] `git push`

## Release Notes
- [ ] Edit the release notes title and uncheck the box to publish : https://github.com/brave/browser-laptop/releases
- [ ] Update dependency release notes as needed
- [ ] Announce release on https://community.brave.com/
- [ ] Announce release on https://www.reddit.com/r/brave_browser/

## Push To Production
- [ ] `git push heroku`

## Updates And Broadcast
- [ ] Wait for confirmation that Windows live update works
- [ ] Wait for confirmation that Linux live update works
- [ ] Wait for confirmation that macOS live update works
- [ ] Notify w0ts0n and update the Brave Snap Package under Ubuntu
- [ ] Notify #browser, #community, #general, #pr, #testers of the latest release with a link to the release notes
- [ ] Add a screenshot to the #pr channel for social broadcast

## Download Binaries from Brave.com
- [ ] download binary using https://laptop-updates.brave.com/latest/osx
- [ ] download binary using https://laptop-updates.brave.com/latest/winx64
- [ ] download binary using https://laptop-updates.brave.com/latest/winia32

## Update crash server
- [ ] Modify BRAVE_VERSIONS env. var. on brave-stats to include brave/electron version (at most three versions) (`BRAVE_VERSIONS='1.3.1 1.3.2 1.3.3'`) We need to keep to a maximum of three versions currently.
- [ ] Modify `NODE_MODULES_CACHE` env. var. to force node_modules reload (`NODE_MODULES_CACHE=false`)
- [ ] Commit empty change for Heroku (`git commit -am 'install electron symbols for 1.3.3, remove old version' --allow-empty`)
- [ ] `git push heroku master`

## Update Release channel wiki
- [ ] Update entries here as needed: https://github.com/brave/browser-laptop/wiki/Release-channels

## Branch Channel Maintenance
- [ ] Create branch channel if needed

**Comment by bsclifton** [comment]
closing in favor of https://github.com/brave/browser-laptop/issues/13835
