### ISSUE TITLE
Refine Toolbar UI with New Icons and styling refinements

### ISSUE THREAD

**Issue by bradleyrichter** [brave/browser-laptop#13981]
Issue: Dreams of UI refinements stuck in design world. 

Fix: Implement collection of UI design refinements and new icon set.

Test proceedure:

Open new instance that includes new changes.
Compare to previous version.
Be amazed by beauty of new version.
Click buttons and resize window to make sure nothing blows up or looks wonky.

actual screen shot showing changes from @petemill go here:

**Comment by petemill** [comment]
Initial aims:
- [ ] top nav height / alignment polish
- [ ] Url bar style: titlemode, non-titlemode, :hover, :focus, :active
- [ ] Url bar loading progress bar
- [ ] Navigation icons update
- [ ] Preferences icons update
- [ ] Tab bar style update
- [ ] Preview build 1
    - [ ] Style updates from build 1 feedback
- [ ] Preview build 2
    - [ ] Style updates from build 2 feedback
- [ ] Preview build 3
    - [ ] Style updates from build 3 feedback

Additional aims:
 - [x] Icons v3 with explicit box sizing inside SVG
 - 

Dependencies:
 - [x] v1 design sketch
 - [x] icons
 - [ ] Shields icon spec
 - [ ]

**Comment by petemill** [comment]
# Status as of preview2:

## Url bar
### Title mode
![image](https://user-images.githubusercontent.com/741836/40386733-687abb32-5dbf-11e8-953f-dbdba91dd17f.png)
### Url mode
![image](https://user-images.githubusercontent.com/741836/40386962-05438da4-5dc0-11e8-9360-84917e86293a.png)
### Hover
![image](https://user-images.githubusercontent.com/741836/40387510-d042476a-5dc1-11e8-9922-1575c2eed746.png)
### Focus
![image](https://user-images.githubusercontent.com/741836/40387527-da4bb264-5dc1-11e8-8993-d1bf0f445478.png)

### Icon variations
![image](https://user-images.githubusercontent.com/741836/40387563-f68ae47c-5dc1-11e8-9b1e-3a437e71b85f.png)




## Tabs bar (click to enlarge)
![image](https://user-images.githubusercontent.com/741836/40386759-7b38b51c-5dbf-11e8-85e9-6be746bf123b.png)

![image](https://user-images.githubusercontent.com/741836/40386776-8856ea52-5dbf-11e8-8c92-10178bf10403.png)

### New Tab Button
![image](https://user-images.githubusercontent.com/741836/40390541-6d7513c0-5dca-11e8-9260-cb28e6b0338d.png)
Hover 
![image](https://user-images.githubusercontent.com/741836/40390548-72e0ab1c-5dca-11e8-87df-22787d4db338.png)
Mouse down 
![image](https://user-images.githubusercontent.com/741836/40390552-78be0b7e-5dca-11e8-8301-0b3ee84b491b.png)



## Nav buttons
![image](https://user-images.githubusercontent.com/741836/40386849-bb2acf2a-5dbf-11e8-9374-db10b09d7986.png)

#### Hover
![image](https://user-images.githubusercontent.com/741836/40386827-a7163a24-5dbf-11e8-989d-065506e36ac1.png)

#### Mouse down
![image](https://user-images.githubusercontent.com/741836/40386835-b13c4f48-5dbf-11e8-813e-356cbf6d5606.png)

#### All the buttons

![image](https://user-images.githubusercontent.com/741836/40390823-44a05d6e-5dcb-11e8-9742-bddede17fced.png)

![image](https://user-images.githubusercontent.com/741836/40390699-e628a7c8-5dca-11e8-8226-c268969f3fa5.png)


![image](https://user-images.githubusercontent.com/741836/40390712-ef1de5f0-5dca-11e8-99e4-418a4c4a1075.png)
![image](https://user-images.githubusercontent.com/741836/40390724-fb592a6e-5dca-11e8-8289-8f5ad1f1925e.png)
![image](https://user-images.githubusercontent.com/741836/40390749-08106966-5dcb-11e8-9c37-b44732a55c05.png)

# Status as of preview1
![image](https://user-images.githubusercontent.com/741836/40390796-2fa09a14-5dcb-11e8-9938-31c61d47d274.png)

![image](https://user-images.githubusercontent.com/741836/40390770-25f5725a-5dcb-11e8-8a18-a554d9e59eba.png)

**Comment by kjozwiak** [comment]
@petemill @bradleyrichter other than the changes outlined in https://github.com/brave/browser-laptop/issues/13981#issuecomment-391144864, is there anything else QA needs to do? Do we have a design document that outlines the behaviour of the new UI changes anywhere?

**Comment by petemill** [comment]
@kjozwiak no spec, it has been an iterative process. I believe we have approval from the design team along for the UX, with the included and pending iterative requests which are logged as separate issues, as of 0.23.14

**Comment by petemill** [comment]
Added screenshots at https://github.com/brave/browser-laptop/issues/13981#issuecomment-391144864 to verify notable behavior.

**Comment by petemill** [comment]
Added test plan to https://github.com/brave/browser-laptop/issues/13981#issuecomment-391075033

**Comment by srirambv** [comment]
@petemill Is this expected with the new icon set? 
![shields click](https://user-images.githubusercontent.com/17010094/41853227-4f466bbe-785b-11e8-80cc-f717699af378.gif)

**Comment by petemill** [comment]
Not sure from the gif which aspect you are referring to as there are a lot
of separate things going on in it. The hover state is expected as is the
mouse down state, and the active state (which looks the same as hover
state) whilst the menu is open. There is also a focus state when the button
is tabbed to via the keyboard, or is sometimes, like any button, keeps
focus after being clicked. Did some aspect of those states strike you as in
the way of your experience?

**Comment by bradleyrichter** [comment]
Lion face has no color. Please define the svg face shape as white.

**Comment by srirambv** [comment]
Verified on Windows 10 x64 using
* 0.23.19 - 178c3fb
* Muon - `7.1.3`
* libchromiumcontent - `67.0.3396.87`
