### ISSUE TITLE
Per release specialty tests on Linux for 0.22.x Release 5

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#14273]
## Per release specialty tests
 - [x] Grant not being removed from balance breakdown after contribution/reconcilement . ([#14292](https://github.com/brave/browser-laptop/issues/14292))
 - [x] YouTube and Twitch channel display in contribution statement . ([#14284](https://github.com/brave/browser-laptop/issues/14284))
 - [x] Tab jumps position after opening. ([#14281](https://github.com/brave/browser-laptop/issues/14281))
 - [x] Captcha not being dismissed when closing tab/restarting browser. ([#14279](https://github.com/brave/browser-laptop/issues/14279))
 - [x] Reconcile doesn't go through . ([#14276](https://github.com/brave/browser-laptop/issues/14276))
 - [x] Arrow should not be allowed to drag and drop on Brave Payments BAT logo page. ([#14274](https://github.com/brave/browser-laptop/issues/14274))
 - [x] Remove ballot delay. ([#14263](https://github.com/brave/browser-laptop/issues/14263))
 - [x] Optimize ballot proofing . ([#14211](https://github.com/brave/browser-laptop/issues/14211))
 - [x] Add support for batch voting ([#14190](https://github.com/brave/browser-laptop/issues/14190))
- [x] monthly budget amounts changed. ([#14300](https://github.com/brave/browser-laptop/issues/14300))
 - [x] reconcile uses user-added BAT instead of UGP BAT ([#14297](https://github.com/brave/browser-laptop/issues/14297))
 - [x] wrong surveyor link being used under linux. ([#14302](https://github.com/brave/browser-laptop/issues/14302))
 - [x] changing "Congrats" message when user accepts gran ([#14241](https://github.com/brave/browser-laptop/issues/14241))
 - [x] Captcha not being dismissed when closing tab via keyboard shortcut and via reopen closed tab ([#14304](https://github.com/brave/browser-laptop/issues/14304))
 - [x] USD text cut off when higher BAT value is selected ([#14309](https://github.com/brave/browser-laptop/issues/14309))
 - [x] Show less hides publishers with higher % instead of the low % publisher ([#14287](https://github.com/brave/browser-laptop/issues/14287))
 - [x] Payments show mins time not met message even though ledger table contains more than 30mins of usage ([#14310](https://github.com/brave/browser-laptop/issues/14310))
