### ISSUE TITLE
Manual test run on Windows x64 for 0.23.x Release 3 (Release Channel - preview)

### ISSUE THREAD

**Issue by kjozwiak** [brave/browser-laptop#14749]
## Per release specialty tests
 - [x] Can load bookmark in tor tab before tor finishes loading. ([#14680](https://github.com/brave/browser-laptop/issues/14680))
 - [x] [hackerone] favicon issue. ([#14641](https://github.com/brave/browser-laptop/issues/14641))
 - [x] UGP promo should not be checked at startup. ([#14616](https://github.com/brave/browser-laptop/issues/14616))
 - [x] Publisher verification lookup should use a singe list source. ([#14691](https://github.com/brave/browser-laptop/issues/14691))
 - [x] Perform contribution where several regular sites and YT/Twitch videos are included on the ledger. Ensure the sites/channels are listed on the contribution statement.

**Comment by srirambv** [comment]
Looks good to go
