### ISSUE TITLE
Manual test run on OS X for 0.23.x Hotfix

### ISSUE THREAD

**Issue by LaurenWags** [brave/browser-laptop#14927]
## Per release specialty tests
 - [x] Update to Muon 8.0.4. ([#14911](https://github.com/brave/browser-laptop/issues/14911))
 - [x] Update to Chromium 68.0.3440.84. ([#14910](https://github.com/brave/browser-laptop/issues/14910))
 - [x] Seeing JavaScript errors in developer tools on each page. ([#14890](https://github.com/brave/browser-laptop/issues/14890))
 - [ ] Pause/Resume of download causes download to be cancelled. ([#14850](https://github.com/brave/browser-laptop/issues/14850))
 - [x] Download Delete button click is causing the browser hang. ([#14805](https://github.com/brave/browser-laptop/issues/14805))
 - [x] External protocol prompt does not appear on about: pages. ([#14679](https://github.com/brave/browser-laptop/issues/14679))
 - [ ] Mojave: Crash when downloading any file. ([#14346](https://github.com/brave/browser-laptop/issues/14346))

**Comment by LaurenWags** [comment]
Closing in favor of https://github.com/brave/browser-laptop/issues/14937
