### ISSUE TITLE
Manual test run on Windows x64 for 0.23.x Release 5 (Release Channel)

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#15016]
## Per release specialty tests
 - [x] Window.prompt is not supported currently.([#94](https://github.com/brave/browser-laptop/issues/94))
 - [x] Google asking for flash permissions when clicking the adobe test page via search results.([#13500](https://github.com/brave/browser-laptop/issues/13500))
 - [x] URL-like strings can cause empty autocomplete results.([#13718](https://github.com/brave/browser-laptop/issues/13718))
 - [x] Cookie testing site shows leaks.([#14250](https://github.com/brave/browser-laptop/issues/14250))
 - [x] Right click on any setup file and open in new tab doesn't download the file.([#14409](https://github.com/brave/browser-laptop/issues/14409))
 - [x] [hackerone] file open in new tab issue.([#14522](https://github.com/brave/browser-laptop/issues/14522))
 - [ ] Allow for different default search engines based on region.([#14647](https://github.com/brave/browser-laptop/issues/14647))
 - [x] [hackerone] #374969 - permission prompt with window.open.([#14681](https://github.com/brave/browser-laptop/issues/14681))
 - [x] Publisher data file should be deleted when wallet is deleted.([#14758](https://github.com/brave/browser-laptop/issues/14758))
 - [x] Roundtrip calls from the ledgerApi should include clientOptions.([#14874](https://github.com/brave/browser-laptop/issues/14874))
 - [x] Fix security issue.([#14967](https://github.com/brave/browser-laptop/issues/14967))
 - [x] Upgrade to Muon 8.0.8.([#15018](https://github.com/brave/browser-laptop/issues/15018))

**Comment by kjozwiak** [comment]
Closing. Will generate new runs once we get a new build with the muon bump. Only remaining issue is #14647 but QA is having issues verifying the issue. Added more information via https://github.com/brave/browser-laptop/issues/14647#issuecomment-413224175.
