### ISSUE TITLE
Manual test run on Linux for 0.23.x Release 5 (Release Channel)

### ISSUE THREAD

**Issue by kjozwiak** [brave/browser-laptop#15084]
## Per release specialty tests
 - [x] View Page Source opens blank tab. ([#15075](https://github.com/brave/browser-laptop/issues/15075))
 - [x] Block loading of chrome://brave URLs. ([#15074](https://github.com/brave/browser-laptop/issues/15074))
 - [x] Unable to solve captcha. ([#15073](https://github.com/brave/browser-laptop/issues/15073))
 - [x] Reducing time for the ref headers fetch at startup. ([#15067](https://github.com/brave/browser-laptop/issues/15067))
 - [x] [hackerone] chrome:// new tab issue. ([#15045](https://github.com/brave/browser-laptop/issues/15045))
 - [x] Use v2 promotion endpoints. ([#14980](https://github.com/brave/browser-laptop/issues/14980))
 - [x] Visited links are not reset when closing Brave. ([#14667](https://github.com/brave/browser-laptop/issues/14667))

## Installer

- [x] Check that installer is close to the size of last release.
- [ ] Check signature: If OS Run `spctl --assess --verbose /Applications/Brave.app/` and make sure it returns `accepted`.  If Windows right click on the installer exe and go to Properties, go to the Digital Signatures tab and double click on the signature.  Make sure it says "The digital signature is OK" in the popup window.
- [x] Check Brave, muon, and libchromiumcontent version in `about:brave` and make sure it is EXACTLY as expected.

## Tabs, Pinning and Tear off tabs

- [x] Test that tabs are pinnable
- [x] Test that tabs are unpinnable
- [x] Test that tabs are draggable to same tabset
- [x] Test that tabs are draggable to alternate tabset
- [x] Test that tabs can be teared off into a new window
- [x] Test that you are able to reattach a tab that is teared off into a new window
- [x] Test that tab pages can be closed
- [x] Test that tab pages can be muted
- [x] Test that tabs can be cloned
- [x] Test that tab discarding works as expected and doesn't cause crashes/unexpected behaviour
  - [x] using `BRAVE_ENABLE_DEBUG_MENU=1`, disable tab preview via `about:preferences#tabs`, select `Allow manual tab discarding` using the `Debug` menu and manually discard a tab

## Session storage

Do not forget to make a backup of your entire `~/Library/Application\ Support/Brave` folder.

- [x] Temporarily move away your `~/Library/Application\ Support/Brave/session-store-1` and test that clean session storage works. (`%appdata%\Brave` in Windows, `./config/brave` in Ubuntu)
- [x] Test that windows and tabs restore when closed, including active tab.
  - [x] Ensure that the tabs in the above session are being lazy loaded when the session is restored
  - [x] Ensure that hovering over lazy loaded tabs correctly loads the tab without any issues
- [x] Move away your entire `~/Library/Application\ Support/Brave` folder (`%appdata%\Brave` in Windows, `./config/brave` in Ubuntu)

## Cookie and Cache

- [x] Make a backup of your profile, turn on all clearing in preferences and shut down.  Make sure when you bring the browser back up everything is gone that is specified.
- [x] Go to http://samy.pl/evercookie/ and set an evercookie. Check that going to prefs, clearing site data and cache, and going back to the Evercookie site does not remember the old evercookie value.

## Update tests

- [ ] Test that updating using `BRAVE_UPDATE_VERSION=0.8.3` env variable works correctly.
- [ ] Test that using `BRAVE_ENABLE_PREVIEW_UPDATES=TRUE` env variable works and prompts for preview build updates.
