### ISSUE TITLE
Manual test for for macOS 0.11.1 Beta1

### ISSUE THREAD

**Issue by luixxiul** [brave/browser-laptop#2513]
## Installer

1. [x] Check that installer is close to the size of last release.
2. [x] Check signature: If OS Run `spctl --assess --verbose /Applications/Brave.app/` and make sure it returns `accepted`.  If Windows right click on the installer exe and go to Properies, go to the Digital Signatures tab and double click on the signature.  Make sure it says "The digital signature is OK" in the popup window.
3. [x] Check Brave, electron, and libchromiumcontent version in About and make sure it is EXACTLY as expected.

## About pages

1. [x] Test that about:bookmarks loads bookmarks
2. [x] Test that about:downloads loads downloads
3. [x] Test that about:preferences changing a preference takes effect right away
4. [x] Test that about:preferences language change takes effect on re-start
5. [x] Test that about:passwords loads

## Context menus
1. [x] Make sure context menu items in the URL bar work
2. [x] Make sure context menu items on content work with no selected text.
3. [x] Make sure context menu items on content work with selected text.
4. [x] Make sure context menu items on content work inside an editable control (input, textarea, or contenteditable).

## Find on page

1. [x] Ensure search box is shown with shortcut
2. [x] Test successful find
3. [x] Test forward and backward find navigation
4. [x] Test failed find shows 0 results
5. [x] Test match case find

## Site hacks

1. [x] Test twitch.tv sub-page loads a video and you can play it

## Downloads

1. [x] Test downloading a file works and that all actions on the download item works.

## Fullscreen

1. [x] Test that entering full screen window works View -> Toggle Full Screen. And exit back (Not Esc).
2. [x] Test that entering HTML5 full screen works. And Esc to go back. (youtube.com)

## Tabs and Pinning

1. [x] Test that tabs are pinnable
2. [x] Test that tabs are unpinnable
3. [x] Test that tabs are draggable to same tabset
4. [x] Test that tabs are draggable to alternate tabset

## Zoom

1. [x] Test zoom in / out shortcut works
2. [x] Test hamburger menu zooms.
3. [x] Test zoom saved when you close the browser and restore on a single site.
4. [x] Test zoom saved when you navigate within a single origin site.
5. [x] Test that navigating to a different origin resets the zoom

## Bookmarks

1. [x] Test that creating a bookmark on the bookmarks toolbar works
2. [x] Test that creating a bookmark folder on the bookmarks toolbar works
3. [x] Test that moving a bookmark into a folder by drag and drop on the bookmarks folder works
4. [x] Test that clicking a bookmark in the toolbar loads the bookmark.
5. [x] Test that clicking a bookmark in a bookmark toolbar folder loads the bookmark.

## Bravery settings

1. [x] Check that HTTPS Everywhere works by loading http://www.apple.com
2. [x] Turning HTTPS Everywhere off and shields off both disable the redirect to apple.com
3. [x] Check that ad replacement works on http://slashdot.org
4. [x] Check that toggling to blocking and allow ads works as expected.
5. [x] Test that clicking through a cert error in badssl.com works.
6. [x] Test that Safe Browsing works (excellentmovies.net)
7. [x] Turning Safe Browsing off and shields off both disable safe browsing for excellentmovies.net.
8. [x] Visit brianbondy.com and then turn on script blocking, nothing should load. Allow it from the script blocking UI in the URL bar and it should work.
9. [x] Test that about:preferences default Bravery settings take effect on pages with no site settings.
10. [x] Test that turning on fingerprinting protection in about:preferences shows 3 fingerprints blocked at https://jsfiddle.net/bkf50r8v/11/. Test that turning it off in the Bravery menu shows 0 fingerprints blocked.
11. [x] Test that 3rd party storage results are blank at https://jsfiddle.net/7ke9r14a/7/ when 3rd party cookies are blocked.
12. [x] Test that audio fingerprint is blocked at https://audiofingerprint.openwpm.com/ when fingerprinting protection is on.

## Content tests

1. [x] Load twitter and click on a tweet so the popup div shows.   Click to dismiss and repeat with another div. Make sure it shows.
2. [x] Go to brianbondy.com and click on the twitter icon on the top right. Test that context menus work in the new twitter tab.
3. [x] Go to http://www.bennish.net/web-notifications.html and test that clicking on 'Show' pops up a notification asking for permission. Make sure that clicking 'Deny' leads to no notifications being shown.
4. [x] Go to https://trac.torproject.org/projects/tor/login and make sure that the password can be saved. Make sure the saved password shows up in `about:passwords`.
5. [x] Open a github issue and type some misspellings, make sure they are underlined.
6. [x] Make sure that right clicking on a word with suggestions gives a suggestion and that clicking on the suggestion replaces the text.
7. [x] Make sure that Command + Click (Control + Click on Windows, Control + Click on Ubuntu) on a link opens a new tab but does NOT switch to it.  Click on it and make sure it is already loaded.
8. [x] Make sure that clicking links from gmail or inbox.google.com works.
9. [x] Test that PDF is loaded at http://www.orimi.com/pdf-test.pdf
10. [ ] Go to http://samy.pl/evercookie/ and set an evercookie. Check that going to prefs, clearing site data and cache, and going back to the Evercookie site does not remember the old evercookie value.
11. [ ] Make a backup of your profile, turn on all clearing in preferences and shut down.  Make sure when you bring the browser back up everything is gone that is specified.

# Flash tests
1. [x] Turn on Flash in about:preferences#security. Test that clicking on 'Install Flash' banner on myspace.com shows a notification to allow Flash and that the banner disappears when 'Allow' is clicked.
2. [ ] Test that flash placeholder appears on http://www.y8.com/games/superfighters

## Per release specialty tests

- [ ] Added built-in PDF reader with PDF.js. Can be disabled in preferences. ([#1084](https://github.com/brave/browser-laptop/issues/1084))
- [x] Added more data clearing options, including on shutdown. ([#2472](https://github.com/brave/browser-laptop/issues/2472))
- [x] Added support for navigator.registerProtocolHandler (Mostly used for gmail `mailto:` and `bitcoin:` handling). ([#1583](https://github.com/brave/browser-laptop/issues/1583))
- [ ] Added Copy Image to clipboard option through the context menu. ([#1174](https://github.com/brave/browser-laptop/issues/1174))
- [x] Added a customized Windows 10 Start Menu tile. ([#2372](https://github.com/brave/browser-laptop/issues/2372))
- [x] Added edit bookmark ability when staring a site. ([#2439](https://github.com/brave/browser-laptop/issues/2439))
- [x] Added Lastpass preferences. ([#2411](https://github.com/brave/browser-laptop/pull/2411))
- [x] Added `Command + Shift + Click` support for various UI elements to open and focus a new tab. ([#2436](https://github.com/brave/browser-laptop/issues/2436))
- [x] Fixed Vimeo player not playing due to referrer blocking. ([#2474](https://github.com/brave/browser-laptop/issues/2474))
- [x] Fixed crashes with notifications. ([#1931](https://github.com/brave/browser-laptop/issues/1931))
- [x] Fixed new-tab ordering from pinned tabs. ([#2453](https://github.com/brave/browser-laptop/issues/2453))
- [x] Fixed exiting full screen when closing a full screen tab. ([#2404](https://github.com/brave/browser-laptop/issues/2404))
- [x] Fixed spell check happening in URL bar. ([#2434](https://github.com/brave/browser-laptop/issues/2434))
- [x] Fixed webRTC fingerprinting blocking. ([#2412](https://github.com/brave/browser-laptop/issues/2412))
- [x] Fixed find in page highlighting not clearing when find bar is closed. ([#2476](https://github.com/brave/browser-laptop/issues/2476))
- [x] Upgrade to Electron 1.2.7. ([#2470](https://github.com/brave/browser-laptop/issues/2470))

## Session storage

1. [x] Temporarily move away your `~/Library/Application\ Support/Brave/session-store-1` and test that clean session storage works. (`%appdata%\Brave in Windows`, `./config/brave` in Ubuntu)
2. [x] Make sure that data from the last version appears in the new version OK.
3. [x] Test that windows and tabs restore when closed, including active tab.
4. [x] Test that the previous version's cookies are preserved in the next version.
5. [x] Move away your entire `~/Library/Application\ Support/Brave` folder (`%appdata%\Brave in Windows`, `./config/brave` in Ubuntu)

## Update tests

1. [ ] Test that updating using `BRAVE_UPDATE_VERSION=0.8.3` env variable works correctly.

**Comment by luixxiul** [comment]
Test passed, except
- Apperance settings: Home icon is not displayed until the URL bar is actually hovered
- Reloading on the same tab: Turning Safe Browsing off and shields off both disable safe browsing for excellentmovies.net.
- Evercookie
````
userData mechanism: undefined
cookieData mechanism: 675
localData mechanism: 675
globalData mechanism: undefined
sessionData mechanism: 675
windowData mechanism: 675
pngData mechanism: 675
etagData mechanism: 675
cacheData mechanism: 675
dbData mechanism: 675
lsoData mechanism: undefined
slData mechanism: undefined
````
- Browsing history: not cleared for saved and restored tabs 
- Flash placeholder
- PDF.js: Preference to disable it is not applied
- Copy Image: cannot be pasted in a local folder ($HOME/Pictures)

Also
- On contest menu, Look Up "something" and Search for "Something" are duping

PDF loading should be fixed in the next release (Merged in dev-channel already: https://github.com/brave/browser-laptop/commit/0d4c4446bc5b82b4cee61b0aa17599b103a31365)

**Comment by luixxiul** [comment]
Also except update test

**Comment by luixxiul** [comment]
Flash placeholder regression is worked on here: #2489

**Comment by neeklamy** [comment]
Regarding the `Look Up…` and `Search for…` contextual menu items, the `Look Up…` is an OS X only item to do a dictionary search (*thought: should it be limited to word boundaries? Safari doesn’t…*). It was introduced with #2315.

The contextual menu on Safari is much the same, only the latter is simply labelled `Search with [preferred engine]`.

![image](https://cloud.githubusercontent.com/assets/155358/16894805/81f0e9e8-4b5a-11e6-82ec-73d138f4ee6c.png)

**Comment by luixxiul** [comment]
Thanks @neeklamy, I'm a OS X newbie ;-)

**Comment by neeklamy** [comment]
You’re welcome, @luixxiul, and welcome to Cupertino’s loveliest OS!

If you’ve got a trackpad, there’s a wealth of taps, swipes and other gestures you can use, my favourite is the three-finger tap look up. 

> Tap with three fingers to look up a word or take other actions with dates, addresses, phone numbers, and other data.
> – [Use Multi-Touch gestures on your Mac](https://support.apple.com/en-us/HT204895)

It works really nicely on links too in Safari, Apple Mail and most other places, but sadly not in Brave as of yet.

![safari-three-finger-tap-lookup](https://cloud.githubusercontent.com/assets/155358/16895023/53aeeae8-4b60-11e6-867a-9f0bc5a14b6d.gif)

**Comment by luixxiul** [comment]
Thanks @neeklamy! I will appreciate if you create an issue for that :-)

**Comment by luixxiul** [comment]
> Browsing history: not cleared for saved and restored tabs

I think another option should be added to clear session info (clear opened tabs etc)

**Comment by neeklamy** [comment]
Done! #2520

**Comment by luixxiul** [comment]
Closing this as the issues has been reported separately.
