### ISSUE TITLE
Manual tests for 0.12.0 RC1 fixes 

### ISSUE THREAD

**Issue by alexwykoff** [brave/browser-laptop#3699]
- [ ] use ledger-publisher@0.8.58 to get better bullet-proofing against mangled files ([#3697](https://github.com/brave/browser-laptop/issues/3697))
 - [ ] Spelling is wrong on Ukrainian ([#3695](https://github.com/brave/browser-laptop/issues/3695))
 - [ ] Wrong suggestions appear in the autocomplete list under URL bar ([#3643](https://github.com/brave/browser-laptop/issues/3643))
 - [ ] ledger should check bitcoin handler for a specified session ([#3625](https://github.com/brave/browser-laptop/issues/3625))
 - [ ] Add shortcut to view page source ([#3685](https://github.com/brave/browser-laptop/issues/3685))
 - [ ] Add shortcut to view page source ([#3474](https://github.com/brave/browser-laptop/issues/3474))
 - [ ] Extra separator under bookmark menu ([#3666](https://github.com/brave/browser-laptop/issues/3666))
 - [ ] serialize app state saves ([#3632](https://github.com/brave/browser-laptop/issues/3632))
 - [ ] potential race condition on session state save ([#3543](https://github.com/brave/browser-laptop/issues/3543))
 - [ ] siteUtils.clearSitesWithoutTags has misleading name refactoring ([#3639](https://github.com/brave/browser-laptop/issues/3639))
 - [ ] Search Settings Panel: Search Bar Options bookmarks documentation history settings ([#2124](https://github.com/brave/browser-laptop/issues/2124))
 - [ ] Fix #2124: Search Options  ([#3678](https://github.com/brave/browser-laptop/issues/3678))
 - [ ] passwords.properties not being loaded at app level ([#3671](https://github.com/brave/browser-laptop/issues/3671))
 - [ ] Some autofill automated tests are failing ([#3618](https://github.com/brave/browser-laptop/issues/3618))
 - [ ] Bookmark customTitle from previously bookmarked entry is no longer re-used ([#3641](https://github.com/brave/browser-laptop/issues/3641))
 - [ ] Bookmark title is not updated unbookmarking/rebookmarking bookmarks ([#3284](https://github.com/brave/browser-laptop/issues/3284))
 - [ ] Add an option to temporarily disable mixed content protection enhancement security ([#3443](https://github.com/brave/browser-laptop/issues/3443))
 - [ ] check for publisher rules update once a day enhancement ([#3638](https://github.com/brave/browser-laptop/issues/3638))
 - [ ] Found entries on about:history cannot be deleted ([#3566](https://github.com/brave/browser-laptop/issues/3566))
 - [ ] bookmarked pages not deleted from history after restarting bookmarks ([#3616](https://github.com/brave/browser-laptop/issues/3616))
 - [ ] clear the lastAccessedTime for all tags when clearing history ([#3620](https://github.com/brave/browser-laptop/issues/3620))
 - [ ] about:history shows bookmarks when searched ([#3627](https://github.com/brave/browser-laptop/issues/3627))
 - [ ] about:history no longer includes bookmarks ([#3628](https://github.com/brave/browser-laptop/issues/3628))
 - [ ] friendlier add funds panel for users without a bitcoin: handler ([#3623](https://github.com/brave/browser-laptop/issues/3623))
 - [ ] use updated ledger-publisher ledger integration ([#3613](https://github.com/brave/browser-laptop/issues/3613))

**Comment by alexwykoff** [comment]
closed in favor of https://github.com/brave/browser-laptop/issues/3738
