### ISSUE TITLE
Manual tests for 0.12.1 Preview 1 fixes - Ubuntu pass

### ISSUE THREAD

**Issue by alexwykoff** [brave/browser-laptop#3868]
- [ ] detect Brave Payments user location and display different dialog content ([#3711](https://github.com/brave/browser-laptop/issues/3711))
 - [ ] bitcoin wallet address overflows on some screen resolutions ([#3629](https://github.com/brave/browser-laptop/issues/3629))
 - [ ] clipboard icon on add funds popover probably needs to be moved ([#3484](https://github.com/brave/browser-laptop/issues/3484))
 - [ ] New (and much improved) layout for Add funds... dialog ([#3677](https://github.com/brave/browser-laptop/issues/3677))
 - [ ] Harmonize publisher visits ([#3852](https://github.com/brave/browser-laptop/issues/3852))
 - [ ] a publisher should get a visit increment only on a new tab... ([#3830](https://github.com/brave/browser-laptop/issues/3830))
 - [ ] Add Malay (Malaysia) language ([#3843](https://github.com/brave/browser-laptop/issues/3843))
 - [ ] whitelisted mixed content pages incorrectly showing as secure in private browsing mode ([#3793](https://github.com/brave/browser-laptop/issues/3793))
 - [ ] mixed content site setting from private mode should not apply in regular browsing mode privacy ([#3795](https://github.com/brave/browser-laptop/issues/3795))
 - [ ] Mixed-content lock control should be able to re-lock and reload the page like Firefox. ([#3770](https://github.com/brave/browser-laptop/issues/3770))
 - [ ] add notification event 24h prior to reconcilation ([#3828](https://github.com/brave/browser-laptop/issues/3828))
 - [ ] Add notification under status message to inform user of their contribution day ([#3801](https://github.com/brave/browser-laptop/issues/3801))
 - [ ] Bitcoin exchange extravaganza ([#3824](https://github.com/brave/browser-laptop/issues/3824))
 - [ ] Mac menubar is inaccessible while download is in progress ([#3823](https://github.com/brave/browser-laptop/issues/3823))
 - [ ] add something to the UI to inform ledger.js when the user closes the 'add funds' popover ([#3621](https://github.com/brave/browser-laptop/issues/3621))
 - [ ] Clear Autofill option in the Clear browsing data modal autofill suggestion ([#3458](https://github.com/brave/browser-laptop/issues/3458))
 - [ ] Address bar should be active for about:newtab ([#3712](https://github.com/brave/browser-laptop/issues/3712))
 - [ ] Address bar is not "active" when it should be ([#3718](https://github.com/brave/browser-laptop/issues/3718))
 - [ ] Cmd+T (New Tab) shortcut becomes disabled while navigation occurs keyboard-shortcuts ([#3782](https://github.com/brave/browser-laptop/issues/3782))
 - [ ] Balance of bitcoin can show a scary 0 value when no connection duplicate ([#3785](https://github.com/brave/browser-laptop/issues/3785))
 - [ ] Feeling of panic immidiately on every start ([#3778](https://github.com/brave/browser-laptop/issues/3778))
 - [ ] Can't enable "Web notifications" on twitter ([#3579](https://github.com/brave/browser-laptop/issues/3579))
 - [ ] Closed frames shouldn't include newtab ([#3258](https://github.com/brave/browser-laptop/issues/3258))
 - [ ] Show favicons applied on bookmark folders along with bookmarked items. ([#3622](https://github.com/brave/browser-laptop/issues/3622))
 - [ ] Random: ledger balance error: "Error: HTTP response 401 for GET /api/balance" ([#3736](https://github.com/brave/browser-laptop/issues/3736))
 - [ ] memory pressure crash ([#3775](https://github.com/brave/browser-laptop/issues/3775))
 - [ ] Disabling Payments doesn't retain states ([#3612](https://github.com/brave/browser-laptop/issues/3612))
 - [ ] Ledger timer not starting when changing focus to tabs opened in the background ([#3716](https://github.com/brave/browser-laptop/issues/3716))
 - [ ] UI tweak: Insecure dialog has some white on the right ([#3708](https://github.com/brave/browser-laptop/issues/3708))

**Comment by alexwykoff** [comment]
Closing in favor of https://github.com/brave/browser-laptop/issues/3900
