### ISSUE TITLE
Manual tests for Ubuntu 0.12.3 RC6 fixes

### ISSUE THREAD

**Issue by alexwykoff** [brave/browser-laptop#4448]
- [ ] password extensions stop working after switching back to brave password manager ([#4425](https://github.com/brave/browser-laptop/issues/4425))
 - [ ] Brave crashes when Dashlane is selected ([#4422](https://github.com/brave/browser-laptop/issues/4422))
 - [ ] Crash: Closing an undocked chat window in Gmail crashes brave. ([#4415](https://github.com/brave/browser-laptop/issues/4415))
 - [ ] Regression: Bookmarks toolbar - Adding bookmarks to folders does not update the view ([#4420](https://github.com/brave/browser-laptop/issues/4420))
 - [ ] Upgrade to Electron 1.4.9 ([#4414](https://github.com/brave/browser-laptop/issues/4414))
 - [ ] Flash content not loaded in Private window ([#3998](https://github.com/brave/browser-laptop/issues/3998))
 - [ ] Browser 0.12.3 RC3 on Windows periodically becomes unresponsive to clicks after load ([#4391](https://github.com/brave/browser-laptop/issues/4391))
 - [ ] Payment prefs: use relative local and ISO 8601 dates ([#4370](https://github.com/brave/browser-laptop/issues/4370))
 - [ ] Show the caption buttons when in full screen mode (Windows only) ([#4377](https://github.com/brave/browser-laptop/issues/4377))
 - [ ] Caption buttons are not shown when in fullscreen mode (Windows) ([#4376](https://github.com/brave/browser-laptop/issues/4376))
 - [ ] Flicker-Effect on Hover (Unable to Select Text Easily) ([#4365](https://github.com/brave/browser-laptop/issues/4365))
 - [ ] Payment History CSV export download has correct filename (+row sorting and total row) ([#4346](https://github.com/brave/browser-laptop/issues/4346))
 - [ ] Enabling Block Scripts redirects twitter to Mobile site. ([#2884](https://github.com/brave/browser-laptop/issues/2884))
 - [ ] site-specific Bravery settings headers should disappear when the list is empty feature/bravery ([#4319](https://github.com/brave/browser-laptop/issues/4319))
 - [ ] un-ignore cert transparency errors ([#4159](https://github.com/brave/browser-laptop/issues/4159))
 - [ ] mixed content on gq.com ([#4366](https://github.com/brave/browser-laptop/issues/4366))
 - [ ] Unable to open PDF files in browser ([#4335](https://github.com/brave/browser-laptop/issues/4335))
 - [ ] Address-bar shifts at times ([#4309](https://github.com/brave/browser-laptop/issues/4309))
 - [ ] URL Bar resizes when refresh/stop button is loaded ([#4303](https://github.com/brave/browser-laptop/issues/4303))
 - [ ] Change to brave server for our own hosted extensions ([#4123](https://github.com/brave/browser-laptop/issues/4123))
 - [ ] Allow for auto updating extensions without releases extensions ([#4080](https://github.com/brave/browser-laptop/issues/4080))
 - [ ] Install extensions remotely using default component installer instead of prepackaging them extensions ([#4081](https://github.com/brave/browser-laptop/issues/4081))
 - [ ] Install / update extensions w/ component updater ([#4105](https://github.com/brave/browser-laptop/issues/4105))
 - [ ] pulldown on menubar cannot be opened until second click ([#4175](https://github.com/brave/browser-laptop/issues/4175))
 - [ ] Windows 7 - resize handle on top right corner is hard to click ([#4144](https://github.com/brave/browser-laptop/issues/4144))
 - [ ] Fixed draggable areas of window. ([#4296](https://github.com/brave/browser-laptop/issues/4296))
 - [ ] lots of regions on the titlebar can't be dragged but should be able to be dragged ([#4235](https://github.com/brave/browser-laptop/issues/4235))
 - [ ] Brave payments wrong contribution date ([#4058](https://github.com/brave/browser-laptop/issues/4058))
 - [ ] Reset old reconcileStamp when re-enabling Payments ([#4314](https://github.com/brave/browser-laptop/issues/4314))
 - [ ] Hide the load time from URL bar on all platforms if below the narrow breakpoint ([#4315](https://github.com/brave/browser-laptop/issues/4315))
 - [ ] hide page load time info in Address Bar below 600px window width enhancement ([#1046](https://github.com/brave/browser-laptop/issues/1046))
 - [ ] QR Code Popup from Add funds dialog scrolls independently from its parent ([#4043](https://github.com/brave/browser-laptop/issues/4043))
 - [ ] QR popup scrolling ([#4316](https://github.com/brave/browser-laptop/issues/4316))
 - [ ] Ledger does not track windows created before the wallet ([#4274](https://github.com/brave/browser-laptop/issues/4274))
 - [ ] ledger transaction history should have receipt links ([#3477](https://github.com/brave/browser-laptop/issues/3477))
 - [ ] Payment history CSV receipt links #3477 (WIP) ([#4312](https://github.com/brave/browser-laptop/issues/4312))
 - [ ] Enabling Block Scripts redirects twitter to Mobile site. ([#2884](https://github.com/brave/browser-laptop/issues/2884))
 - [ ] HTTPS count shown even when its disabled ([#4300](https://github.com/brave/browser-laptop/issues/4300))
 - [ ] use main frame url for webrequest first party url ([#4145](https://github.com/brave/browser-laptop/issues/4145))
 - [ ] unsafe use of firstPartyUrl ([#4137](https://github.com/brave/browser-laptop/issues/4137))
 - [ ] Bookmarks toolbar render is off when '>>' expander is used. ([#4272](https://github.com/brave/browser-laptop/issues/4272))
 - [ ] Line should always appear when user scroll down ([#4085](https://github.com/brave/browser-laptop/issues/4085))
 - [ ] While in fullscreen the navbar is not visible ([#4234](https://github.com/brave/browser-laptop/issues/4234))
 - [ ] Show top panel in fullscreen on mouse over ([#4193](https://github.com/brave/browser-laptop/issues/4193))
 - [ ] Update translation ([#4308](https://github.com/brave/browser-laptop/issues/4308))
 - [ ] No confirmation window of importing data from IE importer ([#4275](https://github.com/brave/browser-laptop/issues/4275))
 - [ ] Handle nested bookmarks folder ([#4293](https://github.com/brave/browser-laptop/issues/4293))
 - [ ] Importer should be able to handle nested folder from bookmarks properly ([#4291](https://github.com/brave/browser-laptop/issues/4291))
 - [ ] Make toolbar messages non-selectable ([#4306](https://github.com/brave/browser-laptop/issues/4306))
 - [ ] Make toolbar messages non-selectable ([#4126](https://github.com/brave/browser-laptop/issues/4126))
 - [ ] Update favicon of imported items ([#4270](https://github.com/brave/browser-laptop/issues/4270))
 - [ ] Update favicon from importer ([#4271](https://github.com/brave/browser-laptop/issues/4271))
 - [ ] Fix suggestions list overflow (unintentionally introduced when fixing resizing) ([#4299](https://github.com/brave/browser-laptop/issues/4299))
 - [ ] Suggestions Clipped ([#4298](https://github.com/brave/browser-laptop/issues/4298))
 - [ ] Add search shortcuts for MDN, GitHub, and Stack Overflow ([#4213](https://github.com/brave/browser-laptop/issues/4213))
 - [ ] Media queries for elements inside #urlInput need improving ([#4170](https://github.com/brave/browser-laptop/issues/4170))
 - [ ] Improvements to Title Bar ([#4188](https://github.com/brave/browser-laptop/issues/4284))
 - [ ] Shields and Windows button hidden in title mode when browser size is reduced titlebar ([#4241](https://github.com/brave/browser-laptop/issues/4241))
 - [ ] Manually entered URL as bookmark doesn't show the bookmarked(orange) icon ([#4273](https://github.com/brave/browser-laptop/issues/4273))
 - [ ] tracking issue: regressions caused by commit 35de6cf ([#4267](https://github.com/brave/browser-laptop/issues/4267))
