### ISSUE TITLE
Manual tests for Ubuntu 0.12.4 Preview1

### ISSUE THREAD

**Issue by alexwykoff** [brave/browser-laptop#4497]
## Installer

1. [x] Check that installer is close to the size of last release.
2. [x] Check signature: If OS Run `spctl --assess --verbose /Applications/Brave.app/` and make sure it returns `accepted`.  If Windows right click on the installer exe and go to Properties, go to the Digital Signatures tab and double click on the signature.  Make sure it says "The digital signature is OK" in the popup window.
3. [x] Check Brave, electron, and libchromiumcontent version in About and make sure it is EXACTLY as expected.

## Seriously, do these first. If you cannot replicate a particular action, @mention mrose17 in #testers and let's find a solution that is sustainable

1. [ ] Create a wallet with a value other than $5 selected in the monthly budget dropdown. Click on the 'Add Funds' button and check that Coinbase transactions are blocked.
2. [x] Remove all `ledger-*.json` files from `~/Library/Application\ Support/Brave/`. Go to the Payments tab in about:preferences, enable payments, click on `create wallet`. Check that the `add funds` button appears after a wallet is created.
3. [ ] Click on `add funds` and verify that adding funds through Coinbase increases the account balance.
4. [ ] Repeat the step above but add funds by scanning the QR code in a mobile bitcoin app instead of through Coinbase.
5. [ ] Visit nytimes.com for a few seconds and make sure it shows up in the Payments table.
6. [ ] Go to https://jsfiddle.net/LnwtLckc/5/ and click the register button. In the Payments tab, click `add funds`. Verify that the `transfer funds` button is visible and that clicking on `transfer funds` opens a jsfiddle URL in a new tab.
7. [ ] Go to https://jsfiddle.net/LnwtLckc/5/ and click `unregister`. Verify that the `transfer funds` button no longer appears in the `add funds` modal.
8. [ ] Check that disabling payments and enabling them again does not lose state.

## Data

1. [ ] Make sure that data from the last version appears in the new version OK.
2. [ ] Test that the previous version's cookies are preserved in the next version.

## About pages

1. [ ] Test that about:adblock loads
2. [ ] Test that about:autofill loads
3. [ ] Test that about:bookmarks loads bookmarks
4. [ ] Test that about:downloads loads downloads
5. [ ] Test that about:extensions loads
6. [ ] Test that about:history loads history
7. [ ] Test that about:passwords loads
8. [ ] Test that about:preferences changing a preference takes effect right away
9. [ ] Test that about:preferences language change takes effect on re-start

## Bookmarks

1. [ ] Test that creating a bookmark on the bookmarks toolbar works
2. [ ] Test that creating a bookmark folder on the bookmarks toolbar works
3. [ ] Test that moving a bookmark into a folder by drag and drop on the bookmarks folder works
4. [ ] Test that clicking a bookmark in the toolbar loads the bookmark.
5. [ ] Test that clicking a bookmark in a bookmark toolbar folder loads the bookmark.

## Context menus
1. [ ] Make sure context menu items in the URL bar work
2. [ ] Make sure context menu items on content work with no selected text.
3. [ ] Make sure context menu items on content work with selected text.
4. [ ] Make sure context menu items on content work inside an editable control (input, textarea, or contenteditable).

## Find on page

1. [ ] Ensure search box is shown with shortcut
2. [ ] Test successful find
3. [ ] Test forward and backward find navigation
4. [ ] Test failed find shows 0 results
5. [ ] Test match case find

## Geolocation

1. [ ] Check that https://developer.mozilla.org/en-US/docs/Web/API/Geolocation/Using_geolocation works

## Site hacks

1. [ ] Test https://www.twitch.tv/adobe sub-page loads a video and you can play it

## Downloads

1. [ ] Test downloading a file works and that all actions on the download item works.

## Fullscreen

1. [ ] Test that entering full screen window works View -> Toggle Full Screen. And exit back (Not Esc).
2. [ ] Test that entering HTML5 full screen works. And Esc to go back. (youtube.com)

## Tabs and Pinning

1. [ ] Test that tabs are pinnable
2. [ ] Test that tabs are unpinnable
3. [ ] Test that tabs are draggable to same tabset
4. [ ] Test that tabs are draggable to alternate tabset

## Zoom

1. [ ] Test zoom in / out shortcut works
2. [ ] Test hamburger menu zooms.
3. [ ] Test zoom saved when you close the browser and restore on a single site.
4. [ ] Test zoom saved when you navigate within a single origin site.
5. [ ] Test that navigating to a different origin resets the zoom

## Bravery settings

1. [ ] Check that HTTPS Everywhere works by loading http://www.apple.com
2. [ ] Turning HTTPS Everywhere off and shields off both disable the redirect to https://www.apple.com
3. [ ] Check that ad replacement works on http://slashdot.org
4. [ ] Check that toggling to blocking and allow ads works as expected.
5. [ ] Test that clicking through a cert error in https://badssl.com/ works.
6. [ ] Test that Safe Browsing works (http://excellentmovies.net/)
7. [ ] Turning Safe Browsing off and shields off both disable safe browsing for http://excellentmovies.net/.
8. [ ] Visit https://brianbondy.com/ and then turn on script blocking, nothing should load. Allow it from the script blocking UI in the URL bar and it should work.
9. [ ] Test that about:preferences default Bravery settings take effect on pages with no site settings.
10. [ ] Test that turning on fingerprinting protection in about:preferences shows 3 fingerprints blocked at https://jsfiddle.net/bkf50r8v/13/. Test that turning it off in the Bravery menu shows 0 fingerprints blocked.
11. [ ] Test that 3rd party storage results are blank at https://jsfiddle.net/7ke9r14a/9/ when 3rd party cookies are blocked and not blank when 3rd party cookies are unblocked.
12. [ ] Test that audio fingerprint is blocked at https://audiofingerprint.openwpm.com/ when fingerprinting protection is on.

## Content tests

1. [ ] Go to https://brianbondy.com/ and click on the twitter icon on the top right. Test that context menus work in the new twitter tab.
2. [ ] Load twitter and click on a tweet so the popup div shows.   Click to dismiss and repeat with another div. Make sure it shows.
3. [ ] Go to http://www.bennish.net/web-notifications.html and test that clicking on 'Show' pops up a notification asking for permission. Make sure that clicking 'Deny' leads to no notifications being shown.
4. [ ] Go to https://trac.torproject.org/projects/tor/login and make sure that the password can be saved. Make sure the saved password shows up in `about:passwords`. Then reload https://trac.torproject.org/projects/tor/login and make sure the password is autofilled.
5. [ ] Open a github issue and type some misspellings, make sure they are underlined.
6. [ ] Make sure that right clicking on a word with suggestions gives a suggestion and that clicking on the suggestion replaces the text.
7. [ ] Make sure that Command + Click (Control + Click on Windows, Control + Click on Ubuntu) on a link opens a new tab but does NOT switch to it.  Click on it and make sure it is already loaded.
8. [ ] Open an email on http://mail.google.com/ or inbox.google.com and click on a link. Make sure it works.
9. [ ] Test that PDF is loaded at http://www.orimi.com/pdf-test.pdf
10. [ ] Test that https://mixed-script.badssl.com/ shows up as grey not red (no mixed content scripts are run).

## Flash tests
1. [ ] Turn on Flash in about:preferences#security. Test that clicking on 'Install Flash' banner on myspace.com shows a notification to allow Flash and that the banner disappears when 'Allow' is clicked.
2. [ ] Test that flash placeholder appears on http://www.y8.com/games/superfighters

## Autofill tests
1. [ ] Test that autofill works on http://www.roboform.com/filling-test-all-fields

## Per release specialty tests

 - [ ] Preview 1 Open Items
 - [x] Style needs update on preferences > search ([#4493](https://github.com/brave/browser-laptop/issues/4493))
 - [x] History columns have style issues ([#4492](https://github.com/brave/browser-laptop/issues/4492))
 - [x] Help -> Submit Feedback is not opening the mail client for certain users ([#4487](https://github.com/brave/browser-laptop/issues/4487))
 - [x] Regression: Brave Payments : Ledger headers should not disappear while scrolling. ([#4461](https://github.com/brave/browser-laptop/issues/4461))
 - [x] Stop recreating shortcut on my desktop after every update ([#1181](https://github.com/brave/browser-laptop/issues/1181))
 - [x] Brave 0.12.2dev-RC4 crash when closing a tab crash ([#4290](https://github.com/brave/browser-laptop/issues/4290))
 - [x] Brave crashes when tabs are pinned(Intermittent issues) ([#3760](https://github.com/brave/browser-laptop/issues/3760))
 - [x] history list shows unnecessary duplicates for same-page actions (like google maps) ([#3848](https://github.com/brave/browser-laptop/issues/3848))
 - [ ] Preview 1 Closed Items
 - [ ] Support regional adblock files ([#1357](https://github.com/brave/browser-laptop/issues/1357))
 - [ ] Regional adblock ([#4489](https://github.com/brave/browser-laptop/issues/4489))
 - [ ] Brave payments: Line should always appear when user scroll down ([#4395](https://github.com/brave/browser-laptop/issues/4395))
 - [ ] Brave payments: Line should always appear when user scroll down design ([#3888](https://github.com/brave/browser-laptop/issues/3888))
 - [ ] Polished up full screen detection logic (Windows only) ([#4463](https://github.com/brave/browser-laptop/issues/4463))
 - [ ] Caption buttons inconsistency ([#4416](https://github.com/brave/browser-laptop/issues/4416))
 - [ ] Minor toolbar visual refinement suggestions ([#4400](https://github.com/brave/browser-laptop/issues/4400))
 - [ ] Generating and filling bookmark folders should cause the bookmark menu to rebuild ([#3968](https://github.com/brave/browser-laptop/issues/3968))
 - [ ] Update `menu.js` to rebuild when handling (add/remove) bookmark folders ([#4390](https://github.com/brave/browser-laptop/issues/4390))
 - [ ] Bookmarks menu not updated when adding/removing bookmark folder ([#4227](https://github.com/brave/browser-laptop/issues/4227))
 - [ ] Use png_data for favicon of bookmarks imported from HTML ([#4345](https://github.com/brave/browser-laptop/issues/4345))
 - [ ] Update Favicons doesnt work as expected ([#4339](https://github.com/brave/browser-laptop/issues/4339))
 - [ ] Defer setAutofill*Detail to frame.js ([#4357](https://github.com/brave/browser-laptop/issues/4357))
 - [ ] Autofill Modal doesn't show when about:autofill opened from about:about ([#4350](https://github.com/brave/browser-laptop/issues/4350))
 - [ ] Adds rounded borders to the top corners for Windows 7 ([#4342](https://github.com/brave/browser-laptop/issues/4342))
 - [ ] Windows 7 - window corners need border radius ([#4216](https://github.com/brave/browser-laptop/issues/4216))
 - [ ] remove the word visit for non-us bitcoin links ([#4333](https://github.com/brave/browser-laptop/issues/4333))
 - [ ] Move the word visit inside the payments button ([#4212](https://github.com/brave/browser-laptop/issues/4212))
 - [ ] Missing "Bookmark This Link" context menu item for selected text link ([#3807](https://github.com/brave/browser-laptop/issues/3807))
 - [ ] Allow per site Bravery settings in private tabs ([#1824](https://github.com/brave/browser-laptop/issues/1824))
 - [ ] Private tab preferences ([#4468](https://github.com/brave/browser-laptop/issues/4468))
 - [ ] Window size is not restored correctly. ([#4385](https://github.com/brave/browser-laptop/issues/4385))
 - [ ] Save the window size (width, height) and use it when restoring from s…  ([#4482](https://github.com/brave/browser-laptop/issues/4482))
 - [ ] about:history enhancements ([#4488](https://github.com/brave/browser-laptop/issues/4488))
 - [ ] refine styles in about:history to look more like mockup ([#4072](https://github.com/brave/browser-laptop/issues/4072))
 - [ ] History entries are not properly aligned ([#3996](https://github.com/brave/browser-laptop/issues/3996))
 - [ ] SitePermissionsPage needs a 'clear all' button ([#4134](https://github.com/brave/browser-laptop/issues/4134))
 - [ ] Add an option to clear saved site exception in clear browsing data dialog ([#4174](https://github.com/brave/browser-laptop/issues/4174))
 - [ ] Add setting observer ([#4452](https://github.com/brave/browser-laptop/issues/4452))
 - [ ] Add tests for Ledger export utilities (and fix bugs) (rebased #4429) ([#4436](https://github.com/brave/browser-laptop/issues/4436))
 - [ ] Flash content not loaded in Private window ([#3998](https://github.com/brave/browser-laptop/issues/3998))
 - [ ] noscript and flash site settings should not be shared from private browsing into regular browsing ([#3835](https://github.com/brave/browser-laptop/issues/3835))
 - [ ] restore noscript 'allow once' functionality ([#2745](https://github.com/brave/browser-laptop/issues/2745))
 - [ ] Localization issue: US date format is confusing to everyone ([#4294](https://github.com/brave/browser-laptop/issues/4294))
 - [ ] Small adjustments to Payment History modal and CSV files ([#4332](https://github.com/brave/browser-laptop/issues/4332))
 - [ ] Use the latest version of ledger-* packages ([#4340](https://github.com/brave/browser-laptop/issues/4340))

## Session storage

Do not forget to make a backup of your entire `~/Library/Application\ Support/Brave` folder.

1. [ ] Temporarily move away your `~/Library/Application\ Support/Brave/session-store-1` and test that clean session storage works. (`%appdata%\Brave in Windows`, `./config/brave` in Ubuntu)
2. [ ] Test that windows and tabs restore when closed, including active tab.
3. [ ] Move away your entire `~/Library/Application\ Support/Brave` folder (`%appdata%\Brave in Windows`, `./config/brave` in Ubuntu)

## Cookie and Cache

1. [ ] Make a backup of your profile, turn on all clearing in preferences and shut down.  Make sure when you bring the browser back up everything is gone that is specified.
2. [ ] Go to http://samy.pl/evercookie/ and set an evercookie. Check that going to prefs, clearing site data and cache, and going back to the Evercookie site does not remember the old evercookie value.

## Update tests

1. [ ] Test that updating using `BRAVE_UPDATE_VERSION=0.8.3` env variable works correctly.
