### ISSUE TITLE
Urlbar Optimization Problems Tracking issues

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#4585]
- [ ] #4584 (BB: We will probably backout the URL bar optimization work to fix this)
- [ ] #4583 (BB: We will probably backout the URL bar optimization work to fix this)
- [ ] #4581 (BB: We will probably backout the URL bar optimization work to fix this)
- [ ] #4580

**Comment by Sh1d0w** [comment]
Can I kindly promote my own set of issues related to the URL bar collected over time ? :)

https://github.com/brave/browser-laptop/issues/4219
https://github.com/brave/browser-laptop/issues/3753
https://github.com/brave/browser-laptop/issues/3730

**Comment by bbondy** [comment]
@Sh1d0w this is only related to the optimizaiton which was backed out, if you'd like a generalized tracking issue though pls post a new issue for that.

**Comment by Sh1d0w** [comment]
Got it, sorry.

**Comment by diracdeltas** [comment]
all of these were fixed in 9e9815434a569d733a10ff077b8198d525fbc4de afaict
