### ISSUE TITLE
Manual tests for Windows x64 0.12.6 Preview 1

### ISSUE THREAD

**Issue by alexwykoff** [brave/browser-laptop#4993]
## Installer

1. [ ] Check that installer is close to the size of last release.
2. [ ] Check signature: If OS Run `spctl --assess --verbose /Applications/Brave.app/` and make sure it returns `accepted`.  If Windows right click on the installer exe and go to Properties, go to the Digital Signatures tab and double click on the signature.  Make sure it says "The digital signature is OK" in the popup window.
3. [ ] Check Brave, electron, and libchromiumcontent version in About and make sure it is EXACTLY as expected.

## Per release specialty tests

 - [ ] [support] invalid homepage URL causes 'uncaught typeerror' ([#4974](https://github.com/brave/browser-laptop/issues/4974))
 - [ ] Setting Brave as default from the startup check on win7 doesn't work ([#4937](https://github.com/brave/browser-laptop/issues/4937))
 - [ ] default browser check should run only on release build ([#4959](https://github.com/brave/browser-laptop/pull/4959))
 - [ ] default browser check should run only on release build ([#4958](https://github.com/brave/browser-laptop/issues/4958))
 - [ ] HackerOne report: punycode not properly displayed when setting homepage ([#4747](https://github.com/brave/browser-laptop/issues/4747))
 - [ ] [HackerOne] about: pages may be clickjacked ([#4885](https://github.com/brave/browser-laptop/issues/4885))
 - [ ] [HackerOne] access-control-allow-origin: * set on about: pages ([#4913](https://github.com/brave/browser-laptop/issues/4913))
 - [ ] Autocomplete does not work well ([#3049](https://github.com/brave/browser-laptop/issues/3049))
 - [ ] Import favicon fix: ([#4930](https://github.com/brave/browser-laptop/pull/4930))
 - [ ] Favicons not loaded when bookmarks imported from browser ([#4882](https://github.com/brave/browser-laptop/issues/4882))
 - [ ] Upgrade to brave/electrton 1.4.16 ([#4954](https://github.com/brave/browser-laptop/issues/4954))
 - [ ] new icons for desktop app releases design ([#4120](https://github.com/brave/browser-laptop/issues/4120))
 - [ ] Improve UX of default browser check and Manage Adblock Setting button ([#4951](https://github.com/brave/browser-laptop/pull/4951))
 - [ ] Always check on startup option is too glued to the set as default... button ([#4935](https://github.com/brave/browser-laptop/issues/4935))
 - [ ] Bookmarks bar select element should not be disabled ([#4936](https://github.com/brave/browser-laptop/issues/4936))
 - [ ] Split apart "always show bookmarks toolbar" and the bookmarks toolbar display mode ([#4944](https://github.com/brave/browser-laptop/pull/4944))
 - [ ] fuzzy.ai listing investigation ([#4938](https://github.com/brave/browser-laptop/issues/4938))
 - [ ] Set as default browser switch should not show default UI settings ([#4934](https://github.com/brave/browser-laptop/issues/4934))
 - [ ] Delete "defaultBrowserCheckComplete" only when check on startup is on ([#4942](https://github.com/brave/browser-laptop/pull/4942))
 - [ ] Setting Brave as default from the startup check on Linux doesn't work ([#4939](https://github.com/brave/browser-laptop/issues/4939))
 - [ ] Add whether brave is default browser check ([#4872](https://github.com/brave/browser-laptop/pull/4872))
 - [ ] General Settings: "Brave is not your default browser" setting documentation ([#2105](https://github.com/brave/browser-laptop/issues/2105))
 - [ ] Upgrade to brave/electron 1.4.15 ([#4932](https://github.com/brave/browser-laptop/issues/4932))
 - [ ] Move bookmark hanger arrow now that reload is on about pages ([#4924](https://github.com/brave/browser-laptop/pull/4924))
 - [ ] Move bookmark hanger arrow now that reload is on about pages ([#4923](https://github.com/brave/browser-laptop/issues/4923))
 - [ ] URL input field on the bookmark pulldown disappears ([#4927](https://github.com/brave/browser-laptop/pull/4927))
 - [ ] URL input field on the bookmark pulldown disappears ([#4897](https://github.com/brave/browser-laptop/issues/4897))
 - [ ] Start suggestions after first character not second ([#3235](https://github.com/brave/browser-laptop/issues/3235))
 - [ ] [HackerOne] window.confirm crashes Brave crash ([#4883](https://github.com/brave/browser-laptop/issues/4883))
 - [ ] Fix Brave crashing on confirm ([#4891](https://github.com/brave/browser-laptop/pull/4891))
 - [ ] History page now properly opens new tab w/ link that was clicked ([#4919](https://github.com/brave/browser-laptop/pull/4919))
 - [ ] regression: double-clicking of entries on about:history opens a blank new tab ([#4909](https://github.com/brave/browser-laptop/issues/4909))
 - [ ] Caption buttons are no longer tab focusable ([#4902](https://github.com/brave/browser-laptop/pull/4902))
 - [ ] Pressing Tab, then Enter in URL bar unexpectedly minimizes window on Windows ([#4846](https://github.com/brave/browser-laptop/issues/4846))
 - [ ] Do not use default setting when value is false ([#4907](https://github.com/brave/browser-laptop/pull/4907))
 - [ ] getSetting() should return the correct vale ([#4903](https://github.com/brave/browser-laptop/issues/4903))
 - [ ] Start suggestions after first character not second fixes #3235 ([#3238](https://github.com/brave/browser-laptop/pull/3238))
 - [ ] UrlbarSuggestions does not work if you are offline ([#4821](https://github.com/brave/browser-laptop/pull/4821))
 - [ ] Allow about pages to reload and clone ([#4881](https://github.com/brave/browser-laptop/pull/4881))
 - [ ] Error tab cannot be reloaded or cloned ([#2826](https://github.com/brave/browser-laptop/issues/2826))
 - [ ] windows URL bar icons and URL text are misaligned ([#4814](https://github.com/brave/browser-laptop/issues/4814))
 - [ ] replace mac install window BG image with updated logo version ([#4817](https://github.com/brave/browser-laptop/issues/4817))
 - [ ] Update localization ([#4889](https://github.com/brave/browser-laptop/pull/4889))
 - [ ] border-right on bookmarkFolderList should be moved to div inside organizeView ([#4866](https://github.com/brave/browser-laptop/issues/4866))
 - [ ] "New bookmark folder" and "New bookmark" buttons added to about:bookmarks ([#4888](https://github.com/brave/browser-laptop/pull/4888))
 - [ ] Buttons to add bookmark / bookmark folder in about:bookmarks ([#4684](https://github.com/brave/browser-laptop/issues/4684))
 - [ ] Disable save button when no detail present ([#4875](https://github.com/brave/browser-laptop/pull/4875))
 - [ ] Enable Save button on Autofill modal only when user adds details ([#4855](https://github.com/brave/browser-laptop/issues/4855))
 - [ ] Reduced specificity of select class in css ([#3282](https://github.com/brave/browser-laptop/issues/3282))
 - [ ] Add bookmark folder modal width changes when a long folder name is added ([#4864](https://github.com/brave/browser-laptop/issues/4864))
 - [ ] Home,Refresh buttons moves up when switching between tabs ([#4854](https://github.com/brave/browser-laptop/issues/4854))
 - [ ] Improve UI/UX of bookmark popup design enhancement ([#2894](https://github.com/brave/browser-laptop/issues/2894))
 - [ ] Improve UI/UX of bookmark popup ([#4726](https://github.com/brave/browser-laptop/pull/4726))
 - [ ] Change URL suggestions to consider last access timestamp and access count ([#4809](https://github.com/brave/browser-laptop/pull/4809))
 - [ ] Tabs fine tuning  ([#4829](https://github.com/brave/browser-laptop/pull/4829))
 - [ ] Updated General Preferences ([#4640](https://github.com/brave/browser-laptop/pull/4640))
 - [ ] Clicking on home button loads Error page when no homepage is set settings ([#3008](https://github.com/brave/browser-laptop/issues/3008))
 - [ ] General Settings: "Bookmarks Bar" setting documentation ([#2111](https://github.com/brave/browser-laptop/issues/2111))
 - [ ] General Settings: "My home page is" setting documentation ([#2108](https://github.com/brave/browser-laptop/issues/2108))
 - [ ] Right click context menu should have "Save Page As" ([#4830](https://github.com/brave/browser-laptop/issues/4830))
 - [ ] Add "Save Page As" to right click context menu ([#4831](https://github.com/brave/browser-laptop/pull/4831))
 - [ ] Fully qualified domains entered in full should sort higher than history items with longer URL ([#4861](https://github.com/brave/browser-laptop/issues/4861))
 - [ ] Clicking Bookmarks Toolbar from "Bookmarks" menu does not change state of check mark ([#4810](https://github.com/brave/browser-laptop/issues/4810))
 - [ ] Fix checked status on menu template (impacts Windows only) ([#4834](https://github.com/brave/browser-laptop/pull/4834))
 - [ ] Moving a folder in Bookmarks Manager can lead to the appearance of duplicates ([#4766](https://github.com/brave/browser-laptop/issues/4766))
 - [ ] Bookmarks and siteUtil hardening ([#4797](https://github.com/brave/browser-laptop/pull/4797))
 - [ ] color of div#window.frameless should be lighter? ([#4648](https://github.com/brave/browser-laptop/issues/4648))
 - [ ] Windows style updates ([#4856](https://github.com/brave/browser-laptop/pull/4856))
 - [ ] Fixing magic number bug in downloads bar ([#4837](https://github.com/brave/browser-laptop/pull/4837))
 - [ ] Get rid of magic numbers associated with downloads bar ([#3604](https://github.com/brave/browser-laptop/issues/3604))
 - [ ] Create new preference for controlling telemetry ([#4691](https://github.com/brave/browser-laptop/issues/4691))
 - [ ] Add new "automatically send usage stats" setting under advanced settings ([#4843](https://github.com/brave/browser-laptop/pull/4843))
 - [ ] "Other Bookmarks" folder no longer shows delete in context menu ([#4857](https://github.com/brave/browser-laptop/pull/4857))
 - [ ] "Other Bookmarks" should not show delete on about:bookmarks ([#4836](https://github.com/brave/browser-laptop/issues/4836))
 - [ ] Advanced setting button should be hidden when payments is disabled ([#4790](https://github.com/brave/browser-laptop/issues/4790))
 - [ ] Brave Payments should have a dev mode using testnet Bitcoin ([#4286](https://github.com/brave/browser-laptop/issues/4286))
 - [ ] Ledger server is configurable by ENV variable "LEDGER_SERVER_URL" ([#4297](https://github.com/brave/browser-laptop/pull/4297))

## Ledger
1. [ ] Create a wallet with a value other than $5 selected in the monthly budget dropdown. Click on the 'Add Funds' button and check that Coinbase transactions are blocked.
2. [ ] Remove all `ledger-*.json` files from `~/Library/Application\ Support/Brave/`. Go to the Payments tab in about:preferences, enable payments, click on `create wallet`. Check that the `add funds` button appears after a wallet is created.
3. [ ] Click on `add funds` and verify that adding funds through Coinbase increases the account balance.
4. [ ] Repeat the step above but add funds by scanning the QR code in a mobile bitcoin app instead of through Coinbase.
5. [ ] Visit nytimes.com for a few seconds and make sure it shows up in the Payments table.
6. [ ] Go to https://jsfiddle.net/LnwtLckc/5/ and click the register button. In the Payments tab, click `add funds`. Verify that the `transfer funds` button is visible and that clicking on `transfer funds` opens a jsfiddle URL in a new tab.
7. [ ] Go to https://jsfiddle.net/LnwtLckc/5/ and click `unregister`. Verify that the `transfer funds` button no longer appears in the `add funds` modal.
8. [ ] Check that disabling payments and enabling them again does not lose state.

## Data

1. [ ] Make sure that data from the last version appears in the new version OK.
2. [ ] Test that the previous version's cookies are preserved in the next version.

## About pages

1. [ ] Test that about:adblock loads
2. [ ] Test that about:autofill loads
3. [ ] Test that about:bookmarks loads bookmarks
4. [ ] Test that about:downloads loads downloads
5. [ ] Test that about:extensions loads
6. [ ] Test that about:history loads history
7. [ ] Test that about:passwords loads
8. [ ] Test that about:preferences changing a preference takes effect right away
9. [ ] Test that about:preferences language change takes effect on re-start
10. [ ] Test that about.com without the http protocol is loaded from URL bar

## Bookmarks

1. [ ] Test that creating a bookmark on the bookmarks toolbar works
2. [ ] Test that creating a bookmark folder on the bookmarks toolbar works
3. [ ] Test that moving a bookmark into a folder by drag and drop on the bookmarks folder works
4. [ ] Test that clicking a bookmark in the toolbar loads the bookmark.
5. [ ] Test that clicking a bookmark in a bookmark toolbar folder loads the bookmark.

## Context menus
1. [ ] Make sure context menu items in the URL bar work
2. [ ] Make sure context menu items on content work with no selected text.
3. [ ] Make sure context menu items on content work with selected text.
4. [ ] Make sure context menu items on content work inside an editable control (input, textarea, or contenteditable).

## Find on page

1. [ ] Ensure search box is shown with shortcut
2. [ ] Test successful find
3. [ ] Test forward and backward find navigation
4. [ ] Test failed find shows 0 results
5. [ ] Test match case find

## Geolocation

1. [ ] Check that https://developer.mozilla.org/en-US/docs/Web/API/Geolocation/Using_geolocation works

## Site hacks

1. [ ] Test https://www.twitch.tv/adobe sub-page loads a video and you can play it

## Downloads

1. [ ] Test downloading a file works and that all actions on the download item works.

## Fullscreen

1. [ ] Test that entering full screen window works View -> Toggle Full Screen. And exit back (Not Esc).
2. [ ] Test that entering HTML5 full screen works. And Esc to go back. (youtube.com)

## Tabs and Pinning

1. [ ] Test that tabs are pinnable
2. [ ] Test that tabs are unpinnable
3. [ ] Test that tabs are draggable to same tabset
4. [ ] Test that tabs are draggable to alternate tabset

## Zoom

1. [ ] Test zoom in / out shortcut works
2. [ ] Test hamburger menu zooms.
3. [ ] Test zoom saved when you close the browser and restore on a single site.
4. [ ] Test zoom saved when you navigate within a single origin site.
5. [ ] Test that navigating to a different origin resets the zoom

## Bravery settings

1. [ ] Check that HTTPS Everywhere works by loading http://www.apple.com
2. [ ] Turning HTTPS Everywhere off and shields off both disable the redirect to https://www.apple.com
3. [ ] Check that ad replacement works on http://slashdot.org
4. [ ] Check that toggling to blocking and allow ads works as expected.
5. [ ] Test that clicking through a cert error in https://badssl.com/ works.
6. [ ] Test that Safe Browsing works (http://excellentmovies.net/)
7. [ ] Turning Safe Browsing off and shields off both disable safe browsing for http://excellentmovies.net/.
8. [ ] Visit https://brianbondy.com/ and then turn on script blocking, nothing should load. Allow it from the script blocking UI in the URL bar and it should work.
9. [ ] Test that about:preferences default Bravery settings take effect on pages with no site settings.
10. [ ] Test that turning on fingerprinting protection in about:preferences shows 3 fingerprints blocked at https://jsfiddle.net/bkf50r8v/13/. Test that turning it off in the Bravery menu shows 0 fingerprints blocked.
11. [ ] Test that 3rd party storage results are blank at https://jsfiddle.net/7ke9r14a/9/ when 3rd party cookies are blocked and not blank when 3rd party cookies are unblocked.
12. [ ] Test that audio fingerprint is blocked at https://audiofingerprint.openwpm.com/ when fingerprinting protection is on.

## Content tests

1. [ ] Go to https://brianbondy.com/ and click on the twitter icon on the top right. Test that context menus work in the new twitter tab.
2. [ ] Load twitter and click on a tweet so the popup div shows.   Click to dismiss and repeat with another div. Make sure it shows.
3. [ ] Go to http://www.bennish.net/web-notifications.html and test that clicking on 'Show' pops up a notification asking for permission. Make sure that clicking 'Deny' leads to no notifications being shown.
4. [ ] Go to https://trac.torproject.org/projects/tor/login and make sure that the password can be saved. Make sure the saved password shows up in `about:passwords`. Then reload https://trac.torproject.org/projects/tor/login and make sure the password is autofilled.
5. [ ] Open a github issue and type some misspellings, make sure they are underlined.
6. [ ] Make sure that right clicking on a word with suggestions gives a suggestion and that clicking on the suggestion replaces the text.
7. [ ] Make sure that Command + Click (Control + Click on Windows, Control + Click on Ubuntu) on a link opens a new tab but does NOT switch to it.  Click on it and make sure it is already loaded.
8. [ ] Open an email on http://mail.google.com/ or inbox.google.com and click on a link. Make sure it works.
9. [ ] Test that PDF is loaded at http://www.orimi.com/pdf-test.pdf
10. [ ] Test that https://mixed-script.badssl.com/ shows up as grey not red (no mixed content scripts are run).

## Flash tests
1. [ ] Turn on Flash in about:preferences#security. Test that clicking on 'Install Flash' banner on myspace.com shows a notification to allow Flash and that the banner disappears when 'Allow' is clicked.
2. [ ] Test that flash placeholder appears on http://www.y8.com/games/superfighters

## Autofill tests
1. [ ] Test that autofill works on http://www.roboform.com/filling-test-all-fields

## Session storage

Do not forget to make a backup of your entire `~/Library/Application\ Support/Brave` folder.

1. [ ] Temporarily move away your `~/Library/Application\ Support/Brave/session-store-1` and test that clean session storage works. (`%appdata%\Brave in Windows`, `./config/brave` in Ubuntu)
2. [ ] Test that windows and tabs restore when closed, including active tab.
3. [ ] Move away your entire `~/Library/Application\ Support/Brave` folder (`%appdata%\Brave in Windows`, `./config/brave` in Ubuntu)

## Cookie and Cache

1. [ ] Make a backup of your profile, turn on all clearing in preferences and shut down.  Make sure when you bring the browser back up everything is gone that is specified.
2. [ ] Go to http://samy.pl/evercookie/ and set an evercookie. Check that going to prefs, clearing site data and cache, and going back to the Evercookie site does not remember the old evercookie value.

## Update tests

1. [ ] Test that updating using `BRAVE_UPDATE_VERSION=0.8.3` env variable works correctly.
