### ISSUE TITLE
Further improvement of UrlBar suggestions

### ISSUE THREAD

**Issue by Sh1d0w** [brave/browser-laptop#5067]
This is a follow up issue after great fixes in https://github.com/brave/browser-laptop/issues/3049 . But there is still more work to do unless url bar become as usable as Chrome's.

These are the outstanding issues:
- [ ] Currently Brave puts a lot of weight on recent link's after https://github.com/brave/browser-laptop/issues/3049 . This is great but has the following pitfall:
  
  Say I visit `twilio.com` and `twitter.com`. Now I start visiting `twitter.com` a lot times for several days. After some time I want to visit `twilio.com` and start typing `tw` in the URL bar. The results is that I get only two suggestions and they are both twitter links, since I visited it recently.
  
  <img src="https://s11.postimg.org/grb0wjfpf/Workspace_1_019.png"/>
  
  This is wrong. Chrome's behaviour has the correct solution - it prioritize domain names first, so if I test the following case in Chrome the result will be:
  
  <img src="https://s11.postimg.org/um9bf0a4j/Workspace_1_020.png" />
  
  Which is great because I want to visit websites, I don't care about recent links. Of course as you can see, Chrome also suggest most visited links of those matching websites, but with lower priority than the domain names.
  
  There is  another case where you browse through a news website and read some article, close the browser and later on when you want to visit this website again it will autocomplete to the last article you have read, so you eighter have to type the domain manually or use the autocomplete and delete the article part so you can go to the root domain.
  
  There is a similar issue opened (https://github.com/brave/browser-laptop/issues/4570)
- [x] I get only two results as suggestions which is not enough. The count should be increased at least to 5 or 6. In order that to happen the size of the url bar suggestions has to be reduced by:
  - Putting the title and the link of the entry on one line. Remove the sections separation and put the result type icon before each row, just like Chrome does.
  - Reduce the padding/margin of each history entry so it is compact
  
  There is issue opened about this (https://github.com/brave/browser-laptop/issues/4073)
- [x] The problem with bookmarks and autocomplete as reported in here (https://github.com/brave/browser-laptop/issues/5024)
- [ ] The problem with hidden history entries (which is the root cause of showing not relevant history autocomplete results because "forgetting" some websites I have visited) - (https://github.com/brave/browser-laptop/issues/4224 and https://github.com/brave/browser-laptop/issues/5072)
- [ ] Wrong website title in suggestions (https://github.com/brave/browser-laptop/issues/4792)
- [x] Fix the async online suggestions blocking the other suggestions from showing and the wrong CTRL + L behaviour (Fixed by https://github.com/brave/browser-laptop/pull/5046 I will mark as completed once merged)

cc @bbondy @aekeus

**Comment by aekeus** [comment]
Thanks again for the detailed discussion on this topic. I will need to break this down into multiple issues to properly address each suggestion. I have a working branch that implements a number of the items.

<img width="807" alt="screen shot 2016-10-24 at 11 11 20 am" src="https://cloud.githubusercontent.com/assets/210240/19651470/ec2b4bea-99da-11e6-9b8b-4ec67fb04932.png">

**Comment by bsclifton** [comment]
@Sh1d0w @aekeus One thing I'd highly suggest too (and I haven't looked to see status) is making sure each use-case is captured as a test :smile: 

We need to capture and characterize each use-case so that accidental regressions don't happen.  And perhaps we could also submit a PR with a test case that fails (but should be passing) along with new issue reports?

**Comment by bradleyrichter** [comment]
@aekeus Please don't toss all of the styling improvements in favor of a mirror of chrome. We can land in a great place that works well and retain some of the improvements we have made.

(chrome user comfort is certainly important though)
