### ISSUE TITLE
Manual tests for Ubuntu 0.12.8 Preview3

### ISSUE THREAD

**Issue by alexwykoff** [brave/browser-laptop#5359]
## Installer

1. [ ] Check that installer is close to the size of last release.
2. [ ] Check signature: If OS Run `spctl --assess --verbose /Applications/Brave.app/` and make sure it returns `accepted`.  If Windows right click on the installer exe and go to Properties, go to the Digital Signatures tab and double click on the signature.  Make sure it says "The digital signature is OK" in the popup window.
3. [ ] Check Brave, electron, and libchromiumcontent version in About and make sure it is EXACTLY as expected.

## Per release specialty tests

 - [ ] Imported bookmarks should set creationTime field (not lastAccessedTime) ([#5183](https://github.com/brave/browser-laptop/issues/5183))
 - [ ] Command+F should close the pulldown on the URL bar ([#5340](https://github.com/brave/browser-laptop/issues/5340))
 - [ ] send close command to "Waiting for deposit Alert message" when a confirmed deposit satisfies alert. ([#5300](https://github.com/brave/browser-laptop/issues/5300))
 - [ ] Removed "blank" option (about:blank !== about:newtab) ([#5335](https://github.com/brave/browser-laptop/pull/5335))
 - [ ] Findbar should provide context menu ([#4975](https://github.com/brave/browser-laptop/issues/4975))
 - [ ] Selected bookmark/history items doesn't clear selection when clicked outside the view ([#5223](https://github.com/brave/browser-laptop/issues/5223))
 - [ ] Bug fixes for about:bookmarks ([#5331](https://github.com/brave/browser-laptop/pull/5331))
 - [ ] about:bookmarks multiselect should be reset following drag-and-drop ([#5249](https://github.com/brave/browser-laptop/issues/5249))
 - [ ] Add transition for new-tabbackground ([#5330](https://github.com/brave/browser-laptop/pull/5330))
 - [ ] Right Click doesn't work after logging into LastPass extension ([#5293](https://github.com/brave/browser-laptop/issues/5293))
 - [ ] remove backspace and shift-backspace nav shortcuts ([#5323](https://github.com/brave/browser-laptop/issues/5323))
 - [ ] New Tab Design: Overview with subtasks (about:newtab) ([#3001](https://github.com/brave/browser-laptop/issues/3001))
 - [ ] General Settings: "A new tab shows" setting documentation ([#2106](https://github.com/brave/browser-laptop/issues/2106))
 - [ ] Findbar has style issues (alignment) ([#5317](https://github.com/brave/browser-laptop/issues/5317))
 - [ ] Style updates per Brad (Findbar + fixed shadowing, colors, alignments on mac) ([#5318](https://github.com/brave/browser-laptop/pull/5318))
 - [ ] download list is out of order ([#4484](https://github.com/brave/browser-laptop/issues/4484))
 - [ ] Undefined properties and nested folders handling ([#5298](https://github.com/brave/browser-laptop/pull/5298))
 - [ ] 1Password and LastPass repeated entries in right click context menu ([#5291](https://github.com/brave/browser-laptop/issues/5291))
 - [ ] URL bar drops last 2 characters when typing fast (not related to auto suggestions or history) ([#5189](https://github.com/brave/browser-laptop/issues/5189))
 - [ ] Limit 24 hour payment notification to once per reconcile period ([#5296](https://github.com/brave/browser-laptop/pull/5296))
 - [ ] Aggressive notification bug ([#4481](https://github.com/brave/browser-laptop/issues/4481))
 - [ ] preferences page tabs broken ([#5295](https://github.com/brave/browser-laptop/issues/5295))
 - [ ] Brave crashes when trying to visit www.sweclockers.com ([#5273](https://github.com/brave/browser-laptop/issues/5273))
 - [ ] Bookmark added before webpage loaded completely doesn't show bookmark icon when visited ([#5148](https://github.com/brave/browser-laptop/issues/5148))
 - [ ] Add Pocket Integration enhancement ([#516](https://github.com/brave/browser-laptop/issues/516))
 - [ ] Manage Autofill should be disabled when Autofill option is disabled design ([#5146](https://github.com/brave/browser-laptop/issues/5146))
 - [ ] Disable autofill management button when autofill is disabled ([#5288](https://github.com/brave/browser-laptop/pull/5288))
 - [ ] Insert virtual history items for sites like www.google.ca in auto-suggestion url ([#5278](https://github.com/brave/browser-laptop/pull/5278))
 - [ ] In some cases favicon is not displayed in history pulldown ([#2747](https://github.com/brave/browser-laptop/issues/2747))
 - [ ] Manually added bookmark pages doesn't create the favicons after visiting the site ([#4860](https://github.com/brave/browser-laptop/issues/4860))
 - [ ] Favicon is now updated in session after visiting site ([#5285](https://github.com/brave/browser-laptop/pull/5285))
 - [ ] Add regional adblock filter lists for india ([#4996](https://github.com/brave/browser-laptop/issues/4996))
 - [ ] Showing findbar and typing fast sometimes would append text instead of replacing selection ([#5289](https://github.com/brave/browser-laptop/issues/5289))
 - [ ] Navigating to new page should reset find state, but keep last text ([#5286](https://github.com/brave/browser-laptop/issues/5286))
 - [ ] regression: date format of next contribution not localized ([#4787](https://github.com/brave/browser-laptop/issues/4787))
 - [ ] Set preferences moment locale to navigator.language ([#5283](https://github.com/brave/browser-laptop/pull/5283))
 - [ ] TripAdvisor crashes Brave confirmed reduced ([#5264](https://github.com/brave/browser-laptop/issues/5264))
 - [ ] Add search autocomplete for start page search engine ([#5281](https://github.com/brave/browser-laptop/issues/5281))
 - [ ] Visiting http://expressjs.com/ causes Brave to crash ([#5270](https://github.com/brave/browser-laptop/issues/5270))
 - [ ] Removing clear cache and clear site data options from the history menu ([#5251](https://github.com/brave/browser-laptop/pull/5251))
 - [ ] Replace Clear data menu items in History menu with new, single item ([#3093](https://github.com/brave/browser-laptop/issues/3093))
 - [ ] Fix clearing the findbar ([#5248](https://github.com/brave/browser-laptop/pull/5248))
 - [ ] Number of matches still shows after clearing findbar ([#5247](https://github.com/brave/browser-laptop/issues/5247))
 - [ ] add placeholder for about style ([#5242](https://github.com/brave/browser-laptop/pull/5242))
 - [ ] Create about:styles page to display style guide ([#5195](https://github.com/brave/browser-laptop/issues/5195))
 - [ ] Pocket: Support ContentMenu Methods ([#4689](https://github.com/brave/browser-laptop/issues/4689))
 - [ ] Add chrome.contextMenus.create and chrome.contextMenus.removeAll ([#5172](https://github.com/brave/browser-laptop/pull/5172))
 - [ ] browserActionBackgroundImage per-tab support ([#5262](https://github.com/brave/browser-laptop/pull/5262))
 - [ ] Pocket: chrome.browserAction.setIcon fails ([#4702](https://github.com/brave/browser-laptop/issues/4702))
 - [ ] Bookmark titles getting renamed after import ([#5060](https://github.com/brave/browser-laptop/issues/5060))
 - [ ] Add custom title for imported bookmark ([#5263](https://github.com/brave/browser-laptop/pull/5263))
 - [ ] Pocket: Repair chrome.runtime.openOptionsPage ([#4700](https://github.com/brave/browser-laptop/issues/4700))
 - [ ] Add Widevine support for Amazon Prime Video ([#5233](https://github.com/brave/browser-laptop/issues/5233))
 - [ ] Move PDFJS into extensions section in preferences ([#5245](https://github.com/brave/browser-laptop/issues/5245))
 - [ ] Start serving pocket from our component updater ([#5226](https://github.com/brave/browser-laptop/issues/5226))
 - [ ] Add pocket as a toggle switch in preferences ([#5227](https://github.com/brave/browser-laptop/issues/5227))
 - [ ] Add button to view about:extensions from preferences ([#5244](https://github.com/brave/browser-laptop/issues/5244))
 - [ ] only set frame title when navigation is not renderer initiated ([#5211](https://github.com/brave/browser-laptop/pull/5211))
 - [ ] Fix regression caused by removing drag from URL bar element ([#5240](https://github.com/brave/browser-laptop/pull/5240))
 - [ ] regression: drag area above URL bar was reduced to ([#5225](https://github.com/brave/browser-laptop/issues/5225))
 - [ ] Upgrade to brave/electron 1.4.23 ([#5243](https://github.com/brave/browser-laptop/issues/5243))
 - [ ] Navigating back doesn't revert URL to the previous site ([#5221](https://github.com/brave/browser-laptop/issues/5221))
 - [ ] Properly handle a null row / zero rows ([#5237](https://github.com/brave/browser-laptop/pull/5237))
 - [ ] Error loading about:preferences#payments ([#5236](https://github.com/brave/browser-laptop/issues/5236))
 - [ ] Check adblock / TP lists more frequently than daily ([#5228](https://github.com/brave/browser-laptop/issues/5228))
 - [ ] Update public suffix list  ([#5138](https://github.com/brave/browser-laptop/pull/5138))
 - [ ] js/lib/psl.js needs update ([#4136](https://github.com/brave/browser-laptop/issues/4136))
 - [ ] don't show blank urlbar for about:blank ([#5209](https://github.com/brave/browser-laptop/issues/5209))
 - [ ] show about:blank in urlbar ([#5214](https://github.com/brave/browser-laptop/pull/5214))
 - [ ] Payment was processed but account balance was not refreshed ([#4432](https://github.com/brave/browser-laptop/issues/4432))
 - [ ] Monthly budget dropped from $10 to $5 without user action ([#4703](https://github.com/brave/browser-laptop/issues/4703))
 - [ ] Brave crashes when Copy recovery key is clicked during wallet creation ([#4980](https://github.com/brave/browser-laptop/issues/4980))
 - [ ] Brave crashes when Copy recovery key is clicked during wallet creation ([#5174](https://github.com/brave/browser-laptop/pull/5174))

## Ledger
1. [ ] Create a wallet with a value other than $5 selected in the monthly budget dropdown. Click on the 'Add Funds' button and check that Coinbase transactions are blocked.
2. [ ] Remove all `ledger-*.json` files from `~/Library/Application\ Support/Brave/`. Go to the Payments tab in about:preferences, enable payments, click on `create wallet`. Check that the `add funds` button appears after a wallet is created.
3. [ ] Click on `add funds` and verify that adding funds through Coinbase increases the account balance.
4. [ ] Repeat the step above but add funds by scanning the QR code in a mobile bitcoin app instead of through Coinbase.
5. [ ] Visit nytimes.com for a few seconds and make sure it shows up in the Payments table.
6. [ ] Go to https://jsfiddle.net/LnwtLckc/5/ and click the register button. In the Payments tab, click `add funds`. Verify that the `transfer funds` button is visible and that clicking on `transfer funds` opens a jsfiddle URL in a new tab.
7. [ ] Go to https://jsfiddle.net/LnwtLckc/5/ and click `unregister`. Verify that the `transfer funds` button no longer appears in the `add funds` modal.
8. [ ] Check that disabling payments and enabling them again does not lose state.

## Data

1. [ ] Make sure that data from the last version appears in the new version OK.
2. [ ] Test that the previous version's cookies are preserved in the next version.

## About pages

1. [ ] Test that about:adblock loads
2. [ ] Test that about:autofill loads
3. [ ] Test that about:bookmarks loads bookmarks
4. [ ] Test that about:downloads loads downloads
5. [ ] Test that about:extensions loads
6. [ ] Test that about:history loads history
7. [ ] Test that about:passwords loads
8. [ ] Test that about:preferences changing a preference takes effect right away
9. [ ] Test that about:preferences language change takes effect on re-start
10. [ ] Test that about.com without the http protocol is loaded from URL bar

## Bookmarks

1. [ ] Test that creating a bookmark on the bookmarks toolbar works
2. [ ] Test that creating a bookmark folder on the bookmarks toolbar works
3. [ ] Test that moving a bookmark into a folder by drag and drop on the bookmarks folder works
4. [ ] Test that clicking a bookmark in the toolbar loads the bookmark.
5. [ ] Test that clicking a bookmark in a bookmark toolbar folder loads the bookmark.

## Context menus
1. [ ] Make sure context menu items in the URL bar work
2. [ ] Make sure context menu items on content work with no selected text.
3. [ ] Make sure context menu items on content work with selected text.
4. [ ] Make sure context menu items on content work inside an editable control (input, textarea, or contenteditable).

## Find on page

1. [ ] Ensure search box is shown with shortcut
2. [ ] Test successful find
3. [ ] Test forward and backward find navigation
4. [ ] Test failed find shows 0 results
5. [ ] Test match case find

## Geolocation

1. [ ] Check that https://developer.mozilla.org/en-US/docs/Web/API/Geolocation/Using_geolocation works

## Site hacks

1. [ ] Test https://www.twitch.tv/adobe sub-page loads a video and you can play it

## Downloads

1. [ ] Test downloading a file works and that all actions on the download item works.

## Fullscreen

1. [ ] Test that entering full screen window works View -> Toggle Full Screen. And exit back (Not Esc).
2. [ ] Test that entering HTML5 full screen works. And Esc to go back. (youtube.com)

## Tabs and Pinning

1. [ ] Test that tabs are pinnable
2. [ ] Test that tabs are unpinnable
3. [ ] Test that tabs are draggable to same tabset
4. [ ] Test that tabs are draggable to alternate tabset

## Zoom

1. [ ] Test zoom in / out shortcut works
2. [ ] Test hamburger menu zooms.
3. [ ] Test zoom saved when you close the browser and restore on a single site.
4. [ ] Test zoom saved when you navigate within a single origin site.
5. [ ] Test that navigating to a different origin resets the zoom

## Bravery settings

1. [ ] Check that HTTPS Everywhere works by loading http://www.apple.com
2. [ ] Turning HTTPS Everywhere off and shields off both disable the redirect to https://www.apple.com
3. [ ] Check that ad replacement works on http://slashdot.org
4. [ ] Check that toggling to blocking and allow ads works as expected.
5. [ ] Test that clicking through a cert error in https://badssl.com/ works.
6. [ ] Test that Safe Browsing works (http://downloadme.org/)
7. [ ] Turning Safe Browsing off and shields off both disable safe browsing for http://downloadme.org/.
8. [ ] Visit https://brianbondy.com/ and then turn on script blocking, nothing should load. Allow it from the script blocking UI in the URL bar and it should work.
9. [ ] Test that about:preferences default Bravery settings take effect on pages with no site settings.
10. [ ] Test that turning on fingerprinting protection in about:preferences shows 3 fingerprints blocked at https://jsfiddle.net/bkf50r8v/13/. Test that turning it off in the Bravery menu shows 0 fingerprints blocked.
11. [ ] Test that 3rd party storage results are blank at https://jsfiddle.net/7ke9r14a/9/ when 3rd party cookies are blocked and not blank when 3rd party cookies are unblocked.
12. [ ] Test that audio fingerprint is blocked at https://audiofingerprint.openwpm.com/ when fingerprinting protection is on.

## Content tests

1. [ ] Go to https://brianbondy.com/ and click on the twitter icon on the top right. Test that context menus work in the new twitter tab.
2. [ ] Load twitter and click on a tweet so the popup div shows.   Click to dismiss and repeat with another div. Make sure it shows.
3. [ ] Go to http://www.bennish.net/web-notifications.html and test that clicking on 'Show' pops up a notification asking for permission. Make sure that clicking 'Deny' leads to no notifications being shown.
4. [ ] Go to https://trac.torproject.org/projects/tor/login and make sure that the password can be saved. Make sure the saved password shows up in `about:passwords`. Then reload https://trac.torproject.org/projects/tor/login and make sure the password is autofilled.
5. [ ] Open a github issue and type some misspellings, make sure they are underlined.
6. [ ] Make sure that right clicking on a word with suggestions gives a suggestion and that clicking on the suggestion replaces the text.
7. [ ] Make sure that Command + Click (Control + Click on Windows, Control + Click on Ubuntu) on a link opens a new tab but does NOT switch to it.  Click on it and make sure it is already loaded.
8. [ ] Open an email on http://mail.google.com/ or inbox.google.com and click on a link. Make sure it works.
9. [ ] Test that PDF is loaded at http://www.orimi.com/pdf-test.pdf
10. [ ] Test that https://mixed-script.badssl.com/ shows up as grey not red (no mixed content scripts are run).

## Flash tests
1. [ ] Turn on Flash in about:preferences#security. Test that clicking on 'Install Flash' banner on myspace.com shows a notification to allow Flash and that the banner disappears when 'Allow' is clicked.
2. [ ] Test that flash placeholder appears on http://www.y8.com/games/superfighters

## Autofill tests
1. [ ] Test that autofill works on http://www.roboform.com/filling-test-all-fields

## Session storage

Do not forget to make a backup of your entire `~/Library/Application\ Support/Brave` folder.

1. [ ] Temporarily move away your `~/Library/Application\ Support/Brave/session-store-1` and test that clean session storage works. (`%appdata%\Brave in Windows`, `./config/brave` in Ubuntu)
2. [ ] Test that windows and tabs restore when closed, including active tab.
3. [ ] Move away your entire `~/Library/Application\ Support/Brave` folder (`%appdata%\Brave in Windows`, `./config/brave` in Ubuntu)

## Cookie and Cache

1. [ ] Make a backup of your profile, turn on all clearing in preferences and shut down.  Make sure when you bring the browser back up everything is gone that is specified.
2. [ ] Go to http://samy.pl/evercookie/ and set an evercookie. Check that going to prefs, clearing site data and cache, and going back to the Evercookie site does not remember the old evercookie value.

## Update tests

1. [ ] Test that updating using `BRAVE_UPDATE_VERSION=0.8.3` env variable works correctly.
