### ISSUE TITLE
Tracking: Disabled tests

### ISSUE THREAD

**Issue by bbondy** [brave/browser-laptop#5389]
# Overview:
This issue tracks the disabled tests. It should always appear in the current milestone so that it's a constant reminder for us to work at re-enabling them. This will help us get green so we can better determine when to merge and when not to merge things.

# Other info:
- If a test is failing, the code that introduced it should be backed out if the test can’t be fixed right away.
- If a test is failing intermittently, it should be added to this list.  If it is newly intermittent, the task that introduced it should be backed out if it can be determined. 
- Everyone should try to get all of these tests below down to 0.
- When a test is fixed check it off and move it to the fixed intermittents section.

# Disabled tests:
 
- [ ] findBar findbar input remembered but no active ordinals after navigation until RETURN key:
  test/about/componentUpdaterTest.js
  test/components/findbarTest.js
  more info: Disabled for https://github.com/brave/browser-laptop/issues/6147
  AssertionError: '0 matches' == '1 of 1'
  expected - actual
  -0 matches
  +1 of 1

- [ ] Google Widevine can be enabled and installed
  test/about/componentUpdaterTest.js
  more info: This is only disabled on Linux and it's because the feature is not available there yet.

- [ ] should attempt a reload when reload is clicked
  test/components/errorPageTest.js
  more info: need a better way to test this
- [x] Limit effect of running insecure content in private frame
  test/components/navigationBarTest.js
  more info: Unknown.
  Owner: @darkdh
- [ ] Parses theme-color meta tag when one is present
  test/components/navigationBarTest.js
  more info: Unknown
  Owner: @bbondy 
- [ ] Obtains theme color from the background
  test/components/navigationBarTest.js
  more info: Unknown
  Owner: @bbondy
- [ ] Obtains theme color from a top header and not background
  test/components/navigationBarTest.js
  more info: Unknown
  Owner: @bbondy
- [ ] focuses the opener
  test/components/windowTest.js
  more info: Unknown
- [ ] blurs the opener
  test/components/windowTest.js
  more info: Unknown
- [ ] setting observer unit test
  test/unit/app/browser/settingObserverTest.js
  more info: I think this can just be removed along with the code since I don't think it's used.  Needs to grep for the module though to be sure.
- [ ] passes NIST Test Case 13
  test/unit/lib/cryptoUtilTest.js
  more info: fails with Error: Unsupported state or unable to authenticate data
- [x] homepage displays punycode
  test/about/preferencesTest.js
  Since: Nov 4. 2016
  more info: Seems to consistently fail on Travis
  Owner: @diracdeltas 
- [ ] does not show faked page title
  test/components/navigationBarTest.js
  Since: Nov 4. 2016
  more info: Seems to consistently fail on Travis
  Owner: @diracdeltas 
- [ ] Closing pinned tabs
  test/components/pinnedTabTest.js
  Since: Nov 24 2016
  more info: Fails intermittently
  Owner: @bbondy
- [ ] change tabs
  test/components/navigationBarTest.js
  Since: January 5, 2017
  Owner: @bbondy

- [x] Credit card auto fill
   test/contents/autofillTest.js
   Since: Mar 30, 2017
   more info: This was disabled because credit card works only when connection is https and local host is only http
   Owner: @darkdh
   fixed in #9375
- [ ] shows a context menu when long pressed (click and hold)
  test/tab-components/tabTest.js
  Since: April 20, 2017
  more info: Does not work with a native context menu.
- [ ] shows a context menu when right clicked
  test/tab-components/tabTest.js
  Since: April 20, 2017
  more info: Does not work with a native context menu.
- [x] notificationBar passwords
  test/bravery-components/notificationBarTest.js
  Since: May 16, 2017
  more info: chromium password manager requires https to prompt users to save password or autofill for them
   Owner: @darkdh
   fixed in #9375 
- [ ] advanced payment panel tests
  test/about/ledgerPanelAdvancedPanelTest.js
  Since: Jul 27, 2017
  more info: can be re-enabled when #9677 is fixed
- [ ] Ledger table 2 publishers check pinned sites amount, when you have 0 eligible unpinned sites
  test/about/ledgerTableTest.js
  Since: Jul 27, 2017
  more info: can be re-enabled when #9641 is fixed
# Fixed intermittents:

**Comment by alexwykoff** [comment]
we have this tracked in source control and in chat

**Comment by luixxiul** [comment]
Is it surely ok to close this?
