### ISSUE TITLE
Automation Tracking Issue

### ISSUE THREAD

**Issue by alexwykoff** [brave/browser-laptop#5541]
With current master  51 tests are failing:

- [ ] 1. component updater Google Widevine is disabled by default Google Widevine can be enabled and installed:
- [ ] 2. about:newtab when displaying stats shows # trackers blocked:
- [ ] 3. about:newtab when displaying stats shows # ads blocked:
- [ ] 4. sessionStore state is preserved "before all" hook: _callee:
- [ ] 5. sessionStore firstRunTimestamp sets it once:
- [ ] 6. Autofill address "before all" hook: _callee:
- [ ] 7. Autofill credit card "before all" hook: _callee7:
- [ ] 8. Autofill clear autofill data "before all" hook: _callee13:
- [ ] 9. bookmark tests menu behavior rebuilds the menu when a folder is added:
- [ ] 10. bookmark tests menu behavior rebuilds the menu when a bookmark is added:
- [ ] 11. bookmark tests menu behavior rebuilds the menu when add a list of items:
- [ ] 12. bookmarksToolbar when clicking a bookmark folder shows a context menu:
- [ ] 13. bookmarksToolbar when clicking a bookmark folder automatically opens context menu if you move mouse over a different folder:
- [ ] 14. bookmarksToolbar when clicking a bookmark folder hides context menu when mousing over regular bookmark:
- [ ] 15. Bravery Panel Stats detects blocked elements in private tab:
- [ ] 16. Bravery Panel Stats detects blocked elements:
- [ ] 17. Bravery Panel Stats downloads and detects regional adblock resources in private tab:
- [ ] 18. Bravery Panel Stats downloads and detects regional adblock resources:
- [ ] 19. Bravery Panel Stats detects adblock resources in private tab:
- [ ] 20. Bravery Panel Stats detects adblock resources:
- [ ] 21. Bravery Panel Stats blocks custom adblock resources in private tab:
- [ ] 22. Bravery Panel Stats blocks custom adblock resources:
- [ ] 23. Bravery Panel Stats detects https upgrades in private tab:
- [ ] 24. Bravery Panel Stats detects https upgrades:
- [ ] 25. Bravery Panel Stats blocks scripts (regular and private):
- [ ] 26. Clear Browsing Panel with history "before each" hook: _callee for "shows clearing options":
- [ ] 27. Clear Browsing Panel with closedFrames "before each" hook: _callee4 for "clears closedFrames":
- [ ] 28. Clear Browsing Panel with site settings "before each" hook: _callee6 for "clears site settings and permissions":
- [ ] 29. findbar "before all" hook: _callee:
- [ ] 30. clone tab index "before all" hook: _callee17:
- [ ] 31. view source open from pinned tab:
- [ ] 32. resource loading loads a PDF:
- [ ] 33. Payments Panel can setup payments payments can be enabled:
- [ ] 34. Payments Panel can setup payments payments can be disabled:
- [ ] 35. synopsis can disable site:
- [ ] 36. navigationBar lockIcon Limit effect of running insecure content in frame:
- [ ] 37. navigationBar lockIcon Limit effect of running insecure content in private frame:
- [ ] 38. navigationBar themeColor Uses the default tab color when one is not specified:
- [ ] 39. permissions state applies old saved permissions:
- [ ] 40. pinnedTabs Pins an existing frame "before all" hook: _callee:
- [ ] 41) pinnedTabs Pinning with partitions pinning the same site again with a different session is allowed:
- [ ] 42. pinnedTabs Pinned tab navigation "before all" hook: _callee11:
- [ ] 43. pinnedTabs Closing pinned tabs "before all" hook: _callee14:
- [ ] 44. urlbarSuggestions "before each" hook: _callee for "show suggestion when single letter is typed in":
- [ ] 45. application window application launch opens a window and loads the UI:
- [ ] 46. application window appActions.newWindow after resize has the width and height of the last window resize:
- [ ] 47. application window windw.open with click with features sets the width and height:
- [ ] 48. application window windw.open with click with features sets the window position:
- [ ] 49. application window windw.open with click with width and height below min has a min width of 480 and height of 300:
- [ ] 50. application window open and close windows with scripts keeps the first window and opens a new window:
- [ ] 51. settings constants All settings have default values:

**Comment by alexwykoff** [comment]
Specific Error messages: 

1.     WaitUntilTimeoutError: Promise was rejected with the following reason: Error: unknown error: Cannot read property 'state' of undefined
      at execute(<Function>) - brave.js:283:19

2.      WaitUntilTimeoutError: Promise was rejected with the following reason: Error: unknown error: Cannot read property 'state' of undefined
      at execute(<Function>) - brave.js:283:19

3.     WaitUntilTimeoutError: Promise was rejected with the following reason: Error: unknown error: Cannot read property 'state' of undefined
      at execute(<Function>) - brave.js:283:19

4.     Error: Promise was rejected with the following reason: Error: unknown error: Cannot read property 'state' of undefined

5.      Error: Promise was rejected with the following reason: Error: unknown error: Cannot read property 'state' of undefined

6.     WaitUntilTimeoutError: Promise was rejected with the following reason: Error: unknown error: Cannot read property 'state' of undefined
      at execute(<Function>) - brave.js:283:19

7.     WaitUntilTimeoutError: Promise was rejected with the following reason: Error: unknown error: Cannot read property 'state' of undefined
      at execute(<Function>) - brave.js:283:19

8.     WaitUntilTimeoutError: Promise was rejected with the following reason: Error: unknown error: Cannot read property 'state' of undefined
      at execute(<Function>) - brave.js:283:19

9.     Error: Promise was rejected with the following reason: Error: unknown error: Cannot read property 'state' of undefined

10.     Error: Promise was rejected with the following reason: Error: unknown error: Cannot read property 'state' of undefined

11.     Error: Promise was rejected with the following reason: Error: unknown error: Cannot read property 'state' of undefined

12.     WaitUntilTimeoutError: Promise was rejected with the following reason: Error: unknown error: Cannot read property 'state' of undefined
      at execute(<Function>) - brave.js:283:19

13.     WaitUntilTimeoutError: Promise was rejected with the following reason: Error: unknown error: Cannot read property 'state' of undefined
      at execute(<Function>) - brave.js:283:19

14.     WaitUntilTimeoutError: Promise was rejected with the following reason: Error: unknown error: Cannot read property 'state' of undefined
      at execute(<Function>) - brave.js:283:19

15.     WaitUntilTimeoutError: Promise was rejected with the following reason: Error: unknown error: Cannot read property 'state' of undefined
      at execute(<Function>) - brave.js:283:19

16.     WaitUntilTimeoutError: Promise was rejected with the following reason: Error: unknown error: Cannot read property 'state' of undefined
      at execute(<Function>) - brave.js:283:19

17.     WaitUntilTimeoutError: Promise was rejected with the following reason: Error: unknown error: Cannot read property 'state' of undefined
      at execute(<Function>) - brave.js:283:19

18.     WaitUntilTimeoutError: Promise was rejected with the following reason: Error: unknown error: Cannot read property 'state' of undefined
      at execute(<Function>) - brave.js:283:19

19.     WaitUntilTimeoutError: Promise was rejected with the following reason: Error: unknown error: Cannot read property 'state' of undefined
      at execute(<Function>) - brave.js:283:19

20.     WaitUntilTimeoutError: Promise was rejected with the following reason: Error: unknown error: Cannot read property 'state' of undefined
      at execute(<Function>) - brave.js:283:19

21.     WaitUntilTimeoutError: Promise was rejected with the following reason: Error: unknown error: Cannot read property 'state' of undefined
      at execute(<Function>) - brave.js:283:19

22.     WaitUntilTimeoutError: Promise was rejected with the following reason: Error: unknown error: Cannot read property 'state' of undefined
      at execute(<Function>) - brave.js:283:19

23.     WaitUntilTimeoutError: Promise was rejected with the following reason: Error: unknown error: Cannot read property 'state' of undefined
      at execute(<Function>) - brave.js:283:19

24.     WaitUntilTimeoutError: Promise was rejected with the following reason: Error: unknown error: Cannot read property 'state' of undefined
      at execute(<Function>) - brave.js:283:19

25.     WaitUntilTimeoutError: element (#navigator .noScript) still not visible after 5000ms
      at isVisible("#navigator .noScript") - waitForVisible.js:37:22

26.     Error: Promise was rejected with the following reason: Error: unknown error: Cannot read property 'state' of undefined

27.     Error: Promise was rejected with the following reason: Error: unknown error: Cannot read property 'state' of undefined

28.     Error: Promise was rejected with the following reason: Error: unknown error: Cannot read property 'state' of undefined

29.     Error: Promise was rejected with the following reason: timeout

30.     Error: Promise was rejected with the following reason: timeout

31.     RuntimeError: unknown error: Cannot read property 'setPinned' of undefined
      at execute(<Function>, "http://localhost:15496/find_in_page.html", true, [object Object]) - brave.js:318:19

32.     WaitUntilTimeoutError: Promise was rejected with the following reason: Error: unknown error: Cannot read property 'state' of undefined
      at execute(<Function>) - brave.js:283:19

33.     Error: Promise was rejected with the following reason: Error: unknown error: Cannot read property 'state' of undefined

34.     WaitUntilTimeoutError: Promise was rejected with the following reason: Error: unknown error: Cannot read property 'state' of undefined
      at execute(<Function>) - brave.js:283:19

35.     Error: Promise was rejected with the following reason: Error: unknown error: Cannot read property 'state' of undefined

36.     WaitUntilTimeoutError: Promise was rejected with the following reason: Error: unknown error: Cannot read property 'state' of undefined
      at execute(<Function>) - brave.js:289:19

37.     WaitUntilTimeoutError: Promise was rejected with the following reason: Error: unknown error: Cannot read property 'state' of undefined
      at execute(<Function>) - brave.js:289:19

38.      AssertionError: 'rgba(0,0,0,0)linear-gradient(white,rgb(243,243,243))repeatscroll0%0%/autopadding-boxborder-box' == 'rgba(0,0,0,0)linear-gradient(rgb(255,255,255),rgb(243,243,243))repeatscroll0%0%/autopadding-boxborder-box'
      + expected - actual
      -rgba(0,0,0,0)linear-gradient(white,rgb(243,243,243))repeatscroll0%0%/autopadding-boxborder-box
      +rgba(0,0,0,0)linear-gradient(rgb(255,255,255),rgb(243,243,243))repeatscroll0%0%/autopadding-boxborder-box
      at Context._callee32$ (test/components/navigationBarTest.js:624:14)
      at tryCatch (node_modules/regenerator-runtime/runtime.js:63:40)
      at GeneratorFunctionPrototype.invoke [as _invoke] (node_modules/regenerator-runtime/runtime.js:337:22)
      at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (node_modules/regenerator-runtime/runtime.js:96:21)
      at Object.onFulfilled (node_modules/co-mocha/node_modules/co/index.js:65:19)
      at Object.exec (node_modules/webdriverio/build/lib/helpers/safeExecute.js:28:24)
      at Object.resolve (node_modules/webdriverio/build/lib/webdriverio.js:189:29)
      at node_modules/webdriverio/build/lib/webdriverio.js:487:32
      at _fulfilled (node_modules/q/q.js:834:54)
      at self.promiseDispatch.done (node_modules/q/q.js:863:30)
      at Promise.promise.promiseDispatch (node_modules/q/q.js:796:13)
      at node_modules/q/q.js:604:44
      at runSingle (node_modules/q/q.js:137:13)
      at flush (node_modules/q/q.js:125:13)
      at _combinedTickCallback (internal/process/next_tick.js:67:7)
      at process._tickCallback (internal/process/next_tick.js:98:9)

39.     WaitUntilTimeoutError: element (#titleBar) still not existing after 5000ms
      at isExisting("#titleBar") - waitForExist.js:37:22

40.     RuntimeError: unknown error: Cannot read property 'setPinned' of undefined
      at execute(<Function>, "http://localhost:25360/page1.html", true, [object Object]) - brave.js:318:19

41.     RuntimeError: unknown error: Cannot read property 'setPinned' of undefined
      at execute(<Function>, "http://localhost:9889/page1.html", true, [object Object]) - brave.js:318:19

42.     RuntimeError: unknown error: Cannot read property 'setPinned' of undefined
      at execute(<Function>, "http://localhost:28273/page1.html", true, [object Object]) - brave.js:318:19

43.     RuntimeError: unknown error: Cannot read property 'setPinned' of undefined
      at execute(<Function>, "http://localhost:53052/page1.html", true, [object Object]) - brave.js:318:19

44.     Error: Promise was rejected with the following reason: Error: unknown error: Cannot read property 'state' of undefined

45.     TypeError: Cannot read property 'isMinimized' of undefined
      at Context._callee$ (test/components/windowTest.js:19:13)
      at tryCatch (node_modules/regenerator-runtime/runtime.js:63:40)
      at GeneratorFunctionPrototype.invoke [as _invoke] (node_modules/regenerator-runtime/runtime.js:337:22)
      at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (node_modules/regenerator-runtime/runtime.js:96:21)
      at Object.onFulfilled (node_modules/co-mocha/node_modules/co/index.js:65:19)
      at Object.exec (node_modules/webdriverio/build/lib/helpers/safeExecute.js:28:24)
      at Object.resolve (node_modules/webdriverio/build/lib/webdriverio.js:189:29)
      at node_modules/webdriverio/build/lib/webdriverio.js:487:32
      at _fulfilled (node_modules/q/q.js:834:54)
      at self.promiseDispatch.done (node_modules/q/q.js:863:30)
      at Promise.promise.promiseDispatch (node_modules/q/q.js:796:13)
      at node_modules/q/q.js:604:44
      at runSingle (node_modules/q/q.js:137:13)
      at flush (node_modules/q/q.js:125:13)
      at _combinedTickCallback (internal/process/next_tick.js:67:7)
      at process._tickCallback (internal/process/next_tick.js:98:9)

46.      undefined: expected 1440 to deeply equal 600
      + expected - actual

      -1440
      +600

      at execute(<Function>, "getBounds", , "require") - api.js:291:19

47.     TypeError: Cannot read property 'getBounds' of undefined
      at Context._callee18$ (test/components/windowTest.js:224:15)
      at tryCatch (node_modules/regenerator-runtime/runtime.js:63:40)
      at GeneratorFunctionPrototype.invoke [as _invoke] (node_modules/regenerator-runtime/runtime.js:337:22)
      at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (node_modules/regenerator-runtime/runtime.js:96:21)
      at onFulfilled (node_modules/co-mocha/node_modules/co/index.js:65:19)
      at node_modules/co-mocha/node_modules/co/index.js:54:5
      at Context.co (node_modules/co-mocha/node_modules/co/index.js:50:10)
      at Context.createPromise (node_modules/co-mocha/node_modules/co/index.js:30:15)
      at Test.Runnable.run (node_modules/co-mocha/lib/co-mocha.js:43:16)
      at Hook.Runnable.run (node_modules/co-mocha/lib/co-mocha.js:43:16)

48.     TypeError: Cannot read property 'getBounds' of undefined
      at Context._callee19$ (test/components/windowTest.js:233:15)
      at tryCatch (node_modules/regenerator-runtime/runtime.js:63:40)
      at GeneratorFunctionPrototype.invoke [as _invoke] (node_modules/regenerator-runtime/runtime.js:337:22)
      at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (node_modules/regenerator-runtime/runtime.js:96:21)
      at onFulfilled (node_modules/co-mocha/node_modules/co/index.js:65:19)
      at node_modules/co-mocha/node_modules/co/index.js:54:5
      at Context.co (node_modules/co-mocha/node_modules/co/index.js:50:10)
      at Context.createPromise (node_modules/co-mocha/node_modules/co/index.js:30:15)
      at Test.Runnable.run (node_modules/co-mocha/lib/co-mocha.js:43:16)
      at Hook.Runnable.run (node_modules/co-mocha/lib/co-mocha.js:43:16)

49.     TypeError: Cannot read property 'getBounds' of undefined
      at Context._callee21$ (test/components/windowTest.js:265:15)
      at tryCatch (node_modules/regenerator-runtime/runtime.js:63:40)
      at GeneratorFunctionPrototype.invoke [as _invoke] (node_modules/regenerator-runtime/runtime.js:337:22)
      at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (node_modules/regenerator-runtime/runtime.js:96:21)
      at onFulfilled (node_modules/co-mocha/node_modules/co/index.js:65:19)
      at node_modules/co-mocha/node_modules/co/index.js:54:5
      at Context.co (node_modules/co-mocha/node_modules/co/index.js:50:10)
      at Context.createPromise (node_modules/co-mocha/node_modules/co/index.js:30:15)
      at Test.Runnable.run (node_modules/co-mocha/lib/co-mocha.js:43:16)
      at Hook.Runnable.run (node_modules/co-mocha/lib/co-mocha.js:43:16)

50.      AssertionError: expected 1 to deeply equal 2
      + expected - actual

      -1
      +2

      at assertEqual (node_modules/chai/lib/chai/core/assertions.js:485:19)
      at ctx.(anonymous function) (node_modules/chai/lib/chai/utils/addMethod.js:41:25)
      at Object.<anonymous> (node_modules/chai-as-promised/lib/chai-as-promised.js:308:26)
      at Object.exec (node_modules/webdriverio/build/lib/helpers/safeExecute.js:28:24)
      at Object.resolve (node_modules/webdriverio/build/lib/webdriverio.js:189:29)
      at node_modules/webdriverio/build/lib/webdriverio.js:487:32
      at _fulfilled (node_modules/q/q.js:834:54)
      at self.promiseDispatch.done (node_modules/q/q.js:863:30)
      at Promise.promise.promiseDispatch (node_modules/q/q.js:796:13)
      at node_modules/q/q.js:604:44
      at runSingle (node_modules/q/q.js:137:13)
      at flush (node_modules/q/q.js:125:13)
      at _combinedTickCallback (internal/process/next_tick.js:67:7)
      at process._tickCallback (internal/process/next_tick.js:98:9)

51.     AssertionError: Default setting for IS_DEFAULT_BROWSER should not be undefined
      at test/unit/constants/settingsTest.js:11:14
      at Array.forEach (native)
      at Context._callee$ (test/unit/constants/settingsTest.js:10:27)
      at tryCatch (node_modules/regenerator-runtime/runtime.js:63:40)
      at GeneratorFunctionPrototype.invoke [as _invoke] (node_modules/regenerator-runtime/runtime.js:337:22)
      at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (node_modules/regenerator-runtime/runtime.js:96:21)
      at onFulfilled (node_modules/co-mocha/node_modules/co/index.js:65:19)
      at node_modules/co-mocha/node_modules/co/index.js:54:5
      at Context.co (node_modules/co-mocha/node_modules/co/index.js:50:10)
      at Context.createPromise (node_modules/co-mocha/node_modules/co/index.js:30:15)
      at Test.Runnable.run (node_modules/co-mocha/lib/co-mocha.js:43:16)

**Comment by alexwykoff** [comment]
Now at 56 tests failing: 
commit 0d11443eb661809ad6af7f5073d9aa59160a5605
cc : @bbondy 

  56 failing

  1) component updater Google Widevine is disabled by default Google Widevine can be enabled and installed:
     WaitUntilTimeoutError: Promise was rejected with the following reason: Error: unknown error: Cannot read property 'state' of undefined
      at execute(<Function>) - brave.js:291:19

  2) about:history multi-select behavior deselects everything if something other than the table is clicked:
     Error: element (table.sortableTable tr.selected td.title[data-sort="Brave"]) still  visible after 5000ms


  3) about:newtab tests when displaying stats shows # trackers blocked:
     WaitUntilTimeoutError: Promise was rejected with the following reason: Error: unknown error: Cannot read property 'state' of undefined
      at execute(<Function>) - brave.js:291:19

  4) about:newtab tests when displaying stats shows # ads blocked:
     WaitUntilTimeoutError: Promise was rejected with the following reason: Error: unknown error: Cannot read property 'state' of undefined
      at execute(<Function>) - brave.js:291:19

  5) about:newtab tests with the top sites tile area shows sites that have been visited:
     WaitUntilTimeoutError: Promise was rejected with the following reason: Error: unknown error: Cannot read property 'state' of undefined
      at execute(<Function>) - brave.js:291:19

  6) about:newtab tests with the top sites tile area lets you pin a tile (and shows the pinned icon afterwards):
     WaitUntilTimeoutError: Promise was rejected with the following reason: Error: unknown error: Cannot read property 'state' of undefined
      at execute(<Function>) - brave.js:291:19

  7) sessionStore state is preserved "before all" hook: _callee:
     Error: Promise was rejected with the following reason: Error: unknown error: Cannot read property 'state' of undefined


  8) sessionStore firstRunTimestamp sets it once:
     Error: Promise was rejected with the following reason: Error: unknown error: Cannot read property 'state' of undefined


  9) Autofill address "before all" hook: _callee:
     WaitUntilTimeoutError: Promise was rejected with the following reason: Error: unknown error: Cannot read property 'state' of undefined
      at execute(<Function>) - brave.js:291:19

  10) Autofill credit card "before all" hook: _callee7:
     WaitUntilTimeoutError: Promise was rejected with the following reason: Error: unknown error: Cannot read property 'state' of undefined
      at execute(<Function>) - brave.js:291:19

  11) Autofill clear autofill data "before all" hook: _callee13:
     WaitUntilTimeoutError: Promise was rejected with the following reason: Error: unknown error: Cannot read property 'state' of undefined
      at execute(<Function>) - brave.js:291:19

  12) bookmark tests menu behavior rebuilds the menu when a folder is added:
     Error: Promise was rejected with the following reason: Error: unknown error: Cannot read property 'state' of undefined


  13) bookmark tests menu behavior rebuilds the menu when a bookmark is added:
     Error: Promise was rejected with the following reason: Error: unknown error: Cannot read property 'state' of undefined


  14) bookmark tests menu behavior rebuilds the menu when add a list of items:
     Error: Promise was rejected with the following reason: Error: unknown error: Cannot read property 'state' of undefined


  15) bookmarksToolbar when clicking a bookmark folder shows a context menu:
     WaitUntilTimeoutError: Promise was rejected with the following reason: Error: unknown error: Cannot read property 'state' of undefined
      at execute(<Function>) - brave.js:291:19

  16) bookmarksToolbar when clicking a bookmark folder automatically opens context menu if you move mouse over a different folder:
     WaitUntilTimeoutError: Promise was rejected with the following reason: Error: unknown error: Cannot read property 'state' of undefined
      at execute(<Function>) - brave.js:291:19

  17) bookmarksToolbar when clicking a bookmark folder hides context menu when mousing over regular bookmark:
     WaitUntilTimeoutError: Promise was rejected with the following reason: Error: unknown error: Cannot read property 'state' of undefined
      at execute(<Function>) - brave.js:291:19

  18) Bravery Panel Stats detects blocked elements in private tab:
     WaitUntilTimeoutError: Promise was rejected with the following reason: Error: unknown error: Cannot read property 'state' of undefined
      at execute(<Function>) - brave.js:291:19

  19) Bravery Panel Stats detects blocked elements:
     WaitUntilTimeoutError: Promise was rejected with the following reason: Error: unknown error: Cannot read property 'state' of undefined
      at execute(<Function>) - brave.js:291:19

  20) Bravery Panel Stats downloads and detects regional adblock resources in private tab:
     WaitUntilTimeoutError: Promise was rejected with the following reason: Error: unknown error: Cannot read property 'state' of undefined
      at execute(<Function>) - brave.js:291:19

  21) Bravery Panel Stats downloads and detects regional adblock resources:
     WaitUntilTimeoutError: Promise was rejected with the following reason: Error: unknown error: Cannot read property 'state' of undefined
      at execute(<Function>) - brave.js:291:19

  22) Bravery Panel Stats detects adblock resources in private tab:
     WaitUntilTimeoutError: Promise was rejected with the following reason: Error: unknown error: Cannot read property 'state' of undefined
      at execute(<Function>) - brave.js:291:19

  23) Bravery Panel Stats detects adblock resources:
     WaitUntilTimeoutError: Promise was rejected with the following reason: Error: unknown error: Cannot read property 'state' of undefined
      at execute(<Function>) - brave.js:291:19

  24) Bravery Panel Stats blocks custom adblock resources in private tab:
     WaitUntilTimeoutError: Promise was rejected with the following reason: Error: unknown error: Cannot read property 'state' of undefined
      at execute(<Function>) - brave.js:291:19

  25) Bravery Panel Stats blocks custom adblock resources:
     WaitUntilTimeoutError: Promise was rejected with the following reason: Error: unknown error: Cannot read property 'state' of undefined
      at execute(<Function>) - brave.js:291:19

  26) Bravery Panel Stats detects https upgrades in private tab:
     WaitUntilTimeoutError: Promise was rejected with the following reason: Error: unknown error: Cannot read property 'state' of undefined
      at execute(<Function>) - brave.js:291:19

  27) Bravery Panel Stats detects https upgrades:
     WaitUntilTimeoutError: Promise was rejected with the following reason: Error: unknown error: Cannot read property 'state' of undefined
      at execute(<Function>) - brave.js:291:19

  28) Clear Browsing Panel with history "before each" hook: _callee for "shows clearing options":
     Error: Promise was rejected with the following reason: Error: unknown error: Cannot read property 'state' of undefined


  29) Clear Browsing Panel with closedFrames "before each" hook: _callee4 for "clears closedFrames":
     Error: Promise was rejected with the following reason: Error: unknown error: Cannot read property 'state' of undefined


  30) Clear Browsing Panel with site settings "before each" hook: _callee6 for "clears site settings and permissions":
     Error: Promise was rejected with the following reason: Error: unknown error: Cannot read property 'state' of undefined


  31) findbar "before all" hook: _callee:
     Error: Promise was rejected with the following reason: timeout


  32) frame tests view source open from pinned tab:
     RuntimeError: unknown error: Cannot read property 'setPinned' of undefined
      at execute(<Function>, "http://localhost:11698/find_in_page.html", true, [object Object]) - brave.js:326:19

  33) frame tests resource loading loads a PDF:
     WaitUntilTimeoutError: Promise was rejected with the following reason: Error: unknown error: Cannot read property 'state' of undefined
      at execute(<Function>) - brave.js:291:19

  34) Payments Panel can setup payments payments can be enabled:
     Error: Promise was rejected with the following reason: Error: unknown error: Cannot read property 'state' of undefined


  35) Payments Panel can setup payments payments can be disabled:
     WaitUntilTimeoutError: Promise was rejected with the following reason: Error: unknown error: Cannot read property 'state' of undefined
      at execute(<Function>) - brave.js:291:19

  36) synopsis can disable site:
     Error: Promise was rejected with the following reason: Error: unknown error: Cannot read property 'state' of undefined


  37) navigationBar tests navigation focus newtab hasfocus in urlbar:
     WaitUntilTimeoutError: Promise was rejected with the following reason: Error: unknown error: Cannot read property 'state' of undefined
      at execute(<Function>) - brave.js:297:19

  38) navigationBar tests navigation focus newtab with page has focus in webview:
     WaitUntilTimeoutError: Promise was rejected with the following reason: Error: unknown error: Cannot read property 'state' of undefined
      at execute(<Function>) - brave.js:297:19

  39) navigationBar tests lockIcon Shows insecure URL icon:
     WaitUntilTimeoutError: Promise was rejected with the following reason: timeout
      at getAttribute(".urlbarIcon", "class") - navigationBarTest.js:416:12

  40) navigationBar tests lockIcon "after each" hook for "Shows insecure URL icon":
     Error: timeout of 30000ms exceeded. Ensure the done() callback is being called in this test.


  41) navigationBar tests themeColor Uses the default tab color when one is not specified:

      AssertionError: 'rgba(0,0,0,0)linear-gradient(white,rgb(243,243,243))repeatscroll0%0%/autopadding-boxborder-box' == 'rgba(0,0,0,0)linear-gradient(rgb(255,255,255),rgb(243,243,243))repeatscroll0%0%/autopadding-boxborder-box'
      + expected - actual

      -rgba(0,0,0,0)linear-gradient(white,rgb(243,243,243))repeatscroll0%0%/autopadding-boxborder-box
      +rgba(0,0,0,0)linear-gradient(rgb(255,255,255),rgb(243,243,243))repeatscroll0%0%/autopadding-boxborder-box

      at Context._callee38$ (test/components/navigationBarTest.js:686:14)
      at tryCatch (node_modules/regenerator-runtime/runtime.js:63:40)
      at GeneratorFunctionPrototype.invoke [as _invoke] (node_modules/regenerator-runtime/runtime.js:337:22)
      at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (node_modules/regenerator-runtime/runtime.js:96:21)
      at Object.onFulfilled (node_modules/co-mocha/node_modules/co/index.js:65:19)
      at Object.exec (node_modules/webdriverio/build/lib/helpers/safeExecute.js:28:24)
      at Object.resolve (node_modules/webdriverio/build/lib/webdriverio.js:189:29)
      at node_modules/webdriverio/build/lib/webdriverio.js:487:32
      at _fulfilled (node_modules/q/q.js:834:54)
      at self.promiseDispatch.done (node_modules/q/q.js:863:30)
      at Promise.promise.promiseDispatch (node_modules/q/q.js:796:13)
      at node_modules/q/q.js:604:44
      at runSingle (node_modules/q/q.js:137:13)
      at flush (node_modules/q/q.js:125:13)
      at _combinedTickCallback (internal/process/next_tick.js:67:7)
      at process._tickCallback (internal/process/next_tick.js:98:9)

  42) notificationBar can accept permission request persistently:
     RuntimeError: Couldn't connect to selenium server
      at url() - getUrl.js:29:28
      at getUrl() - brave.js:194:4

  43) notificationBar "before each" hook: _callee2 for "shows notification for login form":
     Error: Promise was rejected with the following reason: Error: Couldn't connect to selenium server


  44) notificationBar "after all" hook:
     RuntimeError: Couldn't connect to selenium server
      at windowHandles() - brave.js:166:32
      at execute(<Function>) - application.js:74:3

  45) permissions state applies old saved permissions:
     WaitUntilTimeoutError: element (#titleBar) still not existing after 5000ms
      at isExisting("#titleBar") - waitForExist.js:37:22

  46) pinnedTabs Pins an existing frame "before all" hook: _callee:
     RuntimeError: unknown error: Cannot read property 'setPinned' of undefined
      at execute(<Function>, "http://localhost:29514/page1.html", true, [object Object]) - brave.js:326:19

  47) pinnedTabs Pinning with partitions pinning the same site again with a different session is allowed:
     RuntimeError: unknown error: Cannot read property 'setPinned' of undefined
      at execute(<Function>, "http://localhost:24341/page1.html", true, [object Object]) - brave.js:326:19

  48) pinnedTabs Gets pins from external windows creates when signaled:
     WaitUntilTimeoutError: Promise was rejected with the following reason: timeout
      at elements(".pinnedTabs .tab") - pinnedTabTest.js:115:57

  49) pinnedTabs Pinned tab navigation "before all" hook: _callee11:
     RuntimeError: unknown error: Cannot read property 'setPinned' of undefined
      at execute(<Function>, "http://localhost:4423/page1.html", true, [object Object]) - brave.js:326:19

  50) pinnedTabs Closing pinned tabs "before all" hook: _callee14:
     RuntimeError: unknown error: Cannot read property 'setPinned' of undefined
      at execute(<Function>, "http://localhost:11730/page1.html", true, [object Object]) - brave.js:326:19

  51) urlBarSuggestions "before each" hook: _callee for "show suggestion when single letter is typed in":
     WaitUntilTimeoutError: Promise was rejected with the following reason: Error: unknown error: Cannot read property 'state' of undefined
      at execute(<Function>) - brave.js:291:19

  52) urlBar tests location bar with loaded tabs Retains user input on tab switches:
     Error: Promise was rejected with the following reason: timeout


  53) urlBar tests location bar with new tabs Retains user input on tab switches:
     WaitUntilTimeoutError: Promise was rejected with the following reason: timeout
      at getValue("#urlInput") - urlBarTest.js:311:21

  54) application window appActions.newWindow after resize has the width and height of the last window resize:

      undefined: expected 1440 to deeply equal 600
      + expected - actual

      -1440
      +600

      at execute(<Function>, "getBounds", , "require") - api.js:291:19

  55) application window windw.open with click with features sets the width and height:
     TypeError: Cannot read property 'getBounds' of undefined
      at Context._callee18$ (test/components/windowTest.js:224:15)
      at tryCatch (node_modules/regenerator-runtime/runtime.js:63:40)
      at GeneratorFunctionPrototype.invoke [as _invoke] (node_modules/regenerator-runtime/runtime.js:337:22)
      at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (node_modules/regenerator-runtime/runtime.js:96:21)
      at onFulfilled (node_modules/co-mocha/node_modules/co/index.js:65:19)
      at node_modules/co-mocha/node_modules/co/index.js:54:5
      at Context.co (node_modules/co-mocha/node_modules/co/index.js:50:10)
      at Context.createPromise (node_modules/co-mocha/node_modules/co/index.js:30:15)
      at Test.Runnable.run (node_modules/co-mocha/lib/co-mocha.js:43:16)
      at Hook.Runnable.run (node_modules/co-mocha/lib/co-mocha.js:43:16)

  56) application window windw.open with click with features sets the window position:
     TypeError: Cannot read property 'getBounds' of undefined
      at Context._callee19$ (test/components/windowTest.js:233:15)
      at tryCatch (node_modules/regenerator-runtime/runtime.js:63:40)
      at GeneratorFunctionPrototype.invoke [as _invoke] (node_modules/regenerator-runtime/runtime.js:337:22)
      at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (node_modules/regenerator-runtime/runtime.js:96:21)
      at onFulfilled (node_modules/co-mocha/node_modules/co/index.js:65:19)
      at node_modules/co-mocha/node_modules/co/index.js:54:5
      at Context.co (node_modules/co-mocha/node_modules/co/index.js:50:10)
      at Context.createPromise (node_modules/co-mocha/node_modules/co/index.js:30:15)
      at Test.Runnable.run (node_modules/co-mocha/lib/co-mocha.js:43:16)
      at Hook.Runnable.run (node_modules/co-mocha/lib/co-mocha.js:43:16)

**Comment by luixxiul** [comment]
Does this block on 0.12.9?

**Comment by bbondy** [comment]
This issue does not block but we can use it for tracking tests temporarily. I think it's out of date though, only 2 tests fail locally but I know remote is not the same as local because travis fails more often.

**Comment by bbondy** [comment]
Most of these are fixed now and we know we have to fix and this is out of date, so I'm going to close this one.
