### ISSUE TITLE
Manual tests for Windows x64 0.12.9 Preview1

### ISSUE THREAD

**Issue by alexwykoff** [brave/browser-laptop#5549]
## Installer

1. [x] Check that installer is close to the size of last release.
2. [x] Check signature: If OS Run `spctl --assess --verbose /Applications/Brave.app/` and make sure it returns `accepted`.  If Windows right click on the installer exe and go to Properties, go to the Digital Signatures tab and double click on the signature.  Make sure it says "The digital signature is OK" in the popup window.
3. [x] Check Brave, electron, and libchromiumcontent version in About and make sure it is EXACTLY as expected.

## Per release specialty tests

 - [ ] Use early adblock files when in development mode ([#5543](https://github.com/brave/browser-laptop/issues/5543))
 - [x] Refine the Brave button (look, positioning, feel) on Windows ([#5069](https://github.com/brave/browser-laptop/issues/5069))
 - [x] Fix caption button alignment on Windows 7 ([#5522](https://github.com/brave/browser-laptop/pull/5522))
 - [ ] Selected history entries don't clear selection when clicked outside the view ([#5458](https://github.com/brave/browser-laptop/issues/5458))
 - [ ] about:history - Clicking on something other than the table will clear any selections ([#5525](https://github.com/brave/browser-laptop/pull/5525))
 - [ ] English locale will now show a smaller version of AM/PM ([#5520](https://github.com/brave/browser-laptop/pull/5520))
 - [ ] Create exception for USA clock display to have small "AM/PM" indicator text ([#5381](https://github.com/brave/browser-laptop/issues/5381))
 - [x] Main window(s) stop responding if help about is open ([#2902](https://github.com/brave/browser-laptop/issues/2902))
 - [ ] follow-ups to #5501 ([#5516](https://github.com/brave/browser-laptop/issues/5516))
 - [ ] remove opacity from new tab button ([#5519](https://github.com/brave/browser-laptop/pull/5519))
 - [ ] Remove opacity on new tab button ([#5518](https://github.com/brave/browser-laptop/issues/5518))
 - [ ] Right Click doesn't work when 1Password/Lastpass is enabled as password manager ([#5509](https://github.com/brave/browser-laptop/issues/5509))
 - [ ] Create a script to check for extension updates ([#4911](https://github.com/brave/browser-laptop/issues/4911))
 - [ ] Provide Password Manager/Extension icon in right click context menu ([#5292](https://github.com/brave/browser-laptop/issues/5292))
 - [ ] Set extension icon in context menu ([#5350](https://github.com/brave/browser-laptop/pull/5350))
 - [ ] [HackerOne] https://hackerone.com/reports/178379 ([#5238](https://github.com/brave/browser-laptop/issues/5238))
 - [ ] [Proposal] CSS in JS documentation ([#5205](https://github.com/brave/browser-laptop/pull/5205))
 - [ ] CSS in JS proposal ([#5204](https://github.com/brave/browser-laptop/issues/5204))
 - [ ] Window buttons not properly aligned when browser is maximized ([#5145](https://github.com/brave/browser-laptop/issues/5145))
 - [ ] Don't show HTTP icon while site is loading (since it may be HTTPS) ([#5498](https://github.com/brave/browser-laptop/pull/5498))
 - [ ] Account balance: error, can't retrieve data ([#4920](https://github.com/brave/browser-laptop/issues/4920))
 - [ ] "Add funds" notification: Reduce nag level and add button to "Turn off notifications" ([#5469](https://github.com/brave/browser-laptop/pull/5469))
 - [ ] Add funds bar comes up too often and should have turn off button ([#5418](https://github.com/brave/browser-laptop/issues/5418))
 - [ ] In ledger notifications offer option to "Don't notify me anymore" ([#5299](https://github.com/brave/browser-laptop/issues/5299))
 - [ ] regression: deciding conversion candidate on URL bar searches the candidate ([#5313](https://github.com/brave/browser-laptop/issues/5313))
 - [ ] deciding and searching conversion candidate not working ([#5315](https://github.com/brave/browser-laptop/issues/5315))
 - [ ] Ledger does not track windows created before the wallet ([#4274](https://github.com/brave/browser-laptop/issues/4274))
 - [ ] Widevine dialog permission should always be applied from tab that initiated it and not active frame ([#5488](https://github.com/brave/browser-laptop/issues/5488))
 - [ ] Importing bookmarks shows pinned tabs in history ([#5405](https://github.com/brave/browser-laptop/issues/5405))
 - [ ] refined string text for multiple items including change of Bravery to Shields copy/content/text ([#5421](https://github.com/brave/browser-laptop/pull/5421))
 - [ ] Make new tab page to have only one topSite row with for first release ([#5482](https://github.com/brave/browser-laptop/issues/5482))
 - [ ] Remove row control for topSites on new tab page ([#5483](https://github.com/brave/browser-laptop/pull/5483))
 - [ ] Brave Logo Slides Beneath URL Bar ([#5383](https://github.com/brave/browser-laptop/issues/5383))
 - [ ] Refine the Brave button (look, positioning, feel) on Windows ([#5069](https://github.com/brave/browser-laptop/pull/5069))
 - [ ] Reposition Brave Lion on Windows ([#5485](https://github.com/brave/browser-laptop/issues/5485))
 - [ ] Disabling adblock in private tab still shows the adblock count ([#5376](https://github.com/brave/browser-laptop/pull/5376))
 - [ ] isResourceEnabled for private tab ([#5481](https://github.com/brave/browser-laptop/pull/5481))
 - [ ] To "Review sites" notification add button to Dismiss ([#5473](https://github.com/brave/browser-laptop/issues/5473))
 - [ ] Verified publisher icon should be a hexagon ([#5210](https://github.com/brave/browser-laptop/issues/5210))
 - [ ] Get new signing keys setup for macOS ([#4768](https://github.com/brave/browser-laptop/issues/4768))
 - [ ] Search icons overlapping with urlbar find icon ([#5477](https://github.com/brave/browser-laptop/pull/5477))
 - [ ] Fix search icon overlapping custom search engine icon ([#5479](https://github.com/brave/browser-laptop/pull/5479))
 - [ ] Add basic styles to about:about and created page w/ version information (about:brave) copy/content/text ([#5436](https://github.com/brave/browser-laptop/issues/5436))
 - [ ] Add infogalactic.com to Search prefs ([#5475](https://github.com/brave/browser-laptop/issues/5475))
 - [ ] Add Wolfram Alpha to Search ([#5478](https://github.com/brave/browser-laptop/issues/5478))
 - [ ] URL is normalized when updating favicon for a given site ([#5445](https://github.com/brave/browser-laptop/pull/5445))
 - [ ] Manually added bookmark pages doesn't create the favicons after visiting the site ([#4860](https://github.com/brave/browser-laptop/issues/4860))
 - [ ] AVG is deleting latest update, severity High needs investigation ([#5241](https://github.com/brave/browser-laptop/issues/5241))
 - [ ] svg buttons alignment on tabsbar ([#5456](https://github.com/brave/browser-laptop/issues/5456))
 - [ ] svg buttons alignment on tabsbar ([#5468](https://github.com/brave/browser-laptop/pull/5468))
 - [ ] Don't toggle menu unless ALT was the last key pressed ([#5450](https://github.com/brave/browser-laptop/pull/5450))
 - [ ] Process of Inserting Alt Code Reveals Toolbar ([#4295](https://github.com/brave/browser-laptop/issues/4295))
 - [ ] Clicking in navigation bar only selects part of URL sometimes ([#5460](https://github.com/brave/browser-laptop/issues/5460))
 - [ ] Selecting cut text from context menu refills URL into URL bar ([#5063](https://github.com/brave/browser-laptop/issues/5063))
 - [ ] Various automated navigationBar tests are failing ([#5459](https://github.com/brave/browser-laptop/issues/5459))
 - [ ] URL highlight then type doesn't clear existing ([#5036](https://github.com/brave/browser-laptop/issues/5036))
 - [ ] Implement hide-autofill-popup  ([#5287](https://github.com/brave/browser-laptop/pull/5287))
 - [ ] Context Menus are Visible While Scrolling ([#5023](https://github.com/brave/browser-laptop/issues/5023))
 - [ ] Autofill suggestion should close when form is submit / enter pressed ([#4540](https://github.com/brave/browser-laptop/issues/4540))
 - [ ] Autofill suggestion should close when field is out of focus ([#3816](https://github.com/brave/browser-laptop/issues/3816))
 - [ ] Imported bookmarks should set creationTime field (not lastAccessedTime) ([#5183](https://github.com/brave/browser-laptop/issues/5183))
 - [ ] Updating icons in URL bar  ([#5449](https://github.com/brave/browser-laptop/pull/5449))
 - [ ] change unlocked icon (http) in URL bar to FA warning triangle ([#5446](https://github.com/brave/browser-laptop/issues/5446))
 - [ ] URL bar icon should never be empty, and use magnify (search) icon instead of page icon ([#4910](https://github.com/brave/browser-laptop/issues/4910))
 - [ ] convert toolbar icons to svg  ([#5173](https://github.com/brave/browser-laptop/pull/5173))
 - [ ] convert toolbar icons to SVG design enhancement ([#4852](https://github.com/brave/browser-laptop/issues/4852))
 - [ ] Update default for magic titlebar on Windows/Linux; add favicon for about pages ([#5443](https://github.com/brave/browser-laptop/pull/5443))
 - [ ] URL bar duplicates the title bar ([#5416](https://github.com/brave/browser-laptop/issues/5416))
 - [ ] about:autofill missing Brave favicon misc/favicon ([#5398](https://github.com/brave/browser-laptop/issues/5398))
 - [ ] align percentage column in ledger payments ([#5408](https://github.com/brave/browser-laptop/pull/5408))
 - [ ] Views and % entries alignment are different in payments window ([#5402](https://github.com/brave/browser-laptop/issues/5402))
 - [ ] [hackerone] https://hackerone.com/reports/180234 ([#5447](https://github.com/brave/browser-laptop/issues/5447))
 - [ ] Menu sub items should be capitalized for uniformity copy/content/text ([#5377](https://github.com/brave/browser-laptop/issues/5377))
 - [ ] Capitalize menu items  copy/content/text ([#5422](https://github.com/brave/browser-laptop/pull/5422))
 - [ ] payments advanced settings button hidden when payments disabled ([#5407](https://github.com/brave/browser-laptop/pull/5407))
 - [ ] Payments advance settings button is not hidden when payment is disabled ([#5384](https://github.com/brave/browser-laptop/issues/5384))
 - [ ] Add fallback when a topSite doesn't have favicon ([#5414](https://github.com/brave/browser-laptop/pull/5414))
 - [ ] On new tab page, sometimes a topSite doesn't even have a letter ([#5332](https://github.com/brave/browser-laptop/issues/5332))
 - [ ] Properly display about:newtab when session is null ([#5411](https://github.com/brave/browser-laptop/pull/5411))
 - [ ] Change order of topSites actions to PIN-BM-CLOSE ([#5410](https://github.com/brave/browser-laptop/pull/5410))
 - [ ] change order of BM-PIN-CLOSE hover toolbar buttons so pin can be in the corner ([#5380](https://github.com/brave/browser-laptop/issues/5380))
 - [ ] about:newtabs - pinning is not working ([#5337](https://github.com/brave/browser-laptop/issues/5337))
 - [ ] Fix gridLayout pinning action ([#5406](https://github.com/brave/browser-laptop/pull/5406))
 - [ ] Pinned topSites not retaining its position ([#5321](https://github.com/brave/browser-laptop/issues/5321))
 - [ ] Allow editing location on Add Bookmark in bookmark toolbar ([#5375](https://github.com/brave/browser-laptop/pull/5375))
 - [ ] add Bookmark on context menu of toolbar should allow user to edit location ([#5374](https://github.com/brave/browser-laptop/issues/5374))
 - [ ] about:newtab - favicons are not always shown ([#5310](https://github.com/brave/browser-laptop/issues/5310))
 - [ ] delete folder cause stack overflow ([#5357](https://github.com/brave/browser-laptop/issues/5357))
 - [ ] Created session helper for newTabState ([#5361](https://github.com/brave/browser-laptop/pull/5361))
 - [ ] about:newtab - load images remotely ([#5396](https://github.com/brave/browser-laptop/issues/5396))
 - [ ] Style for darker colored "Top Sites" entries is hard to see ([#5324](https://github.com/brave/browser-laptop/issues/5324))
 - [ ] Fix drag and drop for about:newtab (and other fixes) ([#5354](https://github.com/brave/browser-laptop/pull/5354))
 - [ ] about:newtabs - drag and drop not working for Top Sites items ([#5336](https://github.com/brave/browser-laptop/issues/5336))
 - [ ] Add default lastAccessTime for history entries only ([#5349](https://github.com/brave/browser-laptop/pull/5349))
 - [ ] Site listed under payments even though the visit count is less than 5(default visit count) ([#5200](https://github.com/brave/browser-laptop/issues/5200))
 - [ ] have text regarding contribution dates match ([#5343](https://github.com/brave/browser-laptop/issues/5343))
 - [ ] regression: opening a new tab should not show 'about:blank' ([#5334](https://github.com/brave/browser-laptop/issues/5334))
 - [ ] Add transition for new-tabbackground ([#5330](https://github.com/brave/browser-laptop/pull/5330))
 - [x] Add standalone file for CSS animations ([#5329](https://github.com/brave/browser-laptop/pull/5329))
 - [x] Add standalone file for CSS animations ([#5238](https://github.com/brave/browser-laptop/issues/5328))
 - [ ] New Tab Design: Overview with subtasks (about:newtab) ([#3001](https://github.com/brave/browser-laptop/issues/3001))
 - [x] General Settings: "A new tab shows" setting documentation ([#2106](https://github.com/brave/browser-laptop/issues/2106))
 - [x] Brand new about:newtab page ([#5301](https://github.com/brave/browser-laptop/pull/5301))

## Ledger
1. [ ] Create a wallet with a value other than $5 selected in the monthly budget dropdown. Click on the 'Add Funds' button and check that Coinbase transactions are blocked.
2. [x] Remove all `ledger-*.json` files from `~/Library/Application\ Support/Brave/`. Go to the Payments tab in about:preferences, enable payments, click on `create wallet`. Check that the `add funds` button appears after a wallet is created.
3. [ ] Click on `add funds` and verify that adding funds through Coinbase increases the account balance.
4. [ ] Repeat the step above but add funds by scanning the QR code in a mobile bitcoin app instead of through Coinbase.
5. [x] Visit nytimes.com for a few seconds and make sure it shows up in the Payments table.
6. [x] Go to https://jsfiddle.net/LnwtLckc/5/ and click the register button. In the Payments tab, click `add funds`. Verify that the `transfer funds` button is visible and that clicking on `transfer funds` opens a jsfiddle URL in a new tab.
7. [x] Go to https://jsfiddle.net/LnwtLckc/5/ and click `unregister`. Verify that the `transfer funds` button no longer appears in the `add funds` modal.
8. [x] Check that disabling payments and enabling them again does not lose state.

## Data

1. [x] Make sure that data from the last version appears in the new version OK.
2. [x] Test that the previous version's cookies are preserved in the next version.

## About pages

1. [x] Test that about:adblock loads
2. [x] Test that about:autofill loads
3. [x] Test that about:bookmarks loads bookmarks
4. [x] Test that about:downloads loads downloads
5. [x] Test that about:extensions loads
6. [x] Test that about:history loads history
7. [x] Test that about:passwords loads
8. [x] Test that about:styles loads
9. [x] Test that about:preferences changing a preference takes effect right away
10. [x] Test that about:preferences language change takes effect on re-start
11. [x] Test that about.com without the http protocol is loaded from URL bar

## Bookmarks

1. [x] Test that creating a bookmark on the bookmarks toolbar works
2. [x] Test that creating a bookmark folder on the bookmarks toolbar works
3. [x] Test that moving a bookmark into a folder by drag and drop on the bookmarks folder works
4. [x] Test that clicking a bookmark in the toolbar loads the bookmark.
5. [x] Test that clicking a bookmark in a bookmark toolbar folder loads the bookmark.

## Context menus
1. [x] Make sure context menu items in the URL bar work
2. [x] Make sure context menu items on content work with no selected text.
3. [x] Make sure context menu items on content work with selected text.
4. [x] Make sure context menu items on content work inside an editable control (input, textarea, or contenteditable).

## Find on page

1. [x] Ensure search box is shown with shortcut
2. [x] Test successful find
3. [x] Test forward and backward find navigation
4. [x] Test failed find shows 0 results
5. [x] Test match case find

## Geolocation

1. [x] Check that https://developer.mozilla.org/en-US/docs/Web/API/Geolocation/Using_geolocation works

## Site hacks

1. [x] Test https://www.twitch.tv/adobe sub-page loads a video and you can play it

## Downloads

1. [x] Test downloading a file works and that all actions on the download item works.

## Fullscreen

1. [x] Test that entering full screen window works View -> Toggle Full Screen. And exit back (Not Esc).
2. [x] Test that entering HTML5 full screen works. And Esc to go back. (youtube.com)

## Tabs and Pinning

1. [x] Test that tabs are pinnable
2. [x] Test that tabs are unpinnable
3. [x] Test that tabs are draggable to same tabset
4. [x] Test that tabs are draggable to alternate tabset

## Zoom

1. [x] Test zoom in / out shortcut works
2. [x] Test hamburger menu zooms.
3. [x] Test zoom saved when you close the browser and restore on a single site.
4. [x] Test zoom saved when you navigate within a single origin site.
5. [x] Test that navigating to a different origin resets the zoom

## Bravery settings

1. [x] Check that HTTPS Everywhere works by loading http://www.apple.com
2. [x] Turning HTTPS Everywhere off and shields off both disable the redirect to https://www.apple.com
3. [x] Check that ad replacement works on http://slashdot.org
4. [x] Check that toggling to blocking and allow ads works as expected.
5. [x] Test that clicking through a cert error in https://badssl.com/ works.
6. [x] Test that Safe Browsing works (http://downloadme.org/)
7. [x] Turning Safe Browsing off and shields off both disable safe browsing for http://downloadme.org/.
8. [x] Visit https://brianbondy.com/ and then turn on script blocking, nothing should load. Allow it from the script blocking UI in the URL bar and it should work.
9. [x] Test that about:preferences default Bravery settings take effect on pages with no site settings.
10. [x] Test that turning on fingerprinting protection in about:preferences shows 3 fingerprints blocked at https://jsfiddle.net/bkf50r8v/13/. Test that turning it off in the Bravery menu shows 0 fingerprints blocked.
11. [x] Test that 3rd party storage results are blank at https://jsfiddle.net/7ke9r14a/9/ when 3rd party cookies are blocked and not blank when 3rd party cookies are unblocked.
12. [x] Test that audio fingerprint is blocked at https://audiofingerprint.openwpm.com/ when fingerprinting protection is on.

## Content tests

1. [x] Go to https://brianbondy.com/ and click on the twitter icon on the top right. Test that context menus work in the new twitter tab.
2. [x] Load twitter and click on a tweet so the popup div shows.   Click to dismiss and repeat with another div. Make sure it shows.
3. [x] Go to http://www.bennish.net/web-notifications.html and test that clicking on 'Show' pops up a notification asking for permission. Make sure that clicking 'Deny' leads to no notifications being shown.
4. [x] Go to https://trac.torproject.org/projects/tor/login and make sure that the password can be saved. Make sure the saved password shows up in `about:passwords`. Then reload https://trac.torproject.org/projects/tor/login and make sure the password is autofilled.
5. [x] Open a github issue and type some misspellings, make sure they are underlined.
6. [x] Make sure that right clicking on a word with suggestions gives a suggestion and that clicking on the suggestion replaces the text.
7. [x] Make sure that Command + Click (Control + Click on Windows, Control + Click on Ubuntu) on a link opens a new tab but does NOT switch to it.  Click on it and make sure it is already loaded.
8. [x] Open an email on http://mail.google.com/ or inbox.google.com and click on a link. Make sure it works.
9. [x] Test that PDF is loaded at http://www.orimi.com/pdf-test.pdf
10. [x] Test that https://mixed-script.badssl.com/ shows up as grey not red (no mixed content scripts are run).

## Flash tests
1. [x] Turn on Flash in about:preferences#security. Test that clicking on 'Install Flash' banner on myspace.com shows a notification to allow Flash and that the banner disappears when 'Allow' is clicked.
2. [x] Test that flash placeholder appears on http://www.y8.com/games/superfighters

## Autofill tests
1. [x] Test that autofill works on http://www.roboform.com/filling-test-all-fields

## Session storage

Do not forget to make a backup of your entire `~/Library/Application\ Support/Brave` folder.

1. [x] Temporarily move away your `~/Library/Application\ Support/Brave/session-store-1` and test that clean session storage works. (`%appdata%\Brave in Windows`, `./config/brave` in Ubuntu)
2. [x] Test that windows and tabs restore when closed, including active tab.
3. [x] Move away your entire `~/Library/Application\ Support/Brave` folder (`%appdata%\Brave in Windows`, `./config/brave` in Ubuntu)

## Cookie and Cache

1. [x] Make a backup of your profile, turn on all clearing in preferences and shut down.  Make sure when you bring the browser back up everything is gone that is specified.
2. [x] Go to http://samy.pl/evercookie/ and set an evercookie. Check that going to prefs, clearing site data and cache, and going back to the Evercookie site does not remember the old evercookie value.

## Update tests

1. [x] Test that updating using `BRAVE_UPDATE_VERSION=0.8.3` env variable works correctly.
