### ISSUE TITLE
Manual tests for Ubuntu 0.12.9 Preview 3 per-release items

### ISSUE THREAD

**Issue by alexwykoff** [brave/browser-laptop#5598]
preview 3
 - [x] URLBar selection should be retained when non character key is pressed with selected suggestion ([#5584](https://github.com/brave/browser-laptop/issues/5584))
 - [x] "Top Sites" should consider visit count when ordering ([#5322](https://github.com/brave/browser-laptop/issues/5322))
 - [ ] Refactoring, Bug fixes, and tests for top sites on about:newtab ([#5583](https://github.com/brave/browser-laptop/pull/5583))
 - [ ] ~~Bookmarking a site on new tab gridSites change its position ([#5413](https://github.com/brave/browser-laptop/issues/5413))~~
 - [x] Fix crash that can occur in tracking protection's native module ([#5588](https://github.com/brave/browser-laptop/issues/5588))
 - [x] Typed input in tab is not always retained when changing tabs ([#5585](https://github.com/brave/browser-laptop/issues/5585))
 - [x] typing over urlbar selection, should allow your typed change ([#5582](https://github.com/brave/browser-laptop/issues/5582))
 - [x] User input starting with http doesn't sort suggestion results properly ([#5578](https://github.com/brave/browser-laptop/issues/5578))
 - [ ] Pages are rendering too slowly ([#5536](https://github.com/brave/browser-laptop/issues/5536))
 - [x] Regression : autocomplete is deleting the first character typed in the url bar ([#5529](https://github.com/brave/browser-laptop/issues/5529))
 - [x] URLbar should not remain focused when no back history([#5563](https://github.com/brave/browser-laptop/issues/5563))
 - [x] Edited URL based on history in URL bar autocomplete list is not reflected correctly on the URL bar ([#5506](https://github.com/brave/browser-laptop/issues/5506))
 - [x] fix syncing between react and DOM urlbar focus/select ([#5573](https://github.com/brave/browser-laptop/pull/5573))
 - [x] Regression: mixed content site showing up as insecure ([#5524](https://github.com/brave/browser-laptop/issues/5524))
 - [x] Show passive mixed content as secure ([#5556](https://github.com/brave/browser-laptop/pull/5556))
 - [x] Upgrade to muon 1.4.25 ([#5568](https://github.com/brave/browser-laptop/issues/5568))
 - [ ] ~~Console errors after enabling widevine from preferences ([#5560](https://github.com/brave/browser-laptop/issues/5560))~~
 - [x] [Regression] hitting delete doesn't clear urlbar suggestions ([#5567](https://github.com/brave/browser-laptop/issues/5567))
 - [x] Right click doesn't work after enabling Pocket ([#5561](https://github.com/brave/browser-laptop/issues/5561))
 - [ ] numerous small adjustments to buttons and some other style fixes ([#5526](https://github.com/brave/browser-laptop/pull/5526))
 - [ ] small adjustments to toolbar icons, hover states, colors, etc needed. ([#5527](https://github.com/brave/browser-laptop/issues/5527))
 - [ ] ~~Unable to disable Google Widevine Support ([#5535](https://github.com/brave/browser-laptop/issues/5535))~~
 - [x] Cannot close tabs or change tab focus ([#5558](https://github.com/brave/browser-laptop/issues/5558))

preview 2
 - [ ] Use early adblock files when in development mode ([#5543](https://github.com/brave/browser-laptop/issues/5543))
 - [ ] Refine the Brave button (look, positioning, feel) on Windows ([#5069](https://github.com/brave/browser-laptop/issues/5069))
 - [ ] Fix caption button alignment on Windows 7 ([#5522](https://github.com/brave/browser-laptop/pull/5522))
 - [x] Selected history entries don't clear selection when clicked outside the view ([#5458](https://github.com/brave/browser-laptop/issues/5458))
 - [x] about:history - Clicking on something other than the table will clear any selections ([#5525](https://github.com/brave/browser-laptop/pull/5525))
 - [ ] English locale will now show a smaller version of AM/PM ([#5520](https://github.com/brave/browser-laptop/pull/5520))
 - [ ] Create exception for USA clock display to have small "AM/PM" indicator text ([#5381](https://github.com/brave/browser-laptop/issues/5381))
 - [x] Main window(s) stop responding if help about is open ([#2902](https://github.com/brave/browser-laptop/issues/2902))
 - [x] follow-ups to #5501 ([#5516](https://github.com/brave/browser-laptop/issues/5516))
 - [x] remove opacity from new tab button ([#5519](https://github.com/brave/browser-laptop/pull/5519))
 - [x] Remove opacity on new tab button ([#5518](https://github.com/brave/browser-laptop/issues/5518))
 - [x] Right Click doesn't work when 1Password/Lastpass is enabled as password manager ([#5509](https://github.com/brave/browser-laptop/issues/5509))
 - [ ] Create a script to check for extension updates ([#4911](https://github.com/brave/browser-laptop/issues/4911))
 - [x] Provide Password Manager/Extension icon in right click context menu ([#5292](https://github.com/brave/browser-laptop/issues/5292))
 - [x] Set extension icon in context menu ([#5350](https://github.com/brave/browser-laptop/pull/5350))
 - [ ] [HackerOne] https://hackerone.com/reports/178379 ([#5238](https://github.com/brave/browser-laptop/issues/5238))
 - [x] [Proposal] CSS in JS documentation ([#5205](https://github.com/brave/browser-laptop/pull/5205))
 - [x] CSS in JS proposal ([#5204](https://github.com/brave/browser-laptop/issues/5204))
 - [ ] Window buttons not properly aligned when browser is maximized ([#5145](https://github.com/brave/browser-laptop/issues/5145))
 - [x] Don't show HTTP icon while site is loading (since it may be HTTPS) ([#5498](https://github.com/brave/browser-laptop/pull/5498))
 - [x] Account balance: error, can't retrieve data ([#4920](https://github.com/brave/browser-laptop/issues/4920))
 - [ ] "Add funds" notification: Reduce nag level and add button to "Turn off notifications" ([#5469](https://github.com/brave/browser-laptop/pull/5469))
 - [ ] Add funds bar comes up too often and should have turn off button ([#5418](https://github.com/brave/browser-laptop/issues/5418))
 - [ ] In ledger notifications offer option to "Don't notify me anymore" ([#5299](https://github.com/brave/browser-laptop/issues/5299))
 - [ ] regression: deciding conversion candidate on URL bar searches the candidate ([#5313](https://github.com/brave/browser-laptop/issues/5313))
 - [ ] deciding and searching conversion candidate not working ([#5315](https://github.com/brave/browser-laptop/issues/5315))
 - [x] Ledger does not track windows created before the wallet ([#4274](https://github.com/brave/browser-laptop/issues/4274))
 - [ ] Widevine dialog permission should always be applied from tab that initiated it and not active frame ([#5488](https://github.com/brave/browser-laptop/issues/5488))
 - [x] Importing bookmarks shows pinned tabs in history ([#5405](https://github.com/brave/browser-laptop/issues/5405))
 - [x] refined string text for multiple items including change of Bravery to Shields copy/content/text ([#5421](https://github.com/brave/browser-laptop/pull/5421))
 - [x] Make new tab page to have only one topSite row with for first release ([#5482](https://github.com/brave/browser-laptop/issues/5482))
 - [x] Remove row control for topSites on new tab page ([#5483](https://github.com/brave/browser-laptop/pull/5483))
 - [x] Brave Logo Slides Beneath URL Bar ([#5383](https://github.com/brave/browser-laptop/issues/5383))
 - [ ] Refine the Brave button (look, positioning, feel) on Windows ([#5069](https://github.com/brave/browser-laptop/pull/5069))
 - [ ] Reposition Brave Lion on Windows ([#5485](https://github.com/brave/browser-laptop/issues/5485))
 - [x] Disabling adblock in private tab still shows the adblock count ([#5376](https://github.com/brave/browser-laptop/pull/5376))
 - [ ] isResourceEnabled for private tab ([#5481](https://github.com/brave/browser-laptop/pull/5481))
 - [ ] To "Review sites" notification add button to Dismiss ([#5473](https://github.com/brave/browser-laptop/issues/5473))
 - [x] Verified publisher icon should be a hexagon ([#5210](https://github.com/brave/browser-laptop/issues/5210))
 - [ ] Get new signing keys setup for macOS ([#4768](https://github.com/brave/browser-laptop/issues/4768))
 - [x] Search icons overlapping with urlbar find icon ([#5477](https://github.com/brave/browser-laptop/pull/5477))
 - [x] Fix search icon overlapping custom search engine icon ([#5479](https://github.com/brave/browser-laptop/pull/5479))
 - [x] Add basic styles to about:about and created page w/ version information (about:brave) copy/content/text ([#5436](https://github.com/brave/browser-laptop/issues/5436))
 - [x] Add infogalactic.com to Search prefs ([#5475](https://github.com/brave/browser-laptop/issues/5475))
 - [x] Add Wolfram Alpha to Search ([#5478](https://github.com/brave/browser-laptop/issues/5478))
 - [x] URL is normalized when updating favicon for a given site ([#5445](https://github.com/brave/browser-laptop/pull/5445))
 - [x] Manually added bookmark pages doesn't create the favicons after visiting the site ([#4860](https://github.com/brave/browser-laptop/issues/4860))
 - [ ] AVG is deleting latest update, severity High needs investigation ([#5241](https://github.com/brave/browser-laptop/issues/5241))
 - [x] svg buttons alignment on tabsbar ([#5456](https://github.com/brave/browser-laptop/issues/5456))
 - [x] svg buttons alignment on tabsbar ([#5468](https://github.com/brave/browser-laptop/pull/5468))
 - [ ] Don't toggle menu unless ALT was the last key pressed ([#5450](https://github.com/brave/browser-laptop/pull/5450))
 - [ ] Process of Inserting Alt Code Reveals Toolbar ([#4295](https://github.com/brave/browser-laptop/issues/4295))
 - [x] Clicking in navigation bar only selects part of URL sometimes ([#5460](https://github.com/brave/browser-laptop/issues/5460))
 - [x] Selecting cut text from context menu refills URL into URL bar ([#5063](https://github.com/brave/browser-laptop/issues/5063))
 - [ ] Various automated navigationBar tests are failing ([#5459](https://github.com/brave/browser-laptop/issues/5459))
 - [x] URL highlight then type doesn't clear existing ([#5036](https://github.com/brave/browser-laptop/issues/5036))
 - [x] Implement hide-autofill-popup  ([#5287](https://github.com/brave/browser-laptop/pull/5287))
 - [x] Context Menus are Visible While Scrolling ([#5023](https://github.com/brave/browser-laptop/issues/5023))
 - [x] Autofill suggestion should close when form is submit / enter pressed ([#4540](https://github.com/brave/browser-laptop/issues/4540))
 - [x] Autofill suggestion should close when field is out of focus ([#3816](https://github.com/brave/browser-laptop/issues/3816))
 - [x] Imported bookmarks should set creationTime field (not lastAccessedTime) ([#5183](https://github.com/brave/browser-laptop/issues/5183))
 - [x] Updating icons in URL bar  ([#5449](https://github.com/brave/browser-laptop/pull/5449))
 - [x] change unlocked icon (http) in URL bar to FA warning triangle ([#5446](https://github.com/brave/browser-laptop/issues/5446))
 - [x] URL bar icon should never be empty, and use magnify (search) icon instead of page icon ([#4910](https://github.com/brave/browser-laptop/issues/4910))
 - [x] convert toolbar icons to svg  ([#5173](https://github.com/brave/browser-laptop/pull/5173))
 - [x] convert toolbar icons to SVG design enhancement ([#4852](https://github.com/brave/browser-laptop/issues/4852))
 - [x] Update default for magic titlebar on Windows/Linux; add favicon for about pages ([#5443](https://github.com/brave/browser-laptop/pull/5443))
 - [x] URL bar duplicates the title bar ([#5416](https://github.com/brave/browser-laptop/issues/5416))
 - [x] about:autofill missing Brave favicon misc/favicon ([#5398](https://github.com/brave/browser-laptop/issues/5398))
 - [x] align percentage column in ledger payments ([#5408](https://github.com/brave/browser-laptop/pull/5408))
 - [x] Views and % entries alignment are different in payments window ([#5402](https://github.com/brave/browser-laptop/issues/5402))
 - [x] [hackerone] https://hackerone.com/reports/180234 ([#5447](https://github.com/brave/browser-laptop/issues/5447))
 - [x] Menu sub items should be capitalized for uniformity copy/content/text ([#5377](https://github.com/brave/browser-laptop/issues/5377))
 - [x] Capitalize menu items  copy/content/text ([#5422](https://github.com/brave/browser-laptop/pull/5422))
 - [x] payments advanced settings button hidden when payments disabled ([#5407](https://github.com/brave/browser-laptop/pull/5407))
 - [x] Payments advance settings button is not hidden when payment is disabled ([#5384](https://github.com/brave/browser-laptop/issues/5384))
 - [ ] Add fallback when a topSite doesn't have favicon ([#5414](https://github.com/brave/browser-laptop/pull/5414))
 - [x] On new tab page, sometimes a topSite doesn't even have a letter ([#5332](https://github.com/brave/browser-laptop/issues/5332))
 - [ ] Properly display about:newtab when session is null ([#5411](https://github.com/brave/browser-laptop/pull/5411))
 - [x] Change order of topSites actions to PIN-BM-CLOSE ([#5410](https://github.com/brave/browser-laptop/pull/5410))
 - [x] change order of BM-PIN-CLOSE hover toolbar buttons so pin can be in the corner ([#5380](https://github.com/brave/browser-laptop/issues/5380))
 - [ ] about:newtabs - pinning is not working ([#5337](https://github.com/brave/browser-laptop/issues/5337))
 - [ ] Fix gridLayout pinning action ([#5406](https://github.com/brave/browser-laptop/pull/5406))
 - [ ] Pinned topSites not retaining its position ([#5321](https://github.com/brave/browser-laptop/issues/5321))
 - [x] Allow editing location on Add Bookmark in bookmark toolbar ([#5375](https://github.com/brave/browser-laptop/pull/5375))
 - [x] add Bookmark on context menu of toolbar should allow user to edit location ([#5374](https://github.com/brave/browser-laptop/issues/5374))
 - [x] about:newtab - favicons are not always shown ([#5310](https://github.com/brave/browser-laptop/issues/5310))
 - [x] delete folder cause stack overflow ([#5357](https://github.com/brave/browser-laptop/issues/5357))
 - [x] Created session helper for newTabState ([#5361](https://github.com/brave/browser-laptop/pull/5361))
 - [x] about:newtab - load images remotely ([#5396](https://github.com/brave/browser-laptop/issues/5396))
 - [x] Style for darker colored "Top Sites" entries is hard to see ([#5324](https://github.com/brave/browser-laptop/issues/5324))
 - [ ] Fix drag and drop for about:newtab (and other fixes) ([#5354](https://github.com/brave/browser-laptop/pull/5354))
 - [ ] about:newtabs - drag and drop not working for Top Sites items ([#5336](https://github.com/brave/browser-laptop/issues/5336))
 - [x] Add default lastAccessTime for history entries only ([#5349](https://github.com/brave/browser-laptop/pull/5349))
 - [x] Site listed under payments even though the visit count is less than 5(default visit count) ([#5200](https://github.com/brave/browser-laptop/issues/5200))
 - [x] have text regarding contribution dates match ([#5343](https://github.com/brave/browser-laptop/issues/5343))
 - [x] regression: opening a new tab should not show 'about:blank' ([#5334](https://github.com/brave/browser-laptop/issues/5334))
 - [ ] Add transition for new-tabbackground ([#5330](https://github.com/brave/browser-laptop/pull/5330))
 - [x] Add standalone file for CSS animations ([#5329](https://github.com/brave/browser-laptop/pull/5329))
 - [x] Add standalone file for CSS animations ([#5238](https://github.com/brave/browser-laptop/issues/5328))
 - [x] New Tab Design: Overview with subtasks (about:newtab) ([#3001](https://github.com/brave/browser-laptop/issues/3001))
 - [x] General Settings: "A new tab shows" setting documentation ([#2106](https://github.com/brave/browser-laptop/issues/2106))
 - [x] Brand new about:newtab page ([#5301](https://github.com/brave/browser-laptop/pull/5301))

**Comment by srirambv** [comment]
Issues logged #5637 #5633 #5632 #5631 
Rest all looks good on Ubuntu
