### ISSUE TITLE
0.12.9 Release Process Checklist

### ISSUE THREAD

**Issue by alexwykoff** [brave/browser-laptop#5644]
# Release Process Checklist

Feel free to copy this into an issue if you want to keep track of items per-milestone.
Be super sure that <version> is replaced with the version you wish to use.

### First-time Setup
1. [x] `git clone git@github.com:brave/vault-updater && cd vault-updater`
- [x] `npm install`
- [x] install the heroku toolbelt https://toolbelt.heroku.com/ , ask @mrose17 to add you
- [x] `git remote add heroku-staged https://git.heroku.com/brave-laptop-updates-pre.git`
- [x] *(optional) you can check logs : `heroku logs --tail --app brave-laptop-updates-pre`

### Every time thereafter
1. [x] `cd vault-updater`
- [x] `git checkout -b dev-<version>`
- [x] `npm run build`
- [x] `node tools/update.js --version=<version> --notes="<message approved by @aekeus>`. More details: `<link to release notes>`" `--channel=dev --overwrite`
- [x] `git add -u`
- [x] `git commit -m "<version>" -m "Auditors: @aekeus"`
- [x] `git push (alternatively: git push --set-upstream origin dev-<version>)`
- [x] Ask @bbondy to upload builds
- [x] `git push heroku-staged dev-<version>:master`

## Fastly
1. [x] Log into Fastly and purge the cache

## Test Staging
1. [x] Install a prior version of the app
2. [x] `BRAVE_UPDATE_HOST=https://laptop-updates-pre.brave.com open -a ./Brave.app`

## Merge Into Master
1. [x] `git checkout master`
2. [x] `git merge dev-<version>`
3. [x] `git push`

## Push To Production
1. [x] `git push heroku`

## Update Notes And Broadcast
1. [x] Wait for confirmtion that Windows live update works
2. [x] Edit the release notes title and uncheck the box to publish : https://github.com/brave/browser-laptop/releases
3. [x] Update dependency release notes as needed
4. [x] Notify #browser, #community, #general, #pr, #testers of the latest release with a link to the release notes
4. [x] Add a screenshot to the #pr channel for social broadcast

## Update crash server
1. [x] Modify BRAVE_VERSIONS env. var. on brave-stats to include brave/electron version (at most three versions) (`BRAVE_VERSIONS='1.3.1 1.3.2 1.3.3'`) We need to keep to a maximum of three versions currently.
2. [x] Modify `NODE_MODULES_CACHE` env. var. to force node_modules reload (`NODE_MODULES_CACHE=false`)
3. [x] Commit empty change for Heroku (`git commit -am 'install electron symbols for 1.3.3, remove old version' --allow-empty`)
4. [x] `git push heroku master`

## Update data files
1. [x] Push out data files to match the ones used in browser-laptop master.
