### ISSUE TITLE
Manual tests for OS X & Ubuntu 0.13.0 Preview 3 Batch 1

### ISSUE THREAD

**Issue by alexwykoff** [brave/browser-laptop#6140]
- [ ] Moved default zoom level from Advanced to General prefs ([#5734](https://github.com/brave/browser-laptop/pull/5734))
 - [ ] Made every place of buttons on the navigation bar clickable ([#5750](https://github.com/brave/browser-laptop/pull/5750))
 - [ ] borders and corners of each button on navbar are not clickable ([#5679](https://github.com/brave/browser-laptop/issues/5679))
 - [ ] add windows specific font CSS for URL text and tab text ([#5624](https://github.com/brave/browser-laptop/issues/5624))
 - [ ] Updates for URL bar and tab (Windows only) ([#5752](https://github.com/brave/browser-laptop/pull/5752))
 - [ ] about:newtab appears on the top sites list ([#5638](https://github.com/brave/browser-laptop/issues/5638))
 - [ ] Stop about pages from being shown on topSites ([#5728](https://github.com/brave/browser-laptop/pull/5728))
 - [ ] Findbar text selection ([#5744](https://github.com/brave/browser-laptop/issues/5744))
