### ISSUE TITLE
Manual tests for OS X 0.13.0 Preview 3 Batch 2

### ISSUE THREAD

**Issue by alexwykoff** [brave/browser-laptop#6166]
- [ ] Import browser data switches misaligned ([#5860](https://github.com/brave/browser-laptop/issues/5860))
 - [ ] contents of ledger recovery key text file should be set to the spec ([#4807](https://github.com/brave/browser-laptop/issues/4807))
 - [ ] Clean up formatting for bitcoin wallet backup ([#5862](https://github.com/brave/browser-laptop/pull/5862))
 - [ ] Favicons Only Behavior Now Leaves Blanks when there is no favicon ([#3648](https://github.com/brave/browser-laptop/issues/3648))
 - [ ] bookmark is invisible if favicon.ico is not found ([#2075](https://github.com/brave/browser-laptop/issues/2075))
 - [ ] Favicons need onerror handler (as seen in about:newtab) ([#5455](https://github.com/brave/browser-laptop/issues/5455))
 - [ ] Add default icon for url that has a broken file ([#5826](https://github.com/brave/browser-laptop/pull/5826))
 - [ ] Dropdown not shown completely when right click/long press on newtab button ([#5763](https://github.com/brave/browser-laptop/issues/5763))
 - [ ] Make context menu for newtab button always visible ([#5854](https://github.com/brave/browser-laptop/pull/5854))
 - [ ] Remove tab icons for about:newtab and about:blank ([#5773](https://github.com/brave/browser-laptop/pull/5845))
 - [ ] Newtab should not have an empty favicon ([#3207](https://github.com/brave/browser-laptop/issues/5776))
 - [ ] Font-size of select element inside braveryControlGroup was set to 13px ([#5773](https://github.com/brave/browser-laptop/pull/5773))
 - [ ] Font-size of select element inside braveryControlGroup should be set to 13px ([#5772](https://github.com/brave/browser-laptop/issues/5772))
 - [ ] SyntaxError: Unexpected token: name (WebTorrentRemoteClient) ([#5818](https://github.com/brave/browser-laptop/issues/5818))
 - [ ] webtorrent-remote 0.0.9: no ES6 ([#5847](https://github.com/brave/browser-laptop/pull/5847))
 - [ ] Open bookmarks in new foreground tabs ([#5831](https://github.com/brave/browser-laptop/pull/5831))
 - [ ] Middle click on a bookmark link opens tab in the background ([#3207](https://github.com/brave/browser-laptop/issues/3207))
 - [ ] Update localization files ([#5848](https://github.com/brave/browser-laptop/pull/5848))
 - [ ] Ad control for first time opened private tab doesn't work properly ([#5701](https://github.com/brave/browser-laptop/issues/5701))
 - [ ] Fix isResourceEnabled private tab overlay ([#5812](https://github.com/brave/browser-laptop/pull/5812))
 - [ ] Aligned brave wallet keys ([#5808](https://github.com/brave/browser-laptop/pull/5808))
 - [ ] keyContainer on Brave wallet backup dialog is not aligned ([#5807](https://github.com/brave/browser-laptop/issues/5807))
 - [ ] Cancel button on Brave wallet recovery dialog is too small ([#5804](https://github.com/brave/browser-laptop/issues/5804))
 - [ ] Removed "inlineButton" from Cancel button on Brave wallet recovery dialog ([#5805](https://github.com/brave/browser-laptop/pull/5805))
 - [ ] Magnifying glass icon shown for pdf documents opened in Brave ([#5774](https://github.com/brave/browser-laptop/issues/5774))
 - [ ] Test assertions are broken ([#5722](https://github.com/brave/browser-laptop/issues/5722))
 - [ ] Fix several unit tests (remove generator functions) ([#5823](https://github.com/brave/browser-laptop/pull/5823))
 - [ ] add semanticscholar.org as a new search engine ([#5656](https://github.com/brave/browser-laptop/issues/5656))
 - [ ] Buttons not aligned properly in payments advance settings in different language ([#5771](https://github.com/brave/browser-laptop/issues/5771))
 - [ ] Refactor buttons on about:preferences#payments and bookmark dialog ([#5705](https://github.com/brave/browser-laptop/pull/5705))
 - [ ] l10n of ledger advanced settings modal window ([#4786](https://github.com/brave/browser-laptop/issues/4786))
 - [ ] Add WebTorrent support ([#5342](https://github.com/brave/browser-laptop/pull/5342))
 - [ ] Addfunds ([#5797](https://github.com/brave/browser-laptop/pull/5797))
 - [ ] Add new "empty new tab" option in preferences (for what new tab does) ([#5690](https://github.com/brave/browser-laptop/pull/5690))
 - [ ] Create "Empty New Tab" option in General Settings ([#5682](https://github.com/brave/browser-laptop/issues/5682))
 - [ ] do not count a transaction-in-progress as a transaction... ([#5721](https://github.com/brave/browser-laptop/pull/5721))
 - [ ] Ledger notifications for adding funds should only be shown if brave payments is switched on  ([#5441](https://github.com/brave/browser-laptop/issues/5441))
 - [ ] Monthly ledger payment failed ([#5371](https://github.com/brave/browser-laptop/issues/5371))
 - [ ] Ledger does not track windows created before the wallet ([#4274](https://github.com/brave/browser-laptop/issues/4274))
 - [ ] Stop blue line from appearing above page ([#5661](https://github.com/brave/browser-laptop/issues/5661))
 - [ ] Add user-friendly title for about:blank ([#5782](https://github.com/brave/browser-laptop/pull/5782))
 - [ ] about:blank shows chrome-extension in navigation button history ([#5764](https://github.com/brave/browser-laptop/issues/5764))
 - [ ] l10n of ledger advanced settings modal window ([#5718](https://github.com/brave/browser-laptop/pull/5718))
 - [ ] Create default topSites for new tab page ([#5623](https://github.com/brave/browser-laptop/pull/5623))
 - [ ] newtab - Have default top sites available ([#5594](https://github.com/brave/browser-laptop/issues/5594))
 - [ ] Animate fadeIn of titlebar buttons ([#5667](https://github.com/brave/browser-laptop/pull/5667))
 - [ ] transition of reload button ([#5664](https://github.com/brave/browser-laptop/issues/5664))
 - [ ] Hover background of bookmark bar items is hard to see ([#5665](https://github.com/brave/browser-laptop/issues/5665))
 - [ ] Change hover of bookmark bar items ([#5668](https://github.com/brave/browser-laptop/pull/5668))
 - [ ] move default zoom level from Advanced to General ([#5697](https://github.com/brave/browser-laptop/issues/5697))
