### ISSUE TITLE
Add new "Auto-suggest" sites preference (payments tab)

### ISSUE THREAD

**Issue by mrose17** [brave/browser-laptop#6261]
## Goals

- Give users a toggle for auto-suggest sites
  - Only affects sites going forward (existing site settings are not changed)
  - When true, behavior matches current behavior 
  - When false, it will exclude by default

- If "auto suggest sites" is disabled, let's add a little BTC icon to the right of the address bar allowing users to click to say "include this publisher for payments"

## Additional info
A "permanently hide" button introduced with https://github.com/brave/browser-laptop/pull/6101
(this is approved but not merged- you can cherry pick the commits into the `exclude-by-default` branch in the meantime)

## Tasks 

- [x] only show included sites (preferences). This is something we can test without adding any new code (not counting the code for the button). Users can already include/exclude  
- [x] add a new option for auto suggest sites
- [x] add a new control in the URL bar control; only shown if auto suggest is false AND permanently hide is false
- [x] if brave payments is NOT enabled and the button is clicked, enable it :slightly_smiling_face:
- [x] control should light up orange if publisher included, gray if not (and be clickable to toggle)

## Default values for the two new settings

- Only show included sites - *default to false*
- Auto suggest sites - *default to true*

## Screenshots (mockup)
 
![image](https://cloud.githubusercontent.com/assets/13509546/21334362/b5f8ea48-c60b-11e6-8943-616064a5c3cf.png)

same UI showing mockup for flipped switches:
![image](https://cloud.githubusercontent.com/assets/13509546/21334386/e3b74e70-c60b-11e6-8bcc-5fb6a5749afd.png)

New URL bar button provides a convenient "remote control" for toggling site contributions.

site contributions off: (exclude state)
![image](https://cloud.githubusercontent.com/assets/13509546/21334421/46a2d87e-c60c-11e6-9acd-c37c90447a43.png)

site contributions on: (include state)
![image](https://cloud.githubusercontent.com/assets/13509546/21334426/5149db92-c60c-11e6-8123-1f0cce8c0184.png)

**Comment by mrose17** [comment]
![pasted image at 2016_12_16 06_40 pm](https://cloud.githubusercontent.com/assets/400552/21284039/4bb22d00-c3c4-11e6-99ab-8b8c9f7fa76a.png)

**Comment by mrose17** [comment]
![pasted image at 2016_12_19 02_24 pm 1](https://cloud.githubusercontent.com/assets/400552/21332357/a2faad6e-c5fc-11e6-9e8a-6150f191dbdc.png)
![pasted image at 2016_12_19 02_24 pm 2](https://cloud.githubusercontent.com/assets/400552/21332358/a2fb5ea8-c5fc-11e6-98fb-4eff3fa2417b.png)
![pasted image at 2016_12_19 02_24 pm](https://cloud.githubusercontent.com/assets/400552/21332359/a2fb9cd8-c5fc-11e6-8aff-3cd9bd05eaeb.png)
![pasted image at 2016_12_19 02_25 pm](https://cloud.githubusercontent.com/assets/400552/21332360/a2fce14c-c5fc-11e6-958a-5c1ff6940df6.png)

**Comment by luixxiul** [comment]
I'd like to implement the button and the switches on the UI if it is ok

**Comment by cezaraugusto** [comment]
@luixxiul appreciate your help. We'll be using `exclude-by-default` branch for those changes, thanks.

**Comment by bsclifton** [comment]
Fixed with https://github.com/brave/browser-laptop/pull/6633 which was merged into branch `0.13.1-branch`.
