### ISSUE TITLE
Extension: Pinterest Save Button

### ISSUE THREAD

**Issue by jonathansampson** [brave/browser-laptop#6366]
Extension: [Pinterest Save Button](https://chrome.google.com/webstore/detail/pinterest-save-button/gpdjojdkbbmdfjfahjcgigfpmkopogic)
Background Page: _Coming soon_

## Needed APIs:

**chrome.browserAction**

- [x] #8329 chrome.browserAction.onClicked ([docs](https://developer.chrome.com/extensions/browserAction#event-onClicked))

**chrome.contextMenus**

- [ ] #8331 chrome.contextMenus.create ([docs](https://developer.chrome.com/extensions/contextMenus#method-create))
- [x] #8814 chrome.contextMenus.onClicked ([docs](https://developer.chrome.com/extensions/contextMenus#event-onClicked))
- [x] #8815 chrome.contextMenus.removeAll ([docs](https://developer.chrome.com/extensions/contextMenus#method-removeAll))

**chrome.cookies**
- [ ] #6262 chrome.cookies.getAll
- [ ] #8389 chrome.cookies.set ([docs](https://developer.chrome.com/extensions/cookies#method-set))

**chrome.extension**

- [x] #8688 chrome.extension.getURL

**chrome.i18n**

- [ ] #4755 chrome.i18n.getMessage

**chrome.notifications**

- [ ] #8795 chrome.notifications.clear
- [ ] #8796 chrome.notifications.create
- [ ] #8816 chrome.notifications.onButtonClicked
- [ ] #8817 chrome.notifications.onClicked

**chrome.runtime**

- [ ] #8683 chrome.runtime.getManifest
- [ ] #8791 chrome.runtime.onMessage
- [ ] #8802 chrome.runtime.sendMessage
- [x] #8818 chrome.runtime.setUninstallURL

**chrome.storage**

- [ ] #8804 chrome.storage.local.get
- [ ] #8804 chrome.storage.local.set

**chrome.tabs**

- [ ] #8807 chrome.tabs.captureVisibleTab
- [ ] #8819 chrome.tabs.onActivated
- [ ] #8820 chrome.tabs.onCreated
- [x] #8811 chrome.tabs.query
- [ ] #8812 chrome.tabs.sendMessage

**Comment by kentbrew** [comment]
Happy to help with this; I'm the developer of the Pinterest extension for Chrome.

**Comment by jonathansampson** [comment]
@kentbrew Answered here: https://twitter.com/BraveSampson/status/854509522378993665 🙂

**Comment by jonathansampson** [comment]
@kentbrew Perhaps you can help me with something: I see that Pinterest uses `chrome.notifications`, but I'm not able to actually trigger a notification in Brave or Chrome. Does this portion of the extension work as expected for you and your team?

**Comment by jonathansampson** [comment]
@kentbrew Friendly-bump on https://github.com/brave/browser-laptop/issues/6366#issuecomment-300866586 :) Any input from you/your team would be greatly appreciated.

**Comment by bbondy** [comment]
@sampson is going to split this into an MVP tracking issue and an all issues tracking issue.  The former on the milestone and not the latter.

**Comment by bsclifton** [comment]
When we move to [brave-core](https://github.com/brave/brave-browser) (which is just around the corner), we should have full support for extensions. Stay tuned 😄
