### ISSUE TITLE
Consider dropping node support

### ISSUE THREAD

**Issue by bbondy** [brave/browser-laptop#7073]
We currently only allow node to work in the main process. 
But the amount of things using node is not very high.

- [ ] Adblock node native module (could be moved into muon)
- [ ] Tracking protection node native module (could be moved into muon)
- [x] Spell check (could use chromium code more)
- [ ] WebTorrent? (Not sure how much work that would be)
 ...

**Comment by amitkumarj441** [comment]
@bbondy If I'm not wrong, Are you talking about dropping BTC node? If this is the case, then as far as I know, their could be two away :
- Verifying/Accessing BTC transactions through 3rd party like Blockr.io , Blockchain.info etc.
- bitcoind

Otherwise, running full/lightweight BTC node needs many things like processing transactions in batch(slow in Brave)

**Comment by Liunkae** [comment]
Brave now uses the Chromium spell checker (#9880).

**Comment by bsclifton** [comment]
@Liunkae thanks for finding/updating this 😄  I know @bbondy has thought about merging the adblock code into Muon
