### ISSUE TITLE
0.14.0 Exclusion List

### ISSUE THREAD

**Issue by alexwykoff** [brave/browser-laptop#7709]
Preview 1: 
 - [ ] Manual Test for OSX 0.14.0. ([#7707](https://github.com/brave/browser-laptop/issues/7707))
https://github.com/brave/browser-laptop/issues/7707
 - [ ] Contribution statement should stay open. ([#7698](https://github.com/brave/browser-laptop/issues/7698))
https://github.com/brave/browser-laptop/issues/7698
 - [ ] Payments UI - show grayed out icon when no payment history. ([#7693](https://github.com/brave/browser-laptop/issues/7693))
https://github.com/brave/browser-laptop/issues/7693
 - [ ] Adding custom bookmark name text box not clearing when deleted. ([#7691](https://github.com/brave/browser-laptop/issues/7691))
https://github.com/brave/browser-laptop/issues/7691
 - [ ] Remove about/less/flash.less. ([#7681](https://github.com/brave/browser-laptop/issues/7681))
https://github.com/brave/browser-laptop/issues/7681
 - [ ] Sound icon + close button takes up too much space when tabs are small. ([#7665](https://github.com/brave/browser-laptop/issues/7665))
https://github.com/brave/browser-laptop/issues/7665
 - [ ] Fresh Install of Brave Advertises Brave Properties. ([#7655](https://github.com/brave/browser-laptop/issues/7655))
https://github.com/brave/browser-laptop/issues/7655
 - [ ] If flash is enabled, 'shields down' should allow the site to see that flash is installed. ([#7549](https://github.com/brave/browser-laptop/issues/7549))
https://github.com/brave/browser-laptop/issues/7549
 - [ ] Header bar and tab styling.. ([#7546](https://github.com/brave/browser-laptop/issues/7546))
https://github.com/brave/browser-laptop/issues/7546
 - [ ] Make tab switching lightning fast. ([#7540](https://github.com/brave/browser-laptop/issues/7540))
https://github.com/brave/browser-laptop/issues/7540
 - [ ] When typing quickly in urlbar, keys are sometimes dropped.. ([#7538](https://github.com/brave/browser-laptop/issues/7538))
https://github.com/brave/browser-laptop/issues/7538
 - [ ] Hide "check for updates" on Linux. ([#7537](https://github.com/brave/browser-laptop/issues/7537))
https://github.com/brave/browser-laptop/issues/7537
 - [ ] Hide 1% by default. ([#7536](https://github.com/brave/browser-laptop/issues/7536))
https://github.com/brave/browser-laptop/issues/7536
 - [ ] Add Vimium support. ([#7527](https://github.com/brave/browser-laptop/issues/7527))
https://github.com/brave/browser-laptop/issues/7527
 - [ ] Torrent viewer should maintain the folder structure in the torrent. ([#7494](https://github.com/brave/browser-laptop/issues/7494))
https://github.com/brave/browser-laptop/issues/7494
 - [ ] Provide a save all files button in torrent viewer. ([#7493](https://github.com/brave/browser-laptop/issues/7493))
https://github.com/brave/browser-laptop/issues/7493
 - [ ] Keyboard Shortcuts Not Working. ([#7491](https://github.com/brave/browser-laptop/issues/7491))
https://github.com/brave/browser-laptop/issues/7491
 - [ ] Fix ellipses in string files. ([#7470](https://github.com/brave/browser-laptop/issues/7470))
https://github.com/brave/browser-laptop/issues/7470
 - [ ] Switch to uglify-js-harmony. ([#7461](https://github.com/brave/browser-laptop/issues/7461))
https://github.com/brave/browser-laptop/issues/7461
 - [ ] Support chrome://newtab/ as alias to about:newtab. ([#7457](https://github.com/brave/browser-laptop/issues/7457))
https://github.com/brave/browser-laptop/issues/7457
 - [ ] Incorrect state found in tab.pinned. ([#7440](https://github.com/brave/browser-laptop/issues/7440))
https://github.com/brave/browser-laptop/issues/7440
 - [ ] Can't view "Contribution Statement". ([#7416](https://github.com/brave/browser-laptop/issues/7416))
https://github.com/brave/browser-laptop/issues/7416
 - [ ] Split and refactor BitcoinDashboard. ([#7380](https://github.com/brave/browser-laptop/issues/7380))
https://github.com/brave/browser-laptop/issues/7380
 - [ ] Split and refactor ledgerTable component. ([#7379](https://github.com/brave/browser-laptop/issues/7379))
https://github.com/brave/browser-laptop/issues/7379
 - [ ] Add session-tab icon numbers. ([#7367](https://github.com/brave/browser-laptop/issues/7367))
https://github.com/brave/browser-laptop/issues/7367
 - [ ] Torrent name is missing once download is started. ([#7362](https://github.com/brave/browser-laptop/issues/7362))
https://github.com/brave/browser-laptop/issues/7362
 - [ ] When the browser dives into an anonize2 crypto operation, it is unresponsive for a second or so. ([#7344](https://github.com/brave/browser-laptop/issues/7344))
https://github.com/brave/browser-laptop/issues/7344
 - [ ] Drag & Drop for Images and Files Broken (causes screen to go white). ([#7266](https://github.com/brave/browser-laptop/issues/7266))
https://github.com/brave/browser-laptop/issues/7266
 - [ ] Torrent Viewer CSP rule blocks <iframe> content. ([#7243](https://github.com/brave/browser-laptop/issues/7243))
https://github.com/brave/browser-laptop/issues/7243
 - [ ] Remove unused braveSoftware string. ([#7209](https://github.com/brave/browser-laptop/issues/7209))
https://github.com/brave/browser-laptop/issues/7209
 - [ ] Sites added on add funds toggle lack instant ledger response and favicon. ([#7111](https://github.com/brave/browser-laptop/issues/7111))
https://github.com/brave/browser-laptop/issues/7111
 - [ ] Fix disabled ledger / payments panel tests. ([#6911](https://github.com/brave/browser-laptop/issues/6911))
https://github.com/brave/browser-laptop/issues/6911
 - [ ] Automated test failures: Payments Panel. ([#6890](https://github.com/brave/browser-laptop/issues/6890))
https://github.com/brave/browser-laptop/issues/6890
 - [ ] Brave fails tests on simple-adblock.com. ([#6788](https://github.com/brave/browser-laptop/issues/6788))
https://github.com/brave/browser-laptop/issues/6788
 - [ ] SFGate.com - custom ad calls evading blocking on tablets & desktop (siteHack-level). ([#6635](https://github.com/brave/browser-laptop/issues/6635))
https://github.com/brave/browser-laptop/issues/6635
 - [ ] AdBlocker-Blocker on v3.co.uk. ([#6393](https://github.com/brave/browser-laptop/issues/6393))
https://github.com/brave/browser-laptop/issues/6393
 - [ ] Govexec.com, defenseone.com - full page interstitial on first visit. ([#6352](https://github.com/brave/browser-laptop/issues/6352))
https://github.com/brave/browser-laptop/issues/6352
 - [ ] Tracking: Disabled tests. ([#5389](https://github.com/brave/browser-laptop/issues/5389))
https://github.com/brave/browser-laptop/issues/5389
 - [ ] Flash UX improvement tracking issue. ([#4789](https://github.com/brave/browser-laptop/issues/4789))
https://github.com/brave/browser-laptop/issues/4789
 - [ ] Closing a site immediately after loading shows entry in Brave payment list. ([#4156](https://github.com/brave/browser-laptop/issues/4156))
https://github.com/brave/browser-laptop/issues/4156
 - [ ] UI suggestion: visual distinction between session tabs. ([#3083](https://github.com/brave/browser-laptop/issues/3083))
https://github.com/brave/browser-laptop/issues/3083
 - [ ] General Settings: "Save my downloads here" setting. ([#2110](https://github.com/brave/browser-laptop/issues/2110))
https://github.com/brave/browser-laptop/issues/2110
 - [ ] Cookie option in bravery panel missing option "Block All". ([#1987](https://github.com/brave/browser-laptop/issues/1987))
https://github.com/brave/browser-laptop/issues/1987
 - [ ] Linux update mechanism never finishes. ([#401](https://github.com/brave/browser-laptop/issues/401))
https://github.com/brave/browser-laptop/issues/401

**Comment by luixxiul** [comment]
some seem to be included even if they are not labelled with neither `release-notes/exclude` nor `QA/no-qa-needed`.

#401 and https://github.com/brave/browser-laptop/issues/1987 should be included for example. In fact #1987 *must* be included.

**Comment by alexwykoff** [comment]
@luixxiul that's correct. the selection criterion look for missing labels as well. 

here is the updated list. generated this morning:

Exclusion List:
 - [ ] Follow up of #7547. ([#7739](https://github.com/brave/browser-laptop/issues/7739))
https://github.com/brave/browser-laptop/issues/7739
 - [ ] Automated test failures on findBar. ([#7731](https://github.com/brave/browser-laptop/issues/7731))
https://github.com/brave/browser-laptop/issues/7731
 - [ ] Manual tests for Linux 0.14.0 Preview1. ([#7713](https://github.com/brave/browser-laptop/issues/7713))
https://github.com/brave/browser-laptop/issues/7713
 - [ ] Manual tests for Windows x64 0.14.0 Preview1. ([#7712](https://github.com/brave/browser-laptop/issues/7712))
https://github.com/brave/browser-laptop/issues/7712
 - [ ] Manual checklist for Win ia-32 0.14.0 Preview 1. ([#7711](https://github.com/brave/browser-laptop/issues/7711))
https://github.com/brave/browser-laptop/issues/7711
 - [ ] Manual checklist for OS X 0.14.0 Preview1. ([#7710](https://github.com/brave/browser-laptop/issues/7710))
https://github.com/brave/browser-laptop/issues/7710
 - [ ] 0.14.0 Exclusion List. ([#7709](https://github.com/brave/browser-laptop/issues/7709))
https://github.com/brave/browser-laptop/issues/7709
 - [ ] Create 0.14.0 Release Notes. ([#7708](https://github.com/brave/browser-laptop/issues/7708))
https://github.com/brave/browser-laptop/issues/7708
 - [ ] Manual Test for OSX 0.14.0. ([#7707](https://github.com/brave/browser-laptop/issues/7707))
https://github.com/brave/browser-laptop/issues/7707
 - [ ] Adding custom bookmark name text box not clearing when deleted. ([#7691](https://github.com/brave/browser-laptop/issues/7691))
https://github.com/brave/browser-laptop/issues/7691
 - [ ] Remove about/less/flash.less. ([#7681](https://github.com/brave/browser-laptop/issues/7681))
https://github.com/brave/browser-laptop/issues/7681
 - [ ] Header bar and tab styling.. ([#7546](https://github.com/brave/browser-laptop/issues/7546))
https://github.com/brave/browser-laptop/issues/7546
 - [ ] Add Vimium support. ([#7527](https://github.com/brave/browser-laptop/issues/7527))
https://github.com/brave/browser-laptop/issues/7527
 - [ ] Keyboard Shortcuts Not Working. ([#7491](https://github.com/brave/browser-laptop/issues/7491))
https://github.com/brave/browser-laptop/issues/7491
 - [ ] Fix ellipses in string files. ([#7470](https://github.com/brave/browser-laptop/issues/7470))
https://github.com/brave/browser-laptop/issues/7470
 - [ ] Switch to uglify-js-harmony. ([#7461](https://github.com/brave/browser-laptop/issues/7461))
https://github.com/brave/browser-laptop/issues/7461
 - [ ] Can't view "Contribution Statement". ([#7416](https://github.com/brave/browser-laptop/issues/7416))
https://github.com/brave/browser-laptop/issues/7416
 - [ ] Split and refactor BitcoinDashboard. ([#7380](https://github.com/brave/browser-laptop/issues/7380))
https://github.com/brave/browser-laptop/issues/7380
 - [ ] Split and refactor ledgerTable component. ([#7379](https://github.com/brave/browser-laptop/issues/7379))
https://github.com/brave/browser-laptop/issues/7379
 - [ ] Add session-tab icon numbers. ([#7367](https://github.com/brave/browser-laptop/issues/7367))
https://github.com/brave/browser-laptop/issues/7367
 - [ ] Drag & Drop for Images and Files Broken (causes screen to go white). ([#7266](https://github.com/brave/browser-laptop/issues/7266))
https://github.com/brave/browser-laptop/issues/7266
 - [ ] Remove unused braveSoftware string. ([#7209](https://github.com/brave/browser-laptop/issues/7209))
https://github.com/brave/browser-laptop/issues/7209
 - [ ] Automated test failure on tab. ([#6981](https://github.com/brave/browser-laptop/issues/6981))
https://github.com/brave/browser-laptop/issues/6981
 - [ ] Automated test failure on urlBarSuggestions. ([#6980](https://github.com/brave/browser-laptop/issues/6980))
https://github.com/brave/browser-laptop/issues/6980
 - [ ] URL address bar adds deleted text back immediately, have to delete twice. ([#6956](https://github.com/brave/browser-laptop/issues/6956))
https://github.com/brave/browser-laptop/issues/6956
 - [ ] Fix disabled ledger / payments panel tests. ([#6911](https://github.com/brave/browser-laptop/issues/6911))
https://github.com/brave/browser-laptop/issues/6911
 - [ ] Automated test failures: Payments Panel. ([#6890](https://github.com/brave/browser-laptop/issues/6890))
https://github.com/brave/browser-laptop/issues/6890
 - [ ] Automated test failures on pinnedTabs. ([#6668](https://github.com/brave/browser-laptop/issues/6668))
https://github.com/brave/browser-laptop/issues/6668
 - [ ] Automated test failures on navigationBar. ([#6666](https://github.com/brave/browser-laptop/issues/6666))
https://github.com/brave/browser-laptop/issues/6666
 - [ ] Automated test failures on sessionStore. ([#6664](https://github.com/brave/browser-laptop/issues/6664))
https://github.com/brave/browser-laptop/issues/6664
 - [ ] SFGate.com - custom ad calls evading blocking on tablets & desktop (siteHack-level). ([#6635](https://github.com/brave/browser-laptop/issues/6635))
https://github.com/brave/browser-laptop/issues/6635
 - [ ] Tracking: Disabled tests. ([#5389](https://github.com/brave/browser-laptop/issues/5389))
https://github.com/brave/browser-laptop/issues/5389
 - [ ] Fix failing automated tests. ([#4329](https://github.com/brave/browser-laptop/issues/4329))
https://github.com/brave/browser-laptop/issues/4329
 - [ ] Closing a site immediately after loading shows entry in Brave payment list. ([#4156](https://github.com/brave/browser-laptop/issues/4156))
https://github.com/brave/browser-laptop/issues/4156
 - [ ] UI suggestion: visual distinction between session tabs. ([#3083](https://github.com/brave/browser-laptop/issues/3083))
https://github.com/brave/browser-laptop/issues/3083
 - [ ] Linux update mechanism never finishes. ([#401](https://github.com/brave/browser-laptop/issues/401))
https://github.com/brave/browser-laptop/issues/401

**Comment by alexwykoff** [comment]
Updated exclusion list, generated this morning (0.14.0 Preview 4)
 - [ ] Make tab props more idiomatic. ([#7798](https://github.com/brave/browser-laptop/issues/7798))
https://github.com/brave/browser-laptop/issues/7798
 - [ ] Browser Action Path May Not Exist. ([#7775](https://github.com/brave/browser-laptop/issues/7775))
https://github.com/brave/browser-laptop/issues/7775
 - [ ] 1password not working in 0.14.0 Preview3. ([#7769](https://github.com/brave/browser-laptop/issues/7769))
https://github.com/brave/browser-laptop/issues/7769
 - [ ] Manual tests for OS X 0.14.0 (general regression pass). ([#7766](https://github.com/brave/browser-laptop/issues/7766))
https://github.com/brave/browser-laptop/issues/7766
 - [ ] Autofill session/private tab tests are failing. ([#7763](https://github.com/brave/browser-laptop/issues/7763))
https://github.com/brave/browser-laptop/issues/7763
 - [ ] Manual test run for Linux 0.14.0 Preview3. ([#7760](https://github.com/brave/browser-laptop/issues/7760))
https://github.com/brave/browser-laptop/issues/7760
 - [ ] Manual test run for Windows x64 0.14.0 Preview3. ([#7759](https://github.com/brave/browser-laptop/issues/7759))
https://github.com/brave/browser-laptop/issues/7759
 - [ ] Manual test run for Windows ia-32 0.14.0 Preview3. ([#7758](https://github.com/brave/browser-laptop/issues/7758))
https://github.com/brave/browser-laptop/issues/7758
 - [ ] Manual test run for OS X 0.14.0 Preview 3. ([#7757](https://github.com/brave/browser-laptop/issues/7757))
https://github.com/brave/browser-laptop/issues/7757
 - [ ] Automated test failures on findBar. ([#7731](https://github.com/brave/browser-laptop/issues/7731))
https://github.com/brave/browser-laptop/issues/7731
 - [ ] Manual tests for Linux 0.14.0 Preview1. ([#7713](https://github.com/brave/browser-laptop/issues/7713))
https://github.com/brave/browser-laptop/issues/7713
 - [ ] Manual tests for Windows x64 0.14.0 Preview1. ([#7712](https://github.com/brave/browser-laptop/issues/7712))
https://github.com/brave/browser-laptop/issues/7712
 - [ ] Manual checklist for Win ia-32 0.14.0 Preview 1. ([#7711](https://github.com/brave/browser-laptop/issues/7711))
https://github.com/brave/browser-laptop/issues/7711
 - [ ] Manual checklist for OS X 0.14.0 Preview1. ([#7710](https://github.com/brave/browser-laptop/issues/7710))
https://github.com/brave/browser-laptop/issues/7710
 - [ ] 0.14.0 Exclusion List. ([#7709](https://github.com/brave/browser-laptop/issues/7709))
https://github.com/brave/browser-laptop/issues/7709
 - [ ] Create 0.14.0 Release Notes. ([#7708](https://github.com/brave/browser-laptop/issues/7708))
https://github.com/brave/browser-laptop/issues/7708
 - [ ] Manual Test for OSX 0.14.0. ([#7707](https://github.com/brave/browser-laptop/issues/7707))
https://github.com/brave/browser-laptop/issues/7707
 - [ ] Adding custom bookmark name text box not clearing when deleted. ([#7691](https://github.com/brave/browser-laptop/issues/7691))
https://github.com/brave/browser-laptop/issues/7691
 - [ ] Remove about/less/flash.less. ([#7681](https://github.com/brave/browser-laptop/issues/7681))
https://github.com/brave/browser-laptop/issues/7681
 - [ ] Header bar and tab styling.. ([#7546](https://github.com/brave/browser-laptop/issues/7546))
https://github.com/brave/browser-laptop/issues/7546
 - [ ] Add Vimium support. ([#7527](https://github.com/brave/browser-laptop/issues/7527))
https://github.com/brave/browser-laptop/issues/7527
 - [ ] Keyboard Shortcuts Not Working. ([#7491](https://github.com/brave/browser-laptop/issues/7491))
https://github.com/brave/browser-laptop/issues/7491
 - [ ] Fix ellipses in string files. ([#7470](https://github.com/brave/browser-laptop/issues/7470))
https://github.com/brave/browser-laptop/issues/7470
 - [ ] Switch to uglify-js-harmony. ([#7461](https://github.com/brave/browser-laptop/issues/7461))
https://github.com/brave/browser-laptop/issues/7461
 - [ ] Can't view "Contribution Statement". ([#7416](https://github.com/brave/browser-laptop/issues/7416))
https://github.com/brave/browser-laptop/issues/7416
 - [ ] Split and refactor BitcoinDashboard. ([#7380](https://github.com/brave/browser-laptop/issues/7380))
https://github.com/brave/browser-laptop/issues/7380
 - [ ] Split and refactor ledgerTable component. ([#7379](https://github.com/brave/browser-laptop/issues/7379))
https://github.com/brave/browser-laptop/issues/7379
 - [ ] Add session-tab icon numbers. ([#7367](https://github.com/brave/browser-laptop/issues/7367))
https://github.com/brave/browser-laptop/issues/7367
 - [ ] Remove unused braveSoftware string. ([#7209](https://github.com/brave/browser-laptop/issues/7209))
https://github.com/brave/browser-laptop/issues/7209
 - [ ] Automated test failure on tab. ([#6981](https://github.com/brave/browser-laptop/issues/6981))
https://github.com/brave/browser-laptop/issues/6981
 - [ ] Automated test failure on urlBarSuggestions. ([#6980](https://github.com/brave/browser-laptop/issues/6980))
https://github.com/brave/browser-laptop/issues/6980
 - [ ] URL address bar adds deleted text back immediately, have to delete twice. ([#6956](https://github.com/brave/browser-laptop/issues/6956))
https://github.com/brave/browser-laptop/issues/6956
 - [ ] Fix disabled ledger / payments panel tests. ([#6911](https://github.com/brave/browser-laptop/issues/6911))
https://github.com/brave/browser-laptop/issues/6911
 - [ ] Automated test failures on pinnedTabs. ([#6668](https://github.com/brave/browser-laptop/issues/6668))
https://github.com/brave/browser-laptop/issues/6668
 - [ ] Automated test failures on navigationBar. ([#6666](https://github.com/brave/browser-laptop/issues/6666))
https://github.com/brave/browser-laptop/issues/6666
 - [ ] Automated test failures on sessionStore. ([#6664](https://github.com/brave/browser-laptop/issues/6664))
https://github.com/brave/browser-laptop/issues/6664
 - [ ] SFGate.com - custom ad calls evading blocking on tablets & desktop (siteHack-level). ([#6635](https://github.com/brave/browser-laptop/issues/6635))
https://github.com/brave/browser-laptop/issues/6635
 - [ ] Tracking: Disabled tests. ([#5389](https://github.com/brave/browser-laptop/issues/5389))
https://github.com/brave/browser-laptop/issues/5389
 - [ ] Fix failing automated tests. ([#4329](https://github.com/brave/browser-laptop/issues/4329))
https://github.com/brave/browser-laptop/issues/4329
 - [ ] Closing a site immediately after loading shows entry in Brave payment list. ([#4156](https://github.com/brave/browser-laptop/issues/4156))
https://github.com/brave/browser-laptop/issues/4156
 - [ ] UI suggestion: visual distinction between session tabs. ([#3083](https://github.com/brave/browser-laptop/issues/3083))
https://github.com/brave/browser-laptop/issues/3083
 - [ ] Linux update mechanism never finishes. ([#401](https://github.com/brave/browser-laptop/issues/401))
https://github.com/brave/browser-laptop/issues/401

**Comment by srirambv** [comment]
Autofill suggestion is not retained when clicked on the input field. (#7768) -  merged after preview 4
Disable close button on tabs if tab size is too small. (#5431) - not yet merged issue still open

Waiting on Muon update
Vimium: Icon not displayed near address bar. (#6193)
Feature Request: Bitwarden Password Manager. (#4776) 
'View Certificate' non-functional. (#2611)

**Comment by alexwykoff** [comment]
Updated Exclusion list for 0.14.0 RC1

 - [ ] Hide bitwarden support. ([#7919](https://github.com/brave/browser-laptop/issues/7919))
https://github.com/brave/browser-laptop/issues/7919
 - [ ] Reduce installer size. ([#7896](https://github.com/brave/browser-laptop/issues/7896))
https://github.com/brave/browser-laptop/issues/7896
 - [ ] `Digest method not supported` when making contribution. ([#7875](https://github.com/brave/browser-laptop/issues/7875))
https://github.com/brave/browser-laptop/issues/7875
 - [ ] Tests in test/lib are not being run in travis. ([#7844](https://github.com/brave/browser-laptop/issues/7844))
https://github.com/brave/browser-laptop/issues/7844
 - [ ] Automated test failures on sessionStore. ([#7839](https://github.com/brave/browser-laptop/issues/7839))
https://github.com/brave/browser-laptop/issues/7839
 - [ ] Automated test failures on urlBarSuggestions. ([#7837](https://github.com/brave/browser-laptop/issues/7837))
https://github.com/brave/browser-laptop/issues/7837
 - [ ] Automated test failures on Browsing Panel. ([#7833](https://github.com/brave/browser-laptop/issues/7833))
https://github.com/brave/browser-laptop/issues/7833
 - [ ] Linting should run once per travis build instead of every job. ([#7819](https://github.com/brave/browser-laptop/issues/7819))
https://github.com/brave/browser-laptop/issues/7819
 - [ ] YouTube.com has big empty div placeholders for ads. ([#7818](https://github.com/brave/browser-laptop/issues/7818))
https://github.com/brave/browser-laptop/issues/7818
 - [ ] Manual tests for OS X 0.14.0 Preview 4 . ([#7811](https://github.com/brave/browser-laptop/issues/7811))
https://github.com/brave/browser-laptop/issues/7811
 - [ ] Manual tests for Windows ia-32 0.14.0 Preview 4. ([#7810](https://github.com/brave/browser-laptop/issues/7810))
https://github.com/brave/browser-laptop/issues/7810
 - [ ] Manual tests for Windows x64 0.14.0 Preview 4. ([#7809](https://github.com/brave/browser-laptop/issues/7809))
https://github.com/brave/browser-laptop/issues/7809
 - [ ] Manual tests for Linux 0.14.0 Preview 4. ([#7808](https://github.com/brave/browser-laptop/issues/7808))
https://github.com/brave/browser-laptop/issues/7808
 - [ ] Make tab props more idiomatic. ([#7798](https://github.com/brave/browser-laptop/issues/7798))
https://github.com/brave/browser-laptop/issues/7798
 - [ ] Update to Standard@9.0.0 - rule "no-mixed-operators". ([#7784](https://github.com/brave/browser-laptop/issues/7784))
https://github.com/brave/browser-laptop/issues/7784
 - [ ] Browser Action Path May Not Exist. ([#7775](https://github.com/brave/browser-laptop/issues/7775))
https://github.com/brave/browser-laptop/issues/7775
 - [ ] Manual tests for OS X 0.14.0 (general regression pass). ([#7766](https://github.com/brave/browser-laptop/issues/7766))
https://github.com/brave/browser-laptop/issues/7766
 - [ ] Manual test run for Linux 0.14.0 Preview3. ([#7760](https://github.com/brave/browser-laptop/issues/7760))
https://github.com/brave/browser-laptop/issues/7760
 - [ ] Manual test run for Windows x64 0.14.0 Preview3. ([#7759](https://github.com/brave/browser-laptop/issues/7759))
https://github.com/brave/browser-laptop/issues/7759
 - [ ] Manual test run for Windows ia-32 0.14.0 Preview3. ([#7758](https://github.com/brave/browser-laptop/issues/7758))
https://github.com/brave/browser-laptop/issues/7758
 - [ ] Manual test run for OS X 0.14.0 Preview 3. ([#7757](https://github.com/brave/browser-laptop/issues/7757))
https://github.com/brave/browser-laptop/issues/7757
 - [ ] Automated test failures on findBar. ([#7731](https://github.com/brave/browser-laptop/issues/7731))
https://github.com/brave/browser-laptop/issues/7731
 - [ ] Manual tests for Linux 0.14.0 Preview1. ([#7713](https://github.com/brave/browser-laptop/issues/7713))
https://github.com/brave/browser-laptop/issues/7713
 - [ ] Manual tests for Windows x64 0.14.0 Preview1. ([#7712](https://github.com/brave/browser-laptop/issues/7712))
https://github.com/brave/browser-laptop/issues/7712
 - [ ] Manual checklist for Win ia-32 0.14.0 Preview 1. ([#7711](https://github.com/brave/browser-laptop/issues/7711))
https://github.com/brave/browser-laptop/issues/7711
 - [ ] Manual checklist for OS X 0.14.0 Preview1. ([#7710](https://github.com/brave/browser-laptop/issues/7710))
https://github.com/brave/browser-laptop/issues/7710
 - [ ] 0.14.0 Exclusion List. ([#7709](https://github.com/brave/browser-laptop/issues/7709))
https://github.com/brave/browser-laptop/issues/7709
 - [ ] Create 0.14.0 Release Notes. ([#7708](https://github.com/brave/browser-laptop/issues/7708))
https://github.com/brave/browser-laptop/issues/7708
 - [ ] Adding custom bookmark name text box not clearing when deleted. ([#7691](https://github.com/brave/browser-laptop/issues/7691))
https://github.com/brave/browser-laptop/issues/7691
 - [ ] Remove about/less/flash.less. ([#7681](https://github.com/brave/browser-laptop/issues/7681))
https://github.com/brave/browser-laptop/issues/7681
 - [ ] Fixed header bar and tab styles. ([#7546](https://github.com/brave/browser-laptop/issues/7546))
https://github.com/brave/browser-laptop/issues/7546
 - [ ] Add Vimium support. ([#7527](https://github.com/brave/browser-laptop/issues/7527))
https://github.com/brave/browser-laptop/issues/7527
 - [ ] Fixed keyboard shortcuts not working. ([#7491](https://github.com/brave/browser-laptop/issues/7491))
https://github.com/brave/browser-laptop/issues/7491
 - [ ] Fix ellipses in string files. ([#7470](https://github.com/brave/browser-laptop/issues/7470))
https://github.com/brave/browser-laptop/issues/7470
 - [ ] Switch to uglify-js-harmony. ([#7461](https://github.com/brave/browser-laptop/issues/7461))
https://github.com/brave/browser-laptop/issues/7461
 - [ ] Can't view "Contribution Statement". ([#7416](https://github.com/brave/browser-laptop/issues/7416))
https://github.com/brave/browser-laptop/issues/7416
 - [ ] Fixed style of some ledger elements. ([#7380](https://github.com/brave/browser-laptop/issues/7380))
https://github.com/brave/browser-laptop/issues/7380
 - [ ] Split and refactor ledgerTable component. ([#7379](https://github.com/brave/browser-laptop/issues/7379))
https://github.com/brave/browser-laptop/issues/7379
 - [ ] Added session-tab icon numbers. ([#7367](https://github.com/brave/browser-laptop/issues/7367))
https://github.com/brave/browser-laptop/issues/7367
 - [ ] Object expected in chrome.storage.sync.get callback. ([#7314](https://github.com/brave/browser-laptop/issues/7314))
https://github.com/brave/browser-laptop/issues/7314
 - [ ] Won't build following instructions. ([#7210](https://github.com/brave/browser-laptop/issues/7210))
https://github.com/brave/browser-laptop/issues/7210
 - [ ] Remove unused braveSoftware string. ([#7209](https://github.com/brave/browser-laptop/issues/7209))
https://github.com/brave/browser-laptop/issues/7209
 - [ ] Automated test failure on tab. ([#6981](https://github.com/brave/browser-laptop/issues/6981))
https://github.com/brave/browser-laptop/issues/6981
 - [ ] Automated test failure on urlBarSuggestions. ([#6980](https://github.com/brave/browser-laptop/issues/6980))
https://github.com/brave/browser-laptop/issues/6980
 - [ ] URL address bar adds deleted text back immediately, have to delete twice. ([#6956](https://github.com/brave/browser-laptop/issues/6956))
https://github.com/brave/browser-laptop/issues/6956
 - [ ] Fix disabled ledger / payments panel tests. ([#6911](https://github.com/brave/browser-laptop/issues/6911))
https://github.com/brave/browser-laptop/issues/6911
 - [ ] Automated test failures on pinnedTabs. ([#6668](https://github.com/brave/browser-laptop/issues/6668))
https://github.com/brave/browser-laptop/issues/6668
 - [ ] Automated test failures on sessionStore. ([#6664](https://github.com/brave/browser-laptop/issues/6664))
https://github.com/brave/browser-laptop/issues/6664
 - [ ] SFGate.com - custom ad calls evading blocking on tablets & desktop (siteHack-level). ([#6635](https://github.com/brave/browser-laptop/issues/6635))
https://github.com/brave/browser-laptop/issues/6635
 - [ ] [hackerone] 181558. ([#5762](https://github.com/brave/browser-laptop/issues/5762))
https://github.com/brave/browser-laptop/issues/5762
 - [ ] [hackerone] 181686. ([#5700](https://github.com/brave/browser-laptop/issues/5700))
https://github.com/brave/browser-laptop/issues/5700
 - [ ] Closing a site immediately after loading shows entry in Brave payment list. ([#4156](https://github.com/brave/browser-laptop/issues/4156))
https://github.com/brave/browser-laptop/issues/4156
 - [ ] Back/forward gesture does not respect system preferences. ([#3299](https://github.com/brave/browser-laptop/issues/3299))
https://github.com/brave/browser-laptop/issues/3299
 - [ ] Fixed visual distinction between session tabs. ([#3083](https://github.com/brave/browser-laptop/issues/3083))
https://github.com/brave/browser-laptop/issues/3083
 - [ ] About: pages fail load in private tabs. ([#1817](https://github.com/brave/browser-laptop/issues/1817))
https://github.com/brave/browser-laptop/issues/1817
 - [ ] Fixed Linux update mechanism never finishing. ([#401](https://github.com/brave/browser-laptop/issues/401))
https://github.com/brave/browser-laptop/issues/401
