### ISSUE TITLE
Manual checklist for OS X 0.14.0 Preview1

### ISSUE THREAD

**Issue by alexwykoff** [brave/browser-laptop#7710]
- [ ] Replace float:right with flex on alert dialogs. ([#7673](https://github.com/brave/browser-laptop/issues/7673))
 - [ ] Unit test failing. ([#7667](https://github.com/brave/browser-laptop/issues/7667))
 - [ ] Add searx as Search Engine. ([#7658](https://github.com/brave/browser-laptop/issues/7658))
 - [ ] Resize favicons when tabs are too small. ([#7656](https://github.com/brave/browser-laptop/issues/7656))
 - [ ] Remember password prompt uses password as username. ([#7649](https://github.com/brave/browser-laptop/issues/7649))
 - [ ] Menu on Windows - Context menu (right click) does not work on nested items. ([#7624](https://github.com/brave/browser-laptop/issues/7624))
 - [ ] Re-enable DAU and MAU stats on Linux. ([#7562](https://github.com/brave/browser-laptop/issues/7562))
 - [ ] Recently closed orders the wrong way. ([#7548](https://github.com/brave/browser-laptop/issues/7548))
 - [ ] Tab UI - Fade tab instead of using ellipsis. ([#7535](https://github.com/brave/browser-laptop/issues/7535))
 - [ ] Show base domain urlbar suggestions along with deep linked history suggestions. ([#7533](https://github.com/brave/browser-laptop/issues/7533))
 - [ ] Hide check for update menu items on Linux. ([#7529](https://github.com/brave/browser-laptop/issues/7529))
 - [ ] Show notification for Flash elements that are too small for the placeholder. ([#7523](https://github.com/brave/browser-laptop/issues/7523))
 - [ ] 'hide sites with <1% usage' should be default on in about:preferences#payments. ([#7520](https://github.com/brave/browser-laptop/issues/7520))
 - [ ] Large translucent element obscures Washington Post content. ([#7510](https://github.com/brave/browser-laptop/issues/7510))
 - [ ] Refactor paymentTab. ([#7501](https://github.com/brave/browser-laptop/issues/7501))
 - [ ] Race condition on publisherToggle makes url to load slower if loaded from preferences. ([#7497](https://github.com/brave/browser-laptop/issues/7497))
 - [ ] Update to Standard@9.0.0 - rules "no-multiple-empty-lines", "no-useless-return", "generator-star-spacing", "padded-blocks". ([#7492](https://github.com/brave/browser-laptop/issues/7492))
 - [ ] Brave Payments FAQ link is not obvious. ([#7487](https://github.com/brave/browser-laptop/issues/7487))
 - [ ] Advance Settings button click area is blocked by helpful hints div when browser height is reduced. ([#7452](https://github.com/brave/browser-laptop/issues/7452))
 - [ ] Publishers are auto included even when auto-include sites is turned off. ([#7451](https://github.com/brave/browser-laptop/issues/7451))
 - [ ] New tab small window. ([#7411](https://github.com/brave/browser-laptop/issues/7411))
 - [ ] Reset sync on pyramid 0 and re-enabling sync doesn't sync bookmarks properly across devices. ([#7405](https://github.com/brave/browser-laptop/issues/7405))
 - [ ] Default order in torrent list should be numerical order. ([#7361](https://github.com/brave/browser-laptop/issues/7361))
 - [ ] Update ledger settings UI area to match 1.0 features/changes. ([#7348](https://github.com/brave/browser-laptop/issues/7348))
 - [ ] Refactor about:extensions with Aphrodite. ([#7345](https://github.com/brave/browser-laptop/issues/7345))
 - [ ] Need new strings to handle overdue payments. ([#7078](https://github.com/brave/browser-laptop/issues/7078))
 - [ ] Idle timer never stopping the idle timer. ([#6826](https://github.com/brave/browser-laptop/issues/6826))
 - [ ] Buttons on Torrent viewer needs spacing. ([#6735](https://github.com/brave/browser-laptop/issues/6735))
 - [ ] Allow more than 20 tabs per set. ([#6692](https://github.com/brave/browser-laptop/issues/6692))
 - [ ] "Estimated Time Saved" should take minutes into account. ([#6650](https://github.com/brave/browser-laptop/issues/6650))
 - [ ] URL autocomplete should offer the option of only completing the hostname. ([#6537](https://github.com/brave/browser-laptop/issues/6537))
 - [ ] Be able to get code coverage (for use with an online tool). ([#6473](https://github.com/brave/browser-laptop/issues/6473))
 - [ ] Options in the select elements on about:preferences#payments should be localizable. ([#6364](https://github.com/brave/browser-laptop/issues/6364))
 - [ ] Menu should not be activated with ALT key. ([#5775](https://github.com/brave/browser-laptop/issues/5775))
 - [ ] [HackerOne] access-control-allow-origin: * set on about: pages. ([#4913](https://github.com/brave/browser-laptop/issues/4913))
 - [ ] Feature Request: Bitwarden Password Manager. ([#4776](https://github.com/brave/browser-laptop/issues/4776))
 - [ ] Show some sort of UI for passive (display) mixed content. ([#2168](https://github.com/brave/browser-laptop/issues/2168))
