### ISSUE TITLE
Manual test run for Windows ia-32 0.14.0 Preview3

### ISSUE THREAD

**Issue by alexwykoff** [brave/browser-laptop#7758]
- [x] NewTab retains about:newtab text until mouse pointer is moved away from tab. ([#7724](https://github.com/brave/browser-laptop/issues/7724))
 - [x] Private session tab should have predominant color. ([#7720](https://github.com/brave/browser-laptop/issues/7720))
 - [x] Partition text for session tab is overlapping on the tab title. ([#7716](https://github.com/brave/browser-laptop/issues/7716))
 - [x] Private Tab Text Unreadable. ([#7715](https://github.com/brave/browser-laptop/issues/7715))
 - [x] Contribution statement should stay open. ([#7698](https://github.com/brave/browser-laptop/issues/7698))
 - [x] Sound icon + close button takes up too much space when tabs are small. ([#7665](https://github.com/brave/browser-laptop/issues/7665))
 - [x] Fresh Install of Brave Advertises Brave Properties. ([#7655](https://github.com/brave/browser-laptop/issues/7655))
 - [x] Alt+PrtSc key combination is not recognized by Brave. ([#7566](https://github.com/brave/browser-laptop/issues/7566))
 - [x] If flash is enabled, 'shields down' should allow the site to see that flash is installed. ([#7549](https://github.com/brave/browser-laptop/issues/7549))
 - [ ] Publishers are auto included even when auto-include sites is turned off. ([#7451](https://github.com/brave/browser-laptop/issues/7451))
 - [ ] Reset sync on pyramid 0 and re-enabling sync doesn't sync bookmarks properly across devices. ([#7405](https://github.com/brave/browser-laptop/issues/7405))
 - [x] No way to open a new tab in same session as session tab . ([#7376](https://github.com/brave/browser-laptop/issues/7376))
 - [ ] Torrent Viewer CSP rule blocks <iframe> content. ([#7243](https://github.com/brave/browser-laptop/issues/7243))
 - [ ] Idle timer never stopping the idle timer. ([#6826](https://github.com/brave/browser-laptop/issues/6826))
 - [ ] Vimium: Icon not displayed near address bar. ([#6193](https://github.com/brave/browser-laptop/issues/6193))
 - [ ] Feature Request: Bitwarden Password Manager. ([#4776](https://github.com/brave/browser-laptop/issues/4776))
 - [x] General Settings: "Save my downloads here" setting. ([#2110](https://github.com/brave/browser-laptop/issues/2110))
 - [x] Cookie option in bravery panel missing option "Block All". ([#1987](https://github.com/brave/browser-laptop/issues/1987))
