### ISSUE TITLE
Manual test run for Windows x64 0.14.0 Preview3

### ISSUE THREAD

**Issue by alexwykoff** [brave/browser-laptop#7759]
- [x] NewTab retains about:newtab text until mouse pointer is moved away from tab. ([#7724](https://github.com/brave/browser-laptop/issues/7724))
 - [x] Private session tab should have predominant color. ([#7720](https://github.com/brave/browser-laptop/issues/7720))
 - [x] Partition text for session tab is overlapping on the tab title. ([#7716](https://github.com/brave/browser-laptop/issues/7716))
 - [x] Private Tab Text Unreadable. ([#7715](https://github.com/brave/browser-laptop/issues/7715))
 - [x] Contribution statement should stay open. ([#7698](https://github.com/brave/browser-laptop/issues/7698))
 - [x] Payments UI - show grayed out icon when no payment history. ([#7693](https://github.com/brave/browser-laptop/issues/7693))
 - [ ] ~~Unit test failing. ([#7667](https://github.com/brave/browser-laptop/issues/7667))~~
 - [x] Sound icon + close button takes up too much space when tabs are small. ([#7665](https://github.com/brave/browser-laptop/issues/7665))
 - [x] Add searx as Search Engine. ([#7658](https://github.com/brave/browser-laptop/issues/7658))
 - [x] Fresh Install of Brave Advertises Brave Properties. ([#7655](https://github.com/brave/browser-laptop/issues/7655))
 - [x] Alt+PrtSc key combination is not recognized by Brave. ([#7566](https://github.com/brave/browser-laptop/issues/7566))
 - [ ] ~~Re-enable DAU and MAU stats on Linux. ([#7562](https://github.com/brave/browser-laptop/issues/7562))~~
 - [x] If flash is enabled, 'shields down' should allow the site to see that flash is installed. ([#7549](https://github.com/brave/browser-laptop/issues/7549))
 - [ ] ~~Hide check for update menu items on Linux. ([#7529](https://github.com/brave/browser-laptop/issues/7529))~~
 - [ ] ~~Update to Standard@9.0.0 - rules "no-multiple-empty-lines", "no-useless-return", "generator-star-spacing", "padded-blocks". ([#7492](https://github.com/brave/browser-laptop/issues/7492))~~
 - [ ] Publishers are auto included even when auto-include sites is turned off. ([#7451](https://github.com/brave/browser-laptop/issues/7451))
 - [x] Unable to open Browser Console (Shift+F8). ([#7448](https://github.com/brave/browser-laptop/issues/7448))
 - [x] No way to open a new tab in same session as session tab . ([#7376](https://github.com/brave/browser-laptop/issues/7376))
 - [x] Torrent Viewer CSP rule blocks <iframe> content. ([#7243](https://github.com/brave/browser-laptop/issues/7243))
 - [ ] Idle timer never stopping the idle timer. ([#6826](https://github.com/brave/browser-laptop/issues/6826))
 - [ ] Be able to get code coverage (for use with an online tool). ([#6473](https://github.com/brave/browser-laptop/issues/6473))
 - [ ] Vimium: Icon not displayed near address bar. ([#6193](https://github.com/brave/browser-laptop/issues/6193))
 - [ ] Feature Request: Bitwarden Password Manager. ([#4776](https://github.com/brave/browser-laptop/issues/4776))
 - [x] General Settings: "Save my downloads here" setting. ([#2110](https://github.com/brave/browser-laptop/issues/2110))
 - [x] Cookie option in bravery panel missing option "Block All". ([#1987](https://github.com/brave/browser-laptop/issues/1987))
