### ISSUE TITLE
Update to Standard@9.0.0 - rule "no-mixed-operators"

### ISSUE THREAD

**Issue by cezaraugusto** [brave/browser-laptop#7784]
Version 9.0.0 introduced major changes that changed lint rules for several files.

This work will be split to avoid regressions. From [Standard changelog](https://github.com/feross/standard/blob/v9.0.0/CHANGELOG.md#new-rules) those rules were added:

(note that `changed rules` described in Standard changelog didn't affect our repo)

* [x] __Disallow mixing different operators without parens (no-mixed-operators)__
* [x] ~~Enforce 1 newline at end of file (previously 1 or 2 were ok) (no-multiple-empty-lines)~~ (see #7495)
* Disallow Unused Expressions (no-unused-expressions)
* [x] ~~Disallow redundant return statements (no-useless-return)~~ (see #7495)
* Disallow Incorrect Early Use (no-use-before-define)
* Enforce that Promise rejections are passed an Error object as a reason (prefer-promise-reject-errors)
* Enforce comparing typeof expressions against string literals (valid-typeof)
* [x] ~~Enforce spacing around * in generator functions (generator-star-spacing)~~ (see #7495)
* Disallow Unnecessary Labels (no-extra-label)
* Disallow spacing between template tags and their literals (template-tag-spacing)
* [x] ~~Disallow padding within switch statements and classes (padded-blocks)~~ (see #7495)
* Enforce that Symbols are passed a description (symbol-description)

This issue addresses rules marked as checked.
