### ISSUE TITLE
Manual tests for OS X 0.14.0 Preview 4 

### ISSUE THREAD

**Issue by alexwykoff** [brave/browser-laptop#7811]
## Installer

1. [ ] Check that installer is close to the size of last release.
2. [ ] Check signature: If OS Run `spctl --assess --verbose /Applications/Brave.app/` and make sure it returns `accepted`.  If Windows right click on the installer exe and go to Properties, go to the Digital Signatures tab and double click on the signature.  Make sure it says "The digital signature is OK" in the popup window.
3. [ ] Check Brave, muon, and libchromiumcontent version in About and make sure it is EXACTLY as expected.

## Last changeset test

1. [ ] Test what is covered by the last changeset (you can find this by clicking on the SHA in about:brave).

## Per release specialty tests

 - [ ] Autofill suggestion is not retained when clicked on the input field. ([#7768](https://github.com/brave/browser-laptop/issues/7768))
 - [ ] Follow up of #7547 (Update flat design). ([#7739](https://github.com/brave/browser-laptop/issues/7739))
 - [ ] NewTab retains about:newtab text until mouse pointer is moved away from tab. ([#7724](https://github.com/brave/browser-laptop/issues/7724))
 - [ ] Private session tab should have predominant color. ([#7720](https://github.com/brave/browser-laptop/issues/7720))
 - [ ] Partition text for session tab is overlapping on the tab title. ([#7716](https://github.com/brave/browser-laptop/issues/7716))
 - [ ] Private Tab Text Unreadable. ([#7715](https://github.com/brave/browser-laptop/issues/7715))
 - [ ] Contribution statement should stay open. ([#7698](https://github.com/brave/browser-laptop/issues/7698))
 - [ ] Payments UI - show grayed out icon when no payment history. ([#7693](https://github.com/brave/browser-laptop/issues/7693))
 - [ ] Replace float:right with flex on alert dialogs. ([#7673](https://github.com/brave/browser-laptop/issues/7673))
 - [ ] Unit test failing. ([#7667](https://github.com/brave/browser-laptop/issues/7667))
 - [ ] Sound icon + close button takes up too much space when tabs are small. ([#7665](https://github.com/brave/browser-laptop/issues/7665))
 - [ ] When re-launching when maximised, window is offset by several pixels & no longer maximised. ([#7664](https://github.com/brave/browser-laptop/issues/7664))
 - [ ] Add searx as Search Engine. ([#7658](https://github.com/brave/browser-laptop/issues/7658))
 - [ ] Resize favicons when tabs are too small. ([#7656](https://github.com/brave/browser-laptop/issues/7656))
 - [ ] Fresh Install of Brave Advertises Brave Properties. ([#7655](https://github.com/brave/browser-laptop/issues/7655))
 - [ ] Remember password prompt uses password as username. ([#7649](https://github.com/brave/browser-laptop/issues/7649))
 - [ ] Menu on Windows - Context menu (right click) does not work on nested items. ([#7624](https://github.com/brave/browser-laptop/issues/7624))
 - [ ] Alt+PrtSc key combination is not recognized by Brave. ([#7566](https://github.com/brave/browser-laptop/issues/7566))
 - [ ] Re-enable DAU and MAU stats on Linux. ([#7562](https://github.com/brave/browser-laptop/issues/7562))
 - [ ] If flash is enabled, 'shields down' should allow the site to see that flash is installed. ([#7549](https://github.com/brave/browser-laptop/issues/7549))
 - [ ] Recently closed orders the wrong way. ([#7548](https://github.com/brave/browser-laptop/issues/7548))
 - [ ] Tab UI - Fade tab instead of using ellipsis. ([#7535](https://github.com/brave/browser-laptop/issues/7535))
 - [ ] Show base domain urlbar suggestions along with deep linked history suggestions. ([#7533](https://github.com/brave/browser-laptop/issues/7533))
 - [ ] Hide check for update menu items on Linux. ([#7529](https://github.com/brave/browser-laptop/issues/7529))
 - [ ] Show notification for Flash elements that are too small for the placeholder. ([#7523](https://github.com/brave/browser-laptop/issues/7523))
 - [ ] 'hide sites with <1% usage' should be default on in about:preferences#payments. ([#7520](https://github.com/brave/browser-laptop/issues/7520))
 - [ ] Large translucent element obscures Washington Post content. ([#7510](https://github.com/brave/browser-laptop/issues/7510))
 - [ ] Refactor paymentTab. ([#7501](https://github.com/brave/browser-laptop/issues/7501))
 - [ ] Race condition on publisherToggle makes url to load slower if loaded from preferences. ([#7497](https://github.com/brave/browser-laptop/issues/7497))
 - [ ] Update to Standard@9.0.0 - rules "no-multiple-empty-lines", "no-useless-return", "generator-star-spacing", "padded-blocks". ([#7492](https://github.com/brave/browser-laptop/issues/7492))
 - [ ] Brave Payments FAQ link is not obvious. ([#7487](https://github.com/brave/browser-laptop/issues/7487))
 - [ ] Advance Settings button click area is blocked by helpful hints div when browser height is reduced. ([#7452](https://github.com/brave/browser-laptop/issues/7452))
 - [ ] Publishers are auto included even when auto-include sites is turned off. ([#7451](https://github.com/brave/browser-laptop/issues/7451))
 - [ ] Unable to open Browser Console (Shift+F8). ([#7448](https://github.com/brave/browser-laptop/issues/7448))
 - [ ] New tab small window. ([#7411](https://github.com/brave/browser-laptop/issues/7411))
 - [ ] Reset sync on pyramid 0 and re-enabling sync doesn't sync bookmarks properly across devices. ([#7405](https://github.com/brave/browser-laptop/issues/7405))
 - [ ] No way to open a new tab in same session as session tab . ([#7376](https://github.com/brave/browser-laptop/issues/7376))
 - [ ] Torrent name is missing once download is started. ([#7362](https://github.com/brave/browser-laptop/issues/7362))
 - [ ] Default order in torrent list should be numerical order. ([#7361](https://github.com/brave/browser-laptop/issues/7361))
 - [ ] Update ledger settings UI area to match 1.0 features/changes. ([#7348](https://github.com/brave/browser-laptop/issues/7348))
 - [ ] Refactor about:extensions with Aphrodite. ([#7345](https://github.com/brave/browser-laptop/issues/7345))
 - [ ] Drag & Drop for Images and Files Broken (causes screen to go white). ([#7266](https://github.com/brave/browser-laptop/issues/7266))
 - [ ] Torrent Viewer CSP rule blocks <iframe> content. ([#7243](https://github.com/brave/browser-laptop/issues/7243))
 - [ ] Need new strings to handle overdue payments. ([#7078](https://github.com/brave/browser-laptop/issues/7078))
 - [ ] Idle timer never stopping the idle timer. ([#6826](https://github.com/brave/browser-laptop/issues/6826))
 - [ ] Buttons on Torrent viewer needs spacing. ([#6735](https://github.com/brave/browser-laptop/issues/6735))
 - [ ] Allow more than 20 tabs per set. ([#6692](https://github.com/brave/browser-laptop/issues/6692))
 - [ ] "Estimated Time Saved" should take minutes into account. ([#6650](https://github.com/brave/browser-laptop/issues/6650))
 - [ ] URL autocomplete should offer the option of only completing the hostname. ([#6537](https://github.com/brave/browser-laptop/issues/6537))
 - [ ] Be able to get code coverage (for use with an online tool). ([#6473](https://github.com/brave/browser-laptop/issues/6473))
 - [ ] Options in the select elements on about:preferences#payments should be localizable. ([#6364](https://github.com/brave/browser-laptop/issues/6364))
 - [ ] Vimium: Icon not displayed near address bar. ([#6193](https://github.com/brave/browser-laptop/issues/6193))
 - [ ] Menu should not be activated with ALT key. ([#5775](https://github.com/brave/browser-laptop/issues/5775))
 - [ ] New tab page shortcut buttons link tooltips are not user friendly. ([#5657](https://github.com/brave/browser-laptop/issues/5657))
 - [ ] Disable close button on tabs if tab size is too small. ([#5431](https://github.com/brave/browser-laptop/issues/5431))
 - [ ] [HackerOne] access-control-allow-origin: * set on about: pages. ([#4913](https://github.com/brave/browser-laptop/issues/4913))
 - [ ] Feature Request: Bitwarden Password Manager. ([#4776](https://github.com/brave/browser-laptop/issues/4776))
 - [ ] Copy to clipboard(Flash plugin) blocked on Reverso.net. ([#4020](https://github.com/brave/browser-laptop/issues/4020))
 - [ ] 'View Certificate' non-functional. ([#2611](https://github.com/brave/browser-laptop/issues/2611))
 - [ ] Show some sort of UI for passive (display) mixed content. ([#2168](https://github.com/brave/browser-laptop/issues/2168))
 - [ ] General Settings: "Save my downloads here" setting. ([#2110](https://github.com/brave/browser-laptop/issues/2110))
 - [ ] Cookie option in bravery panel missing option "Block All". ([#1987](https://github.com/brave/browser-laptop/issues/1987))

## Widevine/Netflix test

1. [ ] Test that you can log into Netflix and start a show.

## Ledger
1. [ ] Create a wallet with a value other than $5 selected in the monthly budget dropdown. Click on the 'Add Funds' button and check that Coinbase transactions are blocked.
2. [ ] Remove all `ledger-*.json` files from `~/Library/Application\ Support/Brave/`. Go to the Payments tab in about:preferences, enable payments, click on `create wallet`. Check that the `add funds` button appears after a wallet is created.
3. [ ] Click on `add funds` and verify that adding funds through Coinbase increases the account balance.
4. [ ] Repeat the step above but add funds by scanning the QR code in a mobile bitcoin app instead of through Coinbase.
5. [ ] Visit nytimes.com for a few seconds and make sure it shows up in the Payments table.
6. [ ] Go to https://jsfiddle.net/LnwtLckc/5/ and click the register button. In the Payments tab, click `add funds`. Verify that the `transfer funds` button is visible and that clicking on `transfer funds` opens a jsfiddle URL in a new tab.
7. [ ] Go to https://jsfiddle.net/LnwtLckc/5/ and click `unregister`. Verify that the `transfer funds` button no longer appears in the `add funds` modal.
8. [ ] Check that disabling payments and enabling them again does not lose state.

## Sync
1. [ ] Verify you are able to sync two devices using the secret code
2. [ ] Visit a site on device 1 and change shield setting, ensure that the saved site preference is synced to device 2
3. [ ] Enable Browsing history sync on device 1, ensure the history is shown on device 2 
4. [ ] Import/Add bookmarks on device 1, ensure it is synced on device 2 
5. [ ] Ensure imported bookmark folder structure is maintained on device 2
6. [ ] Ensure bookmark favicons are shown after sync

## Data

1. [ ] Make sure that data from the last version appears in the new version OK.
2. [ ] Test that the previous version's cookies are preserved in the next version.

## About pages

1. [ ] Test that about:adblock loads
2. [ ] Test that about:autofill loads
3. [ ] Test that about:bookmarks loads bookmarks
4. [ ] Test that about:downloads loads downloads
5. [ ] Test that about:extensions loads
6. [ ] Test that about:history loads history
7. [ ] Test that about:passwords loads
8. [ ] Test that about:styles loads
9. [ ] Test that about:preferences changing a preference takes effect right away
10. [ ] Test that about:preferences language change takes effect on re-start
11. [ ] Test that about.com without the http protocol is loaded from URL bar

## Bookmarks

1. [ ] Test that creating a bookmark on the bookmarks toolbar works
2. [ ] Test that creating a bookmark folder on the bookmarks toolbar works
3. [ ] Test that moving a bookmark into a folder by drag and drop on the bookmarks folder works
4. [ ] Test that clicking a bookmark in the toolbar loads the bookmark.
5. [ ] Test that clicking a bookmark in a bookmark toolbar folder loads the bookmark.

## Context menus
1. [ ] Make sure context menu items in the URL bar work
2. [ ] Make sure context menu items on content work with no selected text.
3. [ ] Make sure context menu items on content work with selected text.
4. [ ] Make sure context menu items on content work inside an editable control on `about:styles` (input, textarea, or contenteditable).

## Find on page

1. [ ] Ensure search box is shown with shortcut
2. [ ] Test successful find
3. [ ] Test forward and backward find navigation
4. [ ] Test failed find shows 0 results
5. [ ] Test match case find

## Geolocation

1. [ ] Check that https://developer.mozilla.org/en-US/docs/Web/API/Geolocation/Using_geolocation works

## Site hacks

1. [ ] Test https://www.twitch.tv/adobe sub-page loads a video and you can play it

## Downloads

1. [ ] Test downloading a file works and that all actions on the download item works.

## Fullscreen

1. [ ] Test that entering full screen window works View -> Toggle Full Screen. And exit back (Not Esc).
2. [ ] Test that entering HTML5 full screen works. And Esc to go back. (youtube.com)

## Tabs and Pinning

1. [ ] Test that tabs are pinnable
2. [ ] Test that tabs are unpinnable
3. [ ] Test that tabs are draggable to same tabset
4. [ ] Test that tabs are draggable to alternate tabset

## Zoom

1. [ ] Test zoom in / out shortcut works
2. [ ] Test hamburger menu zooms.
3. [ ] Test zoom saved when you close the browser and restore on a single site.
4. [ ] Test zoom saved when you navigate within a single origin site.
5. [ ] Test that navigating to a different origin resets the zoom

## Bravery settings

1. [ ] Check that HTTPS Everywhere works by loading http://www.apple.com
2. [ ] Turning HTTPS Everywhere off and shields off both disable the redirect to https://www.apple.com
3. [ ] Check that ad replacement works on http://slashdot.org
4. [ ] Check that toggling to blocking and allow ads works as expected.
5. [ ] Test that clicking through a cert error in https://badssl.com/ works.
6. [ ] Test that Safe Browsing works (http://downloadme.org/)
7. [ ] Turning Safe Browsing off and shields off both disable safe browsing for http://downloadme.org/.
8. [ ] Visit https://brianbondy.com/ and then turn on script blocking, nothing should load. Allow it from the script blocking UI in the URL bar and it should work.
9. [ ] Test that about:preferences default Bravery settings take effect on pages with no site settings.
10. [ ] Test that turning on fingerprinting protection in about:preferences shows 3 fingerprints blocked at https://jsfiddle.net/bkf50r8v/13/. Test that turning it off in the Bravery menu shows 0 fingerprints blocked.
11. [ ] Test that 3rd party storage results are blank at https://jsfiddle.net/7ke9r14a/9/ when 3rd party cookies are blocked and not blank when 3rd party cookies are unblocked.
12. [ ] Test that audio fingerprint is blocked at https://audiofingerprint.openwpm.com/ when fingerprinting protection is on.

## Content tests

1. [ ] Go to https://brianbondy.com/ and click on the twitter icon on the top right. Test that context menus work in the new twitter tab.
2. [ ] Load twitter and click on a tweet so the popup div shows.   Click to dismiss and repeat with another div. Make sure it shows.
3. [ ] Go to http://www.bennish.net/web-notifications.html and test that clicking on 'Show' pops up a notification asking for permission. Make sure that clicking 'Deny' leads to no notifications being shown.
4. [ ] Go to https://trac.torproject.org/projects/tor/login and make sure that the password can be saved. Make sure the saved password shows up in `about:passwords`. Then reload https://trac.torproject.org/projects/tor/login and make sure the password is autofilled.
5. [ ] Open a github issue and type some misspellings, make sure they are underlined.
6. [ ] Make sure that right clicking on a word with suggestions gives a suggestion and that clicking on the suggestion replaces the text.
7. [ ] Make sure that Command + Click (Control + Click on Windows, Control + Click on Ubuntu) on a link opens a new tab but does NOT switch to it.  Click on it and make sure it is already loaded.
8. [ ] Open an email on http://mail.google.com/ or inbox.google.com and click on a link. Make sure it works.
9. [ ] Test that PDF is loaded at http://www.orimi.com/pdf-test.pdf
10. [ ] Test that https://mixed-script.badssl.com/ shows up as grey not red (no mixed content scripts are run).

## Flash tests
1. [ ] Turn on Flash in about:preferences#security. Test that clicking on 'Install Flash' banner on myspace.com shows a notification to allow Flash and that the banner disappears when 'Allow' is clicked.
2. [ ] Test that flash placeholder appears on http://www.homestarrunner.com

## Autofill tests
1. [ ] Test that autofill works on http://www.roboform.com/filling-test-all-fields

## Session storage

Do not forget to make a backup of your entire `~/Library/Application\ Support/Brave` folder.

1. [ ] Temporarily move away your `~/Library/Application\ Support/Brave/session-store-1` and test that clean session storage works. (`%appdata%\Brave in Windows`, `./config/brave` in Ubuntu)
2. [ ] Test that windows and tabs restore when closed, including active tab.
3. [ ] Move away your entire `~/Library/Application\ Support/Brave` folder (`%appdata%\Brave in Windows`, `./config/brave` in Ubuntu)

## Cookie and Cache

1. [ ] Make a backup of your profile, turn on all clearing in preferences and shut down.  Make sure when you bring the browser back up everything is gone that is specified.
2. [ ] Go to http://samy.pl/evercookie/ and set an evercookie. Check that going to prefs, clearing site data and cache, and going back to the Evercookie site does not remember the old evercookie value.

## Update tests

1. [ ] Test that updating using `BRAVE_UPDATE_VERSION=0.8.3` env variable works correctly.
