### ISSUE TITLE
Hangouts - Brave v. Chrome functionality and data comparison investigation

### ISSUE THREAD

**Issue by lukemulks** [brave/browser-laptop#7849]
**Objective:** 

Investigation of current status of older functionality issues, and data collection status from Google Hangouts in Brave. 

- Collect supporting data. 
- Update open issues
- Route data & prioritize updates accordingly 
- Inform internal teams of status in prep for 1.0 release target (high-level issue check only for v1.0 prep - functionality investigation can be backlogged, data check = higher pri for 1.0 awareness) 

**Targeted Areas of Focus** 

**1. We have several issues that are specific to Google Hangouts and Brave**

**_Checklist:_ Open Hangouts issues in GH** 
- [ ] _difference between google chrome and brave browser for speaker selection for google hangouts_ https://github.com/brave/browser-laptop/issues/1666 (May, 2016)
- [ ] _Cannot share screen in Google hangouts_ https://github.com/brave/browser-laptop/issues/3392 (Aug, 2016)
- [ ] _Cannot send '%' while sending messages in Google Hangouts_ https://github.com/brave/browser-laptop/issues/6632 (Jan, 2017) 

**_Checklist:_ Issue review**
- [ ] Review each of the open issues.
- [ ] Confirm if issues remain.
- [ ] Check in MacOS and Windows10, is behavior consistent. 
- [ ] Check with test team for Linux review.
- [ ] If possible, confirm or determine root cause.
- [ ] If root cause is difficult to diagnose, flag and route to engineering for assistance.
- [ ] Note if additional issues are observed during review.

**_Item 2_ We've had some recent reports of functionality issues with Hangouts and Brave** 

- Issues communicated verbally, or casually in Slack, and not captured in GH as far as I can tell.
- Need more info, but mainly need to test playback and functionality to attempt to repro. 
- Mainly communicated as: "hangouts doesn't work in Brave || hangouts crashed in Brave)

**_Checklist:_ Functionality review**
- [ ] Test Hangout connection functionality: 1:1 conversations, 1:1 video chat.
- [ ] Test Hangout connection functionality: Group Hangout (some on cam, some audio only)
- [ ] Test in MacOSX and Windows10.
- [ ] Note any issues observed. 
- [ ] Check issues in GH, if open, update with info. Open new issues if none exist. 

**_Item 3_ We've had some inquiries and internal questions about user data and how it is passed within Hangouts in Brave, and if the data collected matches collected data for Hangouts in Chrome.** 

**_Checklist:_ Data collection status**
- [ ] Capture HTTPS/SOCKS session in Charles Proxy for Brave
- [ ] Capture Wireshark session for Brave
- [ ] Capture DevTools session for Chrome (requests visible to webRequest API).
- [ ] Capture chrome://net-internals session for Chrome.
- [ ] Compare and analyze chrome://net-internals session traffic from Chrome, against Wireshark session from Brave. Note any irregularities. 
- [ ] Compare and analyze Charles Proxy session traffic from Brave, against DevTools session from Chrome (HAR export). Note any irregularities. 
- [ ] Note any traffic that appears on protocols, or is made from requests that appear to bypass webRequest, if encountered. 
- [ ] Open issues where appropriate. 

- Platform (Win7, 8, 10? macOS? Linux distro?):
Main focus, for accessibility reasons, will be Windows10 and MacOS, but all platforms would be ideal.

- Brave Version (revision SHA):
14.0, pre-1.0

**Comment by bsclifton** [comment]
Closing this issue as `wontfix` since we'll be moving over to [brave-core](https://github.com/brave/brave-browser)
