### ISSUE TITLE
Manual test for OS X 0.14.0 RC1

### ISSUE THREAD

**Issue by alexwykoff** [brave/browser-laptop#7938]
## Installer

1. [x] Check that installer is close to the size of last release.
2. [x] Check signature: If OS Run `spctl --assess --verbose /Applications/Brave.app/` and make sure it returns `accepted`.  If Windows right click on the installer exe and go to Properties, go to the Digital Signatures tab and double click on the signature.  Make sure it says "The digital signature is OK" in the popup window.
3. [x] Check Brave, muon, and libchromiumcontent version in About and make sure it is EXACTLY as expected.

## Last changeset test

1. [x] Test what is covered by the last changeset (you can find this by clicking on the SHA in about:brave).

## Per release specialty tests

 - [x] Crash reporting not enabled for Windows build. ([#7917](https://github.com/brave/browser-laptop/issues/7917))
 - [x] Block phishing/malware not working. ([#7916](https://github.com/brave/browser-laptop/issues/7916))
 - [x] 0.14.0dev-Preview7 does not run on Windows 10 32 bit. ([#7915](https://github.com/brave/browser-laptop/issues/7915))
 - [x] New private tab has a blank page favicon and NewTab text is not visible. ([#7912](https://github.com/brave/browser-laptop/issues/7912))
 - [x] Browser crash when Brave Payments is enabled. ([#7911](https://github.com/brave/browser-laptop/issues/7911))
 - [x] New tab not working for back/forward history. ([#7892](https://github.com/brave/browser-laptop/issues/7892))
 - [x] Widevine is broken on C57 on macOS. ([#7891](https://github.com/brave/browser-laptop/issues/7891))
 - [x] Lion badge should show count for fingerprint block as well. ([#7886](https://github.com/brave/browser-laptop/issues/7886))
 - [x] Webview crash when visiting https://jsfiddle.net/bkf50r8v/13/. ([#7885](https://github.com/brave/browser-laptop/issues/7885))
 - [x] Pref change restart doesn't launch the browser again. ([#7882](https://github.com/brave/browser-laptop/issues/7882))
 - [x] Inspect Extension Background Page. ([#7880](https://github.com/brave/browser-laptop/issues/7880))
 - [x] Hide lion badge when block count is 0. ([#7873](https://github.com/brave/browser-laptop/issues/7873))
 - [x] Added lion icon badge. ([#7859](https://github.com/brave/browser-laptop/issues/7859))
 - [x] Fixed styles on notification & update bars. ([#7853](https://github.com/brave/browser-laptop/issues/7853))
 - [x] Zoom is not saved when you close the browser and restore on a single site. ([#7832](https://github.com/brave/browser-laptop/issues/7832))
 - [x] Fixed re-launching with a maximized window. ([#7825](https://github.com/brave/browser-laptop/issues/7825))
 - [x] Fixed audio indicator has extra bottom padding compared to favicon. ([#7815](https://github.com/brave/browser-laptop/issues/7815))
 - [x] Fixed vertical center display of urlbar . ([#7805](https://github.com/brave/browser-laptop/issues/7805))
 - [x] Added context menu to Bookmarks Manager. ([#7801](https://github.com/brave/browser-laptop/issues/7801))
 - [x] Autofill suggestion is not retained when clicked on the input field. ([#7768](https://github.com/brave/browser-laptop/issues/7768))
 - [x] Follow up of #7547 (Update flat design). ([#7739](https://github.com/brave/browser-laptop/issues/7739))
 - [x] Fixed display of text for new tabs. ([#7724](https://github.com/brave/browser-laptop/issues/7724))
 - [x] Fixed private session tab color to always show purple. ([#7720](https://github.com/brave/browser-laptop/issues/7720))
 - [x] Fixed display of session info on tab. ([#7716](https://github.com/brave/browser-laptop/issues/7716))
 - [x] Private Tab Text Unreadable. ([#7715](https://github.com/brave/browser-laptop/issues/7715))
 - [x] Fixed contribution statement display. ([#7698](https://github.com/brave/browser-laptop/issues/7698))
 - [x] Payments UI - show grayed out icon when no payment history. ([#7693](https://github.com/brave/browser-laptop/issues/7693))
 - [x] Fixed UI on alert dialogs. ([#7673](https://github.com/brave/browser-laptop/issues/7673))
 - [x] Unit test failing. ([#7667](https://github.com/brave/browser-laptop/issues/7667))
 - [x] Fixed Flash discovery for sites if shields are down. ([#7549](https://github.com/brave/browser-laptop/issues/7549))
 - [x] Fixed closed order for tabs in History menu. ([#7548](https://github.com/brave/browser-laptop/issues/7548))
 - [x] Fixed tab UI - fade tab on the right-hand side instead of using ellipsis. ([#7535](https://github.com/brave/browser-laptop/issues/7535))
 - [x] Fixed urlbar suggestions to show base domain along with deep linked history suggestions. ([#7533](https://github.com/brave/browser-laptop/issues/7533))
 - [x] Added notification for Flash elements that are too small for the placeholder. ([#7523](https://github.com/brave/browser-laptop/issues/7523))
 - [x] Fixed 'hide sites with <1% usage' should be default on in about:preferences#payments. ([#7520](https://github.com/brave/browser-laptop/issues/7520))
 - [x] Fixed large translucent element which obscures Washington Post content. ([#7510](https://github.com/brave/browser-laptop/issues/7510))
 - [x] Fixed style and layout on payment tab. ([#7501](https://github.com/brave/browser-laptop/issues/7501))
 - [x] Fixed url loads slower if loaded from preferences. ([#7497](https://github.com/brave/browser-laptop/issues/7497))
 - [x] Update to Standard@9.0.0 - rules "no-multiple-empty-lines", "no-useless-return", "generator-star-spacing", "padded-blocks". ([#7492](https://github.com/brave/browser-laptop/issues/7492))
 - [x] Brave Payments FAQ link is not obvious. ([#7487](https://github.com/brave/browser-laptop/issues/7487))
 - [x] Fixed advance settings button is blocked by helpful hints in certain situations. ([#7452](https://github.com/brave/browser-laptop/issues/7452))
 - [x] Fixed publishers are auto included even when auto-include sites is turned off. ([#7451](https://github.com/brave/browser-laptop/issues/7451))
 - [x] Fixed open browser console (Shift+F8). ([#7448](https://github.com/brave/browser-laptop/issues/7448))
 - [x] Fixed YouTube.com player - updated ad blocking evasion. ([#7432](https://github.com/brave/browser-laptop/issues/7432))
 - [x] Fixed new tab display when the window is small. ([#7411](https://github.com/brave/browser-laptop/issues/7411))
 - [ ] Fixed re-enabling sync doesn't sync bookmarks properly across devices. ([#7405](https://github.com/brave/browser-laptop/issues/7405))
 - [ ] Fixed open a new tab in same session as session tab . ([#7376](https://github.com/brave/browser-laptop/issues/7376))
 - [ ] Fixed torrent name missing after download is started. ([#7362](https://github.com/brave/browser-laptop/issues/7362))
 - [ ] Fixed default order in torrent list. ([#7361](https://github.com/brave/browser-laptop/issues/7361))
 - [ ] Fixed style on ledger settings UI area to match 1.0 features/changes. ([#7348](https://github.com/brave/browser-laptop/issues/7348))
 - [ ] Fixed styles on about:extensions with Aphrodite. ([#7345](https://github.com/brave/browser-laptop/issues/7345))
 - [ ] Fixed drag & drop for images and files broken (causes screen to go white). ([#7266](https://github.com/brave/browser-laptop/issues/7266))
 - [ ] Fixed torrent viewer CSP rule blocks <iframe> content. ([#7243](https://github.com/brave/browser-laptop/issues/7243))
 - [ ] Horizontal scrolling with two-finger gesture is also treated as page navigation. ([#7100](https://github.com/brave/browser-laptop/issues/7100))
 - [ ] Added new strings to handle overdue payments. ([#7078](https://github.com/brave/browser-laptop/issues/7078))
 - [ ] Fixed idle timer never stopping. ([#6826](https://github.com/brave/browser-laptop/issues/6826))
 - [ ] Fixed button alignment on the notification bar. ([#6749](https://github.com/brave/browser-laptop/issues/6749))
 - [ ] Fixed spacing of buttons on torrent viewer. ([#6735](https://github.com/brave/browser-laptop/issues/6735))
 - [ ] Added setting for more than 20 tabs per set. ([#6692](https://github.com/brave/browser-laptop/issues/6692))
 - [ ] Fixed "Estimated Time Saved" to take minutes into account. ([#6650](https://github.com/brave/browser-laptop/issues/6650))
 - [ ] Fixed URL autocomplete offering the option of only completing the hostname. ([#6537](https://github.com/brave/browser-laptop/issues/6537))
 - [ ] Added ability to get code coverage (for use with an online tool). ([#6473](https://github.com/brave/browser-laptop/issues/6473))
 - [ ] Fixed options on about:preferences#payments to allow for localization. ([#6364](https://github.com/brave/browser-laptop/issues/6364))
 - [ ] Vimium: Icon not displayed near address bar. ([#6193](https://github.com/brave/browser-laptop/issues/6193))
 - [ ] Added more details on secure connections. ([#6157](https://github.com/brave/browser-laptop/issues/6157))
 - [ ] Fixed menu activation with ALT key. ([#5775](https://github.com/brave/browser-laptop/issues/5775))
 - [ ] Fixed new tab page shortcut buttons link tooltips to be more user friendly. ([#5657](https://github.com/brave/browser-laptop/issues/5657))
 - [ ] Fixed close button on tabs if tab size is too small. ([#5431](https://github.com/brave/browser-laptop/issues/5431))
 - [ ] Fixed access-control-allow-origin: * set on about: pages. ([#4913](https://github.com/brave/browser-laptop/issues/4913))
 - [ ] [security] disable (or warn about) data: URIs in location bar. ([#4899](https://github.com/brave/browser-laptop/issues/4899))
 - [ ] Added Bitwarden Password Manager. ([#4776](https://github.com/brave/browser-laptop/issues/4776))
 - [ ] Fixed copy to clipboard(Flash plugin) blocked on Reverso.net. ([#4020](https://github.com/brave/browser-laptop/issues/4020))
 - [ ] Fixed 'View Certificate' functionality. ([#2611](https://github.com/brave/browser-laptop/issues/2611))
 - [ ] Fixed UI for passive (display) mixed content. ([#2168](https://github.com/brave/browser-laptop/issues/2168))
 - [ ] Added "Save my downloads here" setting. ([#2110](https://github.com/brave/browser-laptop/issues/2110))
 - [ ] Added  "Block All" cookie option in bravery panel. ([#1987](https://github.com/brave/browser-laptop/issues/1987))

## Widevine/Netflix test

1. [x] Test that you can log into Netflix and start a show.

## Ledger
1. [x] Create a wallet with a value other than $5 selected in the monthly budget dropdown. Click on the 'Add Funds' button and check that Coinbase transactions are blocked.
2. [x] Remove all `ledger-*.json` files from `~/Library/Application\ Support/Brave/`. Go to the Payments tab in about:preferences, enable payments, click on `create wallet`. Check that the `add funds` button appears after a wallet is created.
3. [ ] Click on `add funds` and verify that adding funds through Coinbase increases the account balance.
4. [ ] Repeat the step above but add funds by scanning the QR code in a mobile bitcoin app instead of through Coinbase.
5. [ ] Visit nytimes.com for a few seconds and make sure it shows up in the Payments table.
6. [ ] Go to https://jsfiddle.net/LnwtLckc/5/ and click the register button. In the Payments tab, click `add funds`. Verify that the `transfer funds` button is visible and that clicking on `transfer funds` opens a jsfiddle URL in a new tab.
7. [ ] Go to https://jsfiddle.net/LnwtLckc/5/ and click `unregister`. Verify that the `transfer funds` button no longer appears in the `add funds` modal.
8. [ ] Check that disabling payments and enabling them again does not lose state.

## Sync
1. [x] Verify you are able to sync two devices using the secret code
2. [x] Visit a site on device 1 and change shield setting, ensure that the saved site preference is synced to device 2
3. [x] Enable Browsing history sync on device 1, ensure the history is shown on device 2 
4. [x] Import/Add bookmarks on device 1, ensure it is synced on device 2 
5. [x] Ensure imported bookmark folder structure is maintained on device 2
6. [x] Ensure bookmark favicons are shown after sync

## Data

1. [x] Make sure that data from the last version appears in the new version OK.
2. [x] Test that the previous version's cookies are preserved in the next version.

## About pages

1. [x] Test that about:adblock loads
2. [x] Test that about:autofill loads
3. [x] Test that about:bookmarks loads bookmarks
4. [x] Test that about:downloads loads downloads
5. [x] Test that about:extensions loads
6. [x] Test that about:history loads history
7. [x] Test that about:passwords loads
8. [x] Test that about:styles loads
9. [x] Test that about:preferences changing a preference takes effect right away
10. [x] Test that about:preferences language change takes effect on re-start
11. [x] Test that about.com without the http protocol is loaded from URL bar

## Bookmarks

1. [x] Test that creating a bookmark on the bookmarks toolbar works
2. [x] Test that creating a bookmark folder on the bookmarks toolbar works
3. [x] Test that moving a bookmark into a folder by drag and drop on the bookmarks folder works
4. [x] Test that clicking a bookmark in the toolbar loads the bookmark.
5. [x] Test that clicking a bookmark in a bookmark toolbar folder loads the bookmark.

## Context menus
1. [x] Make sure context menu items in the URL bar work
2. [x] Make sure context menu items on content work with no selected text.
3. [x] Make sure context menu items on content work with selected text.
4. [x] Make sure context menu items on content work inside an editable control on `about:styles` (input, textarea, or contenteditable).

## Find on page

1. [x] Ensure search box is shown with shortcut
2. [x] Test successful find
3. [x] Test forward and backward find navigation
4. [x] Test failed find shows 0 results
5. [x] Test match case find

## Geolocation

1. [x] Check that https://developer.mozilla.org/en-US/docs/Web/API/Geolocation/Using_geolocation works

## Site hacks

1. [x] Test https://www.twitch.tv/adobe sub-page loads a video and you can play it

## Downloads

1. [x] Test downloading a file works and that all actions on the download item works.

## Fullscreen

1. [x] Test that entering full screen window works View -> Toggle Full Screen. And exit back (Not Esc).
2. [x] Test that entering HTML5 full screen works. And Esc to go back. (youtube.com)

## Tabs and Pinning

1. [x] Test that tabs are pinnable
2. [x] Test that tabs are unpinnable
3. [x] Test that tabs are draggable to same tabset
4. [x] Test that tabs are draggable to alternate tabset

## Zoom

1. [x] Test zoom in / out shortcut works
2. [x] Test hamburger menu zooms.
3. [x] Test zoom saved when you close the browser and restore on a single site.
4. [x] Test zoom saved when you navigate within a single origin site.
5. [x] Test that navigating to a different origin resets the zoom

## Bravery settings

1. [ ] Check that HTTPS Everywhere works by loading http://www.apple.com
2. [ ] Turning HTTPS Everywhere off and shields off both disable the redirect to https://www.apple.com
3. [ ] Check that ad replacement works on http://slashdot.org
4. [ ] Check that toggling to blocking and allow ads works as expected.
5. [ ] Test that clicking through a cert error in https://badssl.com/ works.
6. [x] Test that Safe Browsing works (http://downloadme.org/)
7. [x] Turning Safe Browsing off and shields off both disable safe browsing for http://downloadme.org/.
8. [ ] Visit https://brianbondy.com/ and then turn on script blocking, nothing should load. Allow it from the script blocking UI in the URL bar and it should work.
9. [ ] Test that about:preferences default Bravery settings take effect on pages with no site settings.
10. [ ] Test that turning on fingerprinting protection in about:preferences shows 3 fingerprints blocked at https://jsfiddle.net/bkf50r8v/13/. Test that turning it off in the Bravery menu shows 0 fingerprints blocked.
11. [ ] Test that 3rd party storage results are blank at https://jsfiddle.net/7ke9r14a/9/ when 3rd party cookies are blocked and not blank when 3rd party cookies are unblocked.
12. [ ] Test that audio fingerprint is blocked at https://audiofingerprint.openwpm.com/ when fingerprinting protection is on.

## Content tests

1. [ ] Go to https://brianbondy.com/ and click on the twitter icon on the top right. Test that context menus work in the new twitter tab.
2. [ ] Load twitter and click on a tweet so the popup div shows.   Click to dismiss and repeat with another div. Make sure it shows.
3. [ ] Go to http://www.bennish.net/web-notifications.html and test that clicking on 'Show' pops up a notification asking for permission. Make sure that clicking 'Deny' leads to no notifications being shown.
4. [ ] Go to https://trac.torproject.org/projects/tor/login and make sure that the password can be saved. Make sure the saved password shows up in `about:passwords`. Then reload https://trac.torproject.org/projects/tor/login and make sure the password is autofilled.
5. [x] Open a github issue and type some misspellings, make sure they are underlined.
6. [x] Make sure that right clicking on a word with suggestions gives a suggestion and that clicking on the suggestion replaces the text.
7. [x] Make sure that Command + Click (Control + Click on Windows, Control + Click on Ubuntu) on a link opens a new tab but does NOT switch to it.  Click on it and make sure it is already loaded.
8. [ ] Open an email on http://mail.google.com/ or inbox.google.com and click on a link. Make sure it works.
9. [x] Test that PDF is loaded at http://www.orimi.com/pdf-test.pdf
10. [x] Test that https://mixed-script.badssl.com/ shows up as grey not red (no mixed content scripts are run).

## Flash tests
1. [ ] Turn on Flash in about:preferences#security. Test that clicking on 'Install Flash' banner on myspace.com shows a notification to allow Flash and that the banner disappears when 'Allow' is clicked.
2. [ ] Test that flash placeholder appears on http://www.homestarrunner.com

## Autofill tests
1. [x] Test that autofill works on http://www.roboform.com/filling-test-all-fields

## Session storage

Do not forget to make a backup of your entire `~/Library/Application\ Support/Brave` folder.

1. [x] Temporarily move away your `~/Library/Application\ Support/Brave/session-store-1` and test that clean session storage works. (`%appdata%\Brave in Windows`, `./config/brave` in Ubuntu)
2. [x] Test that windows and tabs restore when closed, including active tab.
3. [x] Move away your entire `~/Library/Application\ Support/Brave` folder (`%appdata%\Brave in Windows`, `./config/brave` in Ubuntu)

## Cookie and Cache

1. [ ] Make a backup of your profile, turn on all clearing in preferences and shut down.  Make sure when you bring the browser back up everything is gone that is specified.
2. [ ] Go to http://samy.pl/evercookie/ and set an evercookie. Check that going to prefs, clearing site data and cache, and going back to the Evercookie site does not remember the old evercookie value.

## Update tests

1. [ ] Test that updating using `BRAVE_UPDATE_VERSION=0.8.3` env variable works correctly.
