### ISSUE TITLE
Exclusion List for 0.15.0

### ISSUE THREAD

**Issue by alexwykoff** [brave/browser-laptop#7998]
Generated 03/30:
 - [x] Lion Badge Numbers are Selectable. ([#7994](https://github.com/brave/browser-laptop/issues/7994))
https://github.com/brave/browser-laptop/issues/7994
 - [x] Create commonForm with Aphrodite. ([#7990](https://github.com/brave/browser-laptop/issues/7990))
https://github.com/brave/browser-laptop/issues/7990
 - [x] Brave badge too close to edge. ([#7977](https://github.com/brave/browser-laptop/issues/7977))
https://github.com/brave/browser-laptop/issues/7977
 - [x] JS iloop policing needs to be enhanced. ([#7973](https://github.com/brave/browser-laptop/issues/7973))
https://github.com/brave/browser-laptop/issues/7973
 - [x] Sync does not appear to recover from network outage. ([#7972](https://github.com/brave/browser-laptop/issues/7972))
https://github.com/brave/browser-laptop/issues/7972
 - [x] Sync is losing hierarchy when adding bookmarks to new sync members. ([#7971](https://github.com/brave/browser-laptop/issues/7971))
https://github.com/brave/browser-laptop/issues/7971
 - [x] Restart buttons need to have some visual indication of interaction. ([#7968](https://github.com/brave/browser-laptop/issues/7968))
https://github.com/brave/browser-laptop/issues/7968
 - [x] Sync sometimes shows CSP error. ([#7965](https://github.com/brave/browser-laptop/issues/7965))
https://github.com/brave/browser-laptop/issues/7965
 - [x] ADDFUNDS_URL env var is not correctly displaying Add Funds button in dashboard. ([#7962](https://github.com/brave/browser-laptop/issues/7962))
https://github.com/brave/browser-laptop/issues/7962
 - [x] Delete confirmation message ("Delete?") should be able to be localizable. ([#7958](https://github.com/brave/browser-laptop/issues/7958))
https://github.com/brave/browser-laptop/issues/7958
 - [x] Automated tests fixes. ([#7950](https://github.com/brave/browser-laptop/issues/7950))
https://github.com/brave/browser-laptop/issues/7950
 - [x] Refactor siteInfo.js with Aphrodite. ([#7949](https://github.com/brave/browser-laptop/issues/7949))
https://github.com/brave/browser-laptop/issues/7949
 - [x] Refactor bookmarksToolbar.js with Aphrodite. ([#7920](https://github.com/brave/browser-laptop/issues/7920))
https://github.com/brave/browser-laptop/issues/7920
 - [x] NewTab should be replaced by any new URL bar search query when in same newtab. ([#7918](https://github.com/brave/browser-laptop/issues/7918))
https://github.com/brave/browser-laptop/issues/7918
 - [x] Back/forward gesture should support three finger swipe. ([#7905](https://github.com/brave/browser-laptop/issues/7905))
https://github.com/brave/browser-laptop/issues/7905
 - [x] First time wallet creation needs a better UI. ([#7889](https://github.com/brave/browser-laptop/issues/7889))
https://github.com/brave/browser-laptop/issues/7889
 - [x] Connection info click area is on the urlbarIcon, should be on urlbarIconContainer. ([#7888](https://github.com/brave/browser-laptop/issues/7888))
https://github.com/brave/browser-laptop/issues/7888
 - [x] Refactor contributionStatement.js with Aphrodite. ([#7883](https://github.com/brave/browser-laptop/issues/7883))
https://github.com/brave/browser-laptop/issues/7883
 - [x] When writing session to disk, ensure we do a flush. ([#7876](https://github.com/brave/browser-laptop/issues/7876))
https://github.com/brave/browser-laptop/issues/7876
 - [x] Integrate the new welcome screen. ([#7821](https://github.com/brave/browser-laptop/issues/7821))
https://github.com/brave/browser-laptop/issues/7821
 - [x] Support Extension Option Pages. ([#7812](https://github.com/brave/browser-laptop/issues/7812))
https://github.com/brave/browser-laptop/issues/7812
 - [x] Change "Save Torrent File" button to "Copy Magnet Link" for magnet links. ([#7772](https://github.com/brave/browser-laptop/issues/7772))
https://github.com/brave/browser-laptop/issues/7772
 - [x] Restructure paymentTab.js. ([#7750](https://github.com/brave/browser-laptop/issues/7750))
https://github.com/brave/browser-laptop/issues/7750
 - [x] Unable to add annotations to YouTube videos - youtube.com. ([#7738](https://github.com/brave/browser-laptop/issues/7738))
https://github.com/brave/browser-laptop/issues/7738
 - [x] Cannot unpin an about:error page. ([#7733](https://github.com/brave/browser-laptop/issues/7733))
https://github.com/brave/browser-laptop/issues/7733
 - [x] View Source shortcut should be CTRL+U, not CTRL+ALT+U. ([#7702](https://github.com/brave/browser-laptop/issues/7702))
https://github.com/brave/browser-laptop/issues/7702
 - [x] Refactor about:about with Aphrodite. ([#7670](https://github.com/brave/browser-laptop/issues/7670))
https://github.com/brave/browser-laptop/issues/7670
 - [x] When alert() dialog is dismissed, underlying window does not regain focus. ([#7666](https://github.com/brave/browser-laptop/issues/7666))
https://github.com/brave/browser-laptop/issues/7666
 - [x] Y position of second level (or higher) folders is wrong in Windows bookmark menu. ([#7662](https://github.com/brave/browser-laptop/issues/7662))
https://github.com/brave/browser-laptop/issues/7662
 - [x] Solve issue where black favicons on black tabs are invisible. ([#7635](https://github.com/brave/browser-laptop/issues/7635))
https://github.com/brave/browser-laptop/issues/7635
 - [x] On disable switch make the text grayed out. ([#7634](https://github.com/brave/browser-laptop/issues/7634))
https://github.com/brave/browser-laptop/issues/7634
 - [x] Remove vestigial style on empty divs. ([#7541](https://github.com/brave/browser-laptop/issues/7541))
https://github.com/brave/browser-laptop/issues/7541
 - [x] Make tab switching lightning fast. ([#7540](https://github.com/brave/browser-laptop/issues/7540))
https://github.com/brave/browser-laptop/issues/7540
 - [x] When typing quickly in urlbar, keys are sometimes dropped.. ([#7538](https://github.com/brave/browser-laptop/issues/7538))
https://github.com/brave/browser-laptop/issues/7538
 - [x] Print recovery keys. ([#7512](https://github.com/brave/browser-laptop/issues/7512))
https://github.com/brave/browser-laptop/issues/7512
 - [x] Torrent viewer should maintain the folder structure in the torrent. ([#7494](https://github.com/brave/browser-laptop/issues/7494))
https://github.com/brave/browser-laptop/issues/7494
 - [x] Downloads should show origin. ([#7468](https://github.com/brave/browser-laptop/issues/7468))
https://github.com/brave/browser-laptop/issues/7468
 - [x] Remove label from MultiMedia devices when fingerprinting protection is on.. ([#7462](https://github.com/brave/browser-laptop/issues/7462))
https://github.com/brave/browser-laptop/issues/7462
 - [x] Chrome.tabs.duplicate unsupported. ([#7458](https://github.com/brave/browser-laptop/issues/7458))
https://github.com/brave/browser-laptop/issues/7458
 - [x] Support chrome://newtab/ as alias to about:newtab. ([#7457](https://github.com/brave/browser-laptop/issues/7457))
https://github.com/brave/browser-laptop/issues/7457
 - [x] Chrome.tabs.insertCSS is presently unsupported. ([#7456](https://github.com/brave/browser-laptop/issues/7456))
https://github.com/brave/browser-laptop/issues/7456
 - [x] Pocket was translated when it should not.. ([#7450](https://github.com/brave/browser-laptop/issues/7450))
https://github.com/brave/browser-laptop/issues/7450
 - [x] Incorrect state found in tab.pinned. ([#7440](https://github.com/brave/browser-laptop/issues/7440))
https://github.com/brave/browser-laptop/issues/7440
 - [x] Refactor menubar.js with Aphrodite. ([#7372](https://github.com/brave/browser-laptop/issues/7372))
https://github.com/brave/browser-laptop/issues/7372
 - [x] Pocket extension on Windows i32 is always red . ([#7357](https://github.com/brave/browser-laptop/issues/7357))
https://github.com/brave/browser-laptop/issues/7357
 - [x] Update ledger list control to support new features for 1.0. ([#7347](https://github.com/brave/browser-laptop/issues/7347))
https://github.com/brave/browser-laptop/issues/7347
 - [x] When the browser dives into an anonize2 crypto operation, it is unresponsive for a second or so. ([#7344](https://github.com/brave/browser-laptop/issues/7344))
https://github.com/brave/browser-laptop/issues/7344
 - [x] Pin tabs which are loaded causes a crash. ([#7187](https://github.com/brave/browser-laptop/issues/7187))
https://github.com/brave/browser-laptop/issues/7187
 - [x] Dragging bookmark into a folder (on bookmarks toolbar) doesn't work; puts at root of toolbar. ([#7019](https://github.com/brave/browser-laptop/issues/7019))
https://github.com/brave/browser-laptop/issues/7019
 - [x] Automated test failures: Payments Panel. ([#6890](https://github.com/brave/browser-laptop/issues/6890))
https://github.com/brave/browser-laptop/issues/6890
 - [x] Spotify no longer plays music. ([#6881](https://github.com/brave/browser-laptop/issues/6881))
https://github.com/brave/browser-laptop/issues/6881
 - [x] Automated test failure on application window. ([#6808](https://github.com/brave/browser-laptop/issues/6808))
https://github.com/brave/browser-laptop/issues/6808
 - [x] Partial support for chrome.tabs.update. ([#6790](https://github.com/brave/browser-laptop/issues/6790))
https://github.com/brave/browser-laptop/issues/6790
 - [x] There is no obvious way to stop a torrent download once it has started. ([#6768](https://github.com/brave/browser-laptop/issues/6768))
https://github.com/brave/browser-laptop/issues/6768
 - [x] Various Developer Tools features are broken. ([#6724](https://github.com/brave/browser-laptop/issues/6724))
https://github.com/brave/browser-laptop/issues/6724
 - [x] Auto-purging "Saved site settings" resets Payments "Include" toggles. ([#6708](https://github.com/brave/browser-laptop/issues/6708))
https://github.com/brave/browser-laptop/issues/6708
 - [x] Support torrent link files. ([#6671](https://github.com/brave/browser-laptop/issues/6671))
https://github.com/brave/browser-laptop/issues/6671
 - [x] Automated test failures on about:bookmarks. ([#6669](https://github.com/brave/browser-laptop/issues/6669))
https://github.com/brave/browser-laptop/issues/6669
 - [x] Automated test failures on bookmark. ([#6667](https://github.com/brave/browser-laptop/issues/6667))
https://github.com/brave/browser-laptop/issues/6667
 - [x] Automated test failures on navigationBar. ([#6666](https://github.com/brave/browser-laptop/issues/6666))
https://github.com/brave/browser-laptop/issues/6666
 - [x] Automated test failures on bookmarkToolbar. ([#6663](https://github.com/brave/browser-laptop/issues/6663))
https://github.com/brave/browser-laptop/issues/6663
 - [x] Importing data from Firefox not working. ([#6604](https://github.com/brave/browser-laptop/issues/6604))
https://github.com/brave/browser-laptop/issues/6604
 - [x] Add extensions panel to About:Preferences. ([#6530](https://github.com/brave/browser-laptop/issues/6530))
https://github.com/brave/browser-laptop/issues/6530
 - [x] Make pinned tabs share the same tab content across windows. ([#6413](https://github.com/brave/browser-laptop/issues/6413))
https://github.com/brave/browser-laptop/issues/6413
 - [x] Chrome.browserAction.setIcon doesn't support ImageData objects. ([#6197](https://github.com/brave/browser-laptop/issues/6197))
https://github.com/brave/browser-laptop/issues/6197
 - [x] Close unanswered alert bar if initiating tab is closed before user makes decision. ([#6028](https://github.com/brave/browser-laptop/issues/6028))
https://github.com/brave/browser-laptop/issues/6028
 - [x] Add pref to allow Pinned tabs to function in single-window mode. ([#5800](https://github.com/brave/browser-laptop/issues/5800))
https://github.com/brave/browser-laptop/issues/5800
 - [x] Add context-menu option to close tabs in tab page. ([#5489](https://github.com/brave/browser-laptop/issues/5489))
https://github.com/brave/browser-laptop/issues/5489
 - [x] Opening a context menu freezes video (ex: Youtube). ([#5470](https://github.com/brave/browser-laptop/issues/5470))
https://github.com/brave/browser-laptop/issues/5470
 - [x] Tracking: Disabled tests. ([#5389](https://github.com/brave/browser-laptop/issues/5389))
https://github.com/brave/browser-laptop/issues/5389
 - [x] Honey: Support browserAction.setBadgeBackgroundColor. ([#5367](https://github.com/brave/browser-laptop/issues/5367))
https://github.com/brave/browser-laptop/issues/5367
 - [x] Honey: Support chrome.browserAction.setBadgeText. ([#5366](https://github.com/brave/browser-laptop/issues/5366))
https://github.com/brave/browser-laptop/issues/5366
 - [x] Default browser setting gets reset after upgrade. ([#5246](https://github.com/brave/browser-laptop/issues/5246))
https://github.com/brave/browser-laptop/issues/5246
 - [x] Add alert dialog for wallet backup invitation. ([#4847](https://github.com/brave/browser-laptop/issues/4847))
https://github.com/brave/browser-laptop/issues/4847
 - [x] Brave should detect unclean shutdown and provide better recovery options. ([#4800](https://github.com/brave/browser-laptop/issues/4800))
https://github.com/brave/browser-laptop/issues/4800
 - [x] Fix failing automated tests. ([#4329](https://github.com/brave/browser-laptop/issues/4329))
https://github.com/brave/browser-laptop/issues/4329
 - [x] Dragging texts, crashes the browser. ([#2328](https://github.com/brave/browser-laptop/issues/2328))
https://github.com/brave/browser-laptop/issues/2328
 - [x] Bookmark submenu expansion bug. ([#1589](https://github.com/brave/browser-laptop/issues/1589))
https://github.com/brave/browser-laptop/issues/1589
 - [x] 'Block all HTTP' mode. ([#1576](https://github.com/brave/browser-laptop/issues/1576))
https://github.com/brave/browser-laptop/issues/1576
 - [x] Make linux prompt user that there's an update available and how to manually install it. ([#1470](https://github.com/brave/browser-laptop/issues/1470))
https://github.com/brave/browser-laptop/issues/1470
 - [x] Allow for unlimited tabs (having tabs continue to resize). ([#879](https://github.com/brave/browser-laptop/issues/879))
https://github.com/brave/browser-laptop/issues/879
 - [x] Facebook Messenger Error -- Cannot Send Image. ([#698](https://github.com/brave/browser-laptop/issues/698))
https://github.com/brave/browser-laptop/issues/698

**Comment by alexwykoff** [comment]
Exclusion List generated 04/14/2017:
 - [ ] Replace apple.com with another http site on the test plan. ([#8290](https://github.com/brave/browser-laptop/issues/8290))
https://github.com/brave/browser-laptop/issues/8290
 - [ ] Homepage preference isn't being respected. ([#8278](https://github.com/brave/browser-laptop/issues/8278))
https://github.com/brave/browser-laptop/issues/8278
 - [ ] Manual tests for Linux 0.14.2 Preview 3. ([#8277](https://github.com/brave/browser-laptop/issues/8277))
https://github.com/brave/browser-laptop/issues/8277
 - [ ] Manual tests for Windows x64 0.14.2 Preview 3. ([#8276](https://github.com/brave/browser-laptop/issues/8276))
https://github.com/brave/browser-laptop/issues/8276
 - [ ] Manual tests for Windows ia-32 0.14.2 Preview 3. ([#8275](https://github.com/brave/browser-laptop/issues/8275))
https://github.com/brave/browser-laptop/issues/8275
 - [ ] Manual tests for OS X 0.14.2 Preview 3. ([#8274](https://github.com/brave/browser-laptop/issues/8274))
https://github.com/brave/browser-laptop/issues/8274
 - [ ] Avoid having undefined props on tab audio indicator. ([#8270](https://github.com/brave/browser-laptop/issues/8270))
https://github.com/brave/browser-laptop/issues/8270
 - [ ] Update text for new privateTab. ([#8267](https://github.com/brave/browser-laptop/issues/8267))
https://github.com/brave/browser-laptop/issues/8267
 - [ ] Tab audio icon doesn't show sometimes on non-active tabs. ([#8249](https://github.com/brave/browser-laptop/issues/8249))
https://github.com/brave/browser-laptop/issues/8249
 - [ ] Leak in app state change listener in frame. ([#8244](https://github.com/brave/browser-laptop/issues/8244))
https://github.com/brave/browser-laptop/issues/8244
 - [ ] Unit Tests for bravifyText method. ([#8213](https://github.com/brave/browser-laptop/issues/8213))
https://github.com/brave/browser-laptop/issues/8213
 - [ ] Manual tests for Windows x64 on 0.14.2 Preview 2. ([#8200](https://github.com/brave/browser-laptop/issues/8200))
https://github.com/brave/browser-laptop/issues/8200
 - [ ] Move url bar related files into app. ([#8188](https://github.com/brave/browser-laptop/issues/8188))
https://github.com/brave/browser-laptop/issues/8188
 - [ ] Crash reporting disabled message shown on Windows when launching from console. ([#8183](https://github.com/brave/browser-laptop/issues/8183))
https://github.com/brave/browser-laptop/issues/8183
 - [ ] Instances of "GoogleChrome" only partially replaced. ([#8181](https://github.com/brave/browser-laptop/issues/8181))
https://github.com/brave/browser-laptop/issues/8181
 - [ ] Browser doesn't launch on Preview 2 build. ([#8169](https://github.com/brave/browser-laptop/issues/8169))
https://github.com/brave/browser-laptop/issues/8169
 - [ ] Update to muon 2.57.10. ([#8161](https://github.com/brave/browser-laptop/issues/8161))
https://github.com/brave/browser-laptop/issues/8161
 - [ ] Make tabContent rule for secondary icons consistent. ([#8158](https://github.com/brave/browser-laptop/issues/8158))
https://github.com/brave/browser-laptop/issues/8158
 - [ ] Manual tests for Windows x64 on 0.14.2 Preview 1. ([#8157](https://github.com/brave/browser-laptop/issues/8157))
https://github.com/brave/browser-laptop/issues/8157
 - [ ] React prop-types. ([#8152](https://github.com/brave/browser-laptop/issues/8152))
https://github.com/brave/browser-laptop/issues/8152
 - [ ] Torrent file names should be selectable. ([#8148](https://github.com/brave/browser-laptop/issues/8148))
https://github.com/brave/browser-laptop/issues/8148
 - [ ] Update check fails. ([#8147](https://github.com/brave/browser-laptop/issues/8147))
https://github.com/brave/browser-laptop/issues/8147
 - [ ] Regression: changing default zoom level affects UI. ([#8144](https://github.com/brave/browser-laptop/issues/8144))
https://github.com/brave/browser-laptop/issues/8144
 - [ ] Manual tests for Windows ia-32 0.14.2 Preview 1. ([#8141](https://github.com/brave/browser-laptop/issues/8141))
https://github.com/brave/browser-laptop/issues/8141
 - [ ] Manual tests for Windows x64 0.14.2 Preview 2. ([#8140](https://github.com/brave/browser-laptop/issues/8140))
https://github.com/brave/browser-laptop/issues/8140
 - [ ] Manual tests for Linux 0.14.2 Preview 1. ([#8139](https://github.com/brave/browser-laptop/issues/8139))
https://github.com/brave/browser-laptop/issues/8139
 - [ ] Manual test for 0.14.2 by Veiss from Community. ([#8138](https://github.com/brave/browser-laptop/issues/8138))
https://github.com/brave/browser-laptop/issues/8138
 - [ ] Add cx to notificationBar.js, updateBar.js, and bitcoinDashboard.js. ([#8126](https://github.com/brave/browser-laptop/issues/8126))
https://github.com/brave/browser-laptop/issues/8126
 - [ ] Replace -webkit-user-select with user-select. ([#8124](https://github.com/brave/browser-laptop/issues/8124))
https://github.com/brave/browser-laptop/issues/8124
 - [ ] Fix image title. ([#8116](https://github.com/brave/browser-laptop/issues/8116))
https://github.com/brave/browser-laptop/issues/8116
 - [ ] Uglify error - follow up of #6651. ([#8071](https://github.com/brave/browser-laptop/issues/8071))
https://github.com/brave/browser-laptop/issues/8071
 - [ ] Fix Standard.js lint errors. ([#8061](https://github.com/brave/browser-laptop/issues/8061))
https://github.com/brave/browser-laptop/issues/8061
 - [ ] PrintToPDF issue of chromium 57 . ([#8051](https://github.com/brave/browser-laptop/issues/8051))
https://github.com/brave/browser-laptop/issues/8051
 - [ ] Polishing audio icon in tabs. ([#8041](https://github.com/brave/browser-laptop/issues/8041))
https://github.com/brave/browser-laptop/issues/8041
 - [ ] Generate release notes for 0.14.2. ([#7999](https://github.com/brave/browser-laptop/issues/7999))
https://github.com/brave/browser-laptop/issues/7999
 - [ ] Exclusion List for 0.14.2. ([#7998](https://github.com/brave/browser-laptop/issues/7998))
https://github.com/brave/browser-laptop/issues/7998
 - [ ] Create commonForm with Aphrodite. ([#7990](https://github.com/brave/browser-laptop/issues/7990))
https://github.com/brave/browser-laptop/issues/7990
 - [ ] Automated tests fixes. ([#7950](https://github.com/brave/browser-laptop/issues/7950))
https://github.com/brave/browser-laptop/issues/7950
 - [ ] When the browser dives into an anonize2 crypto operation, it is unresponsive for a second or so. ([#7344](https://github.com/brave/browser-laptop/issues/7344))
https://github.com/brave/browser-laptop/issues/7344
 - [ ] Automated test failures: Payments Panel. ([#6890](https://github.com/brave/browser-laptop/issues/6890))
https://github.com/brave/browser-laptop/issues/6890
 - [ ] Tab discarding. ([#2388](https://github.com/brave/browser-laptop/issues/2388))
https://github.com/brave/browser-laptop/issues/2388

**Comment by alexwykoff** [comment]
Generated 04/24/2017:

Exclusion List:
 - [ ] Pinning a tab by drag and drop throws an error. ([#8469](https://github.com/brave/browser-laptop/issues/8469))
https://github.com/brave/browser-laptop/issues/8469
 - [ ] Download torrent file. ([#8452](https://github.com/brave/browser-laptop/issues/8452))
https://github.com/brave/browser-laptop/issues/8452
 - [ ] Clean install fails. ([#8444](https://github.com/brave/browser-laptop/issues/8444))
https://github.com/brave/browser-laptop/issues/8444
 - [ ] Zoom shortcut not working in 0.15.0 RC3. ([#8438](https://github.com/brave/browser-laptop/issues/8438))
https://github.com/brave/browser-laptop/issues/8438
 - [ ] Manual test run for Ubuntu 0.15.0 RC3. ([#8430](https://github.com/brave/browser-laptop/issues/8430))
https://github.com/brave/browser-laptop/issues/8430
 - [ ] Manual tests for 0.14.2 RC2 on Windows x64. ([#8399](https://github.com/brave/browser-laptop/issues/8399))
https://github.com/brave/browser-laptop/issues/8399
 - [ ] Startup Performance decrease when sync is turned on. ([#8354](https://github.com/brave/browser-laptop/issues/8354))
https://github.com/brave/browser-laptop/issues/8354
 - [ ] Upgrade to Chromium58. ([#8353](https://github.com/brave/browser-laptop/issues/8353))
https://github.com/brave/browser-laptop/issues/8353
 - [ ] Replace apple.com with another http site on the test plan. ([#8290](https://github.com/brave/browser-laptop/issues/8290))
https://github.com/brave/browser-laptop/issues/8290
 - [ ] Tab drag and drop can be jumpy. ([#8288](https://github.com/brave/browser-laptop/issues/8288))
https://github.com/brave/browser-laptop/issues/8288
 - [ ] Manual tests for Linux 0.14.2 RC2. ([#8277](https://github.com/brave/browser-laptop/issues/8277))
https://github.com/brave/browser-laptop/issues/8277
 - [ ] Manual tests for Windows x64 0.14.2 Preview 3. ([#8276](https://github.com/brave/browser-laptop/issues/8276))
https://github.com/brave/browser-laptop/issues/8276
 - [ ] Manual tests for Windows ia-32 0.14.2 Preview 3. ([#8275](https://github.com/brave/browser-laptop/issues/8275))
https://github.com/brave/browser-laptop/issues/8275
 - [ ] Manual tests for OS X 0.14.2 RC2. ([#8274](https://github.com/brave/browser-laptop/issues/8274))
https://github.com/brave/browser-laptop/issues/8274
 - [ ] Update text for new privateTab. ([#8267](https://github.com/brave/browser-laptop/issues/8267))
https://github.com/brave/browser-laptop/issues/8267
 - [ ] Unit Tests for bravifyText method. ([#8213](https://github.com/brave/browser-laptop/issues/8213))
https://github.com/brave/browser-laptop/issues/8213
 - [ ] Manual tests for Windows x64 on 0.14.2 Preview 2. ([#8200](https://github.com/brave/browser-laptop/issues/8200))
https://github.com/brave/browser-laptop/issues/8200
 - [ ] Move url bar related files into app. ([#8188](https://github.com/brave/browser-laptop/issues/8188))
https://github.com/brave/browser-laptop/issues/8188
 - [ ] Instances of "GoogleChrome" only partially replaced. ([#8181](https://github.com/brave/browser-laptop/issues/8181))
https://github.com/brave/browser-laptop/issues/8181
 - [ ] Update to muon 2.58.4. ([#8161](https://github.com/brave/browser-laptop/issues/8161))
https://github.com/brave/browser-laptop/issues/8161
 - [ ] Make tabContent rule for secondary icons consistent. ([#8158](https://github.com/brave/browser-laptop/issues/8158))
https://github.com/brave/browser-laptop/issues/8158
 - [ ] Manual tests for Windows x64 on 0.14.2 Preview 1. ([#8157](https://github.com/brave/browser-laptop/issues/8157))
https://github.com/brave/browser-laptop/issues/8157
 - [ ] React prop-types. ([#8152](https://github.com/brave/browser-laptop/issues/8152))
https://github.com/brave/browser-laptop/issues/8152
 - [ ] Manual tests for Windows ia-32 0.14.2 Preview 1. ([#8141](https://github.com/brave/browser-laptop/issues/8141))
https://github.com/brave/browser-laptop/issues/8141
 - [ ] Manual tests for Windows x64 0.14.2 Preview 2. ([#8140](https://github.com/brave/browser-laptop/issues/8140))
https://github.com/brave/browser-laptop/issues/8140
 - [ ] Manual tests for Linux 0.14.2 Preview 1. ([#8139](https://github.com/brave/browser-laptop/issues/8139))
https://github.com/brave/browser-laptop/issues/8139
 - [ ] Add cx to notificationBar.js, updateBar.js, and bitcoinDashboard.js. ([#8126](https://github.com/brave/browser-laptop/issues/8126))
https://github.com/brave/browser-laptop/issues/8126
 - [ ] Replace -webkit-user-select with user-select. ([#8124](https://github.com/brave/browser-laptop/issues/8124))
https://github.com/brave/browser-laptop/issues/8124
 - [ ] Uglify error - follow up of #6651. ([#8071](https://github.com/brave/browser-laptop/issues/8071))
https://github.com/brave/browser-laptop/issues/8071
 - [ ] Fix Standard.js lint errors. ([#8061](https://github.com/brave/browser-laptop/issues/8061))
https://github.com/brave/browser-laptop/issues/8061
 - [ ] Create commonForm with Aphrodite. ([#7990](https://github.com/brave/browser-laptop/issues/7990))
https://github.com/brave/browser-laptop/issues/7990
 - [ ] Automated tests fixes. ([#7950](https://github.com/brave/browser-laptop/issues/7950))
https://github.com/brave/browser-laptop/issues/7950
 - [ ] Automated test failures: Payments Panel. ([#6890](https://github.com/brave/browser-laptop/issues/6890))
https://github.com/brave/browser-laptop/issues/6890
 - [ ] Ubuntu updates not available for zesty. ([#6260](https://github.com/brave/browser-laptop/issues/6260))
https://github.com/brave/browser-laptop/issues/6260

**Comment by bbondy** [comment]
should this be closed?
