### ISSUE TITLE
Discard .genericForm and .commonForm from forms.less

### ISSUE THREAD

**Issue by luixxiul** [brave/browser-laptop#8010]
**Describe the issue you encountered:**
Discard `.genericForm`. See: https://github.com/brave/browser-laptop/issues/8009#issue-218569501

> Currently there are only three other instances where .genericForm is applied (autofillAddressPanel.js, autofillCreditCardPanel.js, and addEditBookmarkHanger.js), and in every case styles which genericForm defines are overwritten by what commonForm is going to do so (title color, padding inside the dialog, etc). Keeping both of them is a cause of style inconsistency.

- [x] loginRequired.js (#8009) - merged to `refactoring-aphrodite` with #8011
- [x] autofillAddressPanel.js (#8099) - merged to `refactoring-aphrodite` with #8105
- [x] autofillCreditCardPanel.js (#8100) - merged to `refactoring-aphrodite` with #8105
- [x] addEditBookmarkHanger.js (#6040) - merged to `refactoring-aphrodite` with #8136

Also remove `.commonForm` from form.less (as it was already refactored into the aphrodite component).

- [x] autofillAddressPanel.js (#8099) - merged to `refactoring-aphrodite` with #8105
- [x] autofillCreditCardPanel.js (#8100) - merged to `refactoring-aphrodite` with #8105
- [x] checkDefaultBrowserDialog.js (#8137) - merged to `refactoring-aphrodite` with #8154  

Any related issues: #7989 and #7990
