### ISSUE TITLE
Extend drag-n-drop functionality between URL, tabs, bookmarks, tiles, etc.

### ISSUE THREAD

**Issue by bradleyrichter** [brave/browser-laptop#8067]
As a user, I would appreciate being able to drag and drop URLs/tabs/pages into logical places such as the bookmarks bar, a BM bar subfolder, bookmarks manager folders, my home button, and into top-site tiles on the Brave Dashboard.

from:

- [ ] URL icon
- [ ] tab
- [ ] tab favicon
- [ ] bookmark bar item
- [ ] bookmark manager item
- [ ] create bookmark star button
- [ ] history list
- [ ] ledger list

to:

- [ ] tab bar
- [ ] tab page indicator
- [ ] tab page nav button
- [ ] bookmarks bar
- [ ] bookmarks bar folder
- [ ] bookmarks manager folder
- [ ] URL box
- [ ] the page area
- [ ] a new dashboard tile
- [ ] the desktop

All sources should provide a favicon for the page address being dragged from one place to another. It can be scaled up or down to fit within a comfortable 48x square.

## Related
Improve Drag and Drop for Bookmarks Manager #6246
Improve Drag and Drop for Tabs #6242
Improve Drag and Drop for Bookmarks Toolbar #6245

**Comment by bsclifton** [comment]
Biggest bang for the buck, IMO:
- Dragging between bookmarks toolbar and bookmark manager 
- Dragging bookmarks toolbar items into URL bar

**Comment by LaurenWags** [comment]
+1 from community - https://community.brave.com/t/open-url-by-dragging-link-to-new-tab-button-or-empty-page/1563

User would also like to drag a URL from a page up to the tabs bar as you can in Chrome.

**Comment by bsclifton** [comment]
+1 from https://github.com/brave/browser-laptop/issues/10007

You should be able to drag tabs into bookmark folders
![brave-drag-tab-to-folder-bug](https://user-images.githubusercontent.com/25360853/28251474-e61079e4-6aa7-11e7-884a-c7ad2904c457.gif)

**Comment by stephenkru** [comment]
+1 from me
