### ISSUE TITLE
Manual tests for OS X 0.14.2 RC2

### ISSUE THREAD

**Issue by alexwykoff** [brave/browser-laptop#8274]
Mac Checklist:
 - [ ] Opening pdf in new tab fails to load. ([#8364](https://github.com/brave/browser-laptop/issues/8364))
 - [ ] All Predefined Messages Should Be Replaced. ([#8318](https://github.com/brave/browser-laptop/issues/8318))
 - [ ] Sort extensions alphabetically. ([#8315](https://github.com/brave/browser-laptop/issues/8315))
 - [ ] Extensions still show __MSG__ under description  after enabling. ([#8307](https://github.com/brave/browser-laptop/issues/8307))
 - [ ] Wallet creation fails on 0.14.2 RC build. ([#8304](https://github.com/brave/browser-laptop/issues/8304))
 - [ ] Homepage preference isn't being respected. ([#8278](https://github.com/brave/browser-laptop/issues/8278))
 - [ ] Unable to open a partitioned/private link - tab props always false. ([#8271](https://github.com/brave/browser-laptop/issues/8271))
 - [ ] Avoid having undefined props on tab audio indicator. ([#8270](https://github.com/brave/browser-laptop/issues/8270))
 - [ ] Screen Reader Can't Identify Extension Button. ([#8269](https://github.com/brave/browser-laptop/issues/8269))
 - [ ] Increase the tabs bar by another 2 px based on increased user feedback. ([#8263](https://github.com/brave/browser-laptop/issues/8263))
 - [ ] Disable option to exclude extensions. ([#8259](https://github.com/brave/browser-laptop/issues/8259))
 - [ ] Change about:preferences#extensions link to go to the extension request category. ([#8252](https://github.com/brave/browser-laptop/issues/8252))
 - [ ] Tearing off a tab causes the torn off site to display the wrong URL. ([#8251](https://github.com/brave/browser-laptop/issues/8251))
 - [ ] Tab audio icon doesn't show sometimes on non-active tabs. ([#8249](https://github.com/brave/browser-laptop/issues/8249))
 - [ ] Leak in app state change listener in frame. ([#8244](https://github.com/brave/browser-laptop/issues/8244))
 - [ ] Syncing site settings exception. ([#8241](https://github.com/brave/browser-laptop/issues/8241))
 - [ ] Remove old extensions settings area from Advanced prefs panel. ([#8230](https://github.com/brave/browser-laptop/issues/8230))
 - [ ] Crash when opening/closing tabs really fast. ([#8228](https://github.com/brave/browser-laptop/issues/8228))
 - [ ] CRASH: ledger+sync. ([#8217](https://github.com/brave/browser-laptop/issues/8217))
 - [ ] Follow-ups for showing origin of downloads. ([#8215](https://github.com/brave/browser-laptop/issues/8215))
 - [ ] Update webtorrent description on extensions page. ([#8208](https://github.com/brave/browser-laptop/issues/8208))
 - [ ] Add "Extensions..." to window menu. ([#8203](https://github.com/brave/browser-laptop/issues/8203))
 - [ ] About:brave copy to clipboard tooltip is not working. ([#8199](https://github.com/brave/browser-laptop/issues/8199))
 - [ ] Sort indicator is not shown next to the table heading in about:preferences#extensions. ([#8197](https://github.com/brave/browser-laptop/issues/8197))
 - [ ] Wallet creation fails . ([#8195](https://github.com/brave/browser-laptop/issues/8195))
 - [ ] Invisible pinned tab after upgrade. ([#8190](https://github.com/brave/browser-laptop/issues/8190))
 - [ ] Badge designs are inconsistent. ([#8185](https://github.com/brave/browser-laptop/issues/8185))
 - [ ] DownloadItem Animation is Broken. ([#8179](https://github.com/brave/browser-laptop/issues/8179))
 - [ ] URL bar on new tab displays the URL of the next pinned tab. ([#8178](https://github.com/brave/browser-laptop/issues/8178))
 - [ ] Tearing off tab shows - Unchecked runtime.lastError while running guestViewInternal.destroyGuest: Unknown error -. ([#8175](https://github.com/brave/browser-laptop/issues/8175))
 - [ ] URL bar shape is different with payments enabled/disabled when visiting a site. ([#8170](https://github.com/brave/browser-laptop/issues/8170))
 - [ ] Url bar icon bookmark save is not working. ([#8151](https://github.com/brave/browser-laptop/issues/8151))
 - [ ] Clicking Save Torrent File button does not save .torrent file. ([#8146](https://github.com/brave/browser-laptop/issues/8146))
 - [ ] Download item styling is broken when clicking trash bin icon. ([#8143](https://github.com/brave/browser-laptop/issues/8143))
 - [ ] Add temporary notice to sync prefs page regarding mobile sync, + Beta label. ([#8121](https://github.com/brave/browser-laptop/issues/8121))
 - [ ] White tab text on dark tab background is difficult to read. ([#8115](https://github.com/brave/browser-laptop/issues/8115))
 - [ ] Ledger calculation when 0 eligible unpinned sites. ([#8102](https://github.com/brave/browser-laptop/issues/8102))
 - [ ] Replace data-test-id with testId in <Button>. ([#8090](https://github.com/brave/browser-laptop/issues/8090))
 - [ ] Javascript: bookmarks cause connection info box to appear. ([#8087](https://github.com/brave/browser-laptop/issues/8087))
 - [ ] Enabling show include site with autoinclude off shows payment info page when refreshed. ([#8079](https://github.com/brave/browser-laptop/issues/8079))
 - [ ] Revert the inlined files on contributionStatement.js (follow up to #7887). ([#8062](https://github.com/brave/browser-laptop/issues/8062))
 - [ ] Fix radii, colors, focused state styles in URL bar related to new add-funds button. ([#8058](https://github.com/brave/browser-laptop/issues/8058))
 - [ ] PrintToPDF issue of chromium 57 . ([#8051](https://github.com/brave/browser-laptop/issues/8051))
 - [ ] LastPass opens in wrong position when activated by keyboard. ([#8034](https://github.com/brave/browser-laptop/issues/8034))
 - [ ] Use PseudoElement for Narrow-Tab Audio Indicator. ([#8033](https://github.com/brave/browser-laptop/issues/8033))
 - [ ] About pages cannot be synced because data is too big (favicon is encoded in Base64 format). ([#8023](https://github.com/brave/browser-laptop/issues/8023))
 - [ ] Brave crashed when visiting Brave Twitter page. ([#8004](https://github.com/brave/browser-laptop/issues/8004))
 - [ ] Create commonForm.js and redesigned importBrowserDataPanel.js with it. ([#7996](https://github.com/brave/browser-laptop/issues/7996))
 - [ ] Toggle excluding a site from ledger sometimes removes it from the list. ([#7987](https://github.com/brave/browser-laptop/issues/7987))
 - [ ] Fixed - Sync does not appear to recover from network outage. ([#7972](https://github.com/brave/browser-laptop/issues/7972))
 - [ ] Fixed -Sync is losing hierarchy when adding bookmarks to new sync members. ([#7971](https://github.com/brave/browser-laptop/issues/7971))
 - [ ] Delete confirmation message ("Delete?") should be able to be localizable. ([#7958](https://github.com/brave/browser-laptop/issues/7958))
 - [ ] Refactor siteInfo.js with Aphrodite. ([#7949](https://github.com/brave/browser-laptop/issues/7949))
 - [ ] Add a new tab page for private tabs. ([#7934](https://github.com/brave/browser-laptop/issues/7934))
 - [ ] Refactor bookmarksToolbar.js with Aphrodite. ([#7920](https://github.com/brave/browser-laptop/issues/7920))
 - [ ] Back/forward gesture should support three finger swipe. ([#7905](https://github.com/brave/browser-laptop/issues/7905))
 - [ ] First time wallet creation needs a better UI. ([#7889](https://github.com/brave/browser-laptop/issues/7889))
 - [ ] Modified contributionStatement.js with Aphrodite. ([#7883](https://github.com/brave/browser-laptop/issues/7883))
 - [ ] Ubuntu: Brave doesn't know that it's the default browser.. ([#7800](https://github.com/brave/browser-laptop/issues/7800))
 - [ ] As a user i want to see modern looking spinner animation on tab loads. ([#7779](https://github.com/brave/browser-laptop/issues/7779))
 - [ ] Change "Save Torrent File" button to "Copy Magnet Link" for magnet links. ([#7772](https://github.com/brave/browser-laptop/issues/7772))
 - [ ] Tab title often isn't updated until the cursor is moved over it or tab focus is changed. ([#7765](https://github.com/brave/browser-laptop/issues/7765))
 - [ ] Dead tab when enter is pressed twice after typing in URL. ([#7727](https://github.com/brave/browser-laptop/issues/7727))
 - [ ] Add "Command+Click" to home button (opens home in a new background tab). ([#7718](https://github.com/brave/browser-laptop/issues/7718))
 - [ ] View Source shortcut should be CTRL+U, not CTRL+ALT+U. ([#7702](https://github.com/brave/browser-laptop/issues/7702))
 - [ ] Refactor about:about with Aphrodite (part 1). ([#7670](https://github.com/brave/browser-laptop/issues/7670))
 - [ ] Fixed wrong Y position in second level (or higher) folders in bookmark menu (when having many entries). ([#7662](https://github.com/brave/browser-laptop/issues/7662))
 - [ ] Downloads should show origin. ([#7468](https://github.com/brave/browser-laptop/issues/7468))
 - [ ] Remove label from MultiMedia devices when fingerprinting protection is on.. ([#7462](https://github.com/brave/browser-laptop/issues/7462))
 - [ ] Pocket was translated when it should not.. ([#7450](https://github.com/brave/browser-laptop/issues/7450))
 - [ ] Incorrect state found in tab.pinned. ([#7440](https://github.com/brave/browser-laptop/issues/7440))
 - [ ] Right click not dismissing / hiding an open menu  (Windows only). ([#7403](https://github.com/brave/browser-laptop/issues/7403))
 - [ ] Allow user to pin their favorite sites in Brave Payments (and other UI tweaks). ([#7347](https://github.com/brave/browser-laptop/issues/7347))
 - [ ] Tab loading icon is too subtle to notice. ([#7265](https://github.com/brave/browser-laptop/issues/7265))
 - [ ] Pin tabs which are loaded causes a crash. ([#7187](https://github.com/brave/browser-laptop/issues/7187))
 - [ ] Dragging bookmark into a folder (on bookmarks toolbar) doesn't work; puts at root of toolbar. ([#7019](https://github.com/brave/browser-laptop/issues/7019))
 - [ ] Spotify no longer plays music. ([#6881](https://github.com/brave/browser-laptop/issues/6881))
 - [ ] Include current year in PDF statement copyright footer. ([#6878](https://github.com/brave/browser-laptop/issues/6878))
 - [x] There is no obvious way to stop a torrent download once it has started. ([#6768](https://github.com/brave/browser-laptop/issues/6768))
 - [x] Support torrent link files. ([#6671](https://github.com/brave/browser-laptop/issues/6671))
 - [x] Add extensions panel to About:Preferences. ([#6530](https://github.com/brave/browser-laptop/issues/6530))
 - [x] Add the release notes of the same version as the browser to about:brave. ([#6130](https://github.com/brave/browser-laptop/issues/6130))
 - [x] Move noscript into the URL bar. ([#5792](https://github.com/brave/browser-laptop/issues/5792))
 - [x] Some info buttons in preferences are missing content links. ([#5758](https://github.com/brave/browser-laptop/issues/5758))
 - [x] Add context-menu option to close tabs in tab page. ([#5489](https://github.com/brave/browser-laptop/issues/5489))
 - [ ] Added extension badge colors. ([#5367](https://github.com/brave/browser-laptop/issues/5367))
 - [x] Honey: Support chrome.browserAction.setBadgeText. ([#5366](https://github.com/brave/browser-laptop/issues/5366))
 - [ ] Tab discarding. ([#2388](https://github.com/brave/browser-laptop/issues/2388))
 - [x] Windows installer places Brave in "Brave Inc" folder instead of "Brave" or "Brave Software". ([#2061](https://github.com/brave/browser-laptop/issues/2061))

## Installer

1. [x] Check that installer is close to the size of last release.
2. [ ] Check signature: If OS Run `spctl --assess --verbose /Applications/Brave.app/` and make sure it returns `accepted`.  If Windows right click on the installer exe and go to Properties, go to the Digital Signatures tab and double click on the signature.  Make sure it says "The digital signature is OK" in the popup window.
3. [ ] Check Brave, muon, and libchromiumcontent version in About and make sure it is EXACTLY as expected.

## Last changeset test

1. [ ] Test what is covered by the last changeset (you can find this by clicking on the SHA in about:brave).

## Per release specialty tests

1. [ ] Test closed issues to which `QA/step-specified` were added for the release that are going out.
    https://github.com/brave/browser-laptop/issues?utf8=%E2%9C%93&q=is%3Aissue%20label%3AQA%2Fsteps-specified%20is%3Aclosed%20milestone%3A0.13.5%20

## Widevine/Netflix test

1. [ ] Test that you can log into Netflix and start a show.

## Ledger
1. [ ] Create a wallet with a value other than $5 selected in the monthly budget dropdown. Click on the 'Add Funds' button and check that Coinbase transactions are blocked.
2. [ ] Remove all `ledger-*.json` files from `~/Library/Application\ Support/Brave/`. Go to the Payments tab in about:preferences, enable payments, click on `create wallet`. Check that the `add funds` button appears after a wallet is created.
3. [ ] Click on `add funds` and verify that adding funds through Coinbase increases the account balance.
4. [ ] Repeat the step above but add funds by scanning the QR code in a mobile bitcoin app instead of through Coinbase.
5. [ ] Visit nytimes.com for a few seconds and make sure it shows up in the Payments table.
6. [ ] Go to https://jsfiddle.net/LnwtLckc/5/ and click the register button. In the Payments tab, click `add funds`. Verify that the `transfer funds` button is visible and that clicking on `transfer funds` opens a jsfiddle URL in a new tab.
7. [ ] Go to https://jsfiddle.net/LnwtLckc/5/ and click `unregister`. Verify that the `transfer funds` button no longer appears in the `add funds` modal.
8. [ ] Check that disabling payments and enabling them again does not lose state.

## Sync
1. [ ] Verify you are able to sync two devices using the secret code
2. [ ] Visit a site on device 1 and change shield setting, ensure that the saved site preference is synced to device 2
3. [ ] Enable Browsing history sync on device 1, ensure the history is shown on device 2 
4. [ ] Import/Add bookmarks on device 1, ensure it is synced on device 2 
5. [ ] Ensure imported bookmark folder structure is maintained on device 2
6. [ ] Ensure bookmark favicons are shown after sync

## Data

1. [ ] Make sure that data from the last version appears in the new version OK.
2. [ ] Test that the previous version's cookies are preserved in the next version.

## About pages

1. [x] Test that about:adblock loads
2. [x] Test that about:autofill loads
3. [x] Test that about:bookmarks loads bookmarks
4. [x] Test that about:downloads loads downloads
5. [x] Test that about:extensions loads
6. [x] Test that about:history loads history
7. [x] Test that about:passwords loads
8. [x] Test that about:styles loads
9. [x] Test that about:preferences changing a preference takes effect right away
10. [x] Test that about:preferences language change takes effect on re-start
11. [x] Test that about.com without the http protocol is loaded from URL bar

## Bookmarks

1. [ ] Test that creating a bookmark on the bookmarks toolbar works
2. [ ] Test that creating a bookmark folder on the bookmarks toolbar works
3. [ ] Test that moving a bookmark into a folder by drag and drop on the bookmarks folder works
4. [ ] Test that clicking a bookmark in the toolbar loads the bookmark.
5. [ ] Test that clicking a bookmark in a bookmark toolbar folder loads the bookmark.

## Context menus
1. [ ] Make sure context menu items in the URL bar work
2. [ ] Make sure context menu items on content work with no selected text.
3. [ ] Make sure context menu items on content work with selected text.
4. [ ] Make sure context menu items on content work inside an editable control on `about:styles` (input, textarea, or contenteditable).

## Find on page

1. [ ] Ensure search box is shown with shortcut
2. [ ] Test successful find
3. [ ] Test forward and backward find navigation
4. [ ] Test failed find shows 0 results
5. [ ] Test match case find

## Geolocation

1. [ ] Check that https://developer.mozilla.org/en-US/docs/Web/API/Geolocation/Using_geolocation works

## Site hacks

1. [ ] Test https://www.twitch.tv/adobe sub-page loads a video and you can play it

## Downloads

1. [ ] Test downloading a file works and that all actions on the download item works.

## Fullscreen

1. [ ] Test that entering full screen window works View -> Toggle Full Screen. And exit back (Not Esc).
2. [ ] Test that entering HTML5 full screen works. And Esc to go back. (youtube.com)

## Tabs and Pinning

1. [ ] Test that tabs are pinnable
2. [ ] Test that tabs are unpinnable
3. [ ] Test that tabs are draggable to same tabset
4. [ ] Test that tabs are draggable to alternate tabset

## Zoom

1. [ ] Test zoom in / out shortcut works
2. [ ] Test hamburger menu zooms.
3. [ ] Test zoom saved when you close the browser and restore on a single site.
4. [ ] Test zoom saved when you navigate within a single origin site.
5. [ ] Test that navigating to a different origin resets the zoom

## Bravery settings

1. [ ] Check that HTTPS Everywhere works by loading http://www.apple.com
2. [ ] Turning HTTPS Everywhere off and shields off both disable the redirect to https://www.apple.com
3. [ ] Check that ad replacement works on http://slashdot.org
4. [ ] Check that toggling to blocking and allow ads works as expected.
5. [ ] Test that clicking through a cert error in https://badssl.com/ works.
6. [ ] Test that Safe Browsing works (http://downloadme.org/)
7. [ ] Turning Safe Browsing off and shields off both disable safe browsing for http://downloadme.org/.
8. [ ] Visit https://brianbondy.com/ and then turn on script blocking, nothing should load. Allow it from the script blocking UI in the URL bar and it should work.
9. [ ] Test that about:preferences default Bravery settings take effect on pages with no site settings.
10. [ ] Test that turning on fingerprinting protection in about:preferences shows 3 fingerprints blocked at https://jsfiddle.net/bkf50r8v/13/. Test that turning it off in the Bravery menu shows 0 fingerprints blocked.
11. [ ] Test that 3rd party storage results are blank at https://jsfiddle.net/7ke9r14a/9/ when 3rd party cookies are blocked and not blank when 3rd party cookies are unblocked.
12. [ ] Test that audio fingerprint is blocked at https://audiofingerprint.openwpm.com/ when fingerprinting protection is on.

## Content tests

1. [ ] Go to https://brianbondy.com/ and click on the twitter icon on the top right. Test that context menus work in the new twitter tab.
2. [ ] Load twitter and click on a tweet so the popup div shows.   Click to dismiss and repeat with another div. Make sure it shows.
3. [ ] Go to http://www.bennish.net/web-notifications.html and test that clicking on 'Show' pops up a notification asking for permission. Make sure that clicking 'Deny' leads to no notifications being shown.
4. [ ] Go to https://trac.torproject.org/projects/tor/login and make sure that the password can be saved. Make sure the saved password shows up in `about:passwords`. Then reload https://trac.torproject.org/projects/tor/login and make sure the password is autofilled.
5. [ ] Open a github issue and type some misspellings, make sure they are underlined.
6. [ ] Make sure that right clicking on a word with suggestions gives a suggestion and that clicking on the suggestion replaces the text.
7. [ ] Make sure that Command + Click (Control + Click on Windows, Control + Click on Ubuntu) on a link opens a new tab but does NOT switch to it.  Click on it and make sure it is already loaded.
8. [ ] Open an email on http://mail.google.com/ or inbox.google.com and click on a link. Make sure it works.
9. [ ] Test that PDF is loaded at http://www.orimi.com/pdf-test.pdf
10. [ ] Test that https://mixed-script.badssl.com/ shows up as grey not red (no mixed content scripts are run).

## Flash tests
1. [ ] Turn on Flash in about:preferences#security. Test that clicking on 'Install Flash' banner on myspace.com shows a notification to allow Flash and that the banner disappears when 'Allow' is clicked.
2. [ ] Test that flash placeholder appears on http://www.homestarrunner.com

## Autofill tests
1. [ ] Test that autofill works on http://www.roboform.com/filling-test-all-fields

## Session storage

Do not forget to make a backup of your entire `~/Library/Application\ Support/Brave` folder.

1. [ ] Temporarily move away your `~/Library/Application\ Support/Brave/session-store-1` and test that clean session storage works. (`%appdata%\Brave in Windows`, `./config/brave` in Ubuntu)
2. [ ] Test that windows and tabs restore when closed, including active tab.
3. [ ] Move away your entire `~/Library/Application\ Support/Brave` folder (`%appdata%\Brave in Windows`, `./config/brave` in Ubuntu)

## Cookie and Cache

1. [ ] Make a backup of your profile, turn on all clearing in preferences and shut down.  Make sure when you bring the browser back up everything is gone that is specified.
2. [ ] Go to http://samy.pl/evercookie/ and set an evercookie. Check that going to prefs, clearing site data and cache, and going back to the Evercookie site does not remember the old evercookie value.

## Update tests

1. [ ] Test that updating using `BRAVE_UPDATE_VERSION=0.8.3` env variable works correctly.
