### ISSUE TITLE
Manual test Windows x64 per-release items for 0.15.0 RC5

### ISSUE THREAD

**Issue by alexwykoff** [brave/browser-laptop#8490]
Win64 Checklist:
 - [x] 1Password description shows as extension for Google Chrome. ([#8465](https://github.com/brave/browser-laptop/issues/8465))
 - [x] Zoom shortcut not working in 0.15.0 RC3. ([#8438](https://github.com/brave/browser-laptop/issues/8438))
 - [x] About:brave takes *longer than expected* time to fetch version data. ([#8426](https://github.com/brave/browser-laptop/issues/8426))
 - [x] Wallet creation fails on linux and macOS. ([#8423](https://github.com/brave/browser-laptop/issues/8423))
 - [x] Fixed screen reader can't identify extension button. ([#8269](https://github.com/brave/browser-laptop/issues/8269))
 - [x] Syncing site settings exception. ([#8241](https://github.com/brave/browser-laptop/issues/8241))
 - [x] Tab discarding. ([#2388](https://github.com/brave/browser-laptop/issues/2388))

**Comment by srirambv** [comment]
Closing #8490
