### ISSUE TITLE
Manual test OS X per release items for 0.15.0 RC5

### ISSUE THREAD

**Issue by alexwykoff** [brave/browser-laptop#8492]
Mac Checklist:
 - [x] 1Password description shows as extension for Google Chrome. ([#8465](https://github.com/brave/browser-laptop/issues/8465))
 - [x] Zoom shortcut not working in 0.15.0 RC3. ([#8438](https://github.com/brave/browser-laptop/issues/8438))
 - [x] About:brave takes *longer than expected* time to fetch version data. ([#8426](https://github.com/brave/browser-laptop/issues/8426))
 - [x] Wallet creation fails on linux and macOS. ([#8423](https://github.com/brave/browser-laptop/issues/8423))
 - [x] Syncing site settings exception. ([#8241](https://github.com/brave/browser-laptop/issues/8241))
 - [x] Browser doesn't launch on Preview 2 build. ([#8169](https://github.com/brave/browser-laptop/issues/8169))
 - [x] Regression: changing default zoom level affects UI. ([#8144](https://github.com/brave/browser-laptop/issues/8144))
 - [x] Ledger calculation when 0 eligible unpinned sites. ([#8102](https://github.com/brave/browser-laptop/issues/8102))
 - [x] Enabling show include site with autoinclude off shows payment info page when refreshed. ([#8079](https://github.com/brave/browser-laptop/issues/8079))
 - [x] Revert the inlined files on contributionStatement.js (follow up to #7887). ([#8062](https://github.com/brave/browser-laptop/issues/8062))
 - [x] PrintToPDF issue of chromium 57 . ([#8051](https://github.com/brave/browser-laptop/issues/8051))
 - [x] Tab discarding. ([#2388](https://github.com/brave/browser-laptop/issues/2388))
