### ISSUE TITLE
Redux refactoring tracking issue

### ISSUE THREAD

**Issue by NejcZdovc** [brave/browser-laptop#8528]
# General
- [x] Adds reduxComponent (ac5a069)
- [x] Removes last check when component is un-mounting (#8393)
- [x] Removes double call to checkForUpdates (4ec74e8)
- [x] Adds List validation for reduxComponent (#8558, fd3f25c)
- [x] ReduxComponent state is not always saved correctly
- [x] Remove `dispatchProps` from redux (#9310)
- [x] Remove object assign in merge props (#9481)
- [x] Saves computed styles in the state (#9176)
- [x] Use react state manager for redux component (#9403)

# Navigator
@bridiver is working on urlBar related things
- [x] Refactor `Menubar`(#8656)
- [x] Refactor `Navigator` (#8658)
- [x] Refactor `BrowserAction` (#8658)
- [x] Refactor `addEditBookmarkHanger` (#8928)
- [x] Refactor `urlBarSuggestions` (#9051)
- [x] Refactor `publishersToggle` (#9329)
- [x] Refactor `urlBarIcon` (#9415)

# Frame
- [x] Remove ref dependency from Frame (#8336)
- [x] Removes store logic from windowActions (#8381)
- [x] Refactor `Frame` (#8225, c11c1b2e05f)
- [x] Refactor `MessageBox` (#8225)

# Tabs
- [x] Moves tab related files into app folder (#8348)
- [x] Refactor `contextMenus.onTabsToolbarContextMenu`, so that we can remove `activeFrame` object from `Tabs` (#8564)
- [x] Merge `tabs` into `frames` object in windowStore (#8833)
- [x] Refactor window actions, remove the whole frame prop (`closeFrame`, `setTabHoverState`, `setTabBreakpoint`, `moveTab`, `setPreviewFrame`) (#8858)
- [x] Main refactoring (#8396)
- [x] Refactor `TabPage` and `TabPages` (#9414)

# Bookmarks
- [x] Refactor`bookmarksToolbar` and `bookmarkToolbarButton` (#9030)
- [x] Move calc of bookmark item width into the state (#9611)
- [x] Remove non-primitive types from bookmarks (#9713)

# Other components
- [x] Refactor `DownloadsBar` and `DownloadItem` (#9271)
- [x] Refactor `SiteInfo` (#9413)
- [x] Refactor `FindBar` (#9426)
- [x] Refactor `PopupWindow` (#9417)
- [x] Refactor `BraveryPanel` (#9455)
- [x] Refactor `ClearBrowsingDataPanel` (#9457)
- [x] Refactor `ImportBrowserDataPanel` (#9485)
- [x] Refactor `AutofillAddressPanel` (#9490)
- [x] Refactor `NoScriptInfo` (#9494)
- [x] Refactor `ReleaseNotes` (#9496)
- [x] Refactor `UpdateBar` (#9516)
- [x] Refactor `NotificationBar` and `NotificationItem`  (#9518)
- [x] Refactor `ContextMenu` (#9526)
- [x] Refactor `AutofillCreditCardPanel` (#9566)
- [x] Refactor `CheckDefaultBrowserDialog` (#9497)
- [x] Refactor `Main` (#9678)
- [x] Refactor `Window` (#9658)

# Disabled unit tests
- [ ] Frame (`test/unit/js/components/frameTest.js`)

# Impure components (contains non primitive types in mergeProps)
- [ ] Explore possibility to remove `template` prop in `MenuBar`
- [ ] Explore possibility to remove `submenu` prop in `MenuBarItem`
- [x] Refactor `allSiteSettings` in `Frame` component
- [ ] Refactor dnd for tabs  (don't send the whole frame in)

**Comment by NejcZdovc** [comment]
closing as this was done
