### ISSUE TITLE
Generate Exclusion List for 0.15.3

### ISSUE THREAD

**Issue by alexwykoff** [brave/browser-laptop#8618]
Exclusion List:
 - [ ] Node ./tools/downloadSyncClient  fails. ([#8596](https://github.com/brave/browser-laptop/issues/8596))
https://github.com/brave/browser-laptop/issues/8596
 - [ ] Brave is not able to remotely debug a Node.js application. ([#8571](https://github.com/brave/browser-laptop/issues/8571))
https://github.com/brave/browser-laptop/issues/8571
 - [ ] Npm start fails if brave is nested under a folder with spaces in it. ([#8516](https://github.com/brave/browser-laptop/issues/8516))
https://github.com/brave/browser-laptop/issues/8516
 - [ ] Create ScrollableContent element. ([#8505](https://github.com/brave/browser-laptop/issues/8505))
https://github.com/brave/browser-laptop/issues/8505
 - [ ] Improve handling of switching dat file versions. ([#8489](https://github.com/brave/browser-laptop/issues/8489))
https://github.com/brave/browser-laptop/issues/8489
 - [ ] History is not working for Sync. ([#8455](https://github.com/brave/browser-laptop/issues/8455))
https://github.com/brave/browser-laptop/issues/8455
 - [ ] Update to v2.58.5 muon. ([#8445](https://github.com/brave/browser-laptop/issues/8445))
https://github.com/brave/browser-laptop/issues/8445
 - [ ] Notification bar is still visible after restart. ([#8435](https://github.com/brave/browser-laptop/issues/8435))
https://github.com/brave/browser-laptop/issues/8435
 - [ ] Prevent fingerprinting Brave through PDF.JS web_accessible_resources. ([#8365](https://github.com/brave/browser-laptop/issues/8365))
https://github.com/brave/browser-laptop/issues/8365
 - [ ] Move files into app folder (Bookmarks). ([#8351](https://github.com/brave/browser-laptop/issues/8351))
https://github.com/brave/browser-laptop/issues/8351
 - [ ] Move files into app folder (Tabs). ([#8347](https://github.com/brave/browser-laptop/issues/8347))
https://github.com/brave/browser-laptop/issues/8347
 - [ ] Remove ref dependency from Frame. ([#8322](https://github.com/brave/browser-laptop/issues/8322))
https://github.com/brave/browser-laptop/issues/8322
 - [ ] Lock npm versions. ([#8283](https://github.com/brave/browser-laptop/issues/8283))
https://github.com/brave/browser-laptop/issues/8283
 - [ ] Discard .genericForm and .commonForm from forms.less. ([#8010](https://github.com/brave/browser-laptop/issues/8010))
https://github.com/brave/browser-laptop/issues/8010
 - [ ] Re-enable npm travis caching. ([#7820](https://github.com/brave/browser-laptop/issues/7820))
https://github.com/brave/browser-laptop/issues/7820
 - [ ] Investigate & block social media ads and tracking. ([#7678](https://github.com/brave/browser-laptop/issues/7678))
https://github.com/brave/browser-laptop/issues/7678
 - [ ] Add sharing to social media sites (Facebook, twitter, etc.). ([#7555](https://github.com/brave/browser-laptop/issues/7555))
https://github.com/brave/browser-laptop/issues/7555
 - [ ] Faceblock: FB targeted tracking event assessment & protection. ([#7000](https://github.com/brave/browser-laptop/issues/7000))
https://github.com/brave/browser-laptop/issues/7000
 - [ ] Move page-level alerts to below the tabs bar, and add an overlap nub. ([#6935](https://github.com/brave/browser-laptop/issues/6935))
https://github.com/brave/browser-laptop/issues/6935
 - [ ] Folders and Titles lists in about:bookmarks should scroll independently. ([#5076](https://github.com/brave/browser-laptop/issues/5076))
https://github.com/brave/browser-laptop/issues/5076
 - [ ] Send URL by email. ([#3121](https://github.com/brave/browser-laptop/issues/3121))
https://github.com/brave/browser-laptop/issues/3121

**Comment by alexwykoff** [comment]
Generated 05/05/2017
Exclusion List:
 - [ ] Another context menu appears after displaying an context menu on new tab button. ([#8647](https://github.com/brave/browser-laptop/issues/8647))
https://github.com/brave/browser-laptop/issues/8647
 - [ ] Wallet creation fails due to worker error . ([#8632](https://github.com/brave/browser-laptop/issues/8632))
https://github.com/brave/browser-laptop/issues/8632
 - [ ] Per release issue test for Windows x64 0.15.2 preview 2. ([#8620](https://github.com/brave/browser-laptop/issues/8620))
https://github.com/brave/browser-laptop/issues/8620
 - [ ] Option to disable blocked count badge (on Lion). ([#8613](https://github.com/brave/browser-laptop/issues/8613))
https://github.com/brave/browser-laptop/issues/8613
 - [ ] Node ./tools/downloadSyncClient  fails. ([#8596](https://github.com/brave/browser-laptop/issues/8596))
https://github.com/brave/browser-laptop/issues/8596
 - [ ] Fix tests for Sync. ([#8585](https://github.com/brave/browser-laptop/issues/8585))
https://github.com/brave/browser-laptop/issues/8585
 - [ ] Brave is not able to remotely debug a Node.js application. ([#8571](https://github.com/brave/browser-laptop/issues/8571))
https://github.com/brave/browser-laptop/issues/8571
 - [ ] Uitest script is not available in package.json, but it's mentioned in tests.md. ([#8523](https://github.com/brave/browser-laptop/issues/8523))
https://github.com/brave/browser-laptop/issues/8523
 - [ ] Npm start fails if brave is nested under a folder with spaces in it. ([#8516](https://github.com/brave/browser-laptop/issues/8516))
https://github.com/brave/browser-laptop/issues/8516
 - [ ] Test are failing on linux. ([#8506](https://github.com/brave/browser-laptop/issues/8506))
https://github.com/brave/browser-laptop/issues/8506
 - [ ] Create ScrollableContent element. ([#8505](https://github.com/brave/browser-laptop/issues/8505))
https://github.com/brave/browser-laptop/issues/8505
 - [ ] Update to v2.58.8 muon. ([#8445](https://github.com/brave/browser-laptop/issues/8445))
https://github.com/brave/browser-laptop/issues/8445
 - [ ] Move files into app folder (Bookmarks). ([#8351](https://github.com/brave/browser-laptop/issues/8351))
https://github.com/brave/browser-laptop/issues/8351
 - [ ] Move files into app folder (Tabs). ([#8347](https://github.com/brave/browser-laptop/issues/8347))
https://github.com/brave/browser-laptop/issues/8347
 - [ ] Remove ref dependency from Frame. ([#8322](https://github.com/brave/browser-laptop/issues/8322))
https://github.com/brave/browser-laptop/issues/8322
 - [ ] Discard .genericForm and .commonForm from forms.less. ([#8010](https://github.com/brave/browser-laptop/issues/8010))
https://github.com/brave/browser-laptop/issues/8010
 - [ ] When writing session to disk, ensure we do a flush. ([#7876](https://github.com/brave/browser-laptop/issues/7876))
https://github.com/brave/browser-laptop/issues/7876
 - [ ] Re-enable npm travis caching. ([#7820](https://github.com/brave/browser-laptop/issues/7820))
https://github.com/brave/browser-laptop/issues/7820
 - [ ] Investigate & block social media ads and tracking. ([#7678](https://github.com/brave/browser-laptop/issues/7678))
https://github.com/brave/browser-laptop/issues/7678
 - [ ] All video in Brave should default with autoplay=false, w/site level opt-in exceptions. ([#7663](https://github.com/brave/browser-laptop/issues/7663))
https://github.com/brave/browser-laptop/issues/7663
 - [ ] Add sharing to social media sites (Facebook, twitter, etc.). ([#7555](https://github.com/brave/browser-laptop/issues/7555))
https://github.com/brave/browser-laptop/issues/7555
 - [ ] Faceblock: FB targeted tracking event assessment & protection. ([#7000](https://github.com/brave/browser-laptop/issues/7000))
https://github.com/brave/browser-laptop/issues/7000
 - [ ] Move page-level alerts to below the tabs bar, and add an overlap nub. ([#6935](https://github.com/brave/browser-laptop/issues/6935))
https://github.com/brave/browser-laptop/issues/6935
 - [ ] Automated test failure on application window. ([#6808](https://github.com/brave/browser-laptop/issues/6808))
https://github.com/brave/browser-laptop/issues/6808
 - [ ] Automated test failures on bookmark. ([#6667](https://github.com/brave/browser-laptop/issues/6667))
https://github.com/brave/browser-laptop/issues/6667
 - [ ] Automated test failures on navigationBar. ([#6666](https://github.com/brave/browser-laptop/issues/6666))
https://github.com/brave/browser-laptop/issues/6666
 - [ ] Folders and Titles lists in about:bookmarks should scroll independently. ([#5076](https://github.com/brave/browser-laptop/issues/5076))
https://github.com/brave/browser-laptop/issues/5076
 - [ ] Fix failing automated tests. ([#4329](https://github.com/brave/browser-laptop/issues/4329))
https://github.com/brave/browser-laptop/issues/4329
 - [ ] Add option to enable/disable HTML5 autoplay. ([#4045](https://github.com/brave/browser-laptop/issues/4045))
https://github.com/brave/browser-laptop/issues/4045
 - [ ] Send URL by email. ([#3121](https://github.com/brave/browser-laptop/issues/3121))
https://github.com/brave/browser-laptop/issues/3121
 - [ ] Block autoplay videos. ([#2227](https://github.com/brave/browser-laptop/issues/2227))
https://github.com/brave/browser-laptop/issues/2227

**Comment by alexwykoff** [comment]
Updated 05/23/2017:

Exclusion List:
 - [ ] Fix various sorting problems with url suggestions. ([#8994](https://github.com/brave/browser-laptop/issues/8994))
https://github.com/brave/browser-laptop/issues/8994
 - [ ] With pinned tabs, creating enough tabs causes tabs set shift. ([#8909](https://github.com/brave/browser-laptop/issues/8909))
https://github.com/brave/browser-laptop/issues/8909
 - [ ] APP_TAB_CLOSE_REQUESTED needs tests. ([#8875](https://github.com/brave/browser-laptop/issues/8875))
https://github.com/brave/browser-laptop/issues/8875
 - [ ] Hiding menu shows empty white space. ([#8839](https://github.com/brave/browser-laptop/issues/8839))
https://github.com/brave/browser-laptop/issues/8839
 - [ ] Remove BUILD env var for cibuild script. ([#8777](https://github.com/brave/browser-laptop/issues/8777))
https://github.com/brave/browser-laptop/issues/8777
 - [ ] History slow with 10K bookmarks. ([#8767](https://github.com/brave/browser-laptop/issues/8767))
https://github.com/brave/browser-laptop/issues/8767
 - [ ] Per release issue test for Windows x64 0.15.2 preview 2. ([#8620](https://github.com/brave/browser-laptop/issues/8620))
https://github.com/brave/browser-laptop/issues/8620
 - [ ] Node ./tools/downloadSyncClient  fails. ([#8596](https://github.com/brave/browser-laptop/issues/8596))
https://github.com/brave/browser-laptop/issues/8596
 - [ ] Fix tests for Sync. ([#8585](https://github.com/brave/browser-laptop/issues/8585))
https://github.com/brave/browser-laptop/issues/8585
 - [ ] Brave is not able to remotely debug a Node.js application. ([#8571](https://github.com/brave/browser-laptop/issues/8571))
https://github.com/brave/browser-laptop/issues/8571
 - [ ] Uitest script is not available in package.json, but it's mentioned in tests.md. ([#8523](https://github.com/brave/browser-laptop/issues/8523))
https://github.com/brave/browser-laptop/issues/8523
 - [ ] Npm start fails if brave is nested under a folder with spaces in it. ([#8516](https://github.com/brave/browser-laptop/issues/8516))
https://github.com/brave/browser-laptop/issues/8516
 - [ ] Test are failing on linux. ([#8506](https://github.com/brave/browser-laptop/issues/8506))
https://github.com/brave/browser-laptop/issues/8506
 - [ ] Create ScrollableContent element. ([#8505](https://github.com/brave/browser-laptop/issues/8505))
https://github.com/brave/browser-laptop/issues/8505
 - [ ] Update to v3.0.200 muon. ([#8445](https://github.com/brave/browser-laptop/issues/8445))
https://github.com/brave/browser-laptop/issues/8445
 - [ ] Move files into app folder (Bookmarks). ([#8351](https://github.com/brave/browser-laptop/issues/8351))
https://github.com/brave/browser-laptop/issues/8351
 - [ ] Move files into app folder (Tabs). ([#8347](https://github.com/brave/browser-laptop/issues/8347))
https://github.com/brave/browser-laptop/issues/8347
 - [ ] Discard .genericForm and .commonForm from forms.less. ([#8010](https://github.com/brave/browser-laptop/issues/8010))
https://github.com/brave/browser-laptop/issues/8010
 - [ ] When writing session to disk, ensure we do a flush. ([#7876](https://github.com/brave/browser-laptop/issues/7876))
https://github.com/brave/browser-laptop/issues/7876
 - [ ] Investigate & block social media ads and tracking. ([#7678](https://github.com/brave/browser-laptop/issues/7678))
https://github.com/brave/browser-laptop/issues/7678
 - [ ] Add sharing to social media sites (Facebook, twitter, etc.). ([#7555](https://github.com/brave/browser-laptop/issues/7555))
https://github.com/brave/browser-laptop/issues/7555
 - [ ] When typing quickly in urlbar, keys are sometimes dropped.. ([#7538](https://github.com/brave/browser-laptop/issues/7538))
https://github.com/brave/browser-laptop/issues/7538
 - [ ] Faceblock: FB targeted tracking event assessment & protection. ([#7000](https://github.com/brave/browser-laptop/issues/7000))
https://github.com/brave/browser-laptop/issues/7000
 - [ ] Move page-level alerts to below the tabs bar, and add an overlap nub. ([#6935](https://github.com/brave/browser-laptop/issues/6935))
https://github.com/brave/browser-laptop/issues/6935
 - [ ] Automated test failure on application window. ([#6808](https://github.com/brave/browser-laptop/issues/6808))
https://github.com/brave/browser-laptop/issues/6808
 - [ ] Automated test failures on bookmark. ([#6667](https://github.com/brave/browser-laptop/issues/6667))
https://github.com/brave/browser-laptop/issues/6667
 - [ ] Automated test failures on navigationBar. ([#6666](https://github.com/brave/browser-laptop/issues/6666))
https://github.com/brave/browser-laptop/issues/6666
 - [ ] Folders and Titles lists in about:bookmarks should scroll independently. ([#5076](https://github.com/brave/browser-laptop/issues/5076))
https://github.com/brave/browser-laptop/issues/5076
 - [ ] Fix failing automated tests. ([#4329](https://github.com/brave/browser-laptop/issues/4329))
https://github.com/brave/browser-laptop/issues/4329
 - [ ] Send URL by email. ([#3121](https://github.com/brave/browser-laptop/issues/3121))
https://github.com/brave/browser-laptop/issues/3121

**Comment by alexwykoff** [comment]
Generated 05/25/2017:
Exclusion List:
 - [ ] Fix various sorting problems with url suggestions. ([#8994](https://github.com/brave/browser-laptop/issues/8994))
https://github.com/brave/browser-laptop/issues/8994
 - [ ] With pinned tabs, creating enough tabs causes tabs set shift. ([#8909](https://github.com/brave/browser-laptop/issues/8909))
https://github.com/brave/browser-laptop/issues/8909
 - [ ] Hiding menu shows empty white space. ([#8839](https://github.com/brave/browser-laptop/issues/8839))
https://github.com/brave/browser-laptop/issues/8839
 - [ ] Remove BUILD env var for cibuild script. ([#8777](https://github.com/brave/browser-laptop/issues/8777))
https://github.com/brave/browser-laptop/issues/8777
 - [ ] History slow with 10K bookmarks. ([#8767](https://github.com/brave/browser-laptop/issues/8767))
https://github.com/brave/browser-laptop/issues/8767
 - [ ] Per release issue test for Windows x64 0.15.2 preview 2. ([#8620](https://github.com/brave/browser-laptop/issues/8620))
https://github.com/brave/browser-laptop/issues/8620
 - [ ] Node ./tools/downloadSyncClient  fails. ([#8596](https://github.com/brave/browser-laptop/issues/8596))
https://github.com/brave/browser-laptop/issues/8596
 - [ ] Brave is not able to remotely debug a Node.js application. ([#8571](https://github.com/brave/browser-laptop/issues/8571))
https://github.com/brave/browser-laptop/issues/8571
 - [ ] Uitest script is not available in package.json, but it's mentioned in tests.md. ([#8523](https://github.com/brave/browser-laptop/issues/8523))
https://github.com/brave/browser-laptop/issues/8523
 - [ ] Npm start fails if brave is nested under a folder with spaces in it. ([#8516](https://github.com/brave/browser-laptop/issues/8516))
https://github.com/brave/browser-laptop/issues/8516
 - [ ] Create ScrollableContent element. ([#8505](https://github.com/brave/browser-laptop/issues/8505))
https://github.com/brave/browser-laptop/issues/8505
 - [ ] Update to v3.0.200 muon. ([#8445](https://github.com/brave/browser-laptop/issues/8445))
https://github.com/brave/browser-laptop/issues/8445
 - [ ] Move files into app folder (Bookmarks). ([#8351](https://github.com/brave/browser-laptop/issues/8351))
https://github.com/brave/browser-laptop/issues/8351
 - [ ] Move files into app folder (Tabs). ([#8347](https://github.com/brave/browser-laptop/issues/8347))
https://github.com/brave/browser-laptop/issues/8347
 - [ ] Discard .genericForm and .commonForm from forms.less. ([#8010](https://github.com/brave/browser-laptop/issues/8010))
https://github.com/brave/browser-laptop/issues/8010
 - [ ] When writing session to disk, ensure we do a flush. ([#7876](https://github.com/brave/browser-laptop/issues/7876))
https://github.com/brave/browser-laptop/issues/7876
 - [ ] Investigate & block social media ads and tracking. ([#7678](https://github.com/brave/browser-laptop/issues/7678))
https://github.com/brave/browser-laptop/issues/7678
 - [ ] When typing quickly in urlbar, keys are sometimes dropped.. ([#7538](https://github.com/brave/browser-laptop/issues/7538))
https://github.com/brave/browser-laptop/issues/7538
 - [ ] Faceblock: FB targeted tracking event assessment & protection. ([#7000](https://github.com/brave/browser-laptop/issues/7000))
https://github.com/brave/browser-laptop/issues/7000
 - [ ] Move page-level alerts to below the tabs bar, and add an overlap nub. ([#6935](https://github.com/brave/browser-laptop/issues/6935))
https://github.com/brave/browser-laptop/issues/6935
 - [ ] Automated test failure on application window. ([#6808](https://github.com/brave/browser-laptop/issues/6808))
https://github.com/brave/browser-laptop/issues/6808
 - [ ] Automated test failures on bookmark. ([#6667](https://github.com/brave/browser-laptop/issues/6667))
https://github.com/brave/browser-laptop/issues/6667
 - [ ] Automated test failures on navigationBar. ([#6666](https://github.com/brave/browser-laptop/issues/6666))
https://github.com/brave/browser-laptop/issues/6666
 - [ ] Folders and Titles lists in about:bookmarks should scroll independently. ([#5076](https://github.com/brave/browser-laptop/issues/5076))
https://github.com/brave/browser-laptop/issues/5076
 - [ ] Fix failing automated tests. ([#4329](https://github.com/brave/browser-laptop/issues/4329))
https://github.com/brave/browser-laptop/issues/4329
 - [ ] Send URL by email. ([#3121](https://github.com/brave/browser-laptop/issues/3121))
https://github.com/brave/browser-laptop/issues/3121
