### ISSUE TITLE
Per release issue tests for Linux 0.15.2 preview 2

### ISSUE THREAD

**Issue by alexwykoff** [brave/browser-laptop#8621]
Linux Checklist:
 - [ ] List in redux component. ([#8557](https://github.com/brave/browser-laptop/issues/8557))
 - [ ] Pinned tabs lose order after re-launch. ([#8543](https://github.com/brave/browser-laptop/issues/8543))
 - [ ] Autocomplete suggests a porn site. ([#8534](https://github.com/brave/browser-laptop/issues/8534))
 - [ ] View Certificate on mixed content site. ([#8530](https://github.com/brave/browser-laptop/issues/8530))
 - [ ] Contribution statement page break needs extra padding. ([#8467](https://github.com/brave/browser-laptop/issues/8467))
 - [ ] Saving torrent file as "Save link as". ([#8463](https://github.com/brave/browser-laptop/issues/8463))
 - [ ] Sync is not tracking & merging changes between pyramids which creates a loss of hierarchy. ([#8454](https://github.com/brave/browser-laptop/issues/8454))
 - [ ] Reduce warmth on top bars to make them cleaner. ([#8425](https://github.com/brave/browser-laptop/issues/8425))
 - [ ] Sync should only upload records when important fields are changed. ([#8415](https://github.com/brave/browser-laptop/issues/8415))
 - [ ] Over aggressive blocking on mail.ru for RUS: Adguard Russian Filter. ([#8398](https://github.com/brave/browser-laptop/issues/8398))
 - [ ] Remove store logic from windowActions. ([#8380](https://github.com/brave/browser-laptop/issues/8380))
 - [ ] Inconsistent 'open in tab' behaviour. ([#8374](https://github.com/brave/browser-laptop/issues/8374))
 - [ ] "Select the last viewed tab" is not working. ([#8357](https://github.com/brave/browser-laptop/issues/8357))
 - [ ] Add sectionTitle components to about:styles. ([#8350](https://github.com/brave/browser-laptop/issues/8350))
 - [ ] Add commonForm components to about:styles. ([#8349](https://github.com/brave/browser-laptop/issues/8349))
 - [ ] Fingerprinting brave via extension resources. ([#8323](https://github.com/brave/browser-laptop/issues/8323))
 - [ ] Useful context menu that includes "Reopen Last Closed Tab" should be available across entire tab bar. ([#8303](https://github.com/brave/browser-laptop/issues/8303))
 - [ ] Insecure connection info shown for about pages and new tab . ([#8299](https://github.com/brave/browser-laptop/issues/8299))
 - [ ] Remove brave.less with sectionTitle.js. ([#8234](https://github.com/brave/browser-laptop/issues/8234))
 - [ ] Add ledger switch to disable contributions to non-verified sites (in advanced settings). ([#8231](https://github.com/brave/browser-laptop/issues/8231))
 - [ ] Refactor clearBrowsingDataPanel with commonForm. ([#8192](https://github.com/brave/browser-laptop/issues/8192))
 - [ ] Update header style on about:preferences pages. ([#8165](https://github.com/brave/browser-laptop/issues/8165))
 - [ ] Clicking Save Torrent File button does not save .torrent file. ([#8146](https://github.com/brave/browser-laptop/issues/8146))
 - [ ] Refactor checkDefaultBrowserDialog.js with commonForm. ([#8137](https://github.com/brave/browser-laptop/issues/8137))
 - [ ] Change breakpoint for close tab icon visibility. ([#8130](https://github.com/brave/browser-laptop/issues/8130))
 - [ ] Refactor autofillCreditCardPanel.js with commonForm. ([#8100](https://github.com/brave/browser-laptop/issues/8100))
 - [ ] Refactor autofillAddressPanel.js with commonForm. ([#8099](https://github.com/brave/browser-laptop/issues/8099))
 - [ ] Bookmarks toolbar: open link in new window. ([#8063](https://github.com/brave/browser-laptop/issues/8063))
 - [ ] View page source doesn't work for local files. ([#8049](https://github.com/brave/browser-laptop/issues/8049))
 - [ ] Unify modal dialogs of payments and sync. ([#8042](https://github.com/brave/browser-laptop/issues/8042))
 - [ ] Refactor payment/history.js. ([#8037](https://github.com/brave/browser-laptop/issues/8037))
 - [ ] Refactor widevinePanel.js and widevineInfo.js with Aphrodite and commonForm. ([#8028](https://github.com/brave/browser-laptop/issues/8028))
 - [ ] Refactor loginRequired.js with Aphrodite and commonForm. ([#8009](https://github.com/brave/browser-laptop/issues/8009))
 - [ ] Alert box with quite lengthy content cannot be closed. ([#7930](https://github.com/brave/browser-laptop/issues/7930))
 - [ ] Refactor popupWindow.less with Aphrodite. ([#7927](https://github.com/brave/browser-laptop/issues/7927))
 - [ ] Increase font size in URL text to match chrome. ([#7848](https://github.com/brave/browser-laptop/issues/7848))
 - [ ] Bookmark submenu in kabob menu is not dismissed when moved away . ([#7816](https://github.com/brave/browser-laptop/issues/7816))
 - [ ] FAQ bubble should be next to payments on/off switch, not auto-include. ([#7796](https://github.com/brave/browser-laptop/issues/7796))
 - [ ] Restructure paymentTab.js. ([#7750](https://github.com/brave/browser-laptop/issues/7750))
 - [ ] New Session tab submenu goes off screen . ([#7748](https://github.com/brave/browser-laptop/issues/7748))
 - [ ] URL bar suggestions can only be navigated using down key when suggestion list is shown. ([#7682](https://github.com/brave/browser-laptop/issues/7682))
 - [ ] Solve issue where black favicons on black tabs are invisible. ([#7635](https://github.com/brave/browser-laptop/issues/7635))
 - [ ] When the browser dives into an anonize2 crypto operation, it is unresponsive for a second or so. ([#7344](https://github.com/brave/browser-laptop/issues/7344))
 - [ ] Custom filters block resource too strictly. ([#6883](https://github.com/brave/browser-laptop/issues/6883))
 - [ ] Replace input and select elements with <FormTextbox> and <FormDropdown> in .bookmarkFormTable. ([#6777](https://github.com/brave/browser-laptop/issues/6777))
 - [ ]  bookmark modal animation is incredibly slow. ([#6748](https://github.com/brave/browser-laptop/issues/6748))
 - [ ] Opening PDF via Wayback Machine archive.org loads different URL. ([#6726](https://github.com/brave/browser-laptop/issues/6726))
 - [ ] New Tab context menu is retained even after clicking one new tab button. ([#6700](https://github.com/brave/browser-laptop/issues/6700))
 - [ ] Remove wideButton class from the buttons on the Edit Bookmark dialog . ([#6400](https://github.com/brave/browser-laptop/issues/6400))
 - [ ] Apply commonForm to addEditBookmarkHanger.js. ([#6040](https://github.com/brave/browser-laptop/issues/6040))
 - [ ] Increase bookmark text size. ([#4050](https://github.com/brave/browser-laptop/issues/4050))
 - [ ] Allow zoom for UI elements (including font size). ([#1937](https://github.com/brave/browser-laptop/issues/1937))
 - [ ] Use API: app.dock.downloadFinished(filePath). ([#1667](https://github.com/brave/browser-laptop/issues/1667))

**Comment by luixxiul** [comment]
Checked based on the milestone: https://github.com/brave/browser-laptop/issues?page=1&q=is%3Aissue+milestone%3A0.15.2+is%3Aclosed

From that link I also checked issues which have not been added the label of either `QA/steps-specified` or `release-notes/include`. 

Some issues are not checked due to lack of information, which will be provided later. They are checked with the next builds.
