### ISSUE TITLE
Convert React ContextMenu items to native context menu

### ISSUE THREAD

**Issue by bsclifton** [brave/browser-laptop#8641]
This issue is meant to track places which use our React component which we can convert to using native context menus.  This works great on Windows and Linux, but macOS causes video to freeze when the context menu is presented.  The above PR makes that process async

Places we can update:
- [x] new tab button (completed with https://github.com/brave/browser-laptop/pull/8397)
- [x] reload / stop button (has reload / clean reload, #9571)
- [ ] menubar on Windows (we should be able to do this now, since the PR above is macOS only)
... TODO: document other places...

Places we can consider updating (which have moderate difficulty):
- [ ] Bookmarks toolbar folders (would require us to load favicons into the context menu). This would fix https://github.com/brave/browser-laptop/issues/4745
... TODO: document other places...

Places which we shouldn't change (requires a lot of extra work to do natively):
- Hamburger / Kabob menu (since it has zoom buttons; this would require OS specific code)
- Back / Forward navigation already have a different UI planned. See https://github.com/brave/browser-laptop/issues/2737

cc: @Liunkae

**Comment by Liunkae** [comment]
@bsclifton What about the Windows menubar?

**Comment by bsclifton** [comment]
@Liunkae that would be a REALLY nice one actually! Good catch 😄

**Comment by darkdh** [comment]
I do see something about drag and drop handling in `MenuController` of `ui/views/controls/menu/menu_controller.cc`

**Comment by bsclifton** [comment]
@Liunkae did you want to redo the reload/stop button with native context menu?  I remember you had originally submitted the PR with it as a native menu, but we changed back (at my request, since macOS menus were sync at the time)

**Comment by Liunkae** [comment]
Sure. I opened #9571 for this.
