### ISSUE TITLE
Extension: MetaMask

### ISSUE THREAD

**Issue by jonathansampson** [brave/browser-laptop#8671]
Extension: [MetaMask](https://chrome.google.com/webstore/detail/metamask/nkbihfbeogaeaoehlefnkodbefgpgknn)

![image](https://cloud.githubusercontent.com/assets/815158/25688786/9f7f8c76-3047-11e7-8070-7d66c9145c5f.png)

For development purposes, the background page for this extension can be accessed by navigating to the following URL: chrome-extension://dkjoiblfkdpnahoolgkbmgihdfkflnkm/_generated_background_page.html

## Needed APIs:

**chrome.browserAction**

- [x] #5367 chrome.browserAction.setBadgeBackgroundColor ([docs](https://developer.chrome.com/extensions/browserAction#method-setBadgeBackgroundColor))
- [x] #5366 chrome.browserAction.setBadgeText ([docs](https://developer.chrome.com/extensions/browserAction#method-setBadgeText))

**chrome.extension**

- [x] #8688 chrome.extension.getURL ([docs](https://developer.chrome.com/extensions/extension#method-getURL), _deprecated_)

**chrome.runtime**

- [x] #8682 chrome.runtime.connect ([docs](https://developer.chrome.com/extensions/runtime#method-connect))
- [x] #8683 chrome.runtime.getManifest ([docs](https://developer.chrome.com/extensions/runtime#method-getManifest))
- [x] #8684 chrome.runtime.onConnect.addListener ([docs](https://developer.chrome.com/extensions/runtime#event-onConnect))
- [x] #8685 chrome.runtime.onInstalled.addListener ([docs](https://developer.chrome.com/extensions/runtime#event-onConnect))(https://github.com/brave/muon/pull/344)
- [x] ~#8686 chrome.runtime.reload ([docs](https://developer.chrome.com/extensions/runtime#method-reload))~

**chrome.tabs**

- [x] #8680 chrome.tabs.create ([docs](https://developer.chrome.com/extensions/tabs#method-create))

**chrome.windows**

- [x] #6789 chrome.windows.create ([docs](https://developer.chrome.com/extensions/windows#method-create))(https://github.com/brave/muon/pull/295)
- [x] #8677 chrome.windows.getAll ([docs](https://developer.chrome.com/extensions/windows#method-getAll))
- [x] #8678 chrome.windows.remove ([docs](https://developer.chrome.com/extensions/windows#method-remove))
- [x] #8679 chrome.windows.update ([docs](https://developer.chrome.com/extensions/windows#method-update))

**Comment by kevinlawler** [comment]
Snapshot of working/non-working functionality as of this morning:

    Window loads when fox icon clicked: Yes
    Accepting Terms works:              Yes
    Saving secret words works:          Yes
    Main account page displayed:        Yes
    Switching networks:                 Yes
    Switch accounts page displays:      Yes
    Hamburger menu displays:            Yes
    Create additional account:          Yes
    Etherscan Link:                     Yes
    Buy from Coinbase, full flow        Yes
    Close window button after CB buy    No
    "Continue to Coinbase"              Yes, No if switched back from Shapeshift
    Buy:                                Yes (checked w/ Coinbase)
    Send:                               Yes (checked w/ Coinbase)
    Coinbase confirmed:                 Yes
    Badge:                              Yes, seemed to work for me
    Website integration:                Yes* (*no window appears, must click)
    Web window appears automatically:   No
    Website integration, full flow:     Yes (for both successes and failures)

**Comment by bsclifton** [comment]
@kevinlawler we merged your changes with https://github.com/brave/browser-laptop/pull/9647; is there anything needed before we close this issue? It looks like some of the items above are still marked as `open`... but they may be optional or just referenced this issue.  I am thinking this can be closed?

**Comment by kevinlawler** [comment]
@bsclifton leave this issue open. we use these to track the remaining incompatibilities

**Comment by bsclifton** [comment]
@kevinlawler OK sounds great! I'll remove milestone

**Comment by bneiluj** [comment]
Any news on Metamask extension ?

**Comment by darkdh** [comment]
nothing blocks Metamask now :wink:

**Comment by bbondy** [comment]
Closing since this is included.
