### ISSUE TITLE
Manual tests for Windows x64 0.15.3

### ISSUE THREAD

**Issue by alexwykoff** [brave/browser-laptop#8725]
Win64 Checklist:
 - [ ] Remove the legacy code under paymentsContainer. ([#8722](https://github.com/brave/browser-laptop/issues/8722))
 - [ ] Fallback extension to local data always when extension is disabled. ([#8720](https://github.com/brave/browser-laptop/issues/8720))
 - [ ] Base64-js is not found. ([#8712](https://github.com/brave/browser-laptop/issues/8712))
 - [ ] Switch from node-uuid to uuid. ([#8667](https://github.com/brave/browser-laptop/issues/8667))
 - [ ] Browser crashes when trying to save image. ([#8665](https://github.com/brave/browser-laptop/issues/8665))
 - [ ] 'Brave wallet QR code' should be localizable. ([#8663](https://github.com/brave/browser-laptop/issues/8663))
 - [ ] Remove duplicate localization strings (bitcoinAddress and bitcoinPaymentURL). ([#8662](https://github.com/brave/browser-laptop/issues/8662))
 - [ ] Browser crash with payment enabled when clearing browsing data. ([#8659](https://github.com/brave/browser-laptop/issues/8659))
 - [ ] Redux component - Menubar. ([#8652](https://github.com/brave/browser-laptop/issues/8652))
 - [ ] Text inside siteInfo__wrapper should be unselectable. ([#8650](https://github.com/brave/browser-laptop/issues/8650))
 - [ ] Set border-radius to CommonFormBottomWrapper. ([#8649](https://github.com/brave/browser-laptop/issues/8649))
 - [ ] Saving a page/torrent file crashes browser. ([#8648](https://github.com/brave/browser-laptop/issues/8648))
 - [ ] Edit bookmark modal needs refactoring for UI scale . ([#8634](https://github.com/brave/browser-laptop/issues/8634))
 - [ ] Use muon.file.writeImportant to write ledger files. ([#8602](https://github.com/brave/browser-laptop/issues/8602))
 - [ ] Sync alert needs refactoring followup to #8044. ([#8598](https://github.com/brave/browser-laptop/issues/8598))
 - [ ] Add BrowserButton component. ([#8568](https://github.com/brave/browser-laptop/issues/8568))
 - [ ] Remove whole frame from onTabsToolbarContextMenu. ([#8562](https://github.com/brave/browser-laptop/issues/8562))
 - [ ] List in redux component. ([#8557](https://github.com/brave/browser-laptop/issues/8557))
 - [ ] Pinned tabs reappear next load after unpinning. ([#8477](https://github.com/brave/browser-laptop/issues/8477))
 - [ ] Pad lock is retained when url text is cut from context menu. ([#8468](https://github.com/brave/browser-laptop/issues/8468))
 - [ ] Sync is not tracking & merging changes between pyramids which creates a loss of hierarchy. ([#8454](https://github.com/brave/browser-laptop/issues/8454))
 - [ ] Reduce warmth on top bars to make them cleaner. ([#8425](https://github.com/brave/browser-laptop/issues/8425))
 - [ ] Redux component - Frame. ([#8392](https://github.com/brave/browser-laptop/issues/8392))
 - [ ] Empty Modal Covers GlennBeck.com. ([#8390](https://github.com/brave/browser-laptop/issues/8390))
 - [ ] Fingerprinting brave via extension resources. ([#8323](https://github.com/brave/browser-laptop/issues/8323))
 - [ ] Autofill should automatically move cursor to first entry when adding a new record. ([#8280](https://github.com/brave/browser-laptop/issues/8280))
 - [ ] Refactor modalOverlay with Aphrodite. ([#8054](https://github.com/brave/browser-laptop/issues/8054))
 - [ ] Unify modal dialogs of payments and sync. ([#8042](https://github.com/brave/browser-laptop/issues/8042))
 - [ ] When fullscreen (on macOS), move the nav controls left. ([#7872](https://github.com/brave/browser-laptop/issues/7872))
 - [ ] New Session tab submenu goes off screen . ([#7748](https://github.com/brave/browser-laptop/issues/7748))
 - [ ] When maximized, hitboxes seem off for buttons and address bar. ([#7641](https://github.com/brave/browser-laptop/issues/7641))
 - [ ] Maximizing window puts the bottom 1px of window behind the taskbar. ([#7215](https://github.com/brave/browser-laptop/issues/7215))
 - [ ] Re-import to bookmark toolbar will mess up the order. ([#7194](https://github.com/brave/browser-laptop/issues/7194))
 - [ ] Make buttons alignment consistent across different modals. ([#6372](https://github.com/brave/browser-laptop/issues/6372))
 - [ ] Maximizing browser extends into second monitor. ([#5159](https://github.com/brave/browser-laptop/issues/5159))
 - [ ] Use API: app.dock.downloadFinished(filePath). ([#1667](https://github.com/brave/browser-laptop/issues/1667))
 - [ ] Add the ability to close developer tools via keyboard shortcut. ([#45](https://github.com/brave/browser-laptop/issues/45))

**Comment by alexwykoff** [comment]
Generated 05/15/2017:
Win64 Checklist:
 - [ ] MacOS copy issue is back. ([#8876](https://github.com/brave/browser-laptop/issues/8876))
 - [ ] Autocomplete suggestion is way off . ([#8870](https://github.com/brave/browser-laptop/issues/8870))
 - [ ] URL Completion Breaks Additional Input. ([#8865](https://github.com/brave/browser-laptop/issues/8865))
 - [ ] Autoplay refactor. ([#8847](https://github.com/brave/browser-laptop/issues/8847))
 - [ ] Home button is broken in 0.15.303. ([#8845](https://github.com/brave/browser-laptop/issues/8845))
 - [ ] Tab preview causes the tab content to be still shown as a preview rather than loading the content. ([#8842](https://github.com/brave/browser-laptop/issues/8842))
 - [ ] Fixed window border on Windows: focused blue / unfocused gray (broke ~0.15.0). ([#8778](https://github.com/brave/browser-laptop/issues/8778))
 - [ ] Dropping a URL onto URL bar regressed creating a new tab. ([#8750](https://github.com/brave/browser-laptop/issues/8750))
 - [ ] Pressing Enter doesn't load the typed in URL or search term. ([#8741](https://github.com/brave/browser-laptop/issues/8741))
 - [ ] Ctrl+W does not close a tab until another tab is hovered. ([#8740](https://github.com/brave/browser-laptop/issues/8740))
 - [ ] Video doesn't play when opened. ([#8738](https://github.com/brave/browser-laptop/issues/8738))
 - [ ] URL parsing is slow. ([#8707](https://github.com/brave/browser-laptop/issues/8707))
 - [ ] Switch from node-uuid to uuid. ([#8667](https://github.com/brave/browser-laptop/issues/8667))
 - [ ] Redux component - Navigator. ([#8651](https://github.com/brave/browser-laptop/issues/8651))
 - [ ] Another context menu appears after displaying an context menu on new tab button. ([#8647](https://github.com/brave/browser-laptop/issues/8647))
 - [ ] Back/Forward bindings change wrong tab; causes empty new tab. ([#8640](https://github.com/brave/browser-laptop/issues/8640))
 - [ ] Browser background process continues to run after closing the browser window. ([#8629](https://github.com/brave/browser-laptop/issues/8629))
 - [ ] Swipe back/forward is not working. ([#8627](https://github.com/brave/browser-laptop/issues/8627))
 - [ ]  Brave quits when New Tab command issued without window. ([#8575](https://github.com/brave/browser-laptop/issues/8575))
 - [ ] Remove whole frame from onTabsToolbarContextMenu. ([#8562](https://github.com/brave/browser-laptop/issues/8562))
 - [ ] List in redux component. ([#8557](https://github.com/brave/browser-laptop/issues/8557))
 - [ ] Sync is not tracking & merging changes between pyramids which creates a loss of hierarchy. ([#8454](https://github.com/brave/browser-laptop/issues/8454))
 - [ ] Remove ref dependency from Frame. ([#8322](https://github.com/brave/browser-laptop/issues/8322))
 - [ ] Mouse cursor visible while in full screen. ([#7966](https://github.com/brave/browser-laptop/issues/7966))
 - [ ] When fullscreen (on macOS), move the nav controls left. ([#7872](https://github.com/brave/browser-laptop/issues/7872))
 - [ ] Tab title often isn't updated until the cursor is moved over it or tab focus is changed. ([#7765](https://github.com/brave/browser-laptop/issues/7765))
 - [ ] All video in Brave should default with autoplay=false, w/site level opt-in exceptions. ([#7663](https://github.com/brave/browser-laptop/issues/7663))
 - [ ] When the browser dives into an anonize2 crypto operation, it is unresponsive for a second or so. ([#7344](https://github.com/brave/browser-laptop/issues/7344))
 - [ ] Maximizing browser extends into second monitor. ([#5159](https://github.com/brave/browser-laptop/issues/5159))
 - [ ] Add option to enable/disable HTML5 autoplay. ([#4045](https://github.com/brave/browser-laptop/issues/4045))
 - [ ] Integrate password manager autofill with browser autofill. ([#3530](https://github.com/brave/browser-laptop/issues/3530))
 - [ ] Block autoplay videos. ([#2227](https://github.com/brave/browser-laptop/issues/2227))
 - [ ] Use API: app.dock.downloadFinished(filePath). ([#1667](https://github.com/brave/browser-laptop/issues/1667))
 - [ ] Add the ability to close developer tools via keyboard shortcut. ([#45](https://github.com/brave/browser-laptop/issues/45))

**Comment by alexwykoff** [comment]
Updated 05/23/2017 (needs minor dedup vs prior run):
 - [ ] URL Suggestions from History should sort by recently visited. ([#8982](https://github.com/brave/browser-laptop/issues/8982))
 - [ ] Background pages don't preserve bookmarked icon when later clicked.. ([#8977](https://github.com/brave/browser-laptop/issues/8977))
 - [ ] Importing bookmarks throws an error for duplicate folder Ids. ([#8970](https://github.com/brave/browser-laptop/issues/8970))
 - [ ] GetSortByDomain throws error on file:/// URLs. ([#8967](https://github.com/brave/browser-laptop/issues/8967))
 - [ ] Update to Chromium 58.0.3029.110. ([#8962](https://github.com/brave/browser-laptop/issues/8962))
 - [ ] WebGL fingerprinting is not blocked. ([#8961](https://github.com/brave/browser-laptop/issues/8961))
 - [ ] Typing fast in URL bar after new tab gets partially cleared. ([#8959](https://github.com/brave/browser-laptop/issues/8959))
 - [ ] Noscript exceptions applies non-http/https exceptions to all origins. ([#8947](https://github.com/brave/browser-laptop/issues/8947))
 - [ ] Browser crashes when maximized and minimized button is click in quick succession. ([#8938](https://github.com/brave/browser-laptop/issues/8938))
 - [ ] Pressing tab when auto-complete is up should cycle through the results. ([#8919](https://github.com/brave/browser-laptop/issues/8919))
 - [ ] Title is not updated when using navigation buttons. ([#8908](https://github.com/brave/browser-laptop/issues/8908))
 - [ ] About:safebrowsing shows shows a blank page. ([#8905](https://github.com/brave/browser-laptop/issues/8905))
 - [ ] 'NOTIFICATIONUPDATEPASSWORD' should be replaced. ([#8900](https://github.com/brave/browser-laptop/issues/8900))
 - [ ] Selecting URL with right arrow key from the pulldown on URL bar re-selects the 1st entry. ([#8899](https://github.com/brave/browser-laptop/issues/8899))
 - [ ] Copying URLbar text opens the autosuggest dialog. ([#8896](https://github.com/brave/browser-laptop/issues/8896))
 - [ ] Spacing is missing between text for new private tab. ([#8895](https://github.com/brave/browser-laptop/issues/8895))
 - [ ] Disable shields shows orange lion head. ([#8889](https://github.com/brave/browser-laptop/issues/8889))
 - [ ] Unable to reorder tabs with drag and drop. ([#8887](https://github.com/brave/browser-laptop/issues/8887))
 - [ ] Kabob zoom buttons only work once. ([#8885](https://github.com/brave/browser-laptop/issues/8885))
 - [ ] Close tab icon only shows for the last tab. ([#8883](https://github.com/brave/browser-laptop/issues/8883))
 - [ ] MacOS copy issue is back. ([#8876](https://github.com/brave/browser-laptop/issues/8876))
 - [ ] Pinned tab shows blank white page when relaunching the browser. ([#8873](https://github.com/brave/browser-laptop/issues/8873))
 - [ ] Autofill suggestion is way off when UI scale and default zoom is changed from default setting. ([#8870](https://github.com/brave/browser-laptop/issues/8870))
 - [ ] Weird flash effect when opening a new tab. ([#8862](https://github.com/brave/browser-laptop/issues/8862))
 - [ ] Refactor window actions, remove the whole frame prop (related to tabs). ([#8857](https://github.com/brave/browser-laptop/issues/8857))
 - [ ]  Regression - Performance - tab switching is slower in 0.15.3xx. ([#8853](https://github.com/brave/browser-laptop/issues/8853))
 - [ ] Links Should Open Focused Tabs. ([#8851](https://github.com/brave/browser-laptop/issues/8851))
 - [ ] New tab always shows about:blank. ([#8850](https://github.com/brave/browser-laptop/issues/8850))
 - [ ]  Regression - importing cookies not working. ([#8849](https://github.com/brave/browser-laptop/issues/8849))
 - [ ] Importer warning doesn't work. ([#8846](https://github.com/brave/browser-laptop/issues/8846))
 - [ ] URL bar "hint text" is too dark, making me want to select and deleted it. ([#8843](https://github.com/brave/browser-laptop/issues/8843))
 - [ ] Cannot switch directly to parent tab after following link which opens new tab. ([#8823](https://github.com/brave/browser-laptop/issues/8823))
 - [ ] Browser crashes randomly on the latest build. ([#8773](https://github.com/brave/browser-laptop/issues/8773))
 - [ ] Base64-js is not found. ([#8712](https://github.com/brave/browser-laptop/issues/8712))
 - [ ] URL parsing is slow. ([#8707](https://github.com/brave/browser-laptop/issues/8707))
 - [ ] URL bar, on every keystroke the browser re-checks if the current location is bookmarked. ([#8703](https://github.com/brave/browser-laptop/issues/8703))
 - [ ] Switch from node-uuid to uuid. ([#8667](https://github.com/brave/browser-laptop/issues/8667))
 - [ ] Swipe back/forward is not working. ([#8627](https://github.com/brave/browser-laptop/issues/8627))
 - [ ] About:blank loads indefinitely. ([#8584](https://github.com/brave/browser-laptop/issues/8584))
 - [ ]  Brave quits when New Tab command issued without window. ([#8575](https://github.com/brave/browser-laptop/issues/8575))
 - [ ] List in redux component. ([#8557](https://github.com/brave/browser-laptop/issues/8557))
 - [ ] Focus switches to pinned tab when a tab is closed. ([#8547](https://github.com/brave/browser-laptop/issues/8547))
 - [ ] About pages shows about:blank when subsequently opened from a new tab. ([#8525](https://github.com/brave/browser-laptop/issues/8525))
 - [ ] Sync is not tracking & merging changes between pyramids which creates a loss of hierarchy. ([#8454](https://github.com/brave/browser-laptop/issues/8454))
 - [ ] Webgl antifingerprint does not work. ([#8448](https://github.com/brave/browser-laptop/issues/8448))
 - [ ] Move navigation logic into new component. ([#8189](https://github.com/brave/browser-laptop/issues/8189))
 - [ ] When fullscreen (on macOS), move the nav controls left. ([#7872](https://github.com/brave/browser-laptop/issues/7872))
 - [ ] Performance : urlbar response is slow when searching across many bookmarks. ([#7453](https://github.com/brave/browser-laptop/issues/7453))
 - [ ] URL bar selects autocomplete result on keypress. ([#5878](https://github.com/brave/browser-laptop/issues/5878))
 - [ ] Maximizing browser extends into second monitor. ([#5159](https://github.com/brave/browser-laptop/issues/5159))
 - [ ] Use API: app.dock.downloadFinished(filePath). ([#1667](https://github.com/brave/browser-laptop/issues/1667))
 - [ ] Add the ability to close developer tools via keyboard shortcut on macOS. ([#45](https://github.com/brave/browser-laptop/issues/45))
