### ISSUE TITLE
Compact Bravery panel tracking issue

### ISSUE THREAD

**Issue by cezaraugusto** [brave/browser-laptop#9016]
TODOs:

- [x] Fix jumpy double digits (#9077)
- ~~[ ] Set text-overflow to `Fingerprinting Protection (?)`~~
- [ ] feature to save the advanced control open/closed state (#4403)
- [ ] feature to avoid opening the advanced control panel when you click the counter
- [x] hide empty scrollbar on bravery panel (#9296)
- [x] `cursor:text` should be replaced with `cursor:auto` on the scroll bar (#9802)

----

*Original title: jumpy double digits when using compact brave panel*

this is a follow-up of #8990. We should add more room for 2 digits to avoid numbers being "jumpy". See below:

![jumpy_double_digits](https://cloud.githubusercontent.com/assets/4672033/26370590/b0afeca2-3fce-11e7-91e1-a95f4225336b.gif)

/cc @luixxiul

**Comment by Jacalz** [comment]
I also would suggest adding the compact bravery panel as the default and having an option to enable classic bravery panel 😉🦁

**Comment by luixxiul** [comment]
@cezaraugusto I would agree. I'll work on that later.

**Comment by Jacalz** [comment]
Also maby make it shift slowly one step to the right when changing to double digits 😉

**Comment by luixxiul** [comment]
> I also would suggest adding the compact bravery panel as the default and having an option to enable classic bravery panel.

I'm not sure if it should be fine (as we are already used to the current panel). I would like to ask @bradleyrichter for his thought.

**Comment by Jacalz** [comment]
I would say that it is okay to change it to the default since Brave hasn't hit 1.0 yet @luixxiul

**Comment by bradleyrichter** [comment]
One more concern I have is with long URLs. Are they truncating?

We may need to adjust the header and put the URL on its own line if it will be truncated more than 30% of the time.

**Comment by luixxiul** [comment]
@bradleyrichter this is my solution:

![long](https://cloud.githubusercontent.com/assets/3362943/26241987/bc58e06e-3cc1-11e7-8517-a155609684e4.gif)

**Comment by luixxiul** [comment]
@cezaraugusto By setting `min-width: 2ch` you would not get the jumpy counters, instead however:

<img width="326" alt="screenshot 2017-05-24 11 28 57" src="https://cloud.githubusercontent.com/assets/3362943/26384452/45b33a5c-4074-11e7-9c94-83805321f93b.png"> <img width="298" alt="screenshot 2017-05-24 11 32 53" src="https://cloud.githubusercontent.com/assets/3362943/26384504/c128c490-4074-11e7-8b5c-95c91be2ebee.png">


I would prefer the jumpy counters (which only can be noticed when you keep opening the panel while loading the page) to the ugly stats to be honest..

**Comment by bradleyrichter** [comment]
I think we can come up with something else that will make it more solid using a fixed width.

Either reduce the text size to allow for more characters or add another row. 

I’ll mock up both options…

**Comment by luixxiul** [comment]
> solid using a fixed width.

That will cause the same issue as #5726, so using fixed width should be avoided and that's why I aligned the elements vertically in one column.

We should have to find out another way but applying fixed width.

**Comment by luixxiul** [comment]
I assume if users are satisfied with fixed width, they will keep using the original panel, which is why I set the compact panel as optional.

**Comment by luixxiul** [comment]
> Either reduce the text size to allow for more characters

+1, would you please let me know which one is acceptable? I'm going to address that, thanks.

**Comment by bradleyrichter** [comment]
@luixxiul When I meant fixed width, I mean to use a width that is dynamic based on the string width for that language. 

Here is a new layout that should solve our issues:

![image](https://cloud.githubusercontent.com/assets/13509546/26425931/7838cf2a-408b-11e7-907f-ea312332ddec.png)

- I added a close button as I have witnessed some user delay for initial closing.
- I rearranged the top area to make room for the long URL
- I adjusted the number area to allow for 1 or 2 numbers. I think this will look cleanest and not matter if digits are updating when the panel is open.

- This also shows a new popup for a future 3-way selection requested by @diracdeltas

**Comment by luixxiul** [comment]
@bradleyrichter nice!

**Comment by luixxiul** [comment]
@cezaraugusto May I change this ticket into a tracking one, to apply the mockup provided by @bradleyrichter ?

**Comment by cezaraugusto** [comment]
sure all yours ;)

**Comment by cezaraugusto** [comment]
ok so based on Slack convo here's Brad's requests:

* master plan is to make this panel the default. I think the plan is to eliminate the old panel
* main concern is that blocking list increase panel width
* better have it 320px min-width, as it works great in English. Other languages would follow that.
* For small screen size, Brad suggested the picture below:

![pasted image at 2017_06_29 11_24 am](https://user-images.githubusercontent.com/4672033/27744217-0c9cf97c-5d95-11e7-9909-19bf7e90ed38.png)

**Comment by bradleyrichter** [comment]
To be extra clear, I don’t want to reduce language to O/I on the switch for normal widths. Shields Down/Up is part of the lingo that we need to retain normally. 

Also, we may be able to avoid this issue just by increasing the min-width slightly.

**Comment by luixxiul** [comment]
@cezaraugusto and I have discusseed and concluded that we would get the minimum strings for each language with l20n and specify the number of the characters to `min-width: Xch`.

**Comment by luixxiul** [comment]
and in this case we should set `max-width` to `90vw` or so to avoid the panel from covering the viewport on small screens.

**Comment by luixxiul** [comment]
> I don’t want to reduce language to O/I on the switch for normal widths.

is it possible to detect with JS that the words overwrap / overflow, to control when to display O/I instead of language?
