### ISSUE TITLE
Transition polish tracking issue

### ISSUE THREAD

**Issue by cezaraugusto** [brave/browser-laptop#9080]
This is a tracker about user experience improvements regarding how we transit between user actions.

> This is open for editions by anyone. However please only open an issue based on this list from the moment you're going to work on the fix. Issues already open are included here and if you find some, please add as well.

## Navigation chrome items (everything that is not on a page nor a tab)
- [ ] back/forward click action should have the active state visible
- [ ] home/reload click action should have the active state visible
- [ ] publisherToggle click action should have the active state visible
- [ ] omnibar active state should have a fade-in active display (see Safari/Opera)
- [ ] kabob menu should have a growing transition (see Firefox). But no caret pls.

## Tabs
- [x] Transition between background should be smooth (see Opera) (addressed with #12565)
- [ ] Closing/Opening a tab should have a slight animation (see Safari) (addressed with #11720)
- [x] Close tab icon should have a smooth transition (addressed partly with #12565)

## NewTab page
- [ ] dnd actions in top sites should be smooth (see Opera)

**Comment by petemill** [comment]
added some PRs that will or partly satisfy some of the tasks

**Comment by cezaraugusto** [comment]
thanks, co-assigning you too let's make it shine ✨
