### ISSUE TITLE
Edited bookmark bugs tracking issue

### ISSUE THREAD

**Issue by luixxiul** [brave/browser-laptop#9120]
- ~~[ ] #8840~~ dupe
- [ ] #8538
- [x] #8022 - fixed with https://github.com/brave/browser-laptop/pull/10136#issue-245629798
- [x] #7032 - fixed with #10819
- [x] #4978 - fixed with https://github.com/brave/browser-laptop/pull/9710
- [x] #4929 - fixed with https://github.com/brave/browser-laptop/pull/10136#issue-245629798
- [x] #4260 - fixed with https://github.com/brave/browser-laptop/pull/10136#issue-245629798
- [ ] #2601

**Comment by luixxiul** [comment]
@NejcZdovc mind checking the issues are thought to have been fixed with #9710? thanks

**Comment by luixxiul** [comment]
Closing as we have just two different issues 👍
