### ISSUE TITLE
Tracking: Critical performance tracking issue

### ISSUE THREAD

**Issue by bsclifton** [brave/browser-laptop#9311]
The goal of this issue is to track our most painful performance impacting issues

## General slowness
- [x] page load tracking issue #6836
- [x] Findbar slowness (cmd + F, typing) #10271
- [x] Application slowness (when opening new tabs, loading a website) #8541
- [x] new-tab URL bar blocked for ~12ms #12130
- [x] Context menu is slow when you have a lot of bookmarks #10054
- [x] Ledger getPublisher perf is bad even if ledger is off #10186 
- [x] Browser freezes per 5 minutes with existing profile #10094 
- [ ] Window restore #10568
- [x] component mergeProps are unnecessarily running #11515

## Tab switching slowness
   - [x] ~In siteUtil.updateSiteFavicon use location cache #9279~
   - [x] ~https://github.com/brave/muon/pull/208 (browser-laptop https://github.com/brave/browser-laptop/issues/9313)~
   - [ ] When pages are unloaded, or loading, and switching to them

## URL bar
- [x] Focus URL bar (cmd + L) and type https://github.com/brave/browser-laptop/issues/7358
- [ ] Findbar slowness and losing of characters (cmd + F, typing) https://github.com/brave/browser-laptop/issues/10606
- [x] ~Address field performance is really bad #6620~
- [ ] New tab (cmd + T) and type
- [ ] Browser freezes when typing in URL bar #11066

## Tab close speed
  - [x] ~Brave Browser very slow to open or close tabs #4848~

## Page navigation
- [ ] When pages are loaded browser doesn't accept user input (event storm?)
- [ ] isResourceEnabled checks [#9987](https://github.com/brave/browser-laptop/issues/9987)
- [x] ~appState.sites sort takes a long time (Every navigation +200 ms [w/ 10K bookmarks]) #9427~
- [x] pages which create multiple entries on visit https://github.com/brave/browser-laptop/issues/3848

## About pages
  -  [ ] Use bloodhound for about:bookmarks
   - [ ] Query bloodhound for about:history

## Worker threads
  - [x] ~Enable worker threads for ledger #9222~
  - [ ] Generate URL suggestions in a worker thread #10187

## Auditing / instrumentation
- [ ] performance auditing using Lighthouse #9719 
- [ ] Automated performance tests #10115

## Bookmark / sites related
- [x] ~Editing a bookmark (or folder) locks up the browser #9674~
- [x] ~Bookmarks should have only primitives #9712~
- [x] Split sites in the app state #9978
- [x] link hover causes re-render https://github.com/brave/browser-laptop/issues/10194

## Reflows

- [ ] Audit DOM APIs that do layout reflows https://github.com/brave/browser-laptop/issues/10027

## Slow startup time
- [x] Improve startup time #3025 more info [here](https://github.com/brave/browser-laptop/issues/3025#issuecomment-323767720) 

## Battery life
- [ ] GPU-related high battery use on MacBook Pro with Touch Bar #6443

**Comment by ayumi** [comment]
Tab switching slowness should be improved by https://github.com/brave/muon/pull/208 (browser-laptop https://github.com/brave/browser-laptop/issues/9313).

**Comment by bsclifton** [comment]
@ayumi awesome! We're currently on [4.0.0](https://github.com/brave/muon/commits/v4.0.0) which doesn't have the fix... so we'll need a new build. The work you did with https://github.com/brave/browser-laptop/pull/9279 helps a great deal if the tab isn't loaded yet (ex: after you open browser OR if tab is unloaded due to tab discarding)

**Comment by ayumi** [comment]
I've been experiencing an intense slowness when using the browser UI/chrome (browser with 3K bookmarks). I have a bookmarks toolbar with stuff in it, and when I hover over it takes 2000 ms before buttons get the hover effect (highlighting to suggest clickability).

**Comment by NejcZdovc** [comment]
@ayumi on master or 0.17? for master (0.19) this PR should fix perf problems #9713

**Comment by ayumi** [comment]
@NejcZdovc On both master (0562bf4f88f2e285c69c62b86a8c407618100aab) and the current preview release.

**Comment by NejcZdovc** [comment]
for master I have a PR up, but for the current release it's not relevant, because we merged redux for bookmarks in 0.19

**Comment by ayumi** [comment]
@NejcZdovc Sorry I checked again and the latest preview is okay (	0.17.13 rev	f7242c7) – the UI slowness was just in master.

**Comment by NejcZdovc** [comment]
Make sense, so that PR should fix this slowness. It's already done, but we want to improve one more thing

**Comment by bsclifton** [comment]
Most (if not all) of these issues should be addressed with [brave-core](https://github.com/brave/brave-browser)

For folks that want to try specific issues with an experimental release of our new product, you can download a recent release and try it out:
https://github.com/brave/brave-browser/releases
