### ISSUE TITLE
Overall Bookmark Manager Improvement Tracking Issue

### ISSUE THREAD

**Issue by cezaraugusto** [brave/browser-laptop#9312]
### Compact bookmarks view
  - [ ] this means having one pane, not two
  - [ ] mix folders and bookmarks together (see chrome) if done right, can be added as a control (ex: show as side panel)

### Things we can also do:
  - [ ] count of how many items contained inside
  - [ ] multi-non-linear mixed select (select folders + bookmarks at the same time)
  - [ ] show “insert bar” when dragging items (so you see where it lands) in addition to current selection for reordering
  - [ ] option+drag to drag a copy to new location
  - [ ] open folder of BMs as new tabs
  - [ ] add BM to dashboard
  - [ ] drag bookmark to
    - [ ] tab bar
    - [ ] to BM bar
    - [ ]  to URL bar (typed and ready to edit but not loaded yet)

### Tools to help manage bookmark
- [ ] clean sweep 404 BMs (click to find identify broken bookmarks; maybe put them in a trash folder)
- [ ] update FAV icon button
- [ ] selective import

related: #9120

**Comment by bsclifton** [comment]
Removing milestone for now- we can discuss in a triage meeting

**Comment by srirambv** [comment]
Adding one more to the list based on user feedback in [community](https://community.brave.com/t/bookmark-manager-hard-to-use-and-move-everything-in-an-imported-folder-to-the-bookmarks-bar/4495/2)
- [ ]  Multi-select Bookmark folder and drag (similar to multi-select bookmarks)

**Comment by jamesray1** [comment]
@srirambv yes, be able to select all the contents (files and folders) e.g. with CTRL+A, CTRL, SHIFT etc. To do this, the right pane would need to show files and folders, not just files as it does now.

**Comment by tommyquite** [comment]
Adding website logos to the bookmarks (or the option to add), to make it more visible, would also be very useful.

**Comment by NejcZdovc** [comment]
@tommyquite are you talking about favicons? If so, you can enable it in Preferences, under General tab
![image](https://user-images.githubusercontent.com/9574457/28433811-59f5ccdc-6d8d-11e7-95e2-0ae771bfe892.png)

**Comment by tommyquite** [comment]
Yes, sorry missed that, so nvm. Thanks!

**Comment by NejcZdovc** [comment]
Sure not a problem :smiley:

**Comment by LaurenWags** [comment]
+1 from community - user has a large number of bookmarks and is noticing terrible performance. User also recorded a video which is in the community post outlining issues: https://community.brave.com/t/terrible-bookmark-manager-performance/5372

**Comment by NejcZdovc** [comment]
@LaurenWags I watched his video and this Is something that should already be addressed.

1) bookmark dialog is slow -> #9710
2) bookmarks are slow in general -> #10136

**Comment by LaurenWags** [comment]
Thanks @NejcZdovc - I'll let the user know some fixes are coming.

**Comment by derz00** [comment]
Trying to read what is included in these suggestions, but it is not clear. Is one thing that is waiting to be added the ability to move folders around in the Bookmarks Manager (about:bookmarks)? Also, there is a folder called "Other Bookmarks" besides the Bookmarks Toolbar. When I put a bookmark in there, it is removed from the original folder, but is not to be found in "Other Bookmarks". I would like to put entire folders in there, but am glad it is so far not possible to drag whole folders into different folders, or I would have lost the whole folder. Thanks for reading, and clarifying my confusion. 👋

**Comment by luixxiul** [comment]
@derz00 many of the issues will be fixed with 0.20, so let's see if they'll still exist then 😄

**Comment by deoxal** [comment]
I am not sure if this was mentioned or not in the post based off of how it was written, but I would like to be able to open and close the drop down menus of the folders, just like in chrome, so I can easily navigate each of them. It is a hierarchical tree after all.

**Comment by myale** [comment]
ok i didnt see these requests i have unless i missed them...

1. auto bookmark A-z 
2 Top 5 to 25 we can lock as revisted sites) i little different than recent bookmarks
3.  Bookmark EXPORT  to CVS File (all excel versions  with table formatted already set)  i know in the past when this was available in other browsers, trying to import the cvs file to excel would not always properly load no matter what i did) (THIS IS WHAT I WANT MOST...  I hate specialized browser file name backups  
4.   add say a note function that would allow us to make a note regarding the bookmark (an example... Friend runs this site or   Merged with Microsoft  (github is doing so) or this cellfone is better than that cellfone)
5. a Print tool for all bookmarks or selected folders would be cool (for sharing with a friend(social sharing diffrent))

thats enough fer now :)
Thanks

**Comment by tp0** [comment]
* Keyboard navigation like in Chromium's vanilla manager.
