### ISSUE TITLE
Tracking: About pages split up, refactor and testing issue

### ISSUE THREAD

**Issue by cezaraugusto** [brave/browser-laptop#9484]
This is likely a split of https://github.com/brave/browser-laptop/wiki/Refactoring-Components for about pages and purpose is to serve more as a pre-reduxComponent tracking issue. 

### about:about
- [ ] Move to `/app` folder
- [ ] Split components for better maintance
- [ ] Add unit tests if they are missing
- [ ] Move state logic for a Redux-like pattern instead of Flux-like
- [x] ~Aphrodite all the things~

### about:adblock
- [ ] Move to `/app` folder
- [ ] Split components for better maintance
- [ ] Add unit tests if they are missing
- [ ] Move state logic for a Redux-like pattern instead of Flux-like
- [x] ~Aphrodite all the things~

### about:autofill
- [ ] Move to `/app` folder
- [ ] Split components for better maintance
- [ ] Add unit tests if they are missing
- [ ] Move state logic for a Redux-like pattern instead of Flux-like
- [x] ~Aphrodite all the things~

### about:bookmarks
- [ ] Move to `/app` folder
- [ ] Split components for better maintance
- [ ] Add unit tests if they are missing
- [ ] Move state logic for a Redux-like pattern instead of Flux-like
- [x] ~Aphrodite all the things~

### about:brave
- [ ] Move to `/app` folder
- [ ] Split components for better maintance
- [ ] Add unit tests if they are missing
- [ ] Move state logic for a Redux-like pattern instead of Flux-like
- [x] ~Aphrodite all the things~

### about:certerror
- [ ] Move to `/app` folder
- [ ] Split components for better maintance
- [ ] Add unit tests if they are missing
- [ ] Move state logic for a Redux-like pattern instead of Flux-like
- [x] ~Aphrodite all the things~

### about:contribuitions
- [ ] Move to `/app` folder
- [ ] Split components for better maintance
- [ ] Add unit tests if they are missing
- [ ] Move state logic for a Redux-like pattern instead of Flux-like
- [x] ~Aphrodite all the things~

### about:downloads
- [ ] Move to `/app` folder
- [ ] Split components for better maintance
- [ ] Add unit tests if they are missing
- [ ] Move state logic for a Redux-like pattern instead of Flux-like
- [x] ~Aphrodite all the things~

### about:error
- [ ] Move to `/app` folder
- [ ] Split components for better maintance
- [ ] Add unit tests if they are missing
- [ ] Move state logic for a Redux-like pattern instead of Flux-like
- [x] ~Aphrodite all the things~

### about:extensions
- [ ] Move to `/app` folder
- [ ] Split components for better maintance
- [ ] Add unit tests if they are missing
- [ ] Move state logic for a Redux-like pattern instead of Flux-like
- [x] ~Aphrodite all the things~

### about:history
- [ ] Move to `/app` folder
- [ ] Split components for better maintance
- [ ] Add unit tests if they are missing
- [ ] Move state logic for a Redux-like pattern instead of Flux-like
- [x] ~Aphrodite all the things~

### about:newtab
- [ ] Move to `/app` folder
- [ ] Split components for better maintance
- [ ] Add unit tests if they are missing
- [ ] Move state logic for a Redux-like pattern instead of Flux-like
- [x] ~Aphrodite all the things~

### about:passwords
- [ ] Move to `/app` folder
- [ ] Split components for better maintance
- [ ] Add unit tests if they are missing
- [ ] Move state logic for a Redux-like pattern instead of Flux-like
- [x] ~Aphrodite all the things~

### about:preferences
- [ ] Move to `/app` folder
- [ ] Split components for better maintance
- [ ] Add unit tests if they are missing
- [ ] Move state logic for a Redux-like pattern instead of Flux-like
- [x] ~Aphrodite all the things~

### about:safebrowsing
- [ ] Move to `/app` folder
- [ ] Split components for better maintance
- [ ] Add unit tests if they are missing
- [ ] Move state logic for a Redux-like pattern instead of Flux-like
- [x] Aphrodite all the things

### about:styles
- [ ] Move to `/app` folder
- [ ] Split components for better maintance
- [ ] Add unit tests if they are missing
- [ ] Move state logic for a Redux-like pattern instead of Flux-like
- [x] ~Aphrodite all the things~

### about:welcome
- [ ] Move to `/app` folder
- [ ] Split components for better maintenance
- [ ] Add unit tests if they are missing
- [ ] Move state logic for a Redux-like pattern instead of Flux-like
- [x] ~Aphrodite all the things~
