### ISSUE TITLE
0.17.x exclusion list

### ISSUE THREAD

**Issue by alexwykoff** [brave/browser-laptop#9578]
Generated 06/19/2017:
 - [ ] Sort top sites more deterministically. ([#9541](https://github.com/brave/browser-laptop/issues/9541))
https://github.com/brave/browser-laptop/issues/9541
 - [ ] AppState.sites sort takes a long time (Every navigation +200 ms [w/ 10K bookmarks]). ([#9427](https://github.com/brave/browser-laptop/issues/9427))
https://github.com/brave/browser-laptop/issues/9427
 - [ ] Bookmark title is not selected automatically. ([#9091](https://github.com/brave/browser-laptop/issues/9091))
https://github.com/brave/browser-laptop/issues/9091
 - [ ] Redux component is constructed on every render. ([#9067](https://github.com/brave/browser-laptop/issues/9067))
https://github.com/brave/browser-laptop/issues/9067
 - [ ] Bookmarked about pages do not have the filled star icon. ([#9047](https://github.com/brave/browser-laptop/issues/9047))
https://github.com/brave/browser-laptop/issues/9047
 - [ ] Thisdot.co - email signup not working with Shields Up. ([#8825](https://github.com/brave/browser-laptop/issues/8825))
https://github.com/brave/browser-laptop/issues/8825
 - [ ] Add ability to update to preview releases (with advanced option). ([#8769](https://github.com/brave/browser-laptop/issues/8769))
https://github.com/brave/browser-laptop/issues/8769
 - [ ] Replace all CSS and l10n selectors with data-test-id for unit tests. ([#8734](https://github.com/brave/browser-laptop/issues/8734))
https://github.com/brave/browser-laptop/issues/8734
 - [ ] Merge tabs into frames object in windowStore. ([#8689](https://github.com/brave/browser-laptop/issues/8689))
https://github.com/brave/browser-laptop/issues/8689
 - [ ] Follow-up to #5724: the bravery panel should be much wider. ([#5726](https://github.com/brave/browser-laptop/issues/5726))
https://github.com/brave/browser-laptop/issues/5726

**Comment by alexwykoff** [comment]
generated 06/25/2017
Exclusion List:
 - [ ] Add an npm run unittest push hook. ([#9688](https://github.com/brave/browser-laptop/issues/9688))
https://github.com/brave/browser-laptop/issues/9688
 - [ ] Sometimes no active tab is selected after closing a tab. ([#9686](https://github.com/brave/browser-laptop/issues/9686))
https://github.com/brave/browser-laptop/issues/9686
 - [ ] Manual test run on Linux for 0.17.x RC2. ([#9661](https://github.com/brave/browser-laptop/issues/9661))
https://github.com/brave/browser-laptop/issues/9661
 - [ ] Manual test run for 0.17.x on Windows x64 . ([#9636](https://github.com/brave/browser-laptop/issues/9636))
https://github.com/brave/browser-laptop/issues/9636
 - [ ] Hide "update to preview release" toggle on linux. ([#9631](https://github.com/brave/browser-laptop/issues/9631))
https://github.com/brave/browser-laptop/issues/9631
 - [ ] Running tests with npm5 fails. ([#9628](https://github.com/brave/browser-laptop/issues/9628))
https://github.com/brave/browser-laptop/issues/9628
 - [ ] Disable bitwarden in 0.17.x. ([#9619](https://github.com/brave/browser-laptop/issues/9619))
https://github.com/brave/browser-laptop/issues/9619
 - [ ] Unpinning tab intermittently does not display the title on tabs. ([#9608](https://github.com/brave/browser-laptop/issues/9608))
https://github.com/brave/browser-laptop/issues/9608
 - [ ] Add support for Linux Mint - Serena . ([#9590](https://github.com/brave/browser-laptop/issues/9590))
https://github.com/brave/browser-laptop/issues/9590
 - [ ] Optimize top site order lookups. ([#9581](https://github.com/brave/browser-laptop/issues/9581))
https://github.com/brave/browser-laptop/issues/9581
 - [ ] Closing the only tab in second tabset shows wrong number of tabs. ([#9561](https://github.com/brave/browser-laptop/issues/9561))
https://github.com/brave/browser-laptop/issues/9561
 - [ ] AppState.sites sort takes a long time (Every navigation +200 ms [w/ 10K bookmarks]). ([#9427](https://github.com/brave/browser-laptop/issues/9427))
https://github.com/brave/browser-laptop/issues/9427
 - [ ] Editing autocompleted URL deletes autocompleted URL with typed in key. ([#9322](https://github.com/brave/browser-laptop/issues/9322))
https://github.com/brave/browser-laptop/issues/9322
 - [ ] Bookmark title is not selected automatically. ([#9091](https://github.com/brave/browser-laptop/issues/9091))
https://github.com/brave/browser-laptop/issues/9091
 - [ ] Redux component is constructed on every render. ([#9067](https://github.com/brave/browser-laptop/issues/9067))
https://github.com/brave/browser-laptop/issues/9067
 - [ ] Bookmarked about pages do not have the filled star icon. ([#9047](https://github.com/brave/browser-laptop/issues/9047))
https://github.com/brave/browser-laptop/issues/9047
 - [ ] Thisdot.co - email signup not working with Shields Up. ([#8825](https://github.com/brave/browser-laptop/issues/8825))
https://github.com/brave/browser-laptop/issues/8825
 - [ ] Add ability to update to preview releases (with advanced option). ([#8769](https://github.com/brave/browser-laptop/issues/8769))
https://github.com/brave/browser-laptop/issues/8769
 - [ ] Replace all CSS and l10n selectors with data-test-id for unit tests. ([#8734](https://github.com/brave/browser-laptop/issues/8734))
https://github.com/brave/browser-laptop/issues/8734
 - [ ] Merge tabs into frames object in windowStore. ([#8689](https://github.com/brave/browser-laptop/issues/8689))
https://github.com/brave/browser-laptop/issues/8689
