### ISSUE TITLE
Extension: OneTab

### ISSUE THREAD

**Issue by jonathansampson** [brave/browser-laptop#9828]
Extension: [OneTab](https://chrome.google.com/webstore/detail/onetab/chphlpgkkbolifaimnlloiipkdnihall?hl=en)

![image](https://user-images.githubusercontent.com/815158/27767508-5eacb132-5ebf-11e7-9ab1-82a7a92c7677.png)

## Needed APIs:

**chrome.browserAction**

- [x] #8329 chrome.browserAction.onClicked

**chrome.commands**

- [ ] #9829 chrome.commands.onCommand

**chrome.contextMenus**

- [ ] #8331 chrome.contextMenus.create
- [x] #8815 chrome.contextMenus.removeAll
- [ ] #8332 chrome.contextMenus.update

**chrome.i18n**

- [ ] #4755 chrome.i18n.getMessage

**chrome.runtime**

- [x] #9555 chrome.runtime.getURL
- [ ] #8791 chrome.runtime.onMessage
- [ ] #8802 chrome.runtime.sendMessage

**chrome.tabs**

- [ ] #8680 chrome.tabs.create
- [ ] #9830 chrome.tabs.get
- [ ] #8819 chrome.tabs.onActivated
- [ ] #9831 chrome.tabs.onAttached
- [ ] #8820 chrome.tabs.onCreated
- [ ] #9832 chrome.tabs.onDetached
- [ ] chrome.tabs.onMoved
- [ ] #8809 chrome.tabs.onRemoved
- [ ] #6194 chrome.tabs.onReplaced
- [ ] #8810 chrome.tabs.onUpdated
- [ ] #8811 chrome.tabs.query
- [ ] #9833 chrome.tabs.reload
- [ ] #4687 chrome.tabs.remove
- [ ] #8812 chrome.tabs.sendMessage
- [ ] #6790 chrome.tabs.update

**chrome.webRequest**

- [ ] #9837 chrome.webRequest.onCompleted

**chrome.windows**

- [ ] #6789 chrome.windows.create
- [x] #8677 chrome.windows.getAll
- [ ] #9838 chrome.windows.getLastFocused
- [x] #4760 chrome.windows.onFocusChanged
- [ ] #8679 chrome.windows.update
