### ISSUE TITLE
Chrome urls tracking issue

### ISSUE THREAD

**Issue by Jacalz** [brave/browser-laptop#9977]
This issue is to track which chrome urls that work after #9971 

- [ ] chrome://appcache-internals

- [ ] chrome://indexeddb-internals

- [ ] chrome://accessibility

- [ ] chrome://blob-internals

- [ ] chrome://inducebrowsercrashforrealz

- [ ] chrome://dino

- [ ] chrome://gpu

- [ ] chrome://histograms

- [ ] chrome://media-internals

- [ ] chrome://memory-exhaust

- [ ] chrome://view-http-cache

- [ ] chrome://network-error

- [ ] chrome://network-errors

- [ ] chrome://resources

- [ ] chrome://serviceworker-internals

- [ ] chrome://tracing

- [ ] chrome://webrtc-internals

- [ ] chrome://badcastcrash/

- [ ] chrome://checkcrash/

- [ ] chrome://inducebrowsercrashforrealz/

- [ ] chrome://uithreadhang/

- [ ] chrome://crash/

- [ ] chrome://delayeduithreadhang/

- [ ] chrome://crashdump/

- [ ] chrome://gpuclean/

- [ ] chrome://gpucrash/

- [ ] chrome://gpuhang/

- [ ] chrome://hang/

- [ ] chrome://kill/

- [ ] chrome://memory-exhaust/

- [ ] chrome://network-error/

- [ ] chrome://network-errors/

- [ ] chrome://ppapiflashcrash/

- [ ] chrome://ppapiflashhang/

- [ ] chrome://shorthang/
